### DISCUSSION TITLE
Always reject the same filtered movie

### DISCUSSION THREAD

**Discussion by terrellgf** [Flexget/Flexget#2817] [Q&A]
I used the imdb plugin to filter movies that were earlier than 1990 and scored less than 6.0. Also, I used the content_filter plugin to filter some compressed movies. These have caused me to always reject the same movie every time I perform a task. 
  I don't know if the problem is that my flexget configuration is incorrect, or the RSS policy of the PT site causes the same movies that have been filtered by my policy every time I refresh the RSS. Of course, this has not always been the case. I query the RSS via the timer, and I receive few new movies irregularly every day, which causes my flexget to be very inefficient. 
  Please help me, thanks!

![image](https://user-images.githubusercontent.com/54665471/105439903-a3596680-5ca0-11eb-80c5-ad6539764691.png)

```yaml
web_server:

  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  PT:
    template: movie
    priority: 1

schedules:
  - tasks: [PT]
    interval:
      minutes: 5

templates:
  global:
    retry_failed:
      retry_time: 5 minutes
      retry_time_multiplier: 1
      max_retries: 12
  movie:
    transmission:
      host: 1.1.1.1
      port: 1111
      username: xxxx
      password: xxxx
      path: /volume2/videos/movie
    seen_movies:
      matching: strict
    proper_movies: no
    imdb_lookup: yes
    imdb:
      min_year: 1990
      min_score: 6
    list_match:
      from:
        - movie_list: mymovies
    regexp:
      from: title
      reject:
        - msd
        - afg
        - line
        - hc
        - korsub
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'
        - '*.iso'
    inputs:
      - rss:
          url: https://xxxx
          all_entries: yes
```

**Comment by gazpachoking** [comment]
This is working as intended. FlexGet considers every item in the rss feed by default. If the items don't scroll through your feed very fast, you can run the task less frequently to have less overlap. You could also optimize a bit, by turning off `all_entries` in the rss plugin, which will attempt to remember the last item processed. This will work better or worse depending on different rss feed capabilities, and there may be situations in which it does consider the whole feed again anyway (e.g. when your config changes.)
```yaml
rss:
  url: https://xxxx
  all_entries: no
```
