### DISCUSSION TITLE
Questions about updating Kodi library on Android TV

### DISCUSSION THREAD

**Discussion by ultimateguy** [Flexget/Flexget#2830] [Q&A]
I have a new Sony Android TV running Kodi and would like FlexGet to update its library. I have a static IP assigned to the TV. My code is:

```
    kodi_library:
      action: scan
      category: video
      url: http://192.168.1.30
      username: 
      password: 
      port: 8080
```

1. What is the username and password in this case? Do I need to configure this in Android, or in Kodi?
2. I assume that if the TV is off, it will be unable to connect and the task will fail. This is a problem for me since I have other code in the task that sorts shows which I still want to run. Is there a way of telling FlexGet to execute the rest of the task even if this block of code fails?
