### DISCUSSION TITLE
Got an error when use "now - transmission_date_done"

### DISCUSSION THREAD

**Discussion by ProteinPig** [Flexget/Flexget#2832] [Q&A] [answered]
I have a task to clean seeds from transmission when finished 2days. It worwed very well, but today it didn't worked. I looked into the log and I found the error.
Is there anything wrong with this config?

> 2021-01-29 04:00:27 ERROR    if            clean_temp_seeds Error occurred while evaluating statement `now - transmission_date_done >= timedelta(days=2) and 'temp' in transmission_downloadDir`. (unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType')
```
   clean_temp_seeds:
    priority: 1002
    <<: *from_transmission
    if:
      - transmission_ratio >= 3.0 and 'temp' in transmission_downloadDir: accept
      - now - transmission_date_done >= timedelta(days=2) and 'temp' in transmission_downloadDir: accept
    <<: *clean_transmission
```
> Version Info
> Flexget: 3.1.98 
> API: 1.8.0
