### DISCUSSION TITLE
ignoring imdb minimum parameters

### DISCUSSION THREAD

**Discussion by JEZHDK** [Flexget/Flexget#2834] [Q&A] [answered]
Hi all,

Im having an issue where Flexget is accepting movies, even if there are too old.

My config:

```yaml
    transmission:
      host: xxx
      port: xxx
      username: xxx
      password: xxx
      add_paused: yes
      path: /data/movies
      # skip_files:
        # - '*.nfo'
        # - '*.sfv'
        # - '*[sS]ample*'
        # - '*.txt'
    quality:
      - 720p-2160p
      - hdtv-bluray
    imdb_lookup: yes
    imdb:
      min_score: 6
      min_year: 2019
    regexp:
      reject:
        - DVDR
        - 3D
      from: title
      accept:
        - danish
        - dansk
        - DKsubs
        - nordic
```

Example is:
moviesometitle.1986.NORDIC

It gets accepted by regexp because of "nordic", but IMDB min_year: 2019 is ignored. How do i fix this?

System setup:
Flexge version: 3.1.102
Flexget running in docker: cpoppema/docker-flexget
