### DISCUSSION TITLE
decompress plugin

### DISCUSSION THREAD

**Discussion by turb0chrg** [Flexget/Flexget#2838] [Q&A]
Hi there.

Can someone help me to troubleshoot the decompress plugin? https://www.flexget.com/Plugins/decompress

I'm on Windows and have followed the configuration at https://www.flexget.com/Plugins/decompress. Here's my config

```
 set:
      path: e:\
      move_completed_path: "e:\\television\\{{ tvdb_series_name | replace(' ','.') | replace (',','') | replace (':','') }}"
      timeframe: 60 minutes
      target: 720p hdtv+
      quality: hr-1080p hdtv+
      content_filename: >
        {{ tvdb_series_name | replace (' ','.') | replace (',','') | replace (':','') }}.{{ tvdb_ep_id | default(series_id, True) }}.{{ quality | replace(' ','.') | lower }}{% if proper_count %} - PROPER{% if proper_count > 1 %}{{ proper_count }}{% endif %}{% endif %}
      decompress: 
        unrar_tool: "C:\\ProgramData\\chocolatey\\bin\\unrar.exe"
```

It doesn't unrar things, and I don't see anything in the log. I start my flexget using `C:\Python37\Scripts\flexget.exe --loglevel verbose daemon start` from task scheduler and it is downloading and moving my torrents...

Thanks!

**Comment by ianstalk** [comment]
Decompress works on local files. Here's an example from my config:

```  
  series-file-decompress:
    accept_all: yes
    seen: local
    no_entries_ok: yes
    filesystem:
      path: '/etc/transmission-openvpn/completed/tv/'
      recursive: yes
      regexp: '.*\.(rar|r0+[01]|zip|part0+[01])$'
    archives: yes
    decompress:
      keep_dirs: no
      to: '/var/lib/flexget/tmp/tv/'
      regexp: '.*\.(mkv|avi|mp4|mpg|mov|m4v)$'
 ```
