### DISCUSSION TITLE
Trakt_list plugin working for everyone?

### DISCUSSION THREAD

**Discussion by kerryandjane** [Flexget/Flexget#2871] [Q&A]
It's been a while since I wanted to use it, Now I can't get it to work for the life of me.

For starters here's my setup.
  Hardware: Synology DS918+ Server.
  Software: Docker image of flexget (with webui)
  Plugin: Trakt (I used https://trakt.tv/pin/346 to get the pin to auth) (i've tried making my list public so I don't need to auth, but it still doesn't work.)

My config looks like this:

```
tasks:
  tvseries downloader:
    rss: "https://www.torrentday.com/t.rss?2;u=<unique numbers>;tp=<unique number>"
    trakt_list:
      username: <my username>
      account: <my username>
      list: <name of trakt watchlist>
      type: shows
    thetvdb_lookup: yes
    exec:
      on_output:
        for_accepted: <what to do with the torrents found.>
```

It finds the list from from trakt. But it doesn't add them to the "series list".

If I manually add a series via config like this:

```
    series:
      - "The Equalizer"
```

It works as expected. Anyone know what's up with trakt & flexget? or where i'm going wrong?

I've changed the list from a private and public to "trending", entries are populated, but everything is "undecided". Think Trakt isn't working with flexget at all now.
