### DISCUSSION TITLE
Unable to find information about anime

### DISCUSSION THREAD

**Discussion by jterral** [Flexget/Flexget#2900] [Q&A]
Hello,

I want to move/rename anime but I dont succeed to correctly parse the name to find all metadata of the anime.

My task:
```yaml
  sort-series:
    no_entries_ok: yes
    thetvdb_lookup: yes
    seen: local
    series:
      - One Piece:
          sequence_regexp: (\d\d\d)
          name_regexp:
            - _One_Piece_
    move:
      to: '/data/video/anime/{{ series_name }}'
      rename: '{{ series_name }} - {{ series_id }}{{ location|pathext }}'
    mock:
      - { title: '[Kaerizaki-Fansub]_One_Piece_956_[VOSTFR][FHD_1920x1080]' }
      # - { title: 'One Piece ep956 [VOSTFR][FHD_1920x1080].mp4' }
```

My execution result:
```sh
$> flexget -L verbose --test execute --tasks sort-series --dump eval

-- Undecided: --------------------------
title            : [Kaerizaki-Fansub]_One_Piece_956_[VOSTFR][FHD_1920x1080]
url              : mock://localhost/mock/-5089385055380093240
original_url     : mock://localhost/mock/-5089385055380093240
media_id         : None
original_title   : [Kaerizaki-Fansub]_One_Piece_956_[VOSTFR][FHD_1920x1080]
quality          : 1080p
task             : sort-series
```

With the second mock and without the `name_regexp` I find all information (serie name, episode id...).

Any ideas of how to achieve this with first mock?

**Comment by jterral** [comment]
For anyone with same problem, I fixed it with `manipulate` plugin :)

```yaml
manipulate:
  - title:
      replace:
        regexp: '_'
        format: ' '
```
