### DISCUSSION TITLE
Trying to shorten one task execution time

### DISCUSSION THREAD

**Discussion by effemmeffe** [Flexget/Flexget#2914] [Q&A]
In my config there is the following task that takes 7586 seconds to execute:

```
download-series-discover: # task
    priority: 50
    template:
      - series
      - reject
      - torrents
      - transmission-series
    trakt_lookup:
      account: "{? trakt.account ?}"
      username: "{? trakt.user ?}"
    if:
      - trakt_watched: reject
    magnets: yes
    convert_magnet:
      timeout: 10 seconds
      force: yes
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - next_series_episodes: yes
            #from_start: yes
            #backfill: yes
      from:
        - search_rss: https://eztv.re/ezrss.xml
        - search_rss: https://rarbg.to/rssdd.php?category=41  # x264/720p/1080p
```

I want to shorten the execution time of that task.  
In the config I have a series template like this:

```
##### Series config
#
  series:
    metainfo_series: yes
    thetvdb_lookup: yes
    trakt_lookup:
      account: "{? trakt.account ?}"
      username: "{? trakt.user ?}"
    tvmaze_lookup: yes
    configure_series:
      from:
        entry_list: trakt-series
      settings:
        identified_by: ep
        timeframe: 16 hours
        #target: hdtv+ 720p
        #quality: webrip 720p
        #quality: webrip+
        propers: 16 hours
        specials: no
        season_packs: always
    content_size:
      min: 100
```

I noticed that I have the trakt_lookup settings both in the series template and in the task.  
Is it possible that this is a reason why the task is taking so long to execute?

Any other things I can change in the task to make it quick?
Please explain what I should do in practice and not in theory, because but I'm no flexget expert, I copied the config from Jonybat and adapted to my needs and I'm not able to change it drastically without directions, thanks.
