### DISCUSSION TITLE
Simple download

### DISCUSSION THREAD

**Discussion by ciberknibal** [Flexget/Flexget#2975] [General]
hi! 
i.m new in flexget 
I'm trying to get flexget to download torrent files from rss channel to folder but can't get it to work. I am using flexget in synology.
my configuration is the following:

```
web_server:
  bind: 0.0.0.0
  port: 8290
  web_ui: yes

tasks: 
  puntotorrent: 
    rss: 
      url: https://xxxxxxxxx
      all_entries: true
    accept_all: yes
    no_entries_ok: yes
    download: /volumeUSB2/usbshare/torrent
```

all entries are REJECTED. 
thanks
