### DISCUSSION TITLE
Error: Cannot locate template on disk

### DISCUSSION THREAD

**Discussion by frankyw** [Flexget/Flexget#2981] [Q&A] [answered]
Quick question pls.

I am trying to use the notify/pushoever plugin to send push notifications, and have created a template to keep the config clean. I've looked in the source code, and it seems the template needs to end in ".template" so have named accordingly.

The template is in the root config directory, but am still getting an error:

`
2021-05-14 00:19:00 CRITICAL plugin        irc-tv-dl       Cannot locate template on disk: pushover.template
`

My config is below, which works fine when using an inline "message" parameter.

```yml
      notify:
        entries:
          title: Download from task {{task}}
          #message: |+
          template: pushover.template
          via:
            - pushover:
                api_key: '{? pushover.api_key ?}'
                user_key: '{? pushover.user_key ?}'
                url: '{{trakt_series_url|d(imdb_url)}}'
                url_title: More Info
                sound: incoming
                html: yes
```

Any help appreciated, have read the docs and the code, but can't figure it out. Thanks!
