### DISCUSSION TITLE
Help with undecided - what am I missing?

### DISCUSSION THREAD

**Discussion by hybiepoo** [Flexget/Flexget#2995] [Q&A]
I'm having trouble with flexget not downloading episodes because they are filtered as undecided, but I'm not sure why.
Relevant config:
```yaml
templates:
  global:
    # REJECT ANY TORRENT THAT CONTAINS ONE OF THESE
    # WORDS IN BETWEEN A SPACE OR A DOT
    regexp:
      reject:
        - (?i)[ .]cam[ .]
        - (?i)[ .]bdscr[ .]
        - (?i)[ .]dvdscr[ .]
        - (?i)[ .]preair[ .]
        - (?i)[ .]ppvrip[ .]
        - (?i)[ .]r5[ .]
        - (?i)[ .]tc[ .]
        - (?i)[ .]ts[ .]
        - (?i)[ .]ecc[ .]
        - (?i)[ .]avc[ .]
        - (?i)[ .]qebs[ .]
        - (?i)[ .]hdtc[ .]
        - (?i)[ .]hdcam[ .]
        - (?i)[ .]repack[ .]

  streetoutlaws:
    #download: /var/lib/transmission-daemon/watchdir/
    transmission:
      host: localhost
      port: 9091
      username: <username>
      password: <pw>
    next_series_episodes:
      from_start: yes
    series:
      settings:
        hdtv:
          quality: 720p+ !2160p
          tracking: backfill
          identified_by: ep
      hdtv:
        - Street Outlaws:
            exact: yes
            begin: S17E13
        - Street Outlaws No Prep Kings:
            begin: S02E15
        - Street Outlaws Mega Cash Days:
            begin: S01E11
        - Street Outlaws Americas List:
            begin: S01E03
  ##### Common torrents config
  torrents:
    torrent_alive:
      min_seeds: 3
      reject_for: 15 minutes
    magnets: no

  ##### Series metainfo mainly for move and update tasks
  series-metainfo:
    imdb_lookup: yes
    metainfo_series: yes
    thetvdb_lookup: yes
tasks:
##### Discover and download older episodes and pilots from recently added series
  download-series-discover:
    version_checker: yes
    priority: 14
    template:
      - streetoutlaws
      - torrents
    discover:
      release_estimations: ignore
      interval: 5 minutes
      what:
        - next_series_episodes: yes
      from:
        - iptorrents:
            rss_key: '{? ipt.rss_key ?}'
            uid: '{? ipt.uid ?}'
            password: '{? ipt.password ?}'
            category:
              - TV-x264
              - 99 #TV-x265

```

Example of undecided:
```
2021-05-18 11:42:26 VERBOSE  details       download-series-discover Summary - Accepted: 0 (Rejected: 0 Undecided: 12 Failed: 0)
-- Undecided: --------------------------
title            : Street Outlaws-No Prep Kings S02E15 720p HEVC x265-MeGusta
url              : https://iptorrents.com/download.php/3841519/Street.Outlaws-No.Prep.Kings.S02E15.720p.HEVC.x265-MeGusta.torrent?torrent_pass=7b0fa52944526780102c49a9613231f9
original_url     : https://iptorrents.com/download.php/3841519/Street.Outlaws-No.Prep.Kings.S02E15.720p.HEVC.x265-MeGusta.torrent?torrent_pass=7b0fa52944526780102c49a9613231f9
content_size     : 635.1470947265625
discovered_from  : Street Outlaws No Prep Kings S02E15
discovered_with  : iptorrents
media_id         : <LazyField - value will be determined when it is accessed>
original_title   : Street Outlaws-No Prep Kings S02E15 720p HEVC x265-MeGusta
proper           : False
proper_count     : 0
quality          : 720p h265
release_group    : None
season_pack      : None
series_episode   : 15
series_episodes  : 1
series_exact     : False
series_id        : S02E15
series_id_type   : ep
series_identified_by: ep
series_name      : Street Outlaws No Prep Kings
series_parser    : <SeriesParseResult(data=Street Outlaws-No Prep Kings S02E15 720p HEVC x265-MeGusta,name=Street Outlaws No Prep Kings,id=(2, 15),season=2,season_pack=None,episode=15,quality=720p h265,proper=0,special=False,status=OK)>
series_releases  : [815]
series_season    : 2
task             : download-series-discover
torrent_availability: 6
torrent_leeches  : 0
torrent_seeds    : 3
```
It seems to meet the requirements, so why is it undecided?
