### DISCUSSION TITLE
How can i put de series entries to be get list past by cli?

### DISCUSSION THREAD

**Discussion by alannssantos** [Flexget/Flexget#3029] [Q&A]
```
task:
  Series
    discover:
      what:
        - next_series_episodes: yes
      from:
        - 1337x: yes
    list_match:
      from: ?????
```
