### DISCUSSION TITLE
Move process is only copying files after major upgrade

### DISCUSSION THREAD

**Discussion by Shdwdrgn** [Flexget/Flexget#3046] [Q&A]
I just completed a big update on my system yesterday which brought me up to python 3.7 and allowed me to upgrade flexget from 2.10.60 all the way to 3.1.130 (which appears to be the current release).  Unfortunately I've run into an odd problem since then -- most (but not all) TV shows in my sort-tv task are getting copied to their new destination rather than moved, so I end up with two copies of the same file in different folders.

```
    move:
      to: '/{? dir.tv ?}/{{series_name}}/Season {{series_season}}/'
      rename: "{{series_name}} - {{series_id}} - {{episode_name}}"

    exec:
      fail_entries: yes
      on_exit:
        for_accepted:
          - ln -s "{{location}}" "{{old_location}}"
```

This is from my sort-tv task, in which the files should be renamed and moved to their new destination, then a link is created in the original location to allow seeding to continue.  Instead I am getting "Failed <original filename> ([Errno 5] Input/output error: <path/to/new/filename>".  I'm not sure if the error is coming from the move process failing to remove the original file, or if the link command is failing because the original filename is still there.  I've done about 10 downloads since the upgrade and in all cases a copy of the original file is correctly made to the new location with the new name, so that part at least is working well.

I mentioned above that -some- files were successfully moved, and in those cases the link was created as expected.  This has happened with three files.  Two of these were automatically downloaded by flexget, the other file I manually initiated (which was then moved into the tv folder that the sort-tv task monitors).  I can't find any reason for the discrepancy, folder and file permissions are all as expected, and with at least one file that I saw the task failed for the first hour and then suddenly completed successfully.  It just doesn't make any sense.

Anyway, hopefully someone can help me track this down.  As far as I can tell everything else in my old script is still working fine but this one issue stands out.
