### DISCUSSION TITLE
Error:  deluge_time_added not supported between instances of 'float' and 'datetime.datetime')

### DISCUSSION THREAD

**Discussion by loopyd** [Flexget/Flexget#3074] [Q&A]
As-stated in title.

config.yml - sample
```yaml
  clean_daily_task:
    template:
      - read_from_deluge
      - purge_to_deluge
    if:
      - deluge_time_added|to_date > now - timedelta(days=1): reject
      - deluge_ratio < 0.31: accept
      - True: reject
```

_(You don't need to worry about the other template imports for this question, I have them obfuscated here because they contain login credentials)_

The error produced is:

```
clean_daily_task Error occurred while evaluating statement `deluge_time_added|to_date > now - timedelta(days=1)`. ('>' not supported between instances of 'float' and 'datetime.datetime')
```

Which led to reading the docs at:  https://flexget.com/Jinja and seeing the problem.  

Flexget lacks a custom filter to parse deluge timestamps from this entry field, which is a UNIX timestamp as a float.   Here's the relevant line from ``flexget --test execute --tasks clean_daily_task --dump`` on the issue on an example torrent:

```
deluge_time_added: 1626000128.0
```

A custom filter such as:

```yaml
      - deluge_time_added|to_datetime > now - timedelta(days=1): reject
```

Would be the most appropriate implementation.  Do we have one, that I seem to be missing from docs, or is there a native jinja workaround?
