### DISCUSSION TITLE
Filesystem recursion

### DISCUSSION THREAD

**Discussion by jasonlshelton** [Flexget/Flexget#3095] [Q&A]
I have the following task in my config:

```yaml
sync-series:
    manual: yes
    filesystem:
      path: /home/storage/TV_Shows/
      recursive: yes
      regexp: '.*\.(mp4|avi|mkv)$'
    disable: builtins
    configure_series:
      settings:
        set:
          tracking: no
      from:
        filesystem: /home/storage/TV_Shows/
    exec: echo "Found {{title}}"
```

but when it runs I get the following error. 

> 2021-07-19 20:09:10 VERBOSE  filesystem    sync-series     Scanning folder /home/storage/TV_Shows/. Recursion is set to False.

SO, how is recursion set to false when recursive: yes is set? I've tried yes, True, 3, 4, 5, etc  and always get the same error.
