### DISCUSSION TITLE
Passing integers as variable

### DISCUSSION THREAD

**Discussion by arifer612** [Flexget/Flexget#3099] [Q&A] [answered]
I would like to pass my torrent client's host address and port number as variables into the configuration file. 

My variable file looks something like this:
```
client:
  host: 192.1.1.1
  port: 9091
```

where it gets fed into my configuration file that looks something like this:
```
variables: variables.yml

templates:
  torrent:
    host: '{? client.host ?}'
    port: 9091
...
```
because having `port: '{? client.port ?}'` would spit out an error that says that the port needs to be an integer. The problem right now is that variables can only be passed as strings.

Does anybody have an idea to go about this?
