### DISCUSSION TITLE
How to prevent movie upgrades across tasks?

### DISCUSSION THREAD

**Discussion by KronK0321** [Flexget/Flexget#3105] [Q&A]
I have two separate IMDB lists. The intent is to search separate (but overlapping in content) RSS feeds and place downloaded movies into specific directories. 
 
Here are the relevant portions of my config:
```
  populate_movie_list_kids:
    imdb_watchlist:
      user_id: <user id>
      list: <list id1>
    accept_all: yes
    list_add:
      - movie_list: imdb_kids

  populate_movie_list_xmas:
    imdb_watchlist:
      user_id: <user id>
      list: <list id2>
    accept_all: yes
    list_add:
      - movie_list: imdb_xmas

  hd_movies_xmas:
    inputs:
      - rss: <url1>
      - rss: <url2>
    list_match:
      from:
        - movie_list: imdb_xmas
      action: accept
      remove_on_match: yes
      single_match: yes
    imdb_lookup: yes
    quality: 720p-1080p !h265
    upgrade:
      tracking: yes
      target: 1080p
      propers: yes
    proper_movies: yes
    content_size:
#      min: 4500
      max: 11500
      strict: no
    template:
      - stormytransmission
      - pvt_ratio
    transmission:
      path: /mnt/big1/xmasmovies

  hd_movies_kids:
    inputs:
      - rss: <url3>
    list_match:
      from:
        - movie_list: imdb_kids
      action: accept
      remove_on_match: yes
      single_match: yes
    imdb_lookup: yes
    quality: 720p-1080p !h265
    upgrade:
      tracking: yes
      target: 1080p
      propers: yes
    proper_movies: yes
    content_size:
#      min: 4500
      max: 11500
      strict: no
    template:
      - stormytransmission
      - pvt_ratio
    transmission:
      path: /mnt/big1/kids/Movies
```

The `hd_movies_kids` task found Peter Rabbit in 720p quality and downloaded it, as expected:
```
Jul 31 04:09:14 flexget flexget[8604]: 2021-07-31 04:09:14 VERBOSE  task          hd_movies_kids ACCEPTED: `Peter Rabbit 2: The Runaway [2021] by Will Gluck - x264 / Blu-ray / MKV / 720p / Scene [ Peter.Rabbit.2.The.Runaway.2021.720p.BluRay.X264-BEATRIX ]` by list_match plugin
```

But then the `hd_movies_xmas` task found a 1080p version and the upgrade plugin triggered the download.
```
Jul 31 04:15:14 flexget flexget[8604]: 2021-07-31 04:15:14 VERBOSE  task          hd_movies_xmas ACCEPTED: `Peter Rabbit 2: The Runaway [2021] by Will Gluck - x264 / Blu-ray / MKV / 1080p / Scene [ Peter.Rabbit.2.The.Runaway.2021.1080p.BluRay.x264-BEATRIX ]` by upgrade plugin because upgraded quality
```

This means that I ended up with a 720p version in my Kids Movies folder and a 1080p version in my Xmas movies folder when I was expecting both versions in the Kids Movies folder.

What is it about my config that is enabling the Upgrade plugin to work across tasks and how can I restrict it to only the task that has downloaded a specific movie will trigger the upgrade plugin for future movies that task sees?

Thanks!
