### DISCUSSION TITLE
Download all series from the start

### DISCUSSION THREAD

**Discussion by darrenhoggard** [Flexget/Flexget#3127] [Q&A] [answered]
Hello,
I have used the configure_series plugin to get my tv shows from sonarr.
I want to add new tv shows there and then download the whole series.
under discover, i have next_series_episode: yes, but when i try to add in from_start: yes i get the following error:

[/tasks/overseerr_tv_shows/discover/what/0/next_series_episodes] Got `None`, expected: dict or boolean
[/tasks/overseerr_tv_shows/discover/what/0] The key `from_start` is not valid here. Only known plugin names are valid keys.
[/tasks/overseerr_tv_shows/discover/what/0] {'next_series_episodes': None, 'from_start': True} has too many properties

this is my (partial) config file:
```
  tv:
    configure_series:
      settings:
        quality: 720p+
        identified_by: ep
      from:
        sonarr_list:
          base_url: "My Url"
          port: xxx
          api_key: xxx
          include_data: no

  overseerr_tv_shows:
    template:
      - tv
      - one  # deluge config
    discover:
      what:
# this gives the error, if i just have "next_series_episodes: yes" then it works ok, but only get the next episode, 
# i want the whole series from the start
        - next_series_episodes:
          from_start: yes
      from:
        - iptorrents:
            rss_key: xxx
            uid: xxx
            password: xxx
            category:
              - TV-all
        - torrentleech:
            rss_key: xxx
            username: xxx
            password: xxx
            category: 32
```

can someone point me int he right direction please.

many thanks
d
