### DISCUSSION TITLE
unable to search for season packs

### DISCUSSION THREAD

**Discussion by voncloft** [Flexget/Flexget#3132] [Q&A]
My config.yml is here: https://pastebin.com/VgshpBw7

I can not get any season packs for suits. Keep getting message " series-discover no season packs found for series `Suits` with parameters season: None, downloaded: True"

**Comment by lamski** [comment]
In your discover settings, add this:
```
    discover:
      what:
        - next_series_seasons: yes
        - next_series_episodes: yes
```

In your series settings, add:
```
        - Series title:
            begin: S01E01
            season_packs: yes
```
