### DISCUSSION TITLE
How to filter files by screen_size? TS | CAMrip | HDRip | BDRip

### DISCUSSION THREAD

**Discussion by maltsevvv** [Flexget/Flexget#3140] [Q&A] [answered]
Hi. How to add filter files by screen_size
TS | CAMrip | HDRip | BDRip?
The task is to download the movie in TS | CAMRip and as if it appears in HDRip or BDRip Download it

```
my config.yml
  movies:
    metainfo_movie: yes
    tmdb_lookup:
      language: ru
    set:
      path: /var/media/hdd/movies/{{movie_name_rus}} ({{tmdb_year}})

tasks:
  movies:
    template:
      - transmission
      - notifycation
      - movies
    manipulate:
      - title:
          # extract: (.*)\s\/.+?(.\d+.)\s(.*)
          extract: (.*)\s\/.+?(.\d+.)\s(.*)
      - my_quality:
          from: title
          extract: '.*\)\s(.*)'
      - screen_size:
          from: title
          extract: '.*\)\s(.*?)\s.*'
      - movie_name_rus:
          from: title
          extract: '(.*)\s\(.*'

    rss: https://nnmclub.to/forum/rss2.php
    regexp:
      accept:
        - 'Великий'
        - 'Охотник за разумом. Схватка'
      from: title

```

**Comment by darrenhoggard** [comment, marked as answer]
would you be able to add:
    regexp:
      from: title
      reject_excluding:
        - TS | CAMrip | HDRip | BDRip

**Reply by maltsevvv** [reply]
```
    regexp:
      from: title
      reject_excluding:
        - TS | CAMRip | WEBRip | WEB-DLRip | HDRip | BDRip
```
`REJECTED: `Don't Breathe 2 (2021) WEB-DLRip` by regexp plugin because regexp 'TS | CAMRip | WEBRip | WEB-DLRip | HDRip | BDRip' didn't match`

if 
```
    regexp:
      from: title
      reject_excluding:
        - TS|CAMRip|WEBRip|WEB-DLRip|HDRip|BDRip
```
`Would download: Don't Breathe 2 (2021) WEB-DLRip`


thanks, let's see how it works
