### DISCUSSION TITLE
Attempting to read other fields from RSS fields and then use regexp to filter out based on strings

### DISCUSSION THREAD

**Discussion by Nimmo** [Flexget/Flexget#3344] [Q&A]
I'm working with an RSS feed from a site and I'm looking to try to use an extra field beyond the title to help filter out results that I don't want based on tags that the item has associated with it.

I've tried using the following as part of my RSS plugin:
```
other_fields: 
         - tags
         - comments
```

This is working for comments, as when I push the accepted article's details out with notify I'm getting the value that's in that field, however, whenever I try to use tags it's not displaying the tags associated with that release. I'm also trying to use regexp to filter out, but it seems that the tags aren't actually being used to filter out the items I don't want.

The following regexp block is still allowing items tagged with 2160p and MegaPack in them:

```
regexp:      
      accept_excluding:
       - 'MegaPack': {from: tags}
       - 2160p: {from: tags}
       - 480: {from: tags}
       - 540: {from: tags}
```

In the event that it helps point out my (hopefully painfully obvious) error, here's an edited version of an item I thought should have been rejected:
```
<item>
<title>
not-rejected item title
</title>
<link>...?id=791984</link>
<pubDate>Thu, 03 Feb 2022 20:25:26 +0000</pubDate>
<description>
...
</description>
<tags>
1080p x265 x265.reencode x265.10bit hevc.x265 MegaPack
</tags>
<dc:creator>anon</dc:creator>
<comments>...id=791984</comments>
<guid>item-guid</guid>
</item>
```
