### DISCUSSION TITLE
Best Practices/Recommendations for new Flexget Setup

### DISCUSSION THREAD

**Discussion by lamski** [Flexget/Flexget#3348] [General]
In the next couple of days, I'm going to update my Ubuntu server from `14.04` to `20.04`.
I'm going to do a clean install - I have my OS installed on a micro SD card and 34TB worth of drives setup with LVM2.
Reading the Flexget install guide, it is recommended to use python `venv` and install flexget there.

1. What's a good location to setup the `venv` for flexget? I'm thinking of using `/opt/flexget` for this.
2. Where should I save the `config.yml`?
3. Is there a way to break-up the `config.yml`? For example, I want to have a separate file for the series shows and just refer to it in the main config file.

What other tips can you guys recommend?

**Comment by lamski** [comment]
So, I finally finished with my server upgrade. Here were the tasks that I did to do a clean install of Ubuntu server 20.04:

1. Made a backup of my old transmission data including `/etc/transmission-daemon/settings.json` and `/var/lib/transmission-daemon/.config/transmission-daemon` - this is important if you want to have transmission continue with your existing torrents.
2. Make a backup of my flexget files: `config.yml`, `db-config.sqlite`, and `variables.yml`.
3. I opted use a new SD card for the new OS install. This way, it was easy to go back and boot to the old server if needed.
4. Installed Ubuntu server 20.04 to the new SD card. There was an option to install Open SSH and an option to mount my old LVM2 drives on bootup right in the installer, which is a nice touch.
5. After installing, the first things I did was to install samba to make sure that the media folders are accessible remotely.
6. Next was to install transmission from the official transmissionbt PPA. I used my backup of `settings.json` to restore access to the web interface. This will install version 3.00 of transmission.
7. After that I attempted to download some small torrents. I had to fix some permission issues. The transmission daemon runs under the `debian-transmission` user and group and it was saving to the samba folders which use `nouser` and `nogroup`. I had to add `debian-transmission` to the `nogroup` group to fix this.
8. Next was to copy the backup of `/var/lib/transmission-daemon/.config/transmission-daemon`. After restarting transmission, the old torrents were back as they were.
9. The next step was to install flexget. I followed the guides and created a python venv on `/opt/flexget` and installed flexget there, together with `transmission-rpc`, and `cfscrape`.
10. Next was to copy `config.yml` and `variables.yml` to `/etc/flexget`. Running `<flexget venv>/bin/flexget check` while in `/etc/flexget` will check the configuration and create a new `db-config.sqlite`.
11. Last step was to follow the guide on setting up the flexget daemon to run a system unit.

Overall, it took me a couple of hours, mostly googling commands I've forgotten or are new in Ubuntu 20.04.

**Comment by stranger-danger-zamu** [comment]
I primarily use flexget to watch RSS and download torrents. So, for me set up if fairly straight forward with 5 general items: 

* Torrent Client 
    - I choose transmission since it had all the things I needed and remote UI support.
* RSS configuration 
    - This is all baked into my flexget config with each feed as a Flexget Template. I then set up a task per feed and then add series I want to track per feed under the new task (which also defines the download location for each series).
    - Replace `CHANGEME`, `type1`, and `feed1` with good names and add more series:
      ```yml
      templates:
        torrent:
          notify:
            entries:
          transmission:
            host: localhost
            port: 39099
            username: <CHANGEME>
            password: "<CHANGEME>"
            ratio: 1.0
        feed1:
          if:
            - "'batch' in title.lower()": reject
          series:
            settings:
              type1:
                identified_by: sequence
                quanlity: 1080p
          rss:
            url: https://www.example.com/?page=rss
            link: ["link", "magneturi"]
      
      tasks:
        type1-feed1:
          template: ["torrent", "feed1"]
          series:
            type1:
              - <series title>:
                  path: /path/to/series/title
      ```
* Storage
    - I store onto one of my local disks and the locations are set per series within a task. 
* Flexget
    - I use pipx for a lot of python stuff, but for a gentler introduction you can manually set up the virtualenv in `/opt/flexget/venv`
* Service Management
    - I dislike the idea of having flexget operate as a daemon if its not doing anything. Instead I just run flexget execute via systemd.

To migrate my current flexget instance onto a new server, I'd:

1. Spin up a new server (Fedora server is neat!), and install the minimal requirements (ie. python3, transmission)
    ```bash
    sudo dnf install python3 transmission-daemon
    ```
3. Set up the virtualenv, and flexget:
    ```bash
    sudo mkdir /opt/flexget
    sudo chown -R $(whoami):$(whoami) /opt/flexget
    sudo chmod 750 /opt/flexget
    python3 -m venv --copies /opt/flexget/venv
    /opt/flexget/venv/bin/python -m pip install --upgrade pip wheel
    /opt/flexget/venv/bin/pip install flexget transmission-rpc
    sudo ln -s /opt/flexget/venv/bin/flexget /usr/local/bin/flexget
    mkdir ~/.config/flexget
    touch ~/.config/flexget/config.yml
    ```
4. Copy over the config file
   ```bash
   # on the old server
   rsync -avhz ~/.config/flexget/config.yml newserver:~/.config/flexget/config.yml
   ```
5. Configure user systemd service and enable lingering for the user:
   ```ini
   # ~/.config/systemd/user/flexget.service
   [Unit]
   Description=`flexget execute` service

   [Service]
   Environment="PATH=/opt/flexget/venv/bin"
   Type=simple
   ExecStart=flexget execute --now

   [Install]
   WantedBy=default.target
   ```
   ```ini
   # ~/.config/systemd/user/flexget.timer
   [Unit]
   Description=Schedule running flexget approx. every 6 hours

   [Timer]
   Persistent=true
   OnUnitInactiveSec=6h
   OnBootSec=120

   [Install]
   WantedBy=timers.target
   ```
   ```bash
   sudo loginctl enable-linger $(whoami)
   systemctl --user daemon-reload
   systemctl --user enable --now flexget.timer
   ```
6. Done!

With all this, flexget gets run periodically and there is logging of any runtime issues.
