### DISCUSSION TITLE
urlrewriter template for kinozal.tv

### DISCUSSION THREAD

**Discussion by v-milenin** [Flexget/Flexget#3390] [Show and tell]
```
 kinozal:
    headers:
      Cookie: "uid=*******; pass=*************"
    rss:
      url: http://kinozal.tv/rss.xml
      link: guid
    urlrewrite:
      kinozal:
        regexp: 'http://kinozal\.tv/details\.php\?id=(?P<id>\d+)'
        format: 'http://dl.kinozal.tv/download.php?id=\g<id>'
```

**Comment by v-milenin** [comment]
Some updates since it has been changed to https:

```
 kinozal:
  headers:
    Cookie: "uid=*******; pass=*************"

  rss:
    url: http://kinozal.tv/rss.xml
    link: guid
    title: guid

  template:
      - tvshows

   manipulate:
      - title:
          replace:
            regexp: 'https://kinozal.tv/details.php\?id=(?P<id>\d+)'
            format: '\g<id>'
      - guid:
          replace:
            regexp: 'https://kinozal.tv/details.php\?id=(?P<id>\d+)'
            format: 'https://dl.kinozal.tv/download.php?id=\g<id>'
  urlrewrite:
    kinozal:
      regexp: 'https://kinozal.tv/details.php\?id=(?P<id>\d+)'
      format: 'https://dl.kinozal.tv/download.php?id=\g<id>'

  include: /kinozal-list.yml
```
