### DISCUSSION TITLE
get only files instead of creating a dir

### DISCUSSION THREAD

**Discussion by khunalex** [Flexget/Flexget#3424] [General] [answered]
Hi.

Is it possible to avoid creating a directory for every downloaded torrent? The current behavior I got do as follows:
->tvshow_name>season_x->episode_name_as_dir->multiple_files

And I would like to just get 
->tvshow_name->season_x->episode_name_as_file

I tried with skip_files but I might setup sth wrong, since I keep receiving .nfo, .exe, .txt files packed in the torrent.

Here is my config.yml

````
web_server:
  bind: 0.0.0.0
  port: 3539

templates:
  tvshows:
      private_torrents: no
    series:
      settings:
        tvshows:
          season_packs: yes
          exact: yes
          propers: 10 hours
          quality: 720p+
          set:
            path: '/media/Series/{{series_name}}/Season {{series_season}}'
            include_subs: yes
            retrieve: files
            mask: '*.mkv'
         regexp: '.*\.(avi|mkv|mp4|m4v|iso)$'
      tvshows:
        - Better Call Saul
        - Stranger Things

    transmission:
      enabled: Yes
      host: localhost
      port: 9091
      username: 'myusername'
      password: 'mypasswd'
      ratio: -1
      main_file_only: Yes
      path: /media/torrents
      main_file_ratio: 0.70
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*[sS]ample*'
        - '*.exe'
        - '*.txt'
      include_subs: Yes

tasks:
  showrss:
    priority: 1
    rss: https://showrss.info/user/xxxxxxx
    template: tvshows
```

**Comment by khunalex** [comment, marked as answer]
I found a way, but not sure it's the best practice way.
Adding this to showrss task works fine:

```
    filesystem:
      path: /DOWNLOADPATH
      regexp: '.*\.(mkv|mp4|avi)$'
      recursive: yes
    move:
      to: '/media/Series/{{series_name}}/Season {{series_season}}'
```
