### DISCUSSION TITLE
Language Filter

### DISCUSSION THREAD

**Discussion by belzebub40k** [Flexget/Flexget#3454] [Q&A]
Hi, I've started to use Flexget a few days ago but I'm struggling a bit setting up the last missing thing. I'm using an indexer which provides all foreign languages in one feed. As I only care about one language I would like to filter only for this one language. I've look through the documentation but could not find any setting solving my problem. I guess using `regexp` is the correct way buy I wasn't able to build a filter which rejects all entries for other languages before applying the `series` filter.

This is my currenct config. Could anybody push me in the right direction?

```
tasks:

  Series-Foreign:
    rss: http://example.net/rss/foreign

    series:
      1080p:
        - Series A
        - Series B
        - ...

    nzbget:
      url: http://localhost:6789/xmlrpc
      category: Series

```
