### DISCUSSION TITLE
How to handle correctly timedelta and local timezone?

### DISCUSSION THREAD

**Discussion by Jorman** [Flexget/Flexget#3471] [Q&A]
Hi, I've some problem with timedelta, seems that Flexget don't recognize my local timezone and `rss_pubdate` are interpreted like +0000

I live in CEST time that actually is UTC +0200 so, if here is 22pm my pubdate inside one xml is some like that `<pubDate>Mon, 06 Jun 2022 21:55:00 +0000</pubDate>`
My Flexget if condition is:
```
    if:
      - "rss_pubdate >= now - timedelta(minutes=30)": accept
```
But Flexget don't grab the release, my idea is that since I live in CEST, I expect the pubdate time to be "converted" with my local time, is that the case or do I need to configure Flexget to tell it my Timezone? In the latter case, however, I have to watch out for the annual time change.

What am I doing wrong?

**Comment by aidan-** [comment]
I think some more information is required.  Can you please share your Flexget configuration and some output logs running with debug logging?

**Comment by Jorman** [comment]
Hi @aidan-  sure
this's the flexget configuration:
```
tasks:
  freeleech:
    rss:
      url: file:///tmp/testrss/ZDRkYTY5.xml
      other_fields: ['downloadvolumefactor','uploadvolumefactor']
    disable: backlog
    if:
      ##### ALPHARATIO START RULES #####
      - "'alpharatio' in guid and size >= 77309411328 and size < 128849018880 and downloadvolumefactor == '0' and rss_pubdate >= now - timedelta(minutes=10)": accept # Only from AlphaRatio with size >= 72Gb and < 120Gb within the last 10 minutes
      - "'alpharatio' in guid and size >= 2147483648 and size < 10737418240 and downloadvolumefactor == '0' and rss_pubdate >= now - timedelta(minutes=10)": accept # Only from AlphaRatio with size >= 2Gb and < 10Gb within the last 10 minutes
      - "'alpharatio' in guid and size >= 1073741824 and size < 2147483648 and downloadvolumefactor == '0' and rss_pubdate >= now - timedelta(minutes=10)": accept # Only from AlphaRatio with size >= 1Gb and < 2Gb within the last 10 minutes
      - "'alpharatio' in guid and size <= 536870912 and downloadvolumefactor == '0' and (rss_pubdate >= now - timedelta(minutes=30))": accept # Only from AlphaRatio with size <= 500Mb within the last 30 minutes
      ##### ALPHARATIO STOP RULES #####
    qbittorrent:
      host: 10.0.0.100
      port: 8081
      label: FreeLeech
    free_space:
      path: /data/Sharing
      space: 50000
```
And here you can find the debug log
https://pastebin.com/YxAHEHgK

I think is only a temporary problem, I saw some working on tzinfo, so maybe I only have to wait

Let me know if you need extra test or if you need to have the xml file, maybe you can change the timezone and try accordingly your region

J
