### DISCUSSION TITLE
Edit series name and episodes for search in discover

### DISCUSSION THREAD

**Discussion by javikobcn** [Flexget/Flexget#3504] [Q&A]
hi, it's possible to put a custom names on discover to refer to a season and episode?
by default it comes with a "s03e08" but I have some series with the name "cap.308" and the search returns 0 results.

Im using a torznab to search by bt4g engine search but with the standard search i can't find what i want (i only want spanish versions which have specific titles).
There is an example of my config:

```
templates:

  rss-series:
    accept_all: yes
    series:
######default##########
       - vikings:
           alternate_name:
             - atomohd vikingos
             - vikingos hdtv
             - atomixhq vikingos
           begin: S06E16
#######What I tried without result#########
       - vikingos:
           name_regexp:
             - vikingos cap 616
             - descargas2020 vikingos
             - vikingos hdtv
           id_regexp: cap 616
########################## 
    regexp:
      from: title
      reject:
        - subtitulado
        - eng
        - rus
        - ita 
    thetvdb_lookup: yes
    discover:
       release_estimations:
         optimistic: 30 days
       what:
         - next_series_episodes: yes
       from:         
         - torznab:
           ###########BT4G############
             website: http://blabla.duckdns.org:9117/api/v2.0/indexers/bt4g/results/torznab/
           ############Dontorrent##########
             website: http://blabla.duckdns.org:9117/api/v2.0/indexers/dontorrent/results/torznab/    
             apikey: apikey
             searcher: tv             
       interval: 1 day
```

With that I only obtain the first results named vikings s06e16 and next episodes but not what I want.
