### DISCUSSION TITLE
Flexget not downloading 1080p when no 2160p is found. Config error?

### DISCUSSION THREAD

**Discussion by 1337ingDisorder** [Flexget/Flexget#3534] [Q&A]
I just noticed that there have been some episodes posted that should have been downloaded by flexget, but weren't.

My config is set up to wait up to 24 hours for a 2160p version to be posted, and then failover to 1080p if no 4K version is found.

Here's the config:

```
templates:
  tv2160:
    series_premiere: yes
    series:
      settings:
        2160p:
          quality: 1080p-2160p
          target: 2160p h265
          timeframe: 24 hours
          tracking: no
          propers: yes
          upgrade: yes
      2160p:
        - Wild Switzerland

tasks:
  main_tv:
    rss: (url)
    template: 
      - tv2160
    download: /shared/torrents/
```

There are other series in the list, but for the sake of brevity I've snipped all but the relevant series.

I've just checked and three episodes have been released, all in 1080p, but only the first episode was downloaded by Flexget. (Flexget runs on a cron job every 30 minutes, and it typically takes about 12 hours for shows to get bumped from the RSS feed, so it's unlikely flexget failed to see the 1080p versions.)

Have I messed up the config?
