### DISCUSSION TITLE
Matching regex returned as UNDECIDED

### DISCUSSION THREAD

**Discussion by ghost** [Flexget/Flexget#3546] [Q&A] [answered]
Are there some default configs that make Flexget ignore results not featuring certain criteria? (ex: lack of proper quality keyword in title)
`[NC-Raws] 转生成为魔剑 / Tensei shitara Ken Deshita - 01 (B-Global 3840x2160 HEVC AAC MKV)`

Manual `execute` shows the entry is left undecided
```
pi@raspberrypi:~ $ flexget execute -v --tasks "seasonal-misc" | grep "Tensei shitara Ken Deshita"
2022-10-01 19:51:20 VERBOSE  verbose       seasonal-misc   UNDECIDED: `[NC-Raws] 转生成为魔剑 / Tensei shitara Ken Deshita - 01 (B-Global 3840x2160 HEVC AAC MKV)`
```
although the line in the config matches when trying regex interactively
```
-------------------------------------------------------------------------------
Hi there, welcome to try regexps in realtime!
Press ^D or type 'exit' to continue. Type 'continue' to continue non-interactive execution.
Task 'seasonal-misc' has 211 entries, enter regexp to see what matches it.
--> Tensei shitara Ken Deshita
Title: [NC-Raws] 转生成为魔剑 / Tensei shitara Ken Deshita - 01 (B-Global 3840x2160 HEVC AAC MKV) URL:
https://nyaa.si/download/1584037.torrent From: original_title
1 of 211 entries matched
--> exit
Bye!
```
My portion of the configs featuring the task
```yaml
  seasonal-misc:
    template: seasonal
    inputs:
      - rss: https://nyaa.si/?page=rss&q=1080p+-batch&c=0_0&f=0&u=Erai-raws
      - rss: https://nyaa.si/?page=rss&q=1080p+-batch&c=0_0&f=0&u=gst
      - rss: https://nyaa.si/?page=rss&c=1_2&f=0&u=BraveSail
    regexp:
      reject:
        - \[v[2-9]\]
        - \d{1,2}v[2-9]
      from: title
    series:
      - Tensei shitara Ken Deshita
      - Isekai Ojisan:
          identified_by: sequence
```

**Comment by BrutuZ** [comment, marked as answer]
The entry is not being recognized because of the kanji between the group name and romaji, there's no built-in logic for that.
Either of those new lines fix it, pick your preference:
```diff
    series:
      - Tensei shitara Ken Deshita:
+         name_regexp: ['Tensei shitara Ken Deshita']
+         alternate_name: ['转生成为魔剑 / Tensei shitara Ken Deshita']
```

**Reply by BrutuZ** [reply]
Alternatively you can also add a [`manipulate`](https://flexget.com/Plugins/manipulate) to the task to dynamically remove those from every entry:
```yaml
    manipulate:
      - title:
          replace:
            regexp: '] [฀-﫿！-￮]+ / '
            format: '] '
```
The range between Unicode 0E00 and FAFF should cover most [CJK characters](https://en.wikipedia.org/wiki/CJK_characters), along with full-width symbols often used with them, which will make Flexget rewrite the title from
`[NC-Raws] 转生成为魔剑 / Tensei shitara Ken Deshita - 01 (B-Global 3840x2160 HEVC AAC MKV)`
to
`[NC-Raws] Tensei shitara Ken Deshita - 01 (B-Global 3840x2160 HEVC AAC MKV)`
which will match, with the added benefit you don't have to specify for every show.

**Reply by ghost** [reply]
I tried expanding your regex example by matching it against a list of entries from real RSS feeds. I also noticed sometimes illegal characters like `:` are used which forces you to wrap quotation marks around the title so I chained two title replace. My regex has still problems with mixed entries like `IDOLiSH7` one but it's good enough and it covers 99% of the use cases.
```yml
    manipulate:
      # Reformat NC-Raws weird titles
      - title:
          replace:
            regexp: '^(\[.+?\]) [฀-﫿Α-Ωα-ωA-Za-z0-9\s・，：！-]+? \/ '
            format: '\1 '
      # Remove YML breaking characters from title
      - title:
          replace:
            regexp: ':'
            format: ''
```
```
[NC-Raws] 死神 千年血战篇 / Bleach: Sennen Kessen-hen - 10 (B-Global 3840x2160 HEVC AAC MKV)
[NC-Raws] 新人炼金术师的店铺经营 / Shinmai Renkinjutsushi no Tenpo Keiei - 11 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 新人炼金术师的店铺经营 / Shinmai Renkinjutsushi no Tenpo Keiei - 11 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 致不灭的你 第二季 / Fumetsu no Anata e 2nd Season - 08 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 彼得・格里爾的賢者時間 Super Extra / Peter Grill to Kenja no Jikan: Super Extra - 10 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 彼得・格里尔的贤者时间Super Extra / Peter Grill to Kenja no Jikan: Super Extra - 10 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] IDOLiSH7 - 偶像星願 - Third BEAT！ - 24 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 夫婦以上，戀人未滿 / Fuufu Ijou Koibito Miman. - 10 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 夫妇以上 恋人未满 / Fuufu Ijou Koibito Miman. - 10 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 致不灭的你 第二季 / Fumetsu no Anata e 2nd Season - 08 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 機動戰士鋼彈 水星的魔女 / Mobile Suit Gundam: The Witch from Mercury - 10 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 博人传之火影忍者次世代 / Boruto: Naruto Next Generations - 279 (B-Global 3840x2160 HEVC AAC MKV)
[NC-Raws] 博人传之火影忍者次世代 / Boruto: Naruto Next Generations - 279 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 机动战士高达：水星的魔女 / Mobile Suit Gundam: The Witch from Mercury - 10 (B-Global 3840x2160 HEVC AAC MKV)
[NC-Raws] 仙王的日常生活 第三季 / The Daily Life of the Immortal King S3 - 12 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 海贼王 / One Piece - 1044 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 炼气练了3000年 / Qi Refining for 3000 Years - 11 (B-Global Donghua 1920x1080 HEVC AAC MKV)
[NC-Raws] 数码宝贝：幽灵游戏 / Digimon Ghost Game - 55 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 海贼王 / One Piece - 1044 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 美味派对♡光之美少女 / Delicious Party Pretty Cure - 39 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 四人各有小秘密 / 4-nin wa Sorezore Uso wo Tsuku - 09 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 藍色監獄 / Blue Lock - 10 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] Pop Team Epic S2 - 11 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 烙印勇士 黃金時代篇 / Berserk: Ougon Jidai-hen - Memorial Edition - 11 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 四人各有小秘密 / 4-nin wa Sorezore Uso wo Tsuku - 09 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 传颂之物 二人的白皇 / Utawarerumono: Futari no Hakuoro - 25 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 孤獨搖滾！ / Bocchi the Rock! - 10 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 後宮之烏 / Koukyuu no Karasu - 11 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 蓝色监狱 / Blue Lock - 10 (B-Global 3840x2160 HEVC AAC MKV)
[NC-Raws] 烙印勇士 黃金時代篇 MEMORIAL EDITION / Berserk: Ougon Jidai-hen - Memorial Edition - 11 (B-Global 1920x816 HEVC AAC MKV)
[NC-Raws] 间谍过家家 / SPY×FAMILY - 23 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 孤独摇滚！ / Bocchi the Rock! - 10 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 传颂之物 二人的白皇 / Utawarerumono: Futari no Hakuoro - 25 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 被勇者隊伍開除的馭獸使，邂逅了最強種的貓耳少女 / Yuusha Party wo Tsuihou sareta Beast Tamer - 11 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 宇崎学妹想要玩！ω / Uzaki-chan wa Asobitai! Double - 11 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 因為是反派大小姐所以養了魔王 / Akuyaku Reijou nanode Last Boss - 12 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 间谍过家家 / SPY×FAMILY - 23 (B-Global 3840x2160 HEVC AAC MKV)
[NC-Raws] 入间同学入魔了 第三季 / Mairimashita! Iruma-kun S3 - 10 (B-Global 3840x2160 HEVC AAC MKV)
[NC-Raws] 宇崎学妹想要玩！第二季 / Uzaki-chan wa Asobitai! Double - 11 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 因为是反派大小姐所以养了魔王 / Akuyaku Reijou nanode Last Boss - 12 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 點滿農民相關技能後，不知為何就變強了。 / Noumin Kanren no Skill - 11 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 入间同学入魔了 第三季 / Mairimashita! Iruma-kun S3 - 10 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 点满农民相关技能后，不知为何就变强了。 / Noumin Kanren no Skill - 11 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 我的英雄学院 第六季 / Boku no Hero Academia S6 - 124 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 我的英雄学院 第六季 / Boku no Hero Academia S6 - 11 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 元龙 第三季 / Carp Reborn 3rd Season - 04 (B-Global Donghua 1920x1080 HEVC AAC MKV)
[NC-Raws] 三寸人间 / A World Worth Protecting - 15 (B-Global Donghua 1920x1080 HEVC AAC MKV)
[NC-Raws] 影之诗F / Shadowverse Flame - 36 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 民调局异闻录 / Bureau of Paranormal Investigation - 04 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 惑星公主蜥蜴騎士 / Hoshi no Samidare - 22 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 圣剑传说 / Seiken Densetsu: Legend of Mana - The Teardrop Crystal - 10 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 惑星公主蜥蜴骑士 / Hoshi no Samidare - 22 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 明日方舟：黎明前奏 / Arknights: Reimei Zensou - 07 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 圣剑传说 玛娜传奇 -泪珠水晶- / Seiken Densetsu - 10 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 万圣街 / All Saints Street - 05 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 我家师傅没有尾巴 / Uchi no Shishou wa Shippo ga Nai - 11 (B-Global 3840x2160 HEVC AAC MKV)
[NC-Raws] 我家師傅沒有尾巴 / Uchi no Shishou wa Shippo ga Nai - 11 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 血与心 / Blood and heart: The legendary life of a Japanese youth in China - 07 (B-Global Donghua 1920x1080 HEVC AAC MKV)
[NC-Raws] 世界末日与柴犬同行 / Sekai no Owari ni Shiba Inu to - 2022111147 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 世界末日与柴犬同行 / Sekai no Owari ni Shiba Inu to - 2022111548 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 世界末日与柴犬同行 / Sekai no Owari ni Shiba Inu to - 55 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 银河英雄传说：全新命题 策谋 / Gineiden: Sakubou - 47 (CR 1920x1080 AVC AAC MKV)
[NC-Raws] 银河之心 / Foreordination - 08 (B-Global Donghua 1920x1080 HEVC AAC MKV)
[NC-Raws] 两不疑 第二季 / No Doubt In Us S2 - 08 (B-Global Donghua 1920x1080 HEVC AAC MKV)
[NC-Raws] 银河英雄传说：全新命题 策谋 / Gineiden: Sakubou - 11 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] Chiikawa - 17 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 福星小子 / Urusei Yatsura (2022) - 09 (B-Global 3840x2160 HEVC AAC MKV)
[NC-Raws] 秋叶原女仆战争 / Akiba Maid Sensou - 10 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 秋叶原女仆战争 / Akiba Maid Sensou - 10 (B-Global 1920x1080 HEVC AAC MKV)
[NC-Raws] 书虫公主 / Mushikaburi-hime - 10 (Sentai 1920x1080 AVC AAC MKV)
[NC-Raws] 书虫公主 / Mushikaburi-hime - 10 (B-Global 1920x1080 HEVC AAC MKV)
```

**Reply by BrutuZ** [reply]
That's fine and all, but if it came down to expanding the character group so much to even include 0-9a-Z I probably would have just gone nuclear and dumbed it down to
```yaml
regexp: '\[NC-Raws] .+? / '
format: '[NC-Raws] '
```
Seems it would achieve the same with less complications since they separate original title and romaji with a ` / `, only exception there is the IDOLiSH7 you mentioned, but it probably would match series title anyways since it's at the start of the parsed string, if not it's easier to add an exception for it in `series` like in the original answer 😆

**Reply by ghost** [reply]
Fair enough. I just added a positive lookahead that looks for CJK characters so I'm sure it's a valid entry that needs reformatting:
```yml
    manipulate:
      # Reformat NC-Raws weird titles
      - title:
          replace:
            regexp: '^(\[.+?\]) .*(?=[฀-﫿]).+? \/ '
            format: '\1 '
```

**Reply by ghost** [reply]
I've been experimenting on a dummy database and I'm experiencing UNDECIDED results once again
```yml
tasks:
  nyaa:
    template: anime
    transmission:
      username: 'transmission'
      password: 'password'
      path: /mnt/c/Users/User/Downloads
    inputs:
      - rss: https://nyaa.si/?page=rss&q=-batch&c=1_2&f=0&u=BraveSail
    series:
      2160p:
        - Bleach Sennen Kessen-hen

templates:
  anime:
    if:
      - "'[NC-Raws]' in title":
          manipulate:
            - title:
                replace:
                  regexp: '^(\[NC-Raws\]) .*(?=[฀-﫿]).+? \/ '
                  format: '\1 '
            - title:
                replace:
                  regexp: ':'
                  format: ''
          set:
            content_filename: "{{ title }}"
```
The title is correctly reformatted
```
2022-12-19 21:23:46 VERBOSE  manipulate    nyaa            Field `title` is now `[NC-Raws] Bleach: Sennen Kessen-hen - 11 (B-Global 3840x2160 HEVC AAC MKV)`
2022-12-19 21:23:46 VERBOSE  manipulate    nyaa            Field `title` is now `[NC-Raws] Bleach Sennen Kessen-hen - 11 (B-Global 3840x2160 HEVC AAC MKV)`
2022-12-19 21:23:46 VERBOSE  manipulate    nyaa            Modified 71 entries.
2022-12-19 21:23:46 VERBOSE  details       nyaa            Summary - Accepted: 0 (Rejected: 0 Undecided: 75 Failed: 0)
```
but the entry is left UNDECIDED. What is going on?

**Reply by BrutuZ** [reply]
Because `series` runs before `if` (see https://flexget.com/Plugins/plugin_priority).

You can either move the manipulate to the task root (it's redundant anyways since the expression itself already limits it) or reorder the plugins execution making `series` run after `if` (whether you raise the priority of `if` or lower `series` is up to you).

```yaml
tasks:
  test:
    mock:
      - {title: '[NC-Raws] 死神 千年血战篇 / Bleach: Sennen Kessen-hen - 11 (B-Global 3840x2160 HEVC AAC MKV)'}
    if:
      - "'[NC-Raws]' in title":
          manipulate:
            - title:
                replace:
                  regexp: '^(\[NC-Raws\]) .*(?=[฀-﫿]).+? \/ '
                  format: '\1 '
            - title:
                replace:
                  regexp: ':'
                  format: ''
          set:
            content_filename: "{{ title }}"
    series:
      2160p:
        - Bleach Sennen Kessen-hen
    plugin_priority:    # removing these will go back to Undecided
      series: 75
```

**Reply by BrutuZ** [reply]
Probably worth noting: You don't have to remove semicolons from the title, just enclose the title in quotes
```yaml
series:
  2160p:
    - 'Bleach: Sennen Kessen-hen'
```
