### DISCUSSION TITLE
Finished torrents left UNDECIDED by only_complete rule

### DISCUSSION THREAD

**Discussion by ghost** [Flexget/Flexget#3547] [Q&A] [answered]
Finished torrents that met ratio goal are left `undecided` by my `cleaner` task. The `if` condition correctly prevents some torrents in a specific directory from being removed but for some reason the `only_complete` rule doesn't appear to be affecting the others.

I thought this rule was enough to clear finished torrents that met ratio goal. Should I move everything under `if` instead?
```yml
  cleaner:
    template: transmission
    manual: yes
    from_transmission:
      username: transmission
      password: my-password
      only_complete: yes
    disable: [seen, seen_info_hash]
    if:
      - "'.seedbox' in transmission_downloadDir": reject
    transmission:
      action: remove
```
```sh
# crontab
flexget --cron execute --tasks cleaner
```
`Rejected` entry dump
```
transmission_downloadDir       : /home/pi/Downloads/.seedbox
transmission_errorString       :
transmission_error_state       : OK
transmission_id                : 3
transmission_idle_limit_ok     : True
transmission_isFinished        : False
transmission_isPrivate         : False
transmission_leftUntilDone     : 0
transmission_priority          : normal
transmission_progress          : 100.0
transmission_ratio             : 171.9609
transmission_secondsDownloading: 0
transmission_secondsSeeding    : 62398934
transmission_seed_ratio_ok     : True
transmission_status            : seeding
```
`Undecided` entry dump
```
transmission_downloadDir       : /home/pi/Downloads
transmission_errorString       :
transmission_error_state       : OK
transmission_id                : 5
transmission_idle_limit_ok     : True
transmission_isFinished        : True
transmission_isPrivate         : False
transmission_leftUntilDone     : 0
transmission_priority          : normal
transmission_progress          : 100.0
transmission_ratio             : 2.0001
transmission_secondsDownloading: 2697
transmission_secondsSeeding    : 6342
transmission_seed_ratio_ok     : True
transmission_status            : stopped
```
