### DISCUSSION TITLE
Basic config for accepting all rss entries for transmission?

### DISCUSSION THREAD

**Discussion by ghost** [Flexget/Flexget#3554] [Q&A]
I want to create a task to pull all entries from a torrent rss feed and add them to transmission. I've looked at the cookbook but can't find recipe which doesn't match using a list. I do not need a filter as I want *all* rss entries - is this not possible? 

Basic task config: 

```
  download-task1:
    rss: 
      url: https://rss.url
    accept_all: yes
    transmission:
      <<: *transmission
      path: '{? transmission.downloads ?}/foldername/'
```
This produces 75 entries and rejects all of them. I have tried to reset the seen plugin; no difference. There is zero output in the log when running the task.
