### DISCUSSION TITLE
Local series cache for configure_series

### DISCUSSION THREAD

**Discussion by girtsl** [Flexget/Flexget#3636] [Ideas] [answered]
I use trakt lists as input almost exclusively and with trakt now being down for several days it has exposed an issue - my series tasks have stopped working. 
```yaml
    configure_series:
      from:
        trakt_list:
          account: '{? trakt.account ?}'
          list: '{? trakt.tv_watchlist ?}'
          type: shows
```
The problem, as I see it, is that `configure_series` when used with a remote source requires the source to be reachable every time the task runs and if it's not - the output is an empty list. 
The one solution that comes to mind would be to use an intermediary or locally cashed list (much like `movie_list`) that can be used when the upstream is not reachable but it seems that series work differently? 
I can see that all the data is in series db (flexget series list all) but it has every series flexget has encountered not just the ones I want and I'm not sure there is a way to use this as an input.

**Comment by BrutuZ** [comment, marked as answer]
Seems like you found out the solution on your own already 🙂
```yaml
tasks:
  build-cache:
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.tv_watchlist ?}'
      type: shows
    accept_all: yes
    list_add:
      - entry_list: series-cache

  use-cache:
    configure_series:
      from:
        entry_list: series-cache
```
