### DISCUSSION TITLE
Create rss with make_rss

### DISCUSSION THREAD

**Discussion by Vctrsnts** [Flexget/Flexget#3646] [General]
Hello,

Good morning,

I am trying, through 'make_rss' to create a file with what I am downloading.
I have a template as follows:
```
podCastCreateRss:
   make_rss:
     file: '/my_file_destination.rss'
     encoding: utf-8
     days: -1
     rsslink: https://myserver.com
     rstitle: My Server Title
     rssdesc: My Server Desc
```

And the tasks:
```
downloadPodcast:
   template:
      -podCastCreateRss
```

And it works that way, because when downloading it creates the RSS for me, but with the original information of the downloaded file, I want it to put my information. That instead of putting the address from where it can be downloaded (origin of the file) to put the address from where it can be downloaded but on my server.

I don't know if I explain myself correctly.

So can this be done? Modify the href of the rss that is created so that instead of putting the original href of the downloaded file, it puts the href of my server ( ex:` http://myserver.com/podcast/20221229-podcast.mp3` ).

Thanks if you can help me
