### DISCUSSION TITLE
Deluge plugin `path` ignored if "Move completed to" option is enabled

### DISCUSSION THREAD

**Discussion by ghost** [Flexget/Flexget#3660] [Q&A]
Is respecting the original Deluge configuration intended behavior or is this possibly a bug? My daemon is set to download files in a folder named `.pending` and then move finished files in the `Downloads` directory.

```yaml
variables: variables.yml
..
templates:
  my-template:
    deluge:
      path: '{? paths.anime ?}'
```
`variables.yml` :
```yaml
..
paths:
  anime: /var/lib/deluge/Downloads/Anime
```

![image](https://user-images.githubusercontent.com/63500907/213216992-531d9219-f73c-4868-ae21-22d68521635b.png)
