### DISCUSSION TITLE
How do I search for series with alternate names?

### DISCUSSION THREAD

**Discussion by carda21** [Flexget/Flexget#3665] [Q&A]
Hey community!

I have been trying for ages without success.  How do I get flexget to match series whether it be via IRC or searching when the torrent name doesn't match the proper series name?

For example:

We are currently watching Anne Rice's Mayfair Witches.  But the torrents are Mayfair.Witches.*

I get my series list from trakt, but i also have a local series.yml file to try and handle these problems.  My local config is:

```
series:
  - "Anne Rice's Mayfair Witches":
      begin: S01E01
      name_regexp: ^Mayfair.Witches
      alternate_name: "Mayfair Witches"
      set:
        tvdb_id: 413074
```
This doesn't seem to work.  Can I have the series configured in multiple locations? (trakt and yml)

Thanks in advance.

**Comment by paranoidi** [comment]
Sorry to disappoint but it's not supported right now

**Comment by viking1304** [comment]
> I get my series list from trakt, but i also have a local series.yml file to try and handle these problems. My local config is:
> 
> ```
> series:
>   - "Anne Rice's Mayfair Witches":
>       begin: S01E01
>       name_regexp: ^Mayfair.Witches
>       alternate_name: "Mayfair Witches"
>       set:
>         tvdb_id: 413074
> ```
> 
> This doesn't seem to work. Can I have the series configured in multiple locations? (trakt and yml)

Try to simplify things instead of over-complicating them. 🙃

I have this in my series.yml

```
series:
  - Riverdale (2017):
      name_regexp: ^Riverdale(.US)?
  - Doctor Who (2005):
      alternate_name: 
        - Doctor Who 2005
  - Titans (2018):
      alternate_name: 
        - Titans 2018
```

So, just add the alternate name or name_regexp, but not both. Do not forget to remove those entries later (after you finish the show) since they will be added to your search, even if you do not have them in the Trakt list.

Include series.yml with the include a command like this in the download task

```
  tv_show_download:
    private_torrents: no
    template:
      - use_deluge
      - tv_show_lookup
    include: series.yml  
    configure_series:
      settings:
        <<: *series_settings      
      from:
        entry_list: tvshow_download_list
```

Some other things might be confusing in my config, but you can ignore them. 🙃
