### DISCUSSION TITLE
How use Torznab plugin ( with jackett )

### DISCUSSION THREAD

**Discussion by Vctrsnts** [Flexget/Flexget#3697] [General]
Hi.

Im trying to use the plugin torznab ( jackett feed ) for download series that have on file `series.yml`.

I read the documentation about this on flexget but is very confuse. I dont undertand how use.

Im trying to create a task ( the example about flexget )
```
  discoverseries:
    discover:
      what:
       # no trakt_list. Only file `series.yml`
        - trakt_list:
            username: <trakt username>
            account: <account set up in CLI>
            list: watchlist
            type: movies
      from:
         torznab:
          website: http://jackett:9117/api/v2.0/indexers/all/results/torznab/api
          apikey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          searcher: tv
          categories:
            - 5040
    accept_all: yes
    trakt_lookup: yes
    quality: 720p+
    sort_by:
      - quality
      - torrent_availability
      - torrent_seeds
   # this option is possible to put 
   <<: *transmissionSettings #configure about transmission
```

But a dont have how change the wath for using a file `series.yml` with `include` option.

The accept torrents is have in title the word `atomohd`and regex `x265` ( this option is possible to make a template )

Thanks a lot

PD: Is possible have any other documentation about flexget with more example or personal examples about diffents options to use with flexget??

**Comment by girtsl** [comment]
I don't think it's possible to have the series list as a variable - see also https://github.com/Flexget/Flexget/discussions/3730, you might have better luck with using trakt or another list as input.
To filter entries:
```yaml
regexp:
  accept:
    - \batomohd\b
    - \bx265\b
```
or
```yaml
regexp:
  reject_excluding:
    - \batomohd\b
    - \bx265\b
```
The difference is that you can use other filters with the first option while the second option will reject a non-matching entry.
