### DISCUSSION TITLE
Block tasks once successful for a period of time?

### DISCUSSION THREAD

**Discussion by mkjustuk** [Flexget/Flexget#3703] [General]
I am using Flexget's awesomeness to routinely (scheduler) scan for new files.  I want to scan very regularly during particular periods of the week (no problem), in order to get the file I'm after as soon after it becoming listed, as possible.  But, I only want the file once that day or so, despite there potentially being more than one matching file available within an hour or so of the first.

So, ideally, I'd like to have the tasks scheduled every 5 mins let's say, but once there's one result accepted, block that task from running for X hours.

**Comment by girtsl** [comment]
Assuming, the task already has a match on an entry - a wild guess and not tested, and the syntax might be wrong too:
```yaml
if:
  - next_run|now <= now:
      set:
        next_run: now + timedelta(hours = X)
        action: accept
  - next_run|datetime.max > now: reject
```
Update: even if the syntax were right, this would set the `next_run` on the entry not the task. It might work if you can make flexget to treat the file match as the same entry. `unique` might help there - https://flexget.com/Plugins/unique
