### DISCUSSION TITLE
Dynamic entry accepts based on accumulated size

### DISCUSSION THREAD

**Discussion by CoolMintChocolate** [Flexget/Flexget#3708] [Q&A]
Hi,

I am trying to create a Flexget task that would free up disk space by removing entries from the Deluge plugin. The difficult part is that I want to do this dynamically, i.e. the task should accept sorted entries (based on its created date) up until the the point where the accumulated size of all accepted entries becomes greater than a particular threshold, then reject everything else.

I'm trying to avoid writing a custom plugin to do this, so I'm checking if there's a plugin (or a combination of plugins) that I can use to achieve this before I start writing custom code. Conceptually something like `set` plugin but on a global environment, not just per-entry.

Thanks in advance!

**Comment by BrutuZ** [comment]
Have you tried something like this?
```yaml
task:
  from_deluge:
    filter:
      state: paused
  accept_all: yes
  set:
    size_quota: '8000 - {{size_quota|d(0)}} - {{content_size|d(0)}}'    # 8000MB is the arbitrary limit
  if:
    - size_quota <= 0: reject
```

All guess-work, just giving you a starting point for the joyful trial-and-error stages xD
