### DISCUSSION TITLE
list_match vs crossmatch

### DISCUSSION THREAD

**Discussion by Nemesis7** [Flexget/Flexget#3709] [Q&A] [answered]
Hi,

- I have two tasks that produce entries, and add them to an entry_list
- I have a download task that uses the entry lists as a filter to the rss feed
- I would expect that the entires in my rss feed would be matched to those in the entry lists, however that doesn't happen
- Tried, `metainfo_series: yes` on both the producer- and the downloader tasks

The flow does work with `crossmatch`, commented out below, however I think it should work with `list_match` as well. What am I missing?

My config:

```yaml
tasks:
  get-watchlist-imdb-series:
    imdb_watchlist:
      user_id: '{? imdb.user_id ?}'
      list: watchlist
    if:
      - imdb_type == 'series': accept
    list_add:
      - entry_list: imdb_watchlist_series

  get-watchlist-plex-series:
    plex_watchlist:
      username: '{? plex.username ?}'
      password: '{? plex.password ?}'
      type: show
    accept_all: yes
    list_add:
      - entry_list: plex_watchlist_series

  download-watchlist-series:
    rss: 
      url: {? rss_feed ?}
      all_entries: no
    metainfo_series: yes
    list_match:
      from:
        - entry_list: plex_watchlist_series
        - entry_list: imdb_watchlist_series
      remove_on_match: no
      single_match: no
    configure_series:
      settings:
        quality: 1080p
      from:
        filesystem: '/tv_shows'
    # crossmatch:
    #   from: 
    #     - entry_list: plex_watchlist_series
    #     - entry_list: imdb_watchlist_series
    #   fields:
    #     - imdb_id
    #   action: accept
    template: torrent_client
    exists_series:
      - /tv_shows/{{ series_name }}/Season {{ series_season }}
    set:
      labels:
        - series
    download: /watch/
```

This might be related: the entries that are added to the `imdb_watchlist_series` don't show the proper metadata (title, series info, images, etc.) where the `plex_watchlist_series` does have the right metadata.
