### DISCUSSION TITLE
Multiple input of "variables.yml" files

### DISCUSSION THREAD

**Discussion by ahuacate** [Flexget/Flexget#3720] [Q&A]
Is it possible to have more than one "variables.yml" files. For example:

In my config.yml lines would be:
```
variables:
  - variables_credentials.yml
  - variables_code.yml

or/

variables: variables_credentials.yml variables_code.yml

```

Where "variables_credentials" would include all the standard plugin usernames and passwords and paths and "variables_code.yml" would include variables such as:
 
```
#---- FlexGet variables

# Regex variables
regex:
  # Regex - video metadata keywords (MVGroup)
  # Lookahead for first metadata keyword in a string (hdtv, 720p,1080p etc)
  mvgroup_quality_metadata: '(?=\.(\d{3,4}[pi]|hdtv|web[-_]?dl|x265|h265|x264|h264|hdtv\.pdtv\.dvd|blu[-_]?ray))'

  # Regex - Broadcaster name only (MVGroup)
  # Lookahead for first word only that identifies a broadcaster (i.e bbc,nhk)
  mvgroup_broadcaster_name: '(?:(bbc\.(?!documentaries)|ch[0-9]?\.|itv\.(?!documentaries)|nhk\.(?!documentaries|world\.documentaries)|s4c\.|sbs\.|ng\.|uktv\.|sky\.|bskyb\.|dw\.(?!documentaries)|canal\.|\(cit\)\.|%28CIT%29\.|arte\.|pbs\.(?!documentaries|specials)|cnn\.|national\.geographic\.)'
```

I am wanting to separate my user credentials from other variables into two different yml files. I do not think the plugin 'include:' will work as I want to pass the variables (i.e {? regex.mvgroup_broadcaster_name ?} ) into my config.yml.

Any ideas or recommendations are much appreciated
