### DISCUSSION TITLE
How to pin down a series to a known tmdb_id or imdb_id number?

### DISCUSSION THREAD

**Discussion by ahuacate** [Flexget/Flexget#3723] [Q&A]
I have a simple task for downloading an RSS feed. The RSS feed file names do not use a proper naming convention. I have used FlexGet manipulate to modify them into a usable filename format. For example:

Old name: Ch4.Dispatches.2023.Undercover.Ambulance.NHS.in.Chaos.1080p.HDTV.x265.AAC.MVGroup.org.mkv
>>>
New name: ch4 - dispatches - Undercover.Ambulance.NHS.in.Chaos.mkv

I know this is the Ch4 Dispatches series "tmdb_id: 6507". I want to match the new file name with a text file (lookup file) I have made and insert the corresponding series ID into the filename on any match. I do not want to use tmdb_lookup etc because I am using FileBot for that task on this particular RSS feed. I want to pin down what I can and can 100% identify using my lookup file before post-processing with FileBot.

ch4 - dispatches - Undercover.Ambulance.NHS.in.Chaos - {id:6507}.mkv

Hope someone can help. 

Here is my task.
```
tasks:
  #---- Torrent RSS file downloads
  # Direct download of all RSS feeds included in tmpl: 'torrent_rss_documentary'
  # Downloaded content requires post-processing by Filebot
  torrent_rss_documentary:
    priority: 2
    # Accept or RSS media files
    template:
      - torrent_rss_documentary
      - manipulate_mvgroup
      - global-settings
      - global-filter
    # The entry has to have these fields
    require_field:
      - title
    regexp:
      from: title
      accept:
        # Set dl values - series
        - '{? mvg.capture_s00e00 ?}':
            set:
              # Set Deluge label
              label: 'flexget-documentary-series'
              # Move completed path
              move_completed_path: '{? storage.downloads_torrent ?}/{? path.documentary_series_src ?}'
              # Rename the "content file" to something nice, deluge specific
              content_filename: "{{ title }}"
        # Set dl values - movie
        - '\({? mvg.capture_year ?}\)':
            set:
              # Set Deluge label
              label: 'flexget-documentary-movie'
              # Move completed path
              move_completed_path: '{? storage.downloads_torrent ?}/{? path.documentary_movies_src ?}'
              # Rename the "content file" to something nice, deluge specific
              content_filename: "{{ title }}"
      accept_excluding:
        # Set dl values - unsorted
        - '{? mvg.capture_s00e00 ?} \({? mvg.capture_year ?}\)':
            set:
              # Set Deluge label
              label: 'flexget-documentary-unsorted'
              # Move completed path
              move_completed_path: '{? storage.downloads_torrent ?}/{? path.documentary_unsorted_src ?}'
              # Rename the "content file" to something nice, deluge specific
              content_filename: "{{ title }}"
    # Deluge downloader
    deluge:
      <<: *deluge_credentials
    # Enable cloudflare scraping
    cfscraper: yes
    # Remember downloaded entries
    seen: local
```

And here is my lookup file. I have used the series layout but maybe this is not required.
```

series:
  - Panorama:
      alternate_name:
        - BBC Panorama
      name_regex:
        - ^(bbc)?[\s._-]+?panorama[\s._-]+?(\((19|20)\d{2}\))?
      set:
        tmdb_id: 5675
        tvmaze_series_id: 8534
        imdb_id: tt0199257
  - Our World:
      alternate_name:
        - BBC Our World
      name_regex:
        - ^(bbc)?[\s._-]+?our[\s._-]+?world[\s._-]+?(\((19|20)\d{2}\))?
      set:
        tmdb_id: 70106
        imdb_id: tt4316706
        tvmaze_series_id: 3521
  - On Assignment:
      name_regex:
        - ^(bbc)?[\s._-]+?on[\s._-]+?assignment[\s._-]+?(\((19|20)\d{2}\))?
      set:
        tmdb_id: 133928
        imdb_id: tt3686200
        tvmaze_series_id: 3581
  - BBC Documentaries:
      name_regex:
        - ^bbc[\s._-]+?documentaries[\s._-]+?(\((19|20)\d{2}\))?
      set:
        tmdb: 220603
  - NHK World Documentaries:
      name_regex:
        - ^nhk[\s._-]+?world[\s._-]+?documentaries[\s._-]+?(\((19|20)\d{2}\))?
      set:
        tvmaze_series_id: 1096
  - NHK Documentaries:
      name_regex:
        - ^nhk[\s._-]+?documentaries[\s._-]+?(\((19|20)\d{2}\))?
      set:
        tvmaze_series_id: 35301
  - DW Documentaries:
      name_regex:
        - ^dw[\s._-]+?documentaries[\s._-]+?(\((19|20)\d{2}\))?
      set:
        tvdb_id: 315664
  - PBS Specials:
      name_regex:
        - ^pbs[\s._-]+?specials[\s._-]+?(\((19|20)\d{2}\))?
      alternate_name:
        - PBS Documentaries
      set:
        tvdb_id: 116381
  - Dispatches:
      alternate_name:
        - BBC Dispatches
      name_regex:
        - ^(bbc)?[\s._-]+?dispatches[\s._-]+?(\((19|20)\d{2}\))?
      set:
        tmdb_id: 6507
        imdb_id: tt1043090
        tvmaze_series_id: 8541
        tvdb_id: 83231
  - Cold War:
      alternate_name:
        - CNN Cold War
      set:
        tmdb_id: 13505
        imdb_id: tt0170896
        tvmaze_series_id: 23097
        tvdb_id: 82560
```
