### DISCUSSION TITLE
Is it possible to use a variable as container for all series names?

### DISCUSSION THREAD

**Discussion by ghost** [Flexget/Flexget#3730] [Q&A]
I'm looking for a way to split series names/groups from the main config file. Is a variable the correct way to do this?
```yaml
variables:
  - credentials.yml
  - series.yml

tasks:
  something:
    inputs:
      - rss: a
      - rss: b
    series: {? myseries ?}
```
```yaml
myseries: |
  - show a
  - show b
  - show c
```

**Comment by ghost** [comment]
Looks like series plugin only accepts list formats, not strings

**Comment by girtsl** [comment]
Not an answer to your question, but you might want to look into using a service such as trakt.tv to manage your lists - https://flexget.com/Plugins/List/trakt_list.

**Comment by gazpachoking** [comment]
Yep, should be possible:
```yaml
variables:
  the_series:
    - series 1
    - series 2
tasks:
  test_task:
    series: "{? the_series ?}"
```
Should work the same if you separate the variables out to a file rather than inline.
