### DISCUSSION TITLE
Use if: and set: to determine by Genre the move_completed_path:

### DISCUSSION THREAD

**Discussion by ahuacate** [Flexget/Flexget#3734] [Q&A]
I am trying to set "move_completed_path" by genre. As a basic setup for a single genre (i.e documentary)  works:
```
    if:
      # Set values for documentary series
      - "'documentary' in trakt_genres|lower or 'documentary' in trakt_series_genre|lower or 'documentary' in tmdb_genres|lower or 'documentary' in imdb_genre|lower or 'documentary' in tvmaze_genres|lower":
          set:
            # Set Deluge label
            label: 'manual-documentary-series'
            # Move completed path
            move_completed_path: '{? storage.downloads_torrent ?}/{? path.documentary_series_src ?}/{{trakt_series_name|default(series_name)|pathscrub: windows}}/'
```
But how to capture for many genres (i.e  Documentary|News|History|Food|Reality|Travel|Sport|War|Biography|Film Noir|Reality-TV|DIY|Espionage|Legal|Nature|Talk|War & Politics) or a variable:
```
genres_documentary: "['Documentary', 'News', 'History', 'Food', 'Reality', 'Travel', 'Sport', 'War', 'Biography', 'Film Noir', 'Reality-TV', 'DIY', 'Espionage', 'Legal', 'Nature', 'Talk', 'War & Politics']"
```

EDIT:

Could not get all the genres to work without an error. Not sure why - even 'espionage' would throw an error. But this works for now in a long-winded way:

```
    if:
      # Set values for documentary series
      - "'documentary' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'news' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'history' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'food' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'war' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'biography' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'nature' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower)":
          set:
            # Set Deluge label
            label: 'manual-documentary-series'
            # Move completed path
            move_completed_path: '{? storage.downloads_torrent ?}/{? path.documentary_series_src ?}/{{trakt_series_name|default(series_name)|pathscrub: windows}}/'
            # Rename the "content file" to something nice, deluge specific.
            content_filename: "{{trakt_series_name|default(series_name)|pathscrub: windows}} - {{trakt_ep_id|default(series_id)}}{% if trakt_ep_name|default(False) %} - {{trakt_ep_name|pathscrub: windows}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}"
            # Keep subtitles
            keep_subs: no
      # Set values for standard series
      - "not ('documentary' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'news' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'history' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'food' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'war' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'biography' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower) or 'nature' in (trakt_genres|lower or trakt_series_genre|lower or tmdb_genres|lower or imdb_genre|lower or tvmaze_genres|lower))":
          set:
            # Set Deluge label
            label: 'manual-series'
            # Move completed path
            move_completed_path: '{? storage.downloads_torrent ?}/{? path.series_src ?}/{{trakt_series_name|default(series_name)|pathscrub: windows}}/'
            # Rename the "content file" to something nice, deluge specific.
            content_filename: "{{trakt_series_name|default(series_name)|pathscrub: windows}} - {{trakt_ep_id|default(series_id)}}{% if trakt_ep_name|default(False) %} - {{trakt_ep_name|pathscrub: windows}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}"
            # Keep subtitles
            keep_subs: yes
```
