### DISCUSSION TITLE
If + regex matching

### DISCUSSION THREAD

**Discussion by ghost** [Flexget/Flexget#3736] [Q&A] [answered]
Is it possible to use `If` plugin and regex expressions? I know I can use simple string comparisons like:
```yaml
if:
  - "'my string' in title":
    manipulate:
      - title:
          replace:
            regexp: '/something/'
            format: '\1'
    set:
      content_filename: "{{ title }}"
```
but what if I want to limit the use of `set` to a certain `manipulate`? I'd have to wrap the entire thing in an `If`. But I can't figure out a way to use regex for the string comparison in `title`.

**Comment by BrutuZ** [comment]
You cannot. But you can add `regexp` to the mix and put `set` under it: https://flexget.com/Plugins/regexp#full-syntax
```yaml
if:
  - "'my string' in title":
    manipulate:
      - title:
          replace:
            regexp: '/something/'
            format: '\1'
regexp:
  from: title
  accept:
    - 'my string|something':
        set:
          content_filename: "{{ title }}"
```

**Comment by BrutuZ** [comment, marked as answer]
On second thought, maybe you can with the [custom Jinja filters](https://flexget.com/Jinja):
```yaml
if:
  - "title|re_search('my( regex)? string')":
      set:
        content_filename: "{{ title }}"
```

**Comment by ghost** [comment]
Since the goal of the regex check is to only set `content_filename` = new `title` only when a manipulation does happen, I could append a simple `If` check at the end comparing `filename` to `content_filename` and applying the changes if the two strings don't match:
```yaml
manipulate:
      - title:
          replace:
            regexp: '/something/'
            format: '\1'
if:
  - "title != content_filename":
      set:
          content_filename: "{{ title }}"
```
