### DISCUSSION TITLE
TransmissionError. Query failed with result "unrecognized info"

### DISCUSSION THREAD

**Discussion by Vctrsnts** [Flexget/Flexget#3768] [General]
Hello,
I'm trying to upload a **csv** through **flexget** (this works correctly), but one of the csv fields (16) is the one that has the magnet information to download.
```
  pDownloadeBooks:
    priority: 1
    seen:
      local: yes
    csv:
      url: file:///config/csv_full_imgs.csv
      values:
        idx: 1
        title: 2
        idioma: 11
        url: 16
    accept_all: yes
    regexp:
      reject_excluding:
        - 'Español'
      from: idioma
    manipulate:
      - title:
          replace:
            regexp: ' '
            format: '_'
    set:
      type: 'application/x-bittorrent'
      url: 'magnet:?xt=urn:btih:{{ url }}&dn=EPL_[{{ idx }}]_{{ title }}&tr=udp://93.158.213.92:1337/announce&tr=udp://23.137.251.45:6969/announce'
    transmission:
      <<: *transmission-settings
```
So, as you can see in the code, I modify the `title` to change the whitespaces to `_` and then with the set I create/modify this variable, to theoretically create the magnet, which theoretically transmission would have. to download the file (they are books).

But when it runs, it shows me the following error message:
### Waiting before retrying entry which has failed in the past. (failure reason: Error adding Don't_fuck_the_police to transmission. TransmissionError: Query failed with result "unrecognized info".)
And I don't understand the message, because if I take one of the urls (magnet) that I create and copy it directly to transmission, it downloads it without any problem.

Can someone give me a hand?
Thank you
