### DISCUSSION TITLE
Overriding move_completed_path for specific series.

### DISCUSSION THREAD

**Discussion by polocabbit** [Flexget/Flexget#3786] [Q&A] [answered]
I am attempting to override `move_completed_path` for a specific series on download completion via deluge. I have the following configuration:
```
configure_series:
  from:
    anilist:
      username: "{? anilist.username ?}"
      format:
        - tv
        - ova
        - ona
  settings:
    ep_regexp: (\d{2,4})
    exact: yes
    set:
      move_completed_path: "{? folders.anime ?}/{{series_name}}/Season {{series_season}}/"
series:
  - Vinland Saga Season 2:
      set:
        move_completed_path: "{? folders.anime ?}/Vinland Saga/Season 02/"
```

Downloads work as expected, but the attempted override for a specific series doesn't work as expected. I'm not sure what I'm missing. Documentation seems to indicate this is supported and should be working.
