### DISCUSSION TITLE
Radarr List Quality Profile Issue

### DISCUSSION THREAD

**Discussion by polocabbit** [Flexget/Flexget#3790] [Q&A]
I'm using the following config to push entries into radarr
```
list_add:
  - radarr_list:
      base_url: "http://localhost"
      port: "{? radarr.port ?}"
      api_key: "{? radarr.apikey ?}"
      profile_id: "{? radarr.quality_profile ?}"
```
`radarr.quality_profile` is set to 7 in my variable file, but based on the returned error the value of `1` is being sent to radarr instead

```
[
   {
      "propertyName":"QualityProfileId",
      "errorMessage":"QualityProfile does not exist",
      "attemptedValue":1,
      "severity":"error",
      "errorCode":"ProfileExistsValidator",
      "formattedMessageArguments":[
         
      ],
      "formattedMessagePlaceholderValues":{
         "propertyName":"Quality Profile Id",
         "propertyValue":1
      }
   }
]
```

I have also tried hard coding 7 into the parameter, but I receive the same error.
