### DISCUSSION TITLE
Error connecting to deluge daemon: [Errno 111] Connection refused

### DISCUSSION THREAD

**Discussion by ghost** [Flexget/Flexget#3827] [Q&A]
I am unable to connect to my dockerized deluge. It works fine on its own. I can access it through the web UI and download files but when I try to connect through flexget, the task fails to run returning the critical error in the title. Flexget and the docker container are running on the same client and I used the machine IP as host value since localhost would result in a crash. This same setup worked with a dockerized Transmission so I am sure the local IP value is required for host but flexget still refuses to connect. I am sure the password is correct since it's the same password I used for the dockerized Transmission so I can only assume this is an issue with the user. I already tried adding a new deluge account to the daemon but the very same error is returned.

What I tried so far:
- editing the auth file in .config also changing the password in there
- allowing remote connections in Preferences > Daemon
- restarting the docker container
- using a different user

config.yml
```yaml
templates:
  seasonal:
    deluge:
      label: "flexget"
      path: /downloads/.incomplete
      username: '{? accounts.deluge.user ?}'
      password: '{? accounts.deluge.pass ?}'
      host: '{? server.ip ?}'
#      port: 58846
      remove_at_ratio: yes
```
variables.yml
```yaml
server:
  ip: 192.168.1.10
accounts:
  deluge:
    user: localclient
    pass: mypassword
```
