### DISCUSSION TITLE
How can I configure separate notify messages for accepted and rejected entries?

### DISCUSSION THREAD

**Discussion by dragdragdrag** [Flexget/Flexget#3921] [Q&A] [answered]
As far as I can tell from the docs https://flexget.com/Plugins/notify I can only configure either a notification for accepted entries, or a notification for rejected entries. I'd like to set up both. I tried passing an array of dicts to `entries`, one to apply to accepted and one to rejected, but this doesn't pass validation.

Is there a way?

**Comment by gazpachoking** [comment]
I believe you can pass a list that option:
```yaml
notify:
  entries:
    what:
      - accepted
      - rejected
```
