### DISCUSSION TITLE
Series list is empty

### DISCUSSION THREAD

**Discussion by Karmalakas** [Flexget/Flexget#3924] [Q&A] [answered]
My PC died and I'm setting up FlexGet from scratch with my old config. I'm using Trakt plugin and I ran a task to set series begin successfully. I see all the series when I run `flexget series list all`:
```
+-----------------------------------------------------------------------------+
|                |        | Last           |     |            |               |
| Name           | Begin  | Encountered    | Age | Downloaded | Identified By |
|----------------+--------+----------------+-----+------------+---------------|
| Avatar: The    | S01E01 | -              | -   | -          | ep            |
| Last Airbender |        |                |     |            |               |
| (2024)         |        |                |     |            |               |
| Invasion       | S03E01 | -              | -   | -          | ep            |
| (2021)         |        |                |     |            |               |
| La Brea (2021) | S03E01 | -              | -   | -          | ep            |
| Percy Jackson  | S01E06 | -              | -   | -          | ep            |
| and the        |        |                |     |            |               |
| Olympians      |        |                |     |            |               |
| (2023)         |        |                |     |            |               |
...
```

But list is empty when I run `flexget series list`:
```
+--------------------------------------------------------------------+
| Name | Begin | Last Encountered | Age | Downloaded | Identified By |
|------+-------+------------------+-----+------------+---------------|
+--------------------------------------------------------------------+
Use `flexget series list all` to view all known series.
```

And when I run the discover task, I'm getting:
```
2024-01-18 00:20:19 WARNING  utils         discover-series-episodes Input next_series_episodes did not return anything
2024-01-18 00:20:19 VERBOSE  discover      discover-series-episodes Discovering 0 titles ...
```

Any advice? What am I missing to get it going like it did?

Task setup:
```
templates:
  series-episodes:
    priority: 30
    metainfo_series: yes
    thetvdb_lookup: yes
    trakt_lookup: yes
    parsing:
      series: guessit
    configure_series:
      settings:
        identified_by: ep
        season_packs: no
      from:
        trakt_list:
          account: '{? trakt.account ?}'
          list: watchlistshows
          type: shows
    exists_series:
      path: '{? files_watch.series ?}'
    discover:
      what:
        - next_series_episodes: yes
      from:
        - search_rss:
          url: '{? jackett.lm.url ?}'
          other_fields: [size]
      interval: 15 minutes
    quality: 1080p+ hdtv+ h264+ dd5.1+
    assume_quality:
      1080p+ hdtv+ h264+: ac3
    upgrade:
      tracking: yes
      timeframe: 5 days
      propers: yes
      on_lower: reject
    list_match:
      from:
        - trakt_list:
          account: '{? trakt.account ?}'
          list: watchlistshows
          type: shows
      remove_on_match: no
    sort_by:
      - field: quality.resolution
        reverse: yes
    set:
      content_size: '{{size|int}}'
    content_size:
      min: 100 MB
      max: 6500 MB

tasks:
  discover-series-episodes:
    template:
      - series-episodes
      - torrents
      - deluge-series
      - reject
      - series-notify
```

I excluded 4 last templates, because they don't do any discovery
