### DISCUSSION TITLE
Configured to download 1080p, but downloading 2160p too?

### DISCUSSION THREAD

**Discussion by yabbah** [Flexget/Flexget#3933] [General]
```
     series:
       settings:
         tv-settings:
           timeframe: 4 hours
           target: 1080p
           quality: 720p+
           propers: 4 days
       tv-settings:
         - some serie name
```

I have this in my configuration. And as I understand it, it should target for 1080p, but today it started downloading 2160p version of the same serie as I already have as 1080p ? What am I missing ?
