### DISCUSSION TITLE
Is it possible to run a task only once when daemon spawns?

### DISCUSSION THREAD

**Discussion by christaikobo** [Flexget/Flexget#3945] [Q&A] [answered]
As the title suggests, I would like to run a task only once, with deamon, not cli. I am thinking alone the lines of :
```
    schedule: 
      minute: now+1
      hour: now
      day: now
      month: now
      year: now
```

Obviously it doesn't work, because I don't know python at all...Can someone tell me the correct syntax? Or is there a better way to do it?
Thank you!
