### DISCUSSION TITLE
Can anyone help me understand why this config is not passing schema validation?

### DISCUSSION THREAD

**Discussion by ShrimpyChips** [Flexget/Flexget#3946] [Q&A] [answered]
This is my config file that I have been using for a while and it recently stopped passing schema validation. Note that the RSS feeds have had the API keys removed but the full URLs are in the actual file.

```yaml
tasks:
  populate_list_site:
    tail:
      file: F:\x\6_Usenet Approval\Look Lists\SiteList.csv
      entry:
        title: '(.*)'
        url: '(.*)'
    list_add:
    - regexp_list: sites_regexp
    manipulate:
      - title:
          replace:
            regexp: ' '
            format: '.*'
    accept_all: yes
  populate_list_actress:
    tail:
      file: F:\x\6_Usenet Approval\Look Lists\ActressList.csv
      entry:
        title: '(.*)'
        url: '(.*)'
    list_add:
    - regexp_list: actress_regexp
    manipulate:
      - title:
          replace:
            regexp: ' '
            format: '.*'
    accept_all: yes
  download_with_site_dog:
    rss: https://dognzb.cr/
    list_match:
      from:
        - regexp_list: sites_regexp
      remove_on_match: no
      single_match: no
    download: F:\x\6_Usenet Approval\Found\By Site
  download_with_actress_dog:
    rss: https://dognzb.cr/
    list_match:
      from:
        - regexp_list: actress_regexp
      remove_on_match: no
      single_match: no
    download: F:\x\6_Usenet Approval\Found\By Actress
  download_with_site_geek:
    rss: https://api.nzbgeek.info/
    list_match:
      from:
        - regexp_list: sites_regexp
      remove_on_match: no
      single_match: no
    download: F:\x\6_Usenet Approval\Found\By Site
  download_with_actress_geek:
    rss: https://api.nzbgeek.info/
    list_match:
      from:
        - regexp_list: actress_regexp
      remove_on_match: no
      single_match: no
    download: F:\x\6_Usenet Approval\Found\By Actress

```
