### DISCUSSION TITLE
Regexp seems to be rejecting everything

### DISCUSSION THREAD

**Discussion by ostracizado** [Flexget/Flexget#3950] [Q&A]
```
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes


tasks:
  series:
    rss: https://#####
    series:
      - SerieXXX:
          quality: 2160p
          propers: yes
          set:
            label: seriexxx
          season_packs: no
    regexp:
      from: title
      reject:
        - HDR10

    notify:
      entries:
        title: Flexget Notification.
        message: >           
          {% if series_name is defined %}{{series_name}} {{series_id|pad(2)}}
          {% elif tmdb_name is defined %}{{tmdb_name}} [{{tmdb_year}}]
          {% else %}{{title}}
          {% endif %}
        what: accepted
        via:
          - email:
              from: ####@gmail.com
              to: ####@gmail.com
              smtp_host: smtp.gmail.com
              smtp_port: ###
              smtp_username: ######
              smtp_password: ######
              smtp_tls: yes
              html: yes # To parse template as HTML

    deluge:
      host: ####
      port: ####
      username: ####
      password: ####



schedules:
  - tasks: 'series'
    interval:
      hours: 3
```

Is there something wrong with my config? Just now, there were 4 new additions at the rss. But in Task I only see:
200 (Produced) 0(Accepted) 13(Rejected) 0(Failed)

The 13 rejected seem to be those with "HDR100" in title.
