### DISCUSSION TITLE
Running on two machines

### DISCUSSION THREAD

**Discussion by epross672** [Flexget/Flexget#3957] [General] [answered]
MachineA is running transmission
MachineB is running flexget

MachineA has path of /data/Transmission/_MOVIES and /data/Transmission/_TV

MachineB
```yaml
  sort-movies:
    filesystem:
      path: /volume1/Transmission/_MOVIESFLEXGET/
      regexp: '.*\.(mkv|mp4|avi)$'
      recursive: yes
    template: movies
    move:
      to: "/volume1/Transmission/_MOVIESFLEXGET_DONE/{{imdb_name|replace(':', '.')}} ({{imdb_year}})/"
```
So what is happening is that the files while downloading are on MachineA/Transmission/Incomplete which is good.

But the movies stay in MachineA/Transmission/Incomplete when they are done.  I am wondering if there's a way to make this work.

MachineA is old and I can't upgrade python on it.  MachineB is new but doesn't have the space for the work.  So I am wondering if there's a way to make this work.
