### DISCUSSION TITLE
how to get the url with flexget

### DISCUSSION THREAD

**Discussion by cnpilot** [Flexget/Flexget#3965] [Q&A]
is there something wrong with the code below?  i want to get the id number from the rss 
but when run the flexget ,  i cant get the id
```
from flexget import plugin
from flexget.event import event
import re

class GetIDPlugin:
    schema = {'type': 'boolean'}

    def on_task_modify(self, task, config):
        if not config:
            return
        for entry in task.entries:
            # 从链接地址提取ID值
            link = entry.get('link')
            if link:
                match = re.search(r'id=(\d+)', link)
                if match:
                    entry['id'] = match.group(1)
            # 如果链接中没有ID，则尝试从URL中提取ID值
            if not entry.get('id'):
                url = entry.get('url')
                if url:
                    match = re.search(r'id=(\d+)', url)
                    if match:
                        entry['id'] = match.group(1)

@event('plugin.register')
def register_plugin():
    plugin.register(GetIDPlugin, 'get_id', api_ver=2)
```

**Comment by BrutuZ** [comment]
It could be shortened a little but I don't see anything immediately wrong with it.
Try adding some debug logging to help you identify what part is not returning what you expected

**Reply by cnpilot** [reply]
config.yml
```
tasks:
  Abit:
    rss: https://pandapt.net/torrentrss.php
    seen:
      fields:
        - url
    headers:
      Cookie: "xxxxxxxxx"
    regexp:
      accept:
        - Web
    imdb_tag: yes
    get_id: yes
    set:
      imdb_id: "{{ imdb_id }}"
      get_id: "{{ get_id }}"
    qbittorrent:
      path: "/home/tobox/qbittorrent/download/Panda_{{ get_id }}_{{ imdb_id }}/"
      host: xx.xxx.xxx.xx
      port: 8080
      username: name
      password: xxxxxxxx
    content_size:
      min: 1000
      max: 800000
      strict: no


web_server:
  port: 6566
  web_ui: yes
  base_url: /flexget

schedules: no
```
imdb.tag
```
from flexget import plugin
from flexget.event import event
import re

class IMDBTagPlugin:
    schema = {'type': 'boolean'}

    def on_task_modify(self, task, config):
        if not config:
            return
        for entry in task.entries:
            description = entry.get('description')
            if description:
                match = re.search(r'(tt\d{7,8})', description)
                if match:
                    entry['tags'] = [match.group(1)]
                    
@event('plugin.register')
def register_plugin():
    plugin.register(IMDBTagPlugin, 'imdb_tag', api_ver=2)
```

get id 
```
from flexget import plugin
from flexget.event import event
import re

class GetIDPlugin:
    schema = {'type': 'boolean'}

    def on_task_modify(self, task, config):
        if not config:
            return
        for entry in task.entries:
            # 从链接地址提取ID值
            link = entry.get('link')
            if link:
                match = re.search(r'id=(\d+)', link)
                if match:
                    entry['id'] = match.group(1)
            # 如果链接中没有ID，则尝试从URL中提取ID值
            if not entry.get('id'):
                url = entry.get('url')
                if url:
                    match = re.search(r'id=(\d+)', url)
                    if match:
                        entry['id'] = match.group(1)

@event('plugin.register')
def register_plugin():
    plugin.register(GetIDPlugin, 'get_id', api_ver=2)
```
when i run flexget execute
the one torrent  Save Path  is:	/home/boxbox/qbittorrent/download/Panda_None_tt31805997/
didnt get the id. i dont know where is wrong.  each torrent save path got /home/boxbox/qbittorrent/download/Panda_None_imdb
it means  imdb_tag works fine.but get id maybe not work. anyone know how to fix it?
i use chatgpt3.5 to write the code. and dont know how to debug.

**Reply by BrutuZ** [reply]
```yaml
    set:
      imdb_id: "{{ imdb_id }}"
      get_id: "{{ get_id }}"
```
This makes no sense, you've never set the `get_id` field in the first place, the plugin is editing the `id` field ._. not to mention completely redundant, you're setting the fields to themselves.

You don't need custom plugins for any of that, [`manipulate`](https://flexget.com/Plugins/manipulate) should have all you need.

ChatGPT is pretty much useless for Flexget, read the documentation
