### DISCUSSION TITLE
How do I cleanup torrents from qBittorrent?

### DISCUSSION THREAD

**Discussion by Hash6232** [Flexget/Flexget#3969] [Q&A]
The `qbittorrent` [plugin](https://flexget.com/Plugins/qbittorrent) lacks an `action` option so I can't parse anything with `from_qbittorrent`. Is there any way around it?

```yaml
tasks:
  cleanup:
    manual: yes
    from_qbittorrent:
      host: localhost
      port: 9090
      username: admin
      password: password
      completed: yes
    disable: [seen, seen_info_hash]
    if:
      - qbittorrent_category != 'flexget': reject
      - qbittorrent_ratio >= 2: accept
    qbittorrent:
      host: localhost
      port: 9090
```
