### DISCUSSION TITLE
Flexget Downloading Wrong Shows

### DISCUSSION THREAD

**Discussion by msw1970** [Flexget/Flexget#3977] [General]
I have an issue with a number of shows not correctly matching even when being defined using exact matching... One specific example is a show called Roadkill where flexget is also identifying Roadkill Garage as per below...
```
2024-04-24 19:29:44 INFO     series        DOWNLOAD_SERIES_RSS `Roadkill (2020)`: timeframe waiting for 09h:30min. Currently best is `Roadkill Garage S09E01 1080p HEVC x265-MeGusta`.
```
This actually happens with a number of different shows such as The Curse also identifying The Curse of Oak Island..
```
024-04-21 17:05:34 INFO     series        DOWNLOAD_SERIES_RSS `The Curse (2022)`: timeframe waiting for 23h:59min. Currently best is `The Curse of Oak Island Drilling Down S11E04 1080p HEVC x265-MeGusta`.
```
I define within a separate series.yml file any series where this occurs to make use of exact matching as per the below..
```
series:
  - The Curse (2022):
      exact: yes
  - Roadkill (2020):
      exact: yes
```
And then include this file in my main config file within a template that is then used in a task with the tasks being called on a schedule..
```
### Templates ###
templates:

### Series Config ###
  SERIES:
    thetvdb_lookup: yes
    include: series.yml
    configure_series:
      from:
        entry_list: trakt-series
      settings:
        identified_by: ep
        timeframe: 24 hours
        target: 720p h265
        quality: 720p|1080p h264-h265
        propers: no
        specials: no
        upgrade: yes

### Task Section ###
tasks:

### Download episodes from RSS Feeds ###
  DOWNLOAD_SERIES_RSS:
    priority: 1
    template:
      - SERIES
      - REJECT
      - TORRENTS
      - RTORRENT_SERIES
      - PROWL
      - SERIES_GUESSIT
    inputs:
      - rss: https://ipt.cool/t.rss?u=1499609;tp=6c67dc619cbfd88c8c733d02fb8f4bd3;99;download

### Schedules ###
schedules:
  - tasks: ['CLEAN*', 'UPDATE*', 'SONARR*']
    schedule:
      hour: 0
  - tasks: ['PURGE*', 'FILL*']
    schedule:
      minute: 15
      hour: "*/4"
  - tasks: ['*RSS', '*MAGNET']
    schedule:
      minute: 45
      hour: "*/4"
```
Anyone have any ideas what I might be missing here??
