### DISCUSSION TITLE
403 Client Error: Forbidden for url

### DISCUSSION THREAD

**Discussion by Amishman** [Flexget/Flexget#3980] [General]
I just recently changed my script to work with Trakt. Everything seems to be working properly except it seems to miss episodes. I get the following error message and then Flexget says it has been seen and will not download it again. If I copy/paste the url for itorrents into my browser, the torrent is downloaded. I thought the issue was magnets, so I stopped those but that did not fix the issue. Any ideas as to what I am missing or have wrong?

```
Young.Sheldon.S07E09.1080p.HEVC.x265-MeGusta[TGx]` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Network error during request: 403 Client Error: Forbidden for url: https://itorrents.org/torrent/d6ecbf04bd64bbcc74d8f03aed20fe033e8bec6d.torrent)

REJECTED: `Taskmaster.S17E05.Snooker.Cue.Umbrella.Chin.1080p.HDTV.H264-DARKFLiX[TGx]` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Network error during request: 403 Client Error: Forbidden for url: https://itorrents.org/torrent/422007fdc7456d77fe33ecaf794530d182fb72b2.torrent)

REJECTED: `Sugar.2024.S01E05.Boy.in.the.Corner.1080p.ATVP.WEB-DL.DDP5.1.H.264-NTb[TGx]` by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Network error during request: 403 Client Error: Forbidden for url: https://itorrents.org/torrent/4df79a58722d24a4c554889f16cb74d9b2bd62af.torrent)
```
```
variables: secrets.yml  


tasks:
  follow-from-trakt:
    priority: 5
    seen: local
    next_trakt_episodes:
      account: "{? trakt.account ?}"
      context: collected
      list: TV_Shows
    accept_all: yes
    set_series_begin: yes

          
  tv shows:
    priority: 10
    inputs:
      - rss: http://showrss.info/user/98577.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
      - rss: https://www.limetorrents.info/rss/
      - rss: https://eztv.re/ezrss.xml
      - rss: https://torrentgalaxy.to/rss
      - rss: https://www.torrentdownloads.pro/rss.xml?cid=8&type=last
      - rss: https://twoddl.ws/rss
      - rss: http://ibit.uproxy2.biz/rss/feed/
      - rss: http://glodls.to/rss.php?cat=41
      - rss: http://127.0.0.1:9117/api/v2.0/indexers/extratorrent-st/results/torznab/api?apikey=eu8812y5cxb4yd4aa8rjactn4osndwvn&t=search&cat=&q=
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
      reject:
        - '*.exe'
    content_size:
      min: 100
      max: 4500
      strict: no
    magnets: no
    regexp:
      reject:
        - spanish
        - italian
        - german
        - french
        - dutch
        - hindi
        - Español
        - ita
    discover:
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - solidtorrents:
            category: Video
            remove_potentially_unsafe: yes
            url: https://solidtorrents.to
        - piratebay:
            category: 208
            url: https://thepiratebay.org
        - 1337x: yes
        - limetorrents:
            category: tv
    configure_series:
      settings:
        # Configure all the series options to your taste
        quality: 1080p
        identified_by: ep
      from:
        trakt_list:
          account: "{? trakt.account ?}"
          list: TV_Shows
          type: shows
    download: D:\Torrents
    notify:
      entries:
        title: "[flexget] {{task}}"
        message: "{{title}}"
        via:
          - pushbullet:
              api_key: "{? pushbullet.api ?}"
```
