### DISCUSSION TITLE
Need help with handling .5 (specials) episodes with discover and next_series_episode plugin

### DISCUSSION THREAD

**Discussion by minh2134** [Flexget/Flexget#4035] [Q&A] [answered]
So currently I'm monitoring the series "Monogatari Off & Monster Season" and they have a 6.5 episode (which is not a recap). My config:
for discover
```
    discover:
      what:
        - next_series_episodes: yes
      from:
        - torznab:
            website: <jackett>
            apikey: <apikey>
            categories:
              - 127720
      release_estimations: loose

``` 
for series:
```
    series:
        - 'Monogatari Series - Off & Monster Season':
            identified_by: sequence
            begin: 01
            from_group: MTBB
```
This emits episode 7 instead and miss this one. Any ideas how to handle them? [this discussion](https://github.com/Flexget/Flexget/discussions/3784) suggest that you can manipulate titles for series to recognize, but from what i understand, do not help next_series_episode to emit the correct entry to find out these specials. Unless there's a way to configure that plugin to search for the same last episode again to dig out the .5 episodes then search for the next one. Or maybe there's a way instead to use tvmaze to figure out what's the next episode supposed to be?
