### DISCUSSION TITLE
hybrid hdr with dovi

### DISCUSSION THREAD

**Discussion by andrei376** [Flexget/Flexget#4042] [Q&A]
Hello,

I'm unable to configure flexget to download HDR or "hybrid hdr with dovi".

if I use quality "2160p webrip|webdl hdr|hdrplus" it works for HDR only series  which is fine.

but I see that new series are uploaded as hybrid HDR DOVI and I don't know how to target this.
if I use quality "2160p webrip|webdl hdr|hdrplus|dolbyvision" it will only download the DOVI version.

does anyone know how to download hybrid "hdr+dovi" if hdr is not available?

thank you

**Comment by BrutuZ** [comment]
What do you mean hybrid, Dolby Vision *is* HDR.
Instead of that chain OR you can slap `hdr+` into quality (that's [HDR or higher](https://flexget.com/Qualities), not to be confused with HDR Plus), and also [`sort_by: quality.color_space`](https://flexget.com/Plugins/sort_by)

**Reply by andrei376** [reply]
my TV does not support DOVI in mkv, so that's why I need HDR10 or HDR10+

i have 3 examples:
1. Test.S02E04.2160p.WEB-DL.DDP5.1.DoVi.H.265-xyz
2. Test.S02E04.2160p.WEB-DL.DDP5.1.HDR.H.265-xyz
3. Test.S02E04.2160p.WEB-DL.DDP5.1.Atmos.DoVi.HDR.H.265-xyz

I want to download 2 or 3 
"2160p webrip|webdl hdr|hdrplus|hdr+"
would download 1 which I need to avoid

**Reply by BrutuZ** [reply]
Why would you want the third one if your device doesn't support Dolby Vision?

**Reply by andrei376** [reply]
yes,  3 has dovi and hdr10, so the tv will choose hdr10
copied from video description:
HDR Format.....: Dolby Vision, Version 1.0, Profile 8.1, dvhe.08.06, BL+RPU, no metadata compression, HDR10 compatible / SMPTE ST 2094 App 4, Version HDR10+ Profile B, HDR10+ Profile B compatible

**Reply by BrutuZ** [reply]
Flexget can't handle that, it will only recognize one format and will prioritize the higher one.
To all effects and purposes 1 and 3 are the same quality in Flexget's eyes, the entries from your example are seen as:
```
2160p webdl h265 dolbyvision dd+5.1
2160p webdl h265 hdr dd+5.1
2160p webdl h265 dolbyvision dd+5.1
```

**Reply by andrei376** [reply]
hm, should i open a bug report?

3 should match hdr10 and dovi, not jut dovi

**Reply by BrutuZ** [reply]
Again, it can only have *one value* for each quality category (https://flexget.com/Qualities), if there's more like HDR and DoVi/HDR+, it picks the best one.

You could open an issue requesting this to be changed, but I wouldn't be hopeful on it since it would be a fundamental change that affects several plugins

**Comment by andrei376** [comment]
ok, thanks, i opened an report

**Comment by hahahaplop** [comment]
Hi, did anyone manage to create a regex config to suit that need?
Adding the regex in the task like the below works for me:
```
templates:
  template1:
    series:
      2160p dolbyvision:
...
tasks:
  task1:
    rss: url
    template: template1
    regexp:
      reject_excluding:
        - hdr
```


But for more flexibility I tried to add the regex to the group itself and it's not taken into account:
```
templates:
  template1:
    series:
      settings:
        2160p dolbyvision:
          set:
            regexp:
              reject_excluding:
                - hdr
```
Any idea what the correct syntax is in this case?
Edit: my need is slightly different: I specifically want to match hybrid DV HDR content for best quality (DV) on my TV while keeping compatiblity with older players which don't support DV
