### DISCUSSION TITLE
Cannot daemonize on windows

### DISCUSSION THREAD

**Discussion by Amishman** [Flexget/Flexget#4068] [General] [answered]
I'm not sure what's wrong. I am trying to run Flexget in daemon mode. To test, I opened a cmd prompt and typed:
`flexget daemon start -d`

Then I get the response:
```
C:\Windows\system32>flexget daemon start -d
2024-11-03 08:22:35 ERROR    manager                       Cannot daemonize on windows
2024-11-03 08:22:35 INFO     scheduler                     Starting scheduler
```
I have tried regular and elevated cmd prompts but I receive the same message. I'm not sure where to look for more information. 

Right now I have Flexget set up to run every hour by a Windows task. The reason I want to deamonize it, is I have a target quality setup but it never gets applied. I'm thinking Flexget would not know it has been 18 hours if it was not in daemon mode.

```
  - configure_series:
          from:
            <<: *trakt_tv_list
          settings:
            exact: no
            target: 1080p webrip+ h264
            quality: 1080p webrip+ h265
            timeframe: 18 hours
            propers: 2 days
            identified_by: ep
            specials: no
```
I am using Windows 10 Pro and using Flexget 3.11.53
