### DISCUSSION TITLE
Filter by content length

### DISCUSSION THREAD

**Discussion by heruan** [Flexget/Flexget#4075] [Q&A]
Some feeds provide a `contentLength` attribute, e.g.

```xml
<item>
    <title>This is cool</title>
    <link>https://example.com/cool</link>
    <pubDate>Fri, 29 Nov 2024 22:58:09 +0100</pubDate>
    <torrent:contentLength>2322512994</torrent:contentLength>
    <torrent:infoHash>AAABBBCCCDDDEEEFFFGGG</torrent:infoHash>
    <torrent:magnetURI><![CDATA[ magnet: ... ]]></torrent:magnetURI>
</item>
```

Is it possible to set constraints on the accepted items based on this value? I see there is [content_size](https://flexget.com/Plugins/content_size) but that does not work with magnet links while this attribute could since it's on the feed.

**Comment by BrutuZ** [comment]
```yaml
    rss:
      url: https://cool.feed/rss
      other_fields:
        - "torrent:contentLength": content_length
    if:
      - content_length > 1337: accept
```

**Reply by BrutuZ** [reply]
Can probably even get away with still using the `content_size` plugin for those feeds if you map the XML field to content_size instead
```yaml
    rss:
      url: https://cool.feed/rss
      other_fields:
        - "torrent:contentLength": content_size
    content_size:
      min: 1337KB
      max: 7331MB
```
