### DISCUSSION TITLE
How to I add tvdb-number to my TV Show folder?

### DISCUSSION THREAD

**Discussion by paulpoco** [Flexget/Flexget#4212] [Q&A] [answered]
move_completed_path: "/data/Media/TV Shows/{{series_name}} {{tvdb_id}}/Season {{series_season}}/"

This came back with say "Gold Rush none"  where the tvdb-number should be.

I want the actual want the Plex folder format that Filebot wants.  Like "Brilliant Minds {tvdb-441114}"

**Comment by gazpachoking** [comment]
You could use [thetvdb_lookup plugin](https://flexget.com/Plugins/thetvdb_lookup) to look it up. Or you could just manually set the id per series (depending on how you are configuring your series) as shown on that page as well.
```yaml
series:
  - some_series:
      set:
        tvdb_id: <tvdb_id>
deluge:  # or whatever plugin you are using
  move_completed_path: /data/Media/TV Shows/{{series_name}} {{ "{tvdb-"+tvdb_id+"}" }}/Season {{series_season}}/
```
