### DISCUSSION TITLE
Flexget Config Help

### DISCUSSION THREAD

**Discussion by fruitcake514** [Flexget/Flexget#4314] [General]
I am new to flexget I would like to index my current media library of movies and tv shows. and then for the tv shows find any missing seasons and episodes and send those off to qbittorrent using prowalarr as an indexer. I have a separate flow that takes it from there so flexget will update the index every few days or so to determine what is still missing. I have a Movie list populated properly but the Series list is treating every episode as its own series (im not sure if i actually should be using an entry list). I don't want my current episodes and movies to be treated as a list for downloading. I added my current config I am not sure if this is not the correct use of flexget or if any of this is possible.

```yaml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  index_plex_tv:
    seen: local
    filesystem:
      path:
        - /data/TV Shows/
      recursive: yes
      retrieve:
        - files
        - dirs
      regexp: '.*\.(avi|mkv|mp4)$'
    thetvdb_lookup:
      series_name: "{{ series_name }}"
    accept_all: true
    configure_series:
      from:
        filesystem:
          path:
            - /data/TV Shows/
          recursive: yes
          retrieve:
            - files
            - dirs
          regexp: '.*\.(avi|mkv|mp4)$'
      settings:
        identified_by: ep
      
  index_plex_movies:
    seen: local
    filesystem:
      path:
        - /data/Movies/
      recursive: yes
      retrieve:
        - files
        - dirs
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: true
    list_add:
      - movie_list: plex
schedules: no
```
