### DISCUSSION TITLE
Trying to understand download plugin tags...

### DISCUSSION THREAD

**Discussion by Wuerger** [Flexget/Flexget#4315] [General] [answered]
Hello. I am trying to add some tags to send to qBittorrent. Here is an excerpt from my config:
``` yaml
    series:
      settings:
        seriesgroup:
          timeframe: 48 hours
          target: 1080p webrip|hdtv|webdl h264|h265
          quality: 720p-1080p webrip|hdtv|webdl h264|h265
          upgrade: yes
          path: /download/{{series_name}}/Season {{series_season}}
          set:
            path: /download/{{series_name}}/Season {{series_season}}
            label: tv
            tags:
              - flexget
              - "{{ series_id }}"
              - "{{ url | urlparse | attr('netloc') }}"
            seeding_time_limit: 15 days
        seriesgroup: |
          {? my_shows ?}
      qbittorrent: yes
```
Of these, only the static 'flexget' one works as expected. The other two are also added but as stings. The jinja is not expanded.

Even setting the example provided in the docs does not work:
``` yaml
tasks
  movies:
    set:
      tags:
        - '{quality.resolution}'
```

Can anyone explain where I am going wrong?
