### DISCUSSION TITLE
Throlling / RSS / qBittorrent

### DISCUSSION THREAD

**Discussion by MoonArrow** [Flexget/Flexget#4320] [Q&A]
hi guys,

I just added a new RSS feed to my Flexget existing configuration and I thought "Piece of Cake: another RSS, just add it and run" and obviously, it went south :)
The reason is pretty simple, Flexget get the RSS feed through the RSS plugin, and send each entries to qBittorrent (magnet links mostly) but here is the kicker : the torrent tracker is refusing to accept my requests because too many of them too quickly, I am limited by adding a torrent only every 5 secs. 
I tried to put a sleep plugin in action in the qbittorrent but without success. The sleep is done at the end of qbittorrent but it seems that RSS is sending all the request at the same time or more probably I missed something in my configuration.

Here is my configuration. Do you have any idea how to make RSS or qbittorrent plugin wait 5s between sending each entry found on the RSS feed ?

```
templates:
  qbittorrent_tmpl:
    qbittorrent:
      host: localhost
      port: 1234
      username: fakeadmin
      password: fakepassword
      label: flexget
      tags:
        - anotherspecifictag
      seeding_time_limit: 175 hour
      ratio_limit: -1.0
      maxupspeed: 500
    sleep:
      seconds: 3
  audiobooks:
    rss:
      url: https://here.is.valid.rss/api/last-torrents?limit=100&format=xml
    sleep:
      seconds: 5
    set:
      tags:
        - anothertag
        - audiobooks
    template:
      - qbittorrent_tmpl
    regexp:
      accept:
        - mp3
        - m4b
        - aac

```
Thanks for your help
M.
