### DISCUSSION TITLE
How send matrix message with flexget??

### DISCUSSION THREAD

**Discussion by Vctrsnts** [Flexget/Flexget#4321] [Q&A]
I have a Matrix Server ( conduit ) and client Element and send message without any problem.

In flexget ( config.yml ) I have this configuration:
```
  notify-all:
    notify:
      entries:
        message: 'moveVideos'
        via:
          - matrix:
              server: 'URL_MATRIX'
              token: 'TOKEN'
              room_id: 'ROOM_ID'
```
Is correct this configuration? Because I dont send any message, all time I have the same error:

`WARNING notify moveVideos Error while sending notification to matrix: 404 Client Error: Not Found for url: https://SERVER_MATRIX/_matrix/client/r0/rooms/ROOM_ID/send/m.room.message?access_token=ACCESS_TOKEN`

But I dont understand the error because I send message without any problem that my client ( local ) to my matrix server ( VPS ).

Where is the problem??

Thanks
