### DISCUSSION TITLE
How does the scheduler work in case of frequent calls?

### DISCUSSION THREAD

**Discussion by Hash6232** [Flexget/Flexget#4335] [Q&A] [answered]
I am using the linuxserver's flexget docker image and all of a sudden I am experiencing missed scheduled runs.

Let's say I set the scheduler to run every 5 minutes for testing purposes, would the scheduler skip runs if the rss feeds haven't changed yet? That's the only explanation I can think of.

The image automatically runs a daemon and it generates a .config-lock file. It also auto reloads configs but from what I read on the flexget docs that only happens before a task runs.

This is my redacted config:
```yaml
tasks:
  nyaa:
    template: anime
    series:
      1080p:
        - Kusuriya no Hitorigoto

templates:
  anime:
    download: /data/anime
    inputs:
      - rss: https://nyaa.si/?page=rss&c=1_2&f=0&u=Erai-raws
      - rss: https://nyaa.si/?page=rss&c=1_2&f=0&u=subsplease
      - rss: https://nyaa.si/?page=rss&c=1_2&f=0
    series:
      settings:
        1080p:
          from_group:
            - Erai-raws
            - Subsplease

schedules:
  - tasks: '*'
    interval:
      minutes: 5
```
