### DISCUSSION TITLE
Howto config rtorrent download series with RSS feeds

### DISCUSSION THREAD

**Discussion by ranirahn** [Flexget/Flexget#4354] [Q&A]
I am trying to setup my series to be downloaded with rtorrent and all series to get in different folder and different label, but nothing is working. My current config is this.

```
templates:
  tv1:
    series:
      - Daredevil:
          qualities:
            - 720p+ h264
            - 1080p h265
          begin: S01E09
          season_packs: yes
    disable: seen
    rtorrent:
      uri: scgi://127.0.0.1:5000
      start: no
      path: /home/ftp/STAFF/FTP/Torrentitest/RSSiga/Daredevil/
      custom1: "1 - Daredevil"
  tv2:
    series:
      - Andor:
          qualities:
            - 720p+ h264
            - 1080p h265
          begin: S02E01
          season_packs: yes
    rtorrent:
      uri: scgi://127.0.0.1:5000
      start: no
      path: /home/ftp/STAFF/FTP/Torrentitest/RSSiga/Andor/
      custom1: "1 - Andor"

tasks:
  eztv:
    rss: https://eztvx.to/ezrss.xml
    template: tv1
    template: tv2
``` 

Have tried many diferent ways to do that, but only last series is in the "flexget series list". And NOTHING will be added to my rtorrent. When i add "accept_all: yes" then everything will be added under last series list. First all were in the same template. Thought maybe thats why only last one gets added to the list. Made multiple templates, but nothing changed. With Movies i have movies list to compare what to download, but with series i dont see anything that would filter out series that i want from rss. I read trhough all exaples on flexget.com and found nothing that would explain it. Maybe if i would use transmission or deluge and trackt.tv i could get it working, but i use rtorrent and just want to type the series in my config what i want to get and there is no examples at all how to do that. Maybe i need to make 100+ different config files to get this working for all series?
