### DISCUSSION TITLE
expose more fields in my_anime_list plugin

### DISCUSSION THREAD

**Discussion by natsukashiixo** [Flexget/Flexget#4395] [Ideas] [answered]
current code:

```py
if has_selected_status and has_selected_type and has_selected_airing_status:
  # MAL sometimes returns title as an integer
  anime['anime_title'] = str(anime['anime_title'])
  entry = Entry()
  entry['title'] = anime['anime_title']
  entry['url'] = f'https://myanimelist.net{anime["anime_url"]}'
  entry['mal_name'] = anime['anime_title']
  entry['mal_poster'] = anime['anime_image_path']
  entry['mal_type'] = anime['anime_media_type_string']
  entry['mal_tags'] = anime['tags']
    if entry.isvalid():
      yield entry
```
proposal:

```py
if has_selected_status and has_selected_type and has_selected_airing_status:
  # MAL sometimes returns title as an integer
  anime['anime_title'] = str(anime['anime_title'])
  anime['anime_title_eng'] = str(anime['anime_title_eng']) #perform same type conversion on alt title just to be safe
  entry = Entry()
  entry['title'] = anime['anime_title']
  entry['url'] = f'https://myanimelist.net{anime["anime_url"]}'
  entry['mal_name'] = anime['anime_title']
  entry['mal_poster'] = anime['anime_image_path']
  entry['mal_type'] = anime['anime_media_type_string']
  entry['mal_tags'] = anime['tags']
  entry['mal_id'] = anime['anime_id']
  entry['eng_title'] = anime['anime_title_eng']
    if entry.isvalid():
      yield entry
```

naive assumption on how it would be used:

```yml
templates:
  anime:
    configure_series:
      settings:
        identified_by: sequence
        from_group: MOCK_GROUP
        quality: VALUE
        alternate_title: {{eng_title}}
      from:
        my_anime_list:
          username: MOCK_USER
    set:
      path: '/srv/raid/share/Torrent/Anime/[{{mal_id}}] {{series_name}}'
  [...]
```

Mostly a sanity check to see if I'm misunderstanding something. 
If anyone with an active development environment could test it, it would be appreciated. Currently can't set one up right this moment.

Disclaimer based on my gut feeling: I am not interested in a discussion regarding using other list plugins instead, I know the functionality exists in others. This is solely about extending functionality of the MyAnimeList plugin
