### ISSUE TITLE
New API inject point

### ISSUE THREAD

**Issue by subzero79** [Flexget/Flexget#1001]
This is my testing with the new API inject endpoint

My config.yml is here 

```
web_server:
  bind: 0.0.0.0
  port: 5050
api: yes
webui: yes

secrets: secrets.yml
templates:

  gmail:
    email:
      from: '{{ secrets.email.from }}'
      to:
        - '{{ secrets.email.to }}'
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: '{{ secrets.email.smtp_username }}'
      smtp_password: '{{ secrets.email.smtp_password }}'
      smtp_tls: true
      template: poster

  client_td:
    transmission:
      host: 172.25.0.1
      port: 9091
      username: admin
      password: torrent
    _clean_transmission:
      host: localhost
      port: 9091
      username: admin
      password: torrent
      min_ratio: 1.1

  message_telegram:
    send_telegram:
      bot_token: '{{ secrets.send_telegram.bot_token }}'
      parse_mode: markdown      
      template: | 
        [{{imdb_name}}]({{imdb_url}})
        _{{title}}_
        *Size:* {{ content_size }} MB
        *Rating:* {{imdb_score}}/10 with {{imdb_votes}} Votes
        *Plot:* {{imdb_plot_outline}}
        *Actors:* {% for key, value in imdb_actors.iteritems() %} {{ value|e }},{% endfor %}
      recipients:
        - username: user1
        - username: user2

  test_message_telegram:
    send_telegram:
      bot_token: '{{ secrets.send_telegram.bot_token }}'
      parse_mode: markdown      
      template: | 
        [{{imdb_name}}]({{imdb_url}})
        _{{title}}_
        *Size:* {{ content_size }} MB
        *Rating:* {{imdb_score}}/10 with {{imdb_votes}} Votes
        *Plot:* {{imdb_plot_outline}}
        *Actors:* {% for key, value in imdb_actors.iteritems() %} {{ value|e }},{% endfor %}
      recipients:
        - username: user1

  movies:
    regexp:
      reject_excluding:
      - >
        (?x)(SPARKS|DiVERSiTY|AMIABLE|GECKOS|ALLiANCE|COCAIN|FiCO|YIFY|TASTE|EVO|iMMORTALs
        |PHD|PHOBOS|PublicHD|LiMiTED|mSD|WiKi|Japhson|SADPANDA|MAJESTIC|JODER|GHOULS|ORGANiC|BiPOLAR|REMO|BiPOLAR|SADPANDA|NODLABS
        |GiANGi|PSYCHD|ROVERS|LEGi0N|BLOW|DRONES|DEFLATE|RUSTED|RUSTED|DiAMOND)
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
        - '*.rar'
      reject:
        - '*.zip'
        - '*.wmv'
        - 'Censored HC'
    imdb:
      min_score: 7.0
      min_votes: 10000
      min_year: 2012
      accept_languages:
        - english
        - spanish
        - french
        - portuguese
      reject_languages:
        - hindi
    exists_movie: /videos/peliculas/
    set:
      label: movies

  movies_from_transmission:
    regexp:
      reject_excluding:
      - (SPARKS|DiVERSiTY|AMIABLE|GECKOS|ALLiANCE|COCAIN|FiCO|YIFY|EVO|iMMORTALs|PHD|PHOBOS|PublicHD|LiMiTED|mSD|WiKi|Japhson|SADPANDA|MAJESTIC|JODER|GHOULS|ORGANiC|BiPOLAR|REMO|BiPOLAR|SADPANDA|NODLABS|GiANGi|PSYCHD|ROVERS|LEGi0N|BLOW|DRONES|DEFLATE|RUSTED|RUSTED|DiAMOND)
    imdb:
      min_score: 7.0
    content_filter:
      require:
        - '*.mkv'
        - '*.mp4'
        - '*.rar'
    accept_all: yes

  easy_movies:
    imdb:
      min_score: 5.0
      min_votes: 100
    parsing:
      movie: guessit

  MovieLine:
    trakt_list:
      username: subzero79
      account: traktv_flexget
      list: watchlist
      type: movies
    imdb_list:
      user_id: ur35053981
      list: watchlist
    _imdb_lookup: yes
    set:
      title: "{{ imdb_name }} ({{ imdb_year }})"
    movie_queue: add
    accept_all: yes


tasks:
  QMoviesReload:
    manual: yes
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    template:
      - MovieLine

  QMoviesLoad:
    priority: 1
    template:
      - MovieLine

  _Documentaries:
    priority: 3
    inputs: 
      - rss: http://10.10.10.10:5050/i/?a=rss&nb=60&&get=c_3
      - rss: http://10.10.10.10:5050/i/?a=rss&search=%23DVDRip%2FDVDScreener&nb=60&get=f_16
      - rss: http://10.10.10.10:5050/i/?a=rss&search=%23bdrip&nb=60&get=f_16
    imdb_lookup: yes
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - flexget_archive: yes
    if:
      - imdb_genres <> Documentary: reject
    quality: 480p+ bluray|dvdrip h264
    parsing:
      movie: guessit
    archive: [movies]
    seen_movies: strict
    movie_queue: accept
    torrent_alive: yes
    set:
      path: /storage/torrent/finish/documentaries
    download: yes
    template:
      - movies
      - client_td
      - message_telegram


  speed_cd_sd:
    priority: 8
    inputs: 
      - rss: http://10.10.10.10:5050/i/?a=rss&nb=60&&get=c_3
      - rss: http://10.10.10.10:5050/i/?a=rss&search=%23DVDRip%2FDVDScreener&nb=60&get=f_16
      - rss: http://10.10.10.10:5050/i/?a=rss&search=%23bdrip&nb=60&get=f_16
    assume_quality: 480p
    imdb_lookup: yes
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - flexget_archive: yes
    if:
      - imdb_score >= 7.7: reject
    quality: 480p bluray|dvdrip h264
    parsing:
      movie: guessit
    archive: [movies]
    seen_movies: strict
    movie_queue: accept
    torrent_alive: yes
    set:
      path: /storage/torrent/finish/movies
    download: yes
    template:
      - movies
      - client_td
      - message_telegram


  speed_cd_hd:
    priority: 7
    inputs:
      - rss: http://10.10.10.10:5050/i/?a=rss&search=720p&nb=60&get=c_3
      - rss: http://10.10.10.10:5050/i/?a=rss&search=%23bdrip+720p&nb=60&get=f_16
      - rss: http://10.10.10.10:5050/i/?a=rss&search=%23HD+720p+Bluray&nb=60&get=f_16
    imdb_lookup: yes
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - flexget_archive: yes
    if:
      - imdb_score < 7.7: reject
    quality: 720p bluray h264
    archive: [movies]
    seen_movies: strict
    movie_queue: accept
    torrent_alive: yes
    set:
      path: /storage/torrent/finish/movies/
    download: yes
    template:
      - movies
      - client_td
      - message_telegram

  sort-movies:
    parsing:
      movie: guessit
    manual: yes
    filesystem:
      path: /movies_incoming
      recursive: true
      mask: '*.mkv'
    move:
      to: "/videos/peliculas/{{imdb_name}} ({{imdb_year}})"
      allow_dir: yes
      keep_extension: yes
      filename: '{{imdb_name}} {{imdb_year}} {{ quality|replace("h264","x264") }}'
      along:
        - sub
        - srt
      clean_source: 500


  LoadFromTransmission:
    inputs:
      - from_transmission:
          host: 172.25.0.1
          port: 9091
          username: admin
          password: torrent
          onlycomplete: no
    imdb_lookup: yes
    quality: 480p+ dvdrip+
    template:
      - movies_from_transmission
      - message_telegram

  TestNotification:
    manual: yes
    seen: local
    rss: http://fresh.lan/p/i/?a=rss&search=The+Danish+Girl+2015+BRRip+XviD+AC3-EVO&get=c_3
    movie_queue: accept
    template:
      - easy_movies
      - test_message_telegram

```

Basically my first test, selected the default payload in the webui for API,  added a valid title, URL and a current task name. Entry gets processed and I can see in the logs the torrent being passed to transmission as immortal. The default payload has "force: true" so everything good there. Now setting back this to "force:false" should pass the entry to flexget and do all the checks to see if is eligible. Instead I see in the logs flexget acting as the the execute is being run as testing.
In this paste you'll see the payload with some defaults changed and debug enabled, also the response

http://hastebin.com/inanuyaxuy.dos
