### ISSUE TITLE
Add Scene group name as field for movies

### ISSUE THREAD

**Issue by subzero79** [Flexget/Flexget#1015]
Currently guessit can pick the release group name very easily. Here are some examples.

```
root@nb:/media/7283242e-cb09-40ea-a27e-a91e58cd3dc6/videos/peliculas # guessit The.Master.2012.DVDRiP.AC3-5.1.XviD-AXED/
For: The.Master.2012.DVDRiP.AC3-5.1.XviD-AXED/
GuessIt found: {
    "title": "The Master", 
    "year": 2012, 
    "format": "DVD", 
    "audio_codec": "AC3", 
    "audio_channels": "5.1", 
    "video_codec": "XviD", 
    "release_group": "AXED", 
    "type": "movie"
}
root@nb:/media/7283242e-cb09-40ea-a27e-a91e58cd3dc6/videos/peliculas # guessit Kingsman.The.Secret.Service.2014.HC.HDRiip.XviD.AC3-EVO
For: Kingsman.The.Secret.Service.2014.HC.HDRiip.XviD.AC3-EVO
GuessIt found: {
    "title": "Kingsman The Secret Service", 
    "year": 2014, 
    "episode_title": "HC HDRiip", 
    "video_codec": "XviD", 
    "audio_codec": "AC3", 
    "release_group": "EVO", 
    "type": "movie"
}
root@nb:/media/7283242e-cb09-40ea-a27e-a91e58cd3dc6/videos/peliculas # guessit What.We.Did.on.Our.Holiday.2014.BDRip.X264-AMIABLE
For: What.We.Did.on.Our.Holiday.2014.BDRip.X264-AMIABLE
GuessIt found: {
    "title": "What We Did on Our Holiday", 
    "year": 2014, 
    "format": "BluRay", 
    "video_codec": "h264", 
    "release_group": "AMIABLE", 
    "type": "movie"
}
```

Would it be possible to add this field in an entry so it can be used in jinja2 templates for renaming?

**Comment by cvium** [comment]
Set the parser to guessit and it will be available in `{{ release_group }}`.
```
parsing:
      series: guessit
      movie: guessit
```

**Comment by subzero79** [comment]
Sorry for opening again but at a quick look this appears to only work for series 

This is the task

```
  sort-movies:
    parsing:
      movie: guessit
    imdb_lookup: yes
    manual: yes
    filesystem:
      path: /movies_incoming
      recursive: true
      mask: '*.mkv'
    accept_all: yes 
    move:
      to: "/test/{{movie_name}} ({{movie_year}})"
      allow_dir: yes
      keep_extension: yes
      filename: '{{movie_name}} {{movie_year}} {{ quality|replace("h264","x264") }} {{ release_group }}'
      along:
        - sub
        - srt
      clean_source: 500
```

This is the output in test mode

http://hastebin.com/aramusefiq.rb
