### ISSUE TITLE
Episodes identified by date aren't matching to tvdb lately. 

### ISSUE THREAD

**Issue by leetwanker** [Flexget/Flexget#1036]
I'm not sure how to give any more info on this. Maybe it's something you guys are already aware of?

examples:
seth.meyers.2016.04.13.tom.hiddleston.hdtv.x264-crooks.mkv
The.Daily.Show.2016.04.13.Ken.Jeong.720p.CC.WEBRip.AAC2.0.x264-BTW.mkv
seth.meyers.2016.04.12.anna.wintour.hdtv.x264-crooks.mkv
The.Daily.Show.2016.04.12.King.Bach.720p.HDTV.x264-LATERS.mkv

Is there some way I can look at what tvdb lookup is returning?

**Comment by liiight** [comment]
Please paste logs and config

**Comment by leetwanker** [comment]
```
templates:
###############################################################   GLOBAL BEGIN   ###################################################################################
  global:
    # Make there's 5GB free before adding more downloads
    max_reruns: 1
    free_space:
      path: /mnt/Main
      space: 2000

    manipulate:
      - title:
          replace:
            regexp: '\/'
            format: '.'

      #https://regex101.com/r/oZ4nD1/3
      - title:  
          replace:
            regexp: '^(\[|{|\()(?P<id>\w*(-|\.|\s)?\w*?(-|\.|\s)?\w*?)(\]|}|\))\s?-?\s?'
            format: '\g<id> - '
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
      Referer: "http://torcache.net/"
      Accept-Encoding: "deflate, gzip"

    verify_ssl_certificates: yes

    #torrent_alive: { min_seeds: 3, reject_for: 10 minutes }
    # Filter by filenames. Allow multiple video types and rar packs (but note if there is just a single .rar file it won't be accepted)
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
      reject:
        - '*.wmv'
        - '*.rar'
        - '*.r00'
        - '*.r01'
        - 'password.txt'
      require_mainfile: yes
    # Limit the frequency of requests to domains so they don't complain about using a bot
    deluge:
      #main_file_only: no
      #hide_sparse_files: no
      username: '{{ secrets.deluge.username }}'
      password: '{{ secrets.deluge.password }}'
      path: '{{ secrets.deluge.path }}'
    retry_failed:
      retry_time: 1 hour # Base time in between retries
      retry_time_multiplier: 2 # Amount retry time will be multiplied by after each successive failure
      max_retries: 4 # Number of times the entry will be retried
###############################################################    GLOBAL END    ###################################################################################

############################################################   PRIVATE-GLOBAL BEGIN   ##############################################################################
  # This template is a "global" template for all TV-related feeds.
  # We keep all of the RSS feeds that list tv-related torrents here as well as where to check existing shows.
  private-global:
    # This is a TON of feeds, you probably don't need so many, but why not?
    # Most of these are the results of problem torrents I kept seeing still pop up, so I wholesale blocked them
    # Regex101 (https://regex101.com/#python) is a great tool for testing python regexes

    inputs:
      - rss: 
          url: '{{ secrets.feeds.123 }}'
          title: fileName
          other_fields: [fileName]
      - rss:
          url: '{{ secrets.feeds.456 }}'
      #- rss:
          #url: '{{ secrets.feeds.789 }}'
      - rss:
          url: '{{ secrets.feeds.101 }}'
    # Impose reasonable size constraints
    content_size:
      max: 3000
      min: 20
      strict: yes
    magnets: no
    convert_magnet: no
    thetvdb_lookup: yes
    trakt_lookup:
      username: '{{ secrets.trakt.username }}'
      account: '{{ secrets.trakt.account }}'
    manipulate:
      #- title:
          #replace:            
            #regexp: '\bPilot\b'
            #format: 'S01E01'
      - title:          
          replace:
            regexp: 'Series.*(\d).(\d)of\d'
            format: 'S0\1E0\2'
      - title:          
          replace:
            regexp: 'Series.*(\d).(\d\d)of\d\d'
            format: 'S0\1E\2'
      - title:          
          replace:
            regexp: '(\D)(\d)\D?of\D?\d'
            format: '\1S01E0\2'
      - title:            
          replace:
            regexp: '(\d\d)\D?of\D?\d\d'
            format: 'S01E\1'
      - title:
          replace:            
            regexp: '(\s|\.)\bCA\b(\.|\s)'
            format: ' '

      #- title:
          #from: filename
    exec:
      allow_background: yes
      on_output:
        for_accepted: 'echo "{{task}}: ACCEPTED:,{% if tvdb_ep_name|default(False) %}{{series_name}} - {{series_id}} - {{tvdb_ep_name|default("NotMatched", True)}}{% else %}{{title}}{% endif %}" >> /home/osmc/accepted.log'
        for_failed: 'echo "{{task}}: FAILED:,{{title}}" >> /home/osmc/failed.log'
      on_exit:
        phase: '{% if task.accepted %}~/scripts/notify.sh &{% elif task.failed %}~/scripts/notify.sh &{% endif %}'
        # Give accepted entries a nice name in Deluge
    set:
      content_filename: "{% if tvdb_ep_name|default(False) %}{{series_name}} - {{series_id}} - {{tvdb_ep_name|replace('/', ' ')}} - {{quality|upper}}{% if proper_count %} PROPER{% if proper_count > 1 %}{{proper_count}}{% endif %}{% endif %}{% endif %}"
##############################################################  PRIVATE-GLOBAL END  ################################################################################
#############################################################   PRIVATE-HDTV BEGIN  ################################################################################
  # These are the shows I regularly watch
  private-hdtv:
    manual: no          #Turn this on if you'd rather run this task manually. 
    # I've broken out my series lists into a seperate yml to clean up my config
    include: [ series.yml ]
    # Add accepted entries to Deluge and make sure they end up in the correct folder
    set:
      movedone: /mnt/Main/New_TV/{{ series_name }}/
      label: TV_Shows
      queuetotop: yes
      addpaused: no
    seen: local
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          account: '{{ secrets.trakt.account }}'
          strip_dates: yes
          list: following hdtv
          type: shows
      settings:
        timeframe: 20 minutes
        target: hdtv+ !720p !1080p
        quality: hdrip+ !1080p
        propers: 12 hours
    # Prevent from downloading shows that were aquired manually or are currently downloading
    exists_series:
      - '/mnt/Main/Premieres/'
      - '/mnt/Main/New_TV/'
      - '/mnt/Main/Torrents/'
##############################################################   PRIVATE-HDTV END    ###############################################################################

tasks:
  HDTV-Shows:
    priority: 10
    interval: 30 minutes
    template:
      - private-global
      - private-hdtv
```

Don't know how to get a log that shows what's going wrong during the lookup. Any advice?
