### ISSUE TITLE
SABnzbd - 'Task' object has no attribute 'get'

### ISSUE THREAD

**Issue by Condoamanti** [Flexget/Flexget#1103]
Hello, currently receiving the below error within flexget when attempting to 'add' nzb's to sabnzbd. Recently upgrade sabnzbd to version (1.0.0 [a58bb38]) as well as flexget to (2.05). I have attached the configuration for the tasks listed below.

Any assistance with this would be much appreciated. Please let me know what requirements from logs/configuration are needed.

Error Logs:
```
2016-04-27 17:30 CRITICAL sabnzbd       nzbfinder-2040  Failed to use sabnzbd. Requested http://localhost:54812/sabnzbd/api?nzbname=Breaking.And.Entering.2006.1080p.BluRay.x264.AC3-FuzerHD
2016-04-27 17:30 CRITICAL sabnzbd       nzbfinder-2040  Result was: 'Task' object has no attribute 'get'
2016-04-27 17:30 ERROR    entry         nzbfinder-2040  Failed Breaking.And.Entering.2006.1080p.BluRay.x264.AC3-FuzerHD (sabnzbd unreachable)
```

Configuration:
```
templates:
  movies:
    imdb:
      min_score: 3
      min_votes: 2000
      min_year: 1980
      max_year: 3000
      accept_languages:
          - English
          - english
          - en
          - EN
          - En
    seen_movies: strict
    content_size:
      max: 22000
      min: 500
    quality:
        - 1080p
        - 720p
    regexp:
      reject:
          - 3D
          - SCREENER
      from: title

tasks:
  nzbfinder-2000:
    template: movies
    priority: 1
    rss:
      url: https://nzbfinder.ws/rss?t=2000&dl=1&i=53055&r=292d19bcee7ba3f8502568ffee99c8e7&num=100
    exists_movie:
      path: ~/flexget/Movies_Formatted_New
      type: dirs
      allow_different_qualities: no
      lookup: imdb
    sabnzbd:
      key: 55c17384991ecc5a9d415f7ae6ea7c25
      url: http://127.0.0.1:54812/sabnzbd/api?
      category: flexget
      username: root
      password: <SCRUBBED>

  nzbfinder-2040:
    template: movies
    priority: 2
    rss:
      url: https://nzbfinder.ws/rss?t=2040&dl=1&i=53055&r=292d19bcee7ba3f8502568ffee99c8e7&num=100
    exists_movie:
      path: ~/flexget/Movies_Formatted_New
      type: dirs
      allow_different_qualities: no
      lookup: imdb
    sabnzbd:
      key: 55c17384991ecc5a9d415f7ae6ea7c25
      url: http://localhost:54812/sabnzbd/api?
      category: flexget
      username: root
      password: <SCRUBBED>

```
