### ISSUE TITLE
Look for imdb other people list

### ISSUE THREAD

**Issue by marine1988** [Flexget/Flexget#1110]
Hey I came from couch potato and it has the option to use one list without put password and i use my friend list because she uses imdb a lot and create a good list of movies but i don´t have she's account password. is possible to use that whatchlist without password in flexget?

**Comment by Clem-** [comment]
You can use instead the RSS feed of the IMDb list. See the IMDb list web page for the RSS feed orange icon.

**Comment by marine1988** [comment]
but i need the list of a user is possible?

**Comment by Clem-** [comment]
Sure. With the IMDb list ID (lsXXXXXX), you can find the RSS feed at : http://rss.imdb.com/list/lsXXXXXX

**Comment by marine1988** [comment]
Is not that format but i find it thanks
http://rss.imdb.com/user/ur15183663/watchlist

Now I add it like rss normal or imdb?
http://flexget.com/wiki/Plugins/movie_queue

**Comment by Clem-** [comment]
You don't need the IMDb plugin anymore, just RSS. Something like : 
```
checkIMDBlist:
    rss: 'http://rss.imdb.com/user/ur15183663/watchlist'
    list_add:
      - movie_list: from IMDb
```
And in your download task (ie. discover) :
```
download:
    discover:
      what:
        - movie_list: from IMDb
      from:
        - .........
```
