### ISSUE TITLE
schedule does not run

### ISSUE THREAD

**Issue by M230** [Flexget/Flexget#1115]
I have a simple config file with a scheduled task, but the schedule does not do anyhing. There's nothing in the logs about it. I am running flexget in daemon mode.

config.yml:
```
web_server:
  bind: 0.0.0.0
  port: 3539
api: yes
webui: no

schedules:
  - tasks: '*'
    interval:
      minutes: 1

tasks:
  testtask:
    rss: <my rss url>
    accept_all: yes
    only_new: yes
    deluge:
      path: /Torrents/
      label: flexget
```
