### ISSUE TITLE
Remove the date from a movie list entry

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#1128]
The output of the movie list is composed by the name and the date of the movie, even if the plugin strip_dates plugin is used.

**Comment by wtluke** [comment]
Thanks for putting this in @liiight. Unfortunately, I got the following error
```
2016-05-25 21:27 CRITICAL manager                       [/tasks/moviesPB/discover/what/0/movie_list] Got `{u'strip_year': True, u'list_name': u'allmyfilms'}`, expected: string
```

```
  moviesPB:
    verify_ssl_certificates: no
    discover:
      what:
        - movie_list:
            list_name: allmyfilms
            strip_year: yes
      from:
        - piratebay:
            category: movies
    template: movietemplate
    delay: 10 hours
    priority: 70
    seen: local
    quality:
      - 480p+
      - webrip+
```
