### ISSUE TITLE
seen_movies 'scope: local' not working properly.

### ISSUE THREAD

**Issue by drwyrm** [Flexget/Flexget#1148]
This may be just a configuration issue, so, please advise.

```
 templates:
   local_template:
     disable:
       - seen
       - seen_info_hash
       - retry_failed
 
   local_movies_template:
     accept_all: yes
     imdb_lookup: yes
     <lots of unrelated stuff removed>
 
   local_movies_to_queue_template:
     imdb_required: yes
     exec:
       fail_entries: yes
       on_output:
         for_accepted:
           <lots of unrelated stuff removed>
 
 tasks:
   local_movies:
     filesystem:
       path: '{{secrets.paths.in}}/movies'
       regexp: '.*\.(avi|mkv|mp4|m4v|iso)$'
       recursive: true
       retrieve: files
     template:
       - local_template
       - local_movies_template
       - local_movies_to_queue_template
     seen_movies:
       matching: strict
       **scope: local**
 
```

```
2016-05-07 19:49 VERBOSE  task          **local_subs_movies** REJECTED: `Risen.2016.1080p.BluRay.x264.DTS-JYK` by seen_movies plugin because entry with imdb_id `tt3231054` is already marked seen in the task **local_movies** at 2016-05-06 10:41

```

```
$ sqlite3 db-local.sqlite 
SQLite version 3.8.2 2013-12-06 14:53:30
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select local from seen_entry where feed='local_movies' group by local;
0
sqlite> 
```

Isn't it supposed to set local=1 to all seen_entry from this task/feed ?? Can it be some conflict because i disabled 'seen' plugin and still using 'seen_movies' ?
