### ISSUE TITLE
FTP input plugin improvement suggestions

### ISSUE THREAD

**Issue by Meliox** [Flexget/Flexget#1162]
Findings and suggestions after testing https://github.com/Flexget/Flexget/pull/1161
as discussed with @liiight 

Test config:

```
tasks:
  ftpauto:
    ftp_list:
      username: user
      password: 'a password'
      host: someip
      port: someport
      retrieve: dirs
      use_ssl: yes
      dirs: ./test/
      regex: pal
    series:
      - Girls
    download: C:\Users\Administrator\Desktop\autodl\complete
```

1) Plugin iterates over everything, making it slow to progress 1000 directories.
http://pastebin.com/gg7mPisy

Using the following in dirs property returns above.
./test/
/test/
test

2) Doesn't check/validate valid/invalid properties

3)  Suggest adding a recursion flag to define how many subdirectories should be processed

4) When using dirs, it should only look into the directories defined in config.
