### ISSUE TITLE
send_telegram bug

### ISSUE THREAD

**Issue by Addicted5** [Flexget/Flexget#1177]
When i set send_telegram in a template,i'm getting bug during "flexget send_telegram bootstrap"

```
pi@Raspberry ~ $ flexget send_telegram bootstrap
There is a FlexGet process already running for this config, sending execution there.
Traceback (most recent call last):
  File "/usr/local/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 293, in start
    client.handle_cli(self.args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
KeyError: None

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/flexget/ipc.py", line 80, in exposed_handle_cli
    self.manager.handle_cli(options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/manager.py", line 337, in handle_cli
    options.cli_command_callback(self, command_options)
  File "/usr/local/lib/python2.7/dist-packages/flexget/utils/database.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/send_telegram.py", line 530, in do_cli
    config = _get_config(manager, task_name)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/send_telegram.py", line 520, in _get_config
    return manager.config['tasks'][task].get(_PLUGIN_NAME)
KeyError: None
```

But if i use send_telegram in a task.No bug & telegram message is sent normally.

Here is my config

```
secrets: secrets.yml
#______________SCHEDULE_________________#
schedules: 
  - tasks: [hdanime]
    interval:
      hours: 16
  - tasks: [tvshows]
    schedule:
      hour: 5-13
      minute: "*/25"
  - tasks: [fill_ToDownload]
    interval:
      days: 2
  - tasks: [disc_1080p_mov, disc_720p_mov, disc_movie]
    interval:
      days: 1
  - tasks: [ondisk_imdb]
    interval:
      days: 4
  - tasks: [horrible]
    schedule:
      day_of_week: thu,fri,sat,sun
      minute: "*/45"
#______________WEB_UI_________________#
web_server:
  bind: 0.0.0.0
  port: 9090
api: yes
webui: yes
#_____________TEMPLATES________________#
templates:
#_________________GLOBAL___________________#
  global:
    transmission:
      host: localhost
      port: 9091
      username: '{{secrets.transmission.user}}'
      password: '{{secrets.transmission.pass}}'
      ratio: 0.001
    verify_ssl_certificates: no
    imdb_lookup: yes
    thetvdb_lookup: yes
    send_telegram:
      bot_token: '{{secrets.tg.bot_tk}}'
      parse_mode: markdown
      recipients:
        - username: '{{secrets.tg.user}}'
      template: |
        {%if task in ["disc_1080p_mov","disc_720p_mov","disc_movie"]%}*New Movie added to queue*
        {%else%}*New Episode Added*
        {%endif%}
        {% if series_name is defined -%}
        *{{series_name}}* - {{series_id}} - {{quality|d('')}}
        *{{tvmaze_episode_name|d(tvdb_ep_name)|d('')}}*
        [Image]({{tvmaze_series_original_image|replace("_", "%5F")}})
        [Show page]({{tvmaze_series_url|replace("_", "%5F")}})
        {% elif imdb_name is defined -%}
        *{{imdb_name}}* - ({{imdb_year}})
        {{quality|d('')}}
        {{imdb_score}}/10 - {{imdb_votes}} votes
        {{imdb_genres|join(', ')|title}} 
        *Plot:* {{imdb_plot_outline}}
        [Image]({{tmdb_posters[0]|replace("_", "%5F")}})
        [Movie Page]({{imdb_url|d('')}})
        {% else -%}
        {{title}}
        {%- endif -%}
#_______________MOVIES___________________#
  tempmovie:
    torrent_alive: yes
    discover:
      what:
        - movie_list: ToDownload
      from:
        - search_rss: https://yts.ag/rss/{{ search_term|replace('\ \(\d\d\d\d\)', '')}}/all/all/4
        - rarbg: 
            category: [44, 45]
            ranked: True
#Filter
    regexp:
      reject:
        - (?i)[ .]webrip[ .]
        - (?i)[ .]cam[ .]
        - (?i)[ .]bdscr[ .]
        - (?i)[ .]dvdscr[ .]
        - (?i)[ .]preair[ .]
        - (?i)[ .]ppvrip[ .]
        - (?i)[ .]r5[ .]
        - (?i)[ .]tc[ .]
        - (?i)[ .]ts[ .]
        - (?i)[ .]ecc[ .]
        - (?i)[ .]avc[ .]
        - (?i)[ .]qebs[ .]
        - (?i)[ .]hdtc[ .]
        - (?i)[ .]hdcam[ .]
        - (?i)[ .]hdts[ .]
    list_add:
      - movie_list: OnDisk
    list_queue:
      - movie_list: ToDownload
#_____________END_TEMPLATES________________#
tasks:
  tvshows:
    priority: 1
    inputs:
      - rss: https://eztv.ag/ezrss.xml
    configure_series:
      from:
        trakt_list:
          username: Addicted5
          account: traktuser
          list: mytvshows
          type: shows
          strip_dates: yes
      settings:
        identified_by: ep
        quality: hdtv
        from_group:
          - killers
          - lol
          - asap
          - fum
          - fleet
          - tla
          - dhd
    list_add:
      - trakt_list:
          username: myuser
          account: traktuser
          list: collection
          type: shows
  horrible:
    priority: 2
    inputs:
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=%5BHorribleSubs%5D++%5B720p%5D&filter=2
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=%5BHorribleSubs%5D++%5B480p%5D&filter=2
    series:
      settings:
        anime720p:
          identified_by: sequence
          sequence_regexp:
            - (\d+)
            - S(\d+) (\d+)
          from_group: HorribleSubs
          quality: 720p
        anime480p:
          identified_by: sequence
          sequence_regexp:
            - (\d+)
            - S(\d+) (\d+)
          from_group: HorribleSubs
          quality: 480p
      anime720p:
        - Naruto Shippuuden:
            begin: 460
        - Terra Formars:
            begin: 06
      anime480p:
        - Boku no Hero Academia:
            begin: 07
        - Flying Witch:
            begin: 06
        - Gakusen Toshi Asterisk:
            begin: 19
        - Kabaneri of the Iron Fortress:
            begin: 05
        - Kiznaiver:
            begin: 06
        - Nijiiro Days:
            begin: 18
  hdanime:
    priority: 3
    inputs:
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=commie+K+return+of+kings&filter=2
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=commie+One+Punch+Man&filter=2
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=fff+Noragami+Aragoto&filter=2
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=fff+Gakusen+Toshi+Asterisk&filter=2
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=Hai+to+Gensou+no+Grimgar&filter=3
    accept_all: yes
  fill_ToDownload:
    priority: 4
    template:
      - no_global
    seen: local
    imdb_list:
      login: '{{secrets.imdb.user}}'
      password: '{{secrets.imdb.pass}}'
      list: watchlist
    accept_all: yes
    imdb_lookup: yes
    thetvdb_lookup: yes
    list_add:
      - movie_list: ToDownload
    list_queue:
      - imdb_list:
          login: '{{secrets.imdb.user}}'
          password: '{{secrets.imdb.pass}}'
          list: watchlist
  disc_1080p_mov:
    priority: 5
    template: tempmovie
    quality:
      - 1080p
    content_size:
      min: 1000
      max: 2800
      strict: no
  disc_720p_mov:
    priority: 6
    template: tempmovie
    quality:
      - 720p
    content_size:
      min: 550
      max: 1400
      strict: no
  disc_movie:
    priority: 7
    template: tempmovie
    quality:
      - 1080p
      - 720p
    content_size:
      min: 550
      max: 4200
      strict: no
  ondisk_imdb:
    priority: 8
    template:
      - no_global
    seen: local
    movie_list: OnDisk
    imdb_lookup: yes
    thetvdb_lookup: yes
    accept_all: yes
    list_add:
      - imdb_list:
          login: '{{secrets.imdb.user}}'
          password: '{{secrets.imdb.pass}}'
          list: OnDisk
      - trakt_list:
          username: myuser
          account: traktuser
          list: collection
          type: movies
    list_queue:
      - movie_list: OnDisk
```
