### ISSUE TITLE
rottentomatoes_list not produceing entries

### ISSUE THREAD

**Issue by harywilke** [Flexget/Flexget#1189]
```
tasks:
  Rottentomatoes_DVDs:
    rottentomatoes_list:
      api_key: '{{ secrets.rottentomatoes.api }}'
      dvds:
        - new_releases
        - top_rentals
        - current_releases
    accept_all: yes
```

this task doesn't produce anything.

digging around in the code i believe the problem is line 57 of rottentomatoes_list.py

```
            if type(l_names) is not list: 
                continue
```

this always evaluates to true and all the l_names items hit the continue statement breaking out of the parent for loop.
i tried :

```
            if type(l_names) is not list:
                log.warning('type(%s) is not list, its %s, continuing' % (l_names, type(l_names))) 
                continue
```

and got this :

`WARNING  rottentomatoes_list Rottentomatoes_DVDs type([u'new_releases']) is not list, its <type 'list'>, continuing`

I gather this bit of code is trying to skip the api_key. For now I'm replacing line 57 with:
`if l_type == 'api_key'`
hacky and defiantly not defensive programing, but it works for me.
