### ISSUE TITLE
Telegram bug

### ISSUE THREAD

**Issue by Addicted5** [Flexget/Flexget#1208]
Reinstalled 1 week old backup OS image & so got 1 week old flexget.
Then updated flexget & telegram plugin.
Used working config.(which was working in previous setup,i.e newer to 1 week backup).

Ran a task with send_telegram & here is log & crashlog with task part of config

Log
[http://pastebin.com/x5dPM8sx](http://pastebin.com/x5dPM8sx)

CrashLog
[http://pastebin.com/7SyJb6r2](http://pastebin.com/7SyJb6r2)

Part of config-

```
  HorribleSubs:
    priority: 2
    include: horrible.yml
    deluge:
      label: HorribleSubs
      queuetotop: yes
      movedone: "/home/pi/Downloads/Completed/Anime/{{series_name}}/"
      ratio: 0.001
    inputs:
             #[HorribleSubs] [720p]
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=%5BHorribleSubs%5D+%5B720p%5D&filter=2
             #[HorribleSubs] [480p]
      - rss: http://www.nyaa.se/?page=rss&cats=1_37&term=%5BHorribleSubs%5D+%5B480p%5D&filter=2
    send_telegram:
      bot_token: '{{secrets.tg.tk}}'
      parse_mode: markdown
      recipients:
        - username: '{{secrets.tg.user}}'
      template: |
        *Task:  *{{task|replace("_", "-")}}
        *{{title}}*
        {% if series_name is defined -%}
        *EP-* {{tvdb_ep_name|d('')}}
        *Size:* {{ content_size }} MB
        [{{tvdb_ep_image|replace("_", "%5F")}}]
        [{{imdb_url}}]
        {% else -%}
        *Size:* {{ content_size }} MB
        {%- endif -%} 


```
In horrible.yml i only used series plugin to config all series i want.
In global section 

```
  global:
    deluge:
      host: localhost
      port: 58846
      automanaged: true
      magnetization_timeout: 30
    verify_ssl_certificates: no
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
      Accept-Encoding: "deflate, gzip"
    domain_delay:
      rarbg.to: 3 seconds
      kat.cr: 3 seconds
      www.nyaa.se: 3 seconds
      torcache.net: 3 seconds
      thetvdb.com: 3 seconds
      www.tvmaze.com: 3 seconds
      apt.tvmaze.com: 3 seconds
      torrentapi.org: 3 seconds
    retry_failed:
      retry_time: 10 seconds
      retry_time_multiplier: 1
      max_retries: 4
    add_trackers:
      - udp://tracker.coppersurfer.tk:6969
      - udp://9.rarbg.to:2710
      - http://tracker.trackerfix.com:80
      - udp://tracker.opentrackr.org:1337
    imdb_lookup: yes
    thetvdb_lookup: yes
    tmdb_lookup: yes
```
```
