### ISSUE TITLE
StaleDataError: DELETE statement on table 'trakt_image_movie' expected to delele 7 row(s); only 10 were matched

### ISSUE THREAD

**Issue by qvazzler** [Flexget/Flexget#1212]
### Expected behaviour:
A trakt_lookup was supposed to be done after an entry was injected into a task by irc_daemon

### Actual behaviour:
It crashed.

### Steps to reproduce:
Not entirely sure, but it appears that Flexget only crashed twice, and both times it was because of this movie.

```13 Hours The Secret Soldiers of Benghazi```

#### Config:
```
templates:
  global:
    retry_failed:
      retry_time: 5 minutes # Base time in between retries
      retry_time_multiplier: 1 # Amount retry time will be multiplied by after each successive failure
      max_retries: 25 # Number of times the entry will be retried
  transmit-movies:
    transmission:
      host: '{{ secrets.transmission.host }}'
      port: 9091
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'
      path: '{{ secrets.transmission.download_path_movies }}'
  download-movie:
    discover:
      what:
        - movie_list: 'movies from trakt'
      from:
        - mtv:
            username: '{{ secrets.mtv.username }}'
            password: '{{ secrets.mtv.password }}'
            category:
              - Movies
            #tags: [adventure]
            all_tags: yes
        - torrentleech:
            rss_key: '{{ secrets.torrentleech.rss_key }}'
            username: '{{ secrets.torrentleech.username }}'
            password: '{{ secrets.torrentleech.password }}'
        - iptorrents:
            rss_key: '{{ secrets.iptorrents.rss_key }}'
            uid: 1456769
            password: '{{ secrets.iptorrents.password }}'
            category:
              - Movie-HD-Bluray
              - Movie-DVD-R
        - sceneaccess:
            username: '{{ secrets.sceneaccess.username }}'
            password: '{{ secrets.sceneaccess.password }}'
            gravity_multiplier: 100
            category:
              browse:
                - Movies/x264
              archive:
                - Movies/Packs
tasks:
  get_movies_direct:
    manual: yes
    trakt_lookup:
      username: '{{ secrets.trakt.username }}'
      account: '{{ secrets.trakt.account }}'
    content_size:
      max: 23040
      min: 1024
    quality: 720p bluray+
    list_queue:
      - movie_list: 'movies from trakt'
    template: transmit-movies
```
  
#### Log:

**first time crash**
https://bpaste.net/show/4ec2fddfad10

**second time crash**
https://bpaste.net/show/492dfc6d0758

### Additional information:

- Flexget Version:
- Python Version: 2.0.23 (Latest release: 2.0.35)
- Installation method: pip & venv
- OS and version: Raspbian on Pi3
- Link to crash log: https://bpaste.net/show/492dfc6d0758
