### ISSUE TITLE
Newznab plugin series search not working

### ISSUE THREAD

**Issue by activ** [Flexget/Flexget#1217]
### Expected behaviour:
Episodes should be found, and using the same config with torrents as input and output they are found. (Episode nzb's are available when doing a manual search)

### Actual behaviour:
An error is logged and nothing is found

### Steps to reproduce:
Use the newznab plugin to search for series (I tested with nzbgeek)

#### Config:
```
 series search usenet:
    domain_delay:
      api.nzbgeek.info: 3 seconds
    priority: 14
    thetvdb_lookup: yes
    trakt_lookup: yes
    seen: local
    accept_all: yes    
    template:
      - pushbullet-template       
      - sabnzbd-series-template
    configure_series:
      settings:
        identified_by: ep
        timeframe: 16 hours
        target: 1080p
        quality: 720p-1080p
      from:
        thetvdb_favorites:
          username: XXXXX
          account_id: XXXXXXXX       
    discover:
      what:
        - emit_series:
            from_start: yes
            backfill: yes
      from:
        - newznab:
            website: "https://api.nzbgeek.info/"
            apikey: "XXXXXXXX"
            category: tv
    interval: 1 hour
    exists_series:
      - /mnt/user/Series/
```
#### Log:
search usenet tvrage lookup support is gone, someone needs to update this plugin!

### Additional information:

- Flexget Version: 2.0.31
- Python Version: 2.7.11
- Installation method: PIP
- OS and version: Arch linux in docker on Unraid (Kernel 4.4.6-unRAID)
- Link to crash log:
