### ISSUE TITLE
Flexget & t411 -> UNDECIDED

### ISSUE THREAD

**Issue by Nilremagl** [Flexget/Flexget#1233]
Hello, I can't find out what's wrong with my config file.
I always end with
```
Summary - Accepted: 0 (Rejected: 0 Undecided: 50 Failed: 0)
```

Here is my config
#### Config:
```
templates:
  t411:
    plugin_priority:
      headers:
        User-Agent: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
        Accept-Charset: "ISO-8859-1,utf-8;q=0.7,*;q=0.3"
        Accept-Language: "fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4"
        Cache-Control: "max-age=0"
        Connection: "keep-alive"
        Cookie: "uid=107440019; pass=deleted; authKey=deleted"
  tv-my_shows:
    template:
      - t411
    series:
      - Game Of Thrones:
          identified_by: ep
      - Game Of Thrones:
          begin: S06E08
      - Orange Is The New Black:
          identified_by: ep
      - Orange Is The New Black:
          begin: S04E01
    transmission:
      host: localhost
      port: 9091
      username: deleted
      password: deleted
    set:
      content_filename: "{{series_name}} - {{series_id}} - {{quality}}"
      movedone: "/home/xbian/series/{{ series_name }}/{{'S%02d'|format(series_season)}}"
    html:
      url: "https://www.t411.ch/torrents/search/?name=&description=&file=&user=&cat=210&subcat=433&term%5B46%5D%5B%5D=944&term%5B45%5D%5B%5D=973&term%5B51%5D%5B%5D=1216&term%5B7%5D%5B%5D=16&term%5B7%5D%5B%5D=15&term%5B7%5D%5B%5D=1162&term%5B7%5D%5B%5D=12&search=&submit=Recherche"
      title_from: title
      links_re:
        - "^http://www.t411.ch/torrents/[^/]+(?!/)[^/]+$"
     accept_all: yes
  tv-my_shows_anime:
    template:
      - t411
    series:
      - Dragon Ball Super:
          identified_by: ep
    transmission:
      host: localhost
      port: 9091
      username: xbian
      password: raspberry
     set:
      content_filename: "{{series_name}} - {{series_id}} - {{quality}}"
      movedone: "/home/xbian/series/{{ series_name }}/{{'S%02d'|format(series_season)}}"
    html:
      url: "https://www.t411.ch/torrents/search/?search="
      title_from: title
      links_re:
        - "^http://www.t411.ch/torrents/[^/]+(?!/)[^/]+$"
      accept_all: yes
tasks:
  My_TV_Shows:
    priority: 1
    template:
      - tv-my_shows
    discover:
      what:
        - emit_series: yes
      from:
        - t411:
            category: Série TV
            terms:
              - VOSTFR
              - 1080p
            max_results: 500
    priority: 2
    template:
      - tv-my_shows_anime
    discover:
      what:
        - emit_series: yes
      from:
        - t411:
            category: Animation Série
            terms:
              - VOSTFR
              - 720p
```
Here are my logs with <i><b> flexget --test execute -v</i></b>

#### Log:
```

2016-06-13 17:46 INFO     manager                       Test mode, creating a copy from database ...
2016-06-13 17:46 INFO     manager                       Test database created
2016-06-13 17:47 CRITICAL manager                       while parsing a block mapping in "<unicode string>", line 13, column 5: template: ^ expected <block end>, but found '<block mapping start>' in "<unicode string>", line 37, column 6: accept_all: yes ^
2016-06-13 17:47 CRITICAL manager                       Failed to load config file: Config file is not valid YAML


```
I can't find my mistakes..
Thanks for you help
