### ISSUE TITLE
Trakt_lookup not populating trakt_released field

### ISSUE THREAD

**Issue by Tommatheussen** [Flexget/Flexget#1236]
### Expected behaviour:
Trakt_lookup should populate the trakt_released field

### Actual behaviour:
The trakt_released field is always set to None for movies (haven't tested with series)

### Steps to reproduce:
- Step 1: Add a trakt_lookup in your config
- Step 2: Act on the trakt_released field (for example if statement, or echo)

#### Config:
```
FillMovieQueue:
    trakt_list:
      account: '{{ secrets.trakt.account }}'
      list: watchlist
      type: movies
    trakt_lookup: yes
    accept_all: yes
    exec:
      on_filter:
        for_entries:
          - echo "found {{ trakt_released }}"
```
  
#### Log:
```
2016-06-14 14:32 DEBUG exec FillMovieQueue phase_name: on_filter operation: for_entries cmd: echo "found None”
```

### Additional information:

- Flexget Version: 2.0.45
- Python Version: 2.7.6
- Installation method: Pip
- OS and version: Ubuntu 14.04
- Link to crash log: None
