### ISSUE TITLE
Adding Trakt series collection and having auth issues

### ISSUE THREAD

**Issue by mannionpatrick** [Flexget/Flexget#1244]
Hi - 

I had trakt movies working beautifully pre-upgrade (1.x to 2.0.45 about a week ago). They still work after the upgrade, so I don't think I broke anything :)

I've been trying to add a Trakt series watchlist for the last two days. I've done the flex get trait authorize mannionpatrick thing, and it went successfully; when I execute I receive the same error constantly. Any ideas?

Based on one closed issue I'd found in a search, I've removed the auth on the flex get side and re-auth'd; no change in the error message...

Thanks in advance - this has me baffled.

Error: 
```
2016-06-18 11:01 CRITICAL plugin        trakt_series_queue_fill An error has occured looking up: Trakt_id: 34818 Error: 401 Client Error: Unauthorized for url: https://api-v2launch.trakt.tv/shows/34818/progress/collection
2016-06-18 11:01 WARNING  task          trakt_series_queue_fill Aborting task (plugin: trakt_emit).
```

Config file snippet:
```
  trakt_series_queue_fill:
    priority: 2
    trakt_emit:
      username: mannionpatrick
      context: collected
      position: next
      list: watchlist
    accept_all: yes
    set_series_begin: yes
```
