### ISSUE TITLE
Can only emit ep or series based series. <x> is identified by auto.

### ISSUE THREAD

**Issue by OmegaZero** [Flexget/Flexget#1268]
I'm not sure I'm doing the emit/discover properly as I've had it set up for a while and it never seems to download anything (even though I can go on the torrent sites and find episodes).

Flexget Version: 2.0.43

Here's my config:

```` 
 KidsAutoTV:
    template: kidtv
    configure_series:
      from:
        trakt_list:
          username: xxxxxx
          list: kidwatchlist
          type: shows
          strip_dates: yes
    discover:
      what:
        - emit_series:
            backfill: yes
      from:
        - kat:
            category: tv
            verified: yes
        - torrentz: verified
        - piratebay:
            category: tv
            sort_by: seeds
      interval: 1 day
````

It's obviously using trakt.tv of which the only show I have set up is "Brain Games".

Execute Output:

2016-07-05 15:40 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2016-07-05 15:40 INFO     interval      KidsAutoTV      Ignoring interval because of --now
2016-07-05 15:40 VERBOSE  trakt_list    KidsAutoTV      Retrieving `shows` list `kidwatchlist`
2016-07-05 15:40 VERBOSE  emit_series   KidsAutoTV      Can only emit ep or sequence based series. `Brain Games` is identified_by auto
2016-07-05 15:40 WARNING  discover      KidsAutoTV      Input emit_series did not return anything
2016-07-05 15:40 VERBOSE  discover      KidsAutoTV      Discovering 0 titles ...
2016-07-05 15:40 VERBOSE  details       KidsAutoTV      Task didn't produce any entries.
2016-07-05 15:40 VERBOSE  details       KidsAutoTV      Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)

What am I doing wrong?

**Comment by cvium** [comment]
```
    configure_series:
      from:
        trakt_list:
          username: xxxxxx
          list: kidwatchlist
          type: shows
          strip_dates: yes
      settings:
        identified_by: ep
```

This is not a bug.
