### ISSUE TITLE
Issue with new parameter rpc-url in transmission plugin

### ISSUE THREAD

**Issue by eddyx** [Flexget/Flexget#1339]
### Expected behaviour:
flexget can notify the transmission daemon to start to download the file.

### Actual behaviour:
always said username/password for transmission is invalid. Transmission daemon can't get the notification

I'd like to keep it in brief for after my long time trying, I found the root cause.

In transmission daemon configuration file, to save typing when i want to access the web ui, i modified the rpc-url parameter from /transmission/ to /pt/.  But in flexget configuration file, it seems there is no corresponding parameter. There are only host and port, under this situation, i always can't get these two animals to talk. After I switch back from /pt/ to /transmission/, everything are back on track.

The above is what i found. Not sure if it's the correct place to raise this issue.

Thank you.

**Comment by OmgOhnoes** [comment]
I haven't modified the path myself but, basically Flexget doesn't have a parameter for that change.

TransmissionRPC handles it using the host, you can try changing that in Flexget and see if it works.

TransmissionRPC expects the full path... something like ```host: localhost:9091/pt/``` should work.

**Comment by cvium** [comment]
From what I can see TransmissionRPC supports a complete URI eg. `localhost:9091/pt/`, so having that as your host should work. You'll still have to specify port, but it's not used.

Let me know if this doesn't work. Closing.

**Comment by eddyx** [comment]
Thank you for replying, i tried your way of setting host with port, but i got the crash report as following:

2016-11-14 14:00 DEBUG    manager                       Config file /etc/flexget/config.yml selected                                                   
2016-11-14 14:00 INFO     manager                       Test mode, creating a copy from database ...                                                   
2016-11-14 14:00 INFO     manager                       Test database created                                                                          
2016-11-14 14:00 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.                 
2016-11-14 14:00 INFO     transmission  pt-task         Trying to connect to transmission...                                                           
2016-11-14 14:00 CRITICAL task          pt-task         BUG: Unhandled error in plugin transmission: coercing to Unicode: need string or buffer, NoneTy
pe found                                                                                                                                               
Traceback (most recent call last):                                                                                                                     
  File "/home/someuser/flexget/local/lib/python2.7/site-packages/flexget/task.py", line 477, in __run_plugin                                              
    return method(*args, **kwargs)                                                                                                                     
  File "/home/someuser/flexget/local/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__                                                  
    return self.func(*args, **kwargs)                                                                                                                  
  File "/home/someuser/flexget/local/lib/python2.7/site-packages/flexget/plugins/clients/transmission.py", line 141, in on_task_start                     
    self.client = self.create_rpc_client(config)                                                                                                       
  File "/home/someuser/flexget/local/lib/python2.7/site-packages/flexget/plugins/clients/transmission.py", line 75, in create_rpc_client                  
    cli = transmissionrpc.Client(config['host'], config['port'], user, password)                                                                       
  File "/home/someuser/flexget/local/lib/python2.7/site-packages/transmissionrpc/client.py", line 146, in __init__                                        
    self.url = urlo.scheme + '://' + urlo.hostname + urlo.path                                                                                         
TypeError: coercing to Unicode: need string or buffer, NoneType found                                                                                  

After i modified it back to original, it works again.

**Comment by cvium** [comment]
Need to see the config.

**Comment by eddyx** [comment]
The following is the config
```
tasks:                                                                                                                                                 
  pt-task:                                                                                                                                             
    rss: https://sompt/site
    accept_all: yes                                                                                                                                    
    exists: /download/folder                                                                                                                             
    transmission:                                                                                                                                      
      host: localhost:9091/pt                                                                                                          
      username: usr                                                                                                                                  
      password: passwd                                                                                                                               
    clean_transmission:                                                                                                                                
      host: localhost:9091/pt/                                                                                                                 
      username: usr                                                                                                                                  
      password: passwd                                                                                                                               
      finished_for: 2 days                                                                                                                             
    disable: details                                                                                                                                   
                                                                                                                                                       
schedules:                                                                                                                                             
  - tasks: pt-task                                                                                                                                     
    interval:                                                                                                                                          
      minutes: 15
```
