### ISSUE TITLE
BUG: "Unknown IMDB type entry received: documentary. Skipping" in imdb_list

### ISSUE THREAD

**Issue by wtluke** [Flexget/Flexget#1343]
As [discussed](http://discuss.flexget.com/t/unknown-imdb-type-entry-received-documentary/2618/2) with @liiight.

`Unknown IMDB type entry received: documentary. Skipping`

Config:

``` yaml
fill-movies:
    priority: 1
    imdb_list:
      login: x
      password: x
      list: watchlist
    accept_all: yes
    list_add:
      - movie_list: allmyfilms
```
