### ISSUE TITLE
Error during input plugin trakt_list: Could not retrieve list from trakt (/.../collection/episodes)

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#1380]
I'm having following error:

> Error during input plugin trakt_list: Could not retrieve list from trakt (405 Client Error: Method Not Allowed for url: https://api-v2launch.trakt.tv/users/me/collection/episodes)

with this setup:
```
  Download_Series_Missing:
    manual: yes
    interval: 24 hours
    priority: 3
    trakt_list:
      account: '{{ secrets.trakt.acc }}'
      list: collection
      type: shows
    crossmatch:
      from:
        - trakt_list:
            account: '{{ secrets.trakt.acc }}'
            list: collection
            type: episodes
      fields:
        - imdb_id
      action: reject
    list_add: 
      - entry_list: testing
```    

and same error for another task, with crossmatching already collected episodes:

```
    crossmatch:
      from:
        - trakt_list:
            account: '{{ secrets.trakt.acc }}'
            list: '{{ secrets.trakt.OnHold }}'
            type: shows
        - trakt_list:
            account: '{{ secrets.trakt.acc }}'
            list: collection
            type: episodes
      fields:
        - imdb_id
      action: reject
```
