### ISSUE TITLE
Daemon & task.config_modified

### ISSUE THREAD

**Issue by paranoidi** [Flexget/Flexget#1406]
### Expected behaviour:

next_series_episode starts creating new episodes when series has been added into a configuration file

### Actual behaviour:

When modifying configuration (ie. adding series) at least with daemon running it does NOT cause task.config_modified to be updated.

(Workaround done for this in series.py on_task_start)
### Steps to reproduce:
- start daemon
- add new series to a template which is used in a discover task
- reload daemon configuration
- run discover-task

Result: New series is not mentioned in anywhere

#### Config:
```
templates:
  tv:
    series:
    - foo

tasks:
  discover-series:
  template: [tv]
  discover:
    from:
    - next_series_episodes: {from_start: yes}
```
  
### Additional information:

- Flexget Version: Latest Development branch
- Python Version: 2.7.x
- Installation method: Git
- OS and version:  Ubuntu 14.04
- Link to crash log: N/A
