### ISSUE TITLE
Many Duplicate Downloads

### ISSUE THREAD

**Issue by ssshake** [Flexget/Flexget#1448]
### Expected behaviour:

Only download one copy of a given episode and ignore any new copies that show up in the RSS feed.

### Actual behaviour:

For the past year or so flexget has been aggressively downloading duplicate episodes. By that I mean it will download maybe 5 unique copies of a tv episode. This can happen the same day or many days after. It's almost as if it has no concept of what it has downloaded before and is just getting anything that matches the list.

Any ideas?

Here is an example from the DB

```

lAsh vs. Evil Deadqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
x Episode ID x Release titles                                               x
tqqqqqqqqqqqqnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqu
x S02E01     x Ash.vs.Evil.Dead.S02E01.1080p.WEBRip.X264-DEFLATE            x
x            x Ash.vs.Evil.Dead.S02E01.720p.WEBRip.X264-DEFLATE             x
x            x Ash.vs.Evil.Dead.S02E01.WEBRip.X264-DEFLATE                  x
x            x Ash.vs.Evil.Dead.S02E01.720p.HDTV.x264-FLEET                 x
x            x Ash.vs.Evil.Dead.S02E01.1080p.HDTV.x264-BRISK                x
x            x Ash.vs.Evil.Dead.S02E01.Home.720p.AMZN.WEBRip.DD5.1.x264-NTb x
x S02E03     x Ash.vs.Evil.Dead.S02E03.WEBRip.X264-DEFLATE                  x
x            x Ash.vs.Evil.Dead.S02E03.720p.WEBRip.X264-DEFLATE             x
x            x Ash.vs.Evil.Dead.S02E03.1080p.WEBRip.X264-DEFLATE            x
x            x Ash.vs.Evil.Dead.S02E03.720p.HDTV.x264-FLEET                 x
mqqqqqqqqqqqqvqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
 Downloaded Un-downloaded



```
**All the episodes are showing in grey, looking like "Un-downloaded". I suppose that would be the issue, but I don't know why.

#### Config:
```
tasks:
  TV:
    rss: domain.com
    interval: 1 hour
    content_size:
      min: 300
      max: 3072
      strict: no
    series:
      - Westworld
      - Alone
      - Orphan Black
      - Childhood's End
      - Grandfathered
      - You're the Worst
      - The Expanse
      - Better Call Saul
      - 12 Monkeys
      - Gotham
      - House of Cards
      - Homeland
      - Silicon Valley
      - Rick and Morty
      - Blunt Talk
      - Black Mirror
      - Archer
      - Saturday Night Live
      - Cosmos
      - Suits
      - Aqua
      - Daily Show
      - Mr. Robot
      - Robot Chicken
      - Joe Rogan
      - Heroes Reborn
      - Hell on Wheels
      - Ash vs. Evil Dead
      - Empire
      - Fear of the Walking Dead
      - Californication
      - Curb Your Enthusiasm
      - Drunk and On Drugs Happy Time Fun Hour
      - Eastbound and Down
      - Fringe
      - Futurama
      - Game of Thrones
      - Louie
      - Mad Men
      - Metalocalypse
      - Sons of Anarchy
      - South Park
      - Trailer Park Boys
      - The IT Crowd
      - The League
      - True Detective
      - Newsroom
      - The Walking Dead
      - Vikings
      - Shameless
      - Roast of
      - Halt and Catch Fire
      - Z Nation
    set:
      path: /media/Storz1/Torrents/_TV/{{series_name}}/Season {{series_season}}
    download: /media/Storz1/Torrents/.torrents/
    transmission:
      host: localhost
      port: 9091
      username: **********
      password: ***********

```
 

### Additional information:

- Flexget Version:

flexget --version
2.3.42
Latest release: 2.3.44

**Comment by cvium** [comment]
Gonna need to see some logs of your task accepting multiples of the same episode

**Comment by ssshake** [comment]
It is my full config. I just added some new information to the original post. 

"All the episodes are showing in grey, looking like "Un-downloaded". I suppose that would be the issue, but I don't know why."

I've found it difficult to find any mention of the Downloaded/Un-downloaded criteria. I checked some other shows and they seem to mark Downloaded properly. It appears to be an issue with only some TV show names. 

Looking at the logs quickly I think this might be be a clue.

```


2016-10-16 15:00 ERROR    download      BITME           Exception while writing: [Errno 13] Permission denied: u'/media/Storz1/Torrents/_TV/Ash vs. Evil Dead/Season 2/Ash.vs.Evil.Dead.S02E03.720p.HDTV.x264-FLEET.torrent'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/download.py", line 369, in on_task_output
    self.output(task, entry, config)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/output/download.py", line 476, in output
    shutil.move(entry['file'], destfile)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: u'/media/Storz1/Torrents/_TV/Ash vs. Evil Dead/Season 2/Ash.vs.Evil.Dead.S02E03.720p.HDTV.x264-FLEET.torrent'


```

**Comment by cvium** [comment]
Well, looks like permission issues. This is not really specific to Flexget.

**Comment by ssshake** [comment]
I don't know why it's trying to write the .torrent file to that location, or why when doing so it fails. My flexget config tells it to write .torrent files to a different directory.

**Comment by ssshake** [comment]
Also I agree, I'll figure it out on my end. I suppose the point of my bug report would be that in the case of permission issues, it would be cool if flexget failed gracefully and displayed a notice in standard out. The current behavior is to retry continually which results in burning through a ratio.

**Comment by cvium** [comment]
I've located the problem (although it's not a bug per se). `download` uses the `path` field.

**Comment by ssshake** [comment]
k, cool so this?

```

    download:
      path: /media/Storz1/Torrents/.torrents/


```

**Comment by cvium** [comment]
No. The problem is that you set the `path` field in the entries to `/media/Storz1/Torrents/_TV/{{series_name}}/Season {{series_season}}`. The `path` field always takes precedent over the path specified directly to the plugin.
And so you end up saving the .torrent file to `/media/Storz1/Torrents/_TV/{{series_name}}/Season {{series_season}}`.

There is no way around this.

**Comment by ssshake** [comment]
Sorry but I feel clueless now. Where would the payload be saved if I didn't specify a set->path?  Is there a different way that I'm supposed to achieve this?

Wouldn't path being set for download override the save location of .torrent files?? The docs show that:

```

download:
  path: /path/here
  overwrite: yes
  fail_html: no
  temp: /path/for/temp
  filename: my_filename.torrent

```
