### ISSUE TITLE
Episode look-up does not use localized-string; Episode look-up happens before Series-lookup

### ISSUE THREAD

**Issue by mfonville** [Flexget/Flexget#1460]
### Expected behaviour:
`tvdb_lookup` should use the language information it has when querying episode information.
`tvdb_lookup` should always first search for generic series-details, before searching for the specific episode. That is most robust and could avoid race-conditions, because it would always have as much information about the serie as possible, before querying more details from tvdb, especially having `tvdb_id`.

### Actual behaviour:
`tvdb_lookup` episode lookup does apparently not use the language-accept (or it should have found 'Zondag met Lubach' in Dutch). Neither did have the `tvdb_id` ready when looking for the episode.
I am not sure if that is something that should be fixed in `tvdb_lookup` or whether  `npo_watchlist` should provide more details.

#### Config:
```
tasks:
  Series-NPO:
    npo_watchlist:
      email: 'xxxx@xxxxl.com'
      password: 'xxxxxxxxx'
      max_episode_age_days: 5
    thetvdb_lookup:
      language: nl
    trakt_lookup:
      account: xxxxxxx
      username: xxxxxxxx
    accept_all: yes
    if:
      - "trakt_watched": reject
    exec:
      fail_entries: yes
      auto_escape: yes
      on_output:
        for_accepted:
          - download-npo xxxxxxxxxxxxxx
```
  
#### Log:
```
api_tvdb      Looking up tvdb information for Zondag met Lubach None
api_tvdb      Series <name=Zondag met Lubach,tvdb_id=None> not found in cache, looking up from tvdb.
util.simple_persistence setting key auth_tokens value {u'default': u'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzcxMzQ5MzEsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDc3MDQ4NTMxfQ.jYYWSS2Dm65wREbYa-9vdqi-agrDVMKxU7uBnsXk4ySiDiVHg791Hv-fVtVVk6MIS5X4_JPzTHDX7gf3qLmOCOJDoYVNBrbs2rxfCD6FyUlN5zTxYABr7naKMNOssg2uU2_i6Adq20k_WIFe6midsqfymNmMi24uit4w4dm-XpdZZq-AKTApQK4PDDIjeBQqmh6tYHmZokzuApsEkniVxRNVi4oOMThWe7Xo6Cwjm9Qhd6jwiT-DUUkcajGkx4IQShzKJ960_7sSiqRZjhVsp9pWOo00UG9OHkV5hdLXWfUGw_Ai4_ZSTbd4KLcRfpCwtpcx-hfWVbglB771j0sweg'}
utils.requests Fetching https://api.thetvdb.com/search/series
thetvdb_lookup Error looking up tvdb episode information for Zondag met Lubach (VPWON_1261999): Unable to get search results for Zondag met Lubach: 404 Client Error: Not Found for url: https://api.thetvdb.com/search/series?name=Zondag+met+Lubach
api_trakt     Type of title: <type 'unicode'>
api_trakt     Searching with params: query=Zondag met Lubach, type=show, year=None
utils.requests Fetching https://api-v2launch.trakt.tv/search
trakt_lookup  Unable to find title="Zondag met Lubach" on trakt.
api_tvdb      Looking up tvdb information for Zondag met Lubach None
api_tvdb      Series <name=Zondag met Lubach,tvdb_id=None> not found in cache, looking up from tvdb.
util.simple_persistence setting key auth_tokens value {u'default': u'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzcxMzQ5MzEsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDc3MDQ4NTMxfQ.jYYWSS2Dm65wREbYa-9vdqi-agrDVMKxU7uBnsXk4ySiDiVHg791Hv-fVtVVk6MIS5X4_JPzTHDX7gf3qLmOCOJDoYVNBrbs2rxfCD6FyUlN5zTxYABr7naKMNOssg2uU2_i6Adq20k_WIFe6midsqfymNmMi24uit4w4dm-XpdZZq-AKTApQK4PDDIjeBQqmh6tYHmZokzuApsEkniVxRNVi4oOMThWe7Xo6Cwjm9Qhd6jwiT-DUUkcajGkx4IQShzKJ960_7sSiqRZjhVsp9pWOo00UG9OHkV5hdLXWfUGw_Ai4_ZSTbd4KLcRfpCwtpcx-hfWVbglB771j0sweg'}
utils.requests Fetching https://api.thetvdb.com/search/series
util.simple_persistence setting key auth_tokens value {u'default': u'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzcxMzQ5MzEsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDc3MDQ4NTMxfQ.jYYWSS2Dm65wREbYa-9vdqi-agrDVMKxU7uBnsXk4ySiDiVHg791Hv-fVtVVk6MIS5X4_JPzTHDX7gf3qLmOCOJDoYVNBrbs2rxfCD6FyUlN5zTxYABr7naKMNOssg2uU2_i6Adq20k_WIFe6midsqfymNmMi24uit4w4dm-XpdZZq-AKTApQK4PDDIjeBQqmh6tYHmZokzuApsEkniVxRNVi4oOMThWe7Xo6Cwjm9Qhd6jwiT-DUUkcajGkx4IQShzKJ960_7sSiqRZjhVsp9pWOo00UG9OHkV5hdLXWfUGw_Ai4_ZSTbd4KLcRfpCwtpcx-hfWVbglB771j0sweg'}
utils.requests Fetching https://api.thetvdb.com/series/288799
trakt_lookup  No lookup arguments provided.
api_tvdb      Looking up tvdb information for Zondag met Lubach 288799
api_tvdb      Series <name=Zondag met Lubach,tvdb_id=288799> information restored from cache.
api_tvdb      Looking up actors for series Zondag met Lubach
util.simple_persistence setting key auth_tokens value {u'default': u'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzcxMzQ5MzEsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDc3MDQ4NTMxfQ.jYYWSS2Dm65wREbYa-9vdqi-agrDVMKxU7uBnsXk4ySiDiVHg791Hv-fVtVVk6MIS5X4_JPzTHDX7gf3qLmOCOJDoYVNBrbs2rxfCD6FyUlN5zTxYABr7naKMNOssg2uU2_i6Adq20k_WIFe6midsqfymNmMi24uit4w4dm-XpdZZq-AKTApQK4PDDIjeBQqmh6tYHmZokzuApsEkniVxRNVi4oOMThWe7Xo6Cwjm9Qhd6jwiT-DUUkcajGkx4IQShzKJ960_7sSiqRZjhVsp9pWOo00UG9OHkV5hdLXWfUGw_Ai4_ZSTbd4KLcRfpCwtpcx-hfWVbglB771j0sweg'}
utils.requests Fetching https://api.thetvdb.com/series/288799/actors
api_trakt     Type of title: <type 'unicode'>
api_trakt     Searching with params: query=Zondag met Lubach, type=show, year=None
utils.requests Fetching https://api-v2launch.trakt.tv/search
trakt_lookup  Unable to find title="Zondag met Lubach" on trakt.
api_tvdb      Looking up tvdb information for Zondag met Lubach 288799
api_tvdb      Series <name=Zondag met Lubach,tvdb_id=288799> information restored from cache.
api_tvdb      Getting top 5 posters for series Zondag met Lubach
util.simple_persistence setting key auth_tokens value {u'default': u'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzcxMzQ5MzEsImlkIjoiRmxleEdldCIsIm9yaWdfaWF0IjoxNDc3MDQ4NTMxfQ.jYYWSS2Dm65wREbYa-9vdqi-agrDVMKxU7uBnsXk4ySiDiVHg791Hv-fVtVVk6MIS5X4_JPzTHDX7gf3qLmOCOJDoYVNBrbs2rxfCD6FyUlN5zTxYABr7naKMNOssg2uU2_i6Adq20k_WIFe6midsqfymNmMi24uit4w4dm-XpdZZq-AKTApQK4PDDIjeBQqmh6tYHmZokzuApsEkniVxRNVi4oOMThWe7Xo6Cwjm9Qhd6jwiT-DUUkcajGkx4IQShzKJ960_7sSiqRZjhVsp9pWOo00UG9OHkV5hdLXWfUGw_Ai4_ZSTbd4KLcRfpCwtpcx-hfWVbglB771j0sweg'}
utils.requests Fetching https://api.thetvdb.com/series/288799/images/query
```

### Additional information:

- Flexget Version: 2.4.2

**Comment by liiight** [comment]
that look seems weird. paste full task config please

**Comment by mfonville** [comment]
I updated the config now to the complete (but ofc censored) version

**Comment by liiight** [comment]
try using the `plugin_priority` plugin to force tvdb lookup to happen first

**Comment by mfonville** [comment]
I use the `plugin_priority`:
```
    plugin_priority:
      thetvdb_lookup: 500
      trakt_lookup: 250
```
but it still fails; it always gives this line:
```
DEBUG    thetvdb_lookup Error looking up tvdb episode information for Zondag met Lubach (VPWON_1262000): Unable to get search results for Zondag met Lubach: 404 Client Error: Not Found for url: https://api.thetvdb.com/search/series?name=Zondag+met+Lubach
```
But the weird thing is, this only happens for this specific show, it seems.
and when I specify:
```
    if:
      - "series_name == 'Zondag met Lubach'":
          set:
            tvdb_id: 288799
```
it works around this problem, for this specific show. The other Dutch shows seem to be looked-up correctly.

**Comment by liiight** [comment]
Reproduced it. The problem is that the lookups are lazy, and when you use the `trakt_watched` field, you invoke the `trakt_lookup` but not the `thetvdb_lookup`. Can be more easily reproduced with this:
```yaml
tvdb_test_2:
    mock:
      - {title: "Zondag met Lubach", series_name: "Zondag met Lubach"}
    thetvdb_lookup:
      language: nl
    trakt_lookup: yes
    accept_all: yes
    exec: "echo {{ trakt_series_name }}"
    disable: seen
```
I imagine if you do something like:
```yaml
if:
  - "tvdb_series_name" and "trakt_watched": reject
```
it should probably work. Not ideal, but a potential work around. Can you try this and report back please?
