### ISSUE TITLE
npo_watchlist plugin: Unhandled Error & 1 suggestion

### ISSUE THREAD

**Issue by safi78** [Flexget/Flexget#1462]
Hi all,

I don't know where to direct my questions to, this seems the right place.

I have succesfully ran a working setup of flexget with npo_watchlist & download-npo for a couple of days, but lately it 'crashes' 100% ot the time throwing the following error:

BUG: Unhandled error in plugin npo_watchlist: ('Connection aborted.', BadStatusLine("''",))

I have setup all the right stuff on my server, only thing I did was adding more 'favorites' on my NPO account to download. I suspected some program-names with weird characters or something, so I cleaned out my 'favorites' to 0 and tried again, but it seems to crash before actually picking up my 'favorites', I suspect at login:

versions:
download-npo 2.4, 2016-10-03
flexget 2.5.1
```
config.yml:
tasks:
  download_dingen:
    npo_watchlist:
      email: ******
      password: *****
      remove_accepted: yes
      max_episode_age_days: 7
    accept_all: yes
    exec:
      fail_entries: yes
      auto_escape: yes
      on_output:
        for_accepted:
          - /usr/local/bin/download-npo -o "/media/media/DVR/{{series_name_plain}}" -f "{serie_titel} - {datum} {aflevering_titel}" -t {{url}}
```

Any ideas?

Suggestion:

NPO offers 'previews' (teasers of the programme to come) for some programmes. These are fetched as well, but the naming of these files end up 'empty' like __.__-__.mp4. You don't really need to download these, but I can imagine it's hard to detect if it's a real programme or a teaser. Just a thought.

regards,

Sander
