### ISSUE TITLE
Aria2 can only be used locally?

### ISSUE THREAD

**Issue by mintblackberry** [Flexget/Flexget#1493]
It seems Aria2 plugin enforces the path (options dir) to be a real path, this seems counter intuitive because without this option, the plugin can easily be used for remote servers.

I removed the path requirement from aria2.py, but now I can't seem to use any of the parsed names in the 
```yaml
aria2 options:
    aria2:
      server: www.myhost.com
      port: 6800
      options:
        dir: '/home/myaccount/tv/{{ series_name }}/Season {{series_season}}'
        max-connection-per-server: 10
```
it puts {{ series_name }} as literal in the field.
