### ISSUE TITLE
"tvrage_id" not handed to discover/search plugins.

### ISSUE THREAD

**Issue by Andy2244** [Flexget/Flexget#1516]
### Expected behaviour:
If a "tvrage_id" was found/set via metadata, the next_series_episodes/next_trakt_episodes plugins should be able to route this information to the discover->search plugins, so those can use the id instead of the title if supported.

### Actual behaviour:
The "tvrage_id" is never handed to the search plugins.

### Steps to reproduce:
Use newznab as search plugin, the relevant code is never hit and the correct query is not build.
```
        if arg_entry.get('tvrage_id'):
            lookup = '&rid=%s' % arg_entry.get('tvrage_id')
        else:
            lookup = '&q=%s' % quote(arg_entry['series_name'])
```
PS: I also had to use/setup NZBhydra locally, since i could not get any external nzb indexer to work on there SSL request api's?
#### Config:
```
tasks:
  discover-nzb:
    tvmaze_lookup: yes
  
    series:
      - westworld:
          begin: S01E07

    discover:
      interval: 1 seconds
      what:
        - next_series_episodes: yes
      from:
        - newznab:
            website: '{{ secrets.newznab.url }}'
            apikey: '{{ secrets.newznab.key-api }}'
            category: tv
    accept_all: yes
```
  
#### Log:
VERBOSE  discover      discover-nzb    Discovering 1 titles ...
VERBOSE  discover      discover-nzb    Searching for `westworld S01E08` with plugin `newznab` (1 of 1)
INFO     newznab       discover-nzb    Searching for westworld S01E08
VERBOSE  newznab       discover-nzb    Fetching http://127.0.0.1:5075/api?apikey=%7B%7B+secrets.newznab.key-api+%7D%7D&t=tvsearch&extended=1&q=westworld&season=1&ep=8

### Additional information:

- Flexget Version: 2.6.3
- Python Version: 3.5.2
- Installation method: PiP
- OS and version: Windows 10
