### ISSUE TITLE
newznab plugin via external nzb indexers, wont get any results

### ISSUE THREAD

**Issue by Andy2244** [Flexget/Flexget#1517]
### Expected behaviour:
The newznab plugin should be returning entries on external SSL api requests.

### Actual behaviour:
I cant get any of the external nzb indexers to work with flexget, the only solution was to install nzb hydra locally and use it localy via a none SSL call.

PS: I'm not sure if its a SSL or api/xml problem. If i copy and paste the url from the log (replace the apikey) the request works fine via any browser and returns a valid xml. (I also have the Windows 10 firewall fully disabled.)

### Steps to reproduce:
Use any external nzb indexer via the discover plugin.

#### Config:
```
tasks:
  discover-nzb:
    verify_ssl_certificates: no
    series:
      - westworld:
          begin: S01E07

    discover:
      interval: 1 seconds
      what:
        - next_series_episodes: yes
      from:
        - newznab:
            website: https://newztown.co.za
            apikey: '{{ secrets.newznab.key-api }}'
            category: tv
    accept_all: yes
```
  
#### Log:
VERBOSE  discover      discover-nzb    Searching for `westworld S01E07` with plugin `newznab` (1 of 1)
INFO     newznab       discover-nzb    Searching for westworld S01E07
VERBOSE  newznab       discover-nzb    Fetching https://newztown.co.za/api?extended=1&apikey=%7B%7B+secrets.newznab.key-api+%7D%7D&t=tvsearch&q=westworld&season=1&ep=7
INFO     newznab       discover-nzb    No results returned
VERBOSE  discover      discover-nzb    No search results for `westworld S01E07`
VERBOSE  details       discover-nzb    Task didn't produce any entries.

### Additional information:

- Flexget Version: 2.6.3
- Python Version: 3.5.2
- Installation method: PiP
- OS and version: Windows 10
