### ISSUE TITLE
Series show - Table could not be rendered

### ISSUE THREAD

**Issue by Amishman** [Flexget/Flexget#1520]
### Actual behaviour:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Amishman>flexget series show "duck dynasty"
There is a FlexGet process already running for this config, sending execution th
ere.
 WARNING: Multiple series match to `duck dynasty`.
 Be more specific to see the results of other matches:

 Duck Dynasty (2012)
Least important column `Proper` removed due terminal size
Least important column `Release Quality` removed due terminal size
Least important column `Latest age` removed due terminal size
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\flexget.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\flexget\__init__.py", line 42, in main
    manager.start()
  File "c:\python27\lib\site-packages\flexget\manager.py", line 309, in start
    client.handle_cli(self.args)
  File "c:\python27\lib\site-packages\rpyc\core\netref.py", line 196, in __call_
_
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "c:\python27\lib\site-packages\rpyc\core\netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "c:\python27\lib\site-packages\rpyc\core\protocol.py", line 441, in sync_
request
    raise obj
rpyc.core.vinegar/flexget.terminal.TerminalTableError: Table could not be render
ed correctly using it given data

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\rpyc\core\protocol.py", line 305, in _disp
atch_request
    res = self._HANDLERS[handler](self, *args)
  File "c:\python27\lib\site-packages\rpyc\core\protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "c:\python27\lib\site-packages\flexget\ipc.py", line 90, in exposed_handl
e_cli
    self.manager.handle_cli(options)
  File "c:\python27\lib\site-packages\flexget\manager.py", line 353, in handle_c
li
    options.cli_command_callback(self, command_options)
  File "c:\python27\lib\site-packages\flexget\plugins\cli\series.py", line 37, in do_cli
    display_details(options)
  File "c:\python27\lib\site-packages\flexget\plugins\cli\series.py", line 242,
in display_details
    table = TerminalTable(options.table_type, table_data, table_title, drop_colu
mns=[4, 3, 1])
  File "c:\python27\lib\site-packages\flexget\terminal.py", line 77, in __init__

    self.init_table()
  File "c:\python27\lib\site-packages\flexget\terminal.py", line 86, in init_table
    self.table = self._resize_table()
  File "c:\python27\lib\site-packages\flexget\terminal.py", line 198, in _resize_table
    raise TerminalTableError('Table could not be rendered correctly using it given data')
TerminalTableError: Table could not be rendered correctly using it given data

### Steps to reproduce:
- Step 1: ...

flexget series show "duck dynasty"

this happens with any show.

#### Config:
```
secrets: secrets.yml


schedules:
  - tasks: '*'
    interval:
      minutes: 30



templates:


  common_tv_rss:
    inputs:
      - rss: http://showrss.info/user/98577.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
      - rss: http://extratorrent.cc/rss.xml?type=popular&cid=8
      - rss: https://www.limetorrents.cc/rss/20/
      - rss: https://www.torlock.com/television/rss.xml
      - rss: http://www.torrentbit.net/rss.xml?cat_id=7
      - rss: https://www.torrentfunk.com/tv/rss.xml


  notify_tv:
    pushbullet:
      apikey: '{{ secrets.notify.apikey }}'
      title: "{{series_name}} {{series_id}}"
      body: "Download started"


  tv_shows:
    configure_series:
      from:
        trakt_list:
          account: '{{ secrets.trakt.usr }}'
          list: 720p_list
          type: shows
          strip_dates: yes
      settings:
        quality: webrip hdtv+ 720p
        propers: yes
        tracking: backfill
        upgrade: yes
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
      reject:
        - '*.exe'
      strict: no
    regexp:
      reject:
        - spanish
        - italian
        - german
        - french
        - dutch
        - hindi
        - Español
        - x265
    discover:
      what:
        - trakt_list:
            account: '{{ secrets.trakt.usr }}'
            list: 720p_list
            type: shows
            strip_dates: yes
      from:
        - rarbg:
            category: [18, 41]
            min_seeders: 1
        - piratebay:
            category: highres tv
        - 1337x: yes
        - extratorrent:
            category: tv
        - limetorrents:
            category: tv
    torrent_alive: yes
    magnets: yes
    download: G:\Torrents to Download


tasks:

  shows:
    template:
      - tv_shows
      - common_tv_rss
      - notify_tv

```
  
#### Log:
```
paste log output
use paste service if log is too long
```

### Additional information:

- Flexget Version: 2.6.6
- Python Version: 2.7.12
- Installation method:
- OS and version: Windows 7
- Link to crash log: no crash log
