### ISSUE TITLE
Issue 2.7.2: Form plugin

### ISSUE THREAD

**Issue by sandi-rizky** [Flexget/Flexget#1537]
### Expected behaviour:
No error while using 2.5.2 version
### Actual behaviour:
Got an error while running task that using form plugin
### Steps to reproduce:
Running task with form plugin

#### Config:
```yaml
 avistaz_subs:
    form:
      url: https://avistaz.to/auth/login
      username: "{{secrets.avistaz.usr}}"
      password: "{{secrets.avistaz.pwd}}"
      userfield: email_username
      passfield: password
    html:
      url: "https://avistaz.to/subtitles?type=2&search=720p&language=0&subtitle=45&page={{i}}"
      title_from: url
      links_re:
        - '\.(rar|r0+[01](/01)|zip|srt)'
      increment:
        from: 0
        to: 1
      #dump: result.html
    regexp:
      accept:
        - someregex
    #disable: builtins
    download: yes
    decompress: true
    template: [notify_me]
```
#### Log:
Generated new crash log

### Additional information:

- Flexget Version: 2.7.2
- Python Version: 2.7.9
- Installation method: easy_install upgrade flexget
- OS and version: osmc raspberry pi
- Link to crash log: http://pastebin.com/XHL3dzQH
