### ISSUE TITLE
Manipulate and exec bug..

### ISSUE THREAD

**Issue by ne0ark** [Flexget/Flexget#1565]
### Expected behaviour:
Ability to pass a correct variable from manipulate.

### Actual behaviour:
Is just passes "%(TorrentId)s" and "%(TitleId)s"

#### Config:
```yaml 
manipulate:
       # Create TorrentId field by extracting the ID from the URL.
       - TorrentId:
           from: url
           extract: 'https://test\.to/rss_rt\.php\?id=(.*)&m=d'
       - TitleId:
           from: title
           extract: '(.*)'
     exec: echo >> "/home/test/][id=%(TorrentId)s][title=%(TitleId)s]"
```
  
### Additional information:

- Flexget Version: 2.8.4
- Python Version:2.7.12
- Installation method: pip
- OS and version: ubuntu 16.04
