### ISSUE TITLE
Metadata lazy fields always evaluated on Entry_List/Digest output

### ISSUE THREAD

**Issue by Andy2244** [Flexget/Flexget#1574]
### Expected behaviour:
If a task has a metadata plugin configured, storing the results in a entry_list/digest should not fully resolve all lazy fields. That will just cause unnecessary stress on the apis. Instead the task receiving the input, should again configure the metadata plugins, if needed.

### Actual behaviour:
If a task outputs to a entry_list/digest all stored lazy fields will be fully resolved, even if the field was never accessed beforehand in the task.

### Steps to reproduce:
This will create a total of 8 extra trakt api url requests, because the output triggers a full resolve of all fields.
```
tasks:
  trakt-list-tv:
    trakt_lookup:
      username: '{{ secrets.trakt.username_test }}'
      account: '{{ secrets.trakt.account_test }}'
#START
    trakt_list:
      username: '{{ secrets.trakt.username_test }}'
      account: '{{ secrets.trakt.account_test }}'
      list: watchlist
      type: episodes
    
    accept_all: yes

    list_add:
      - entry_list: testlist
```

Example:
A simple scenario where this is undesired, is to simply retrieve items from a trakt list, but you want to filter out all collected/watched items. The discover plugin can't directly filter inputs, so you have to setup a extra task that gathers the items via a entry_list or digest first. Yet if you want to store the results, so it can be used in the next task via discover, all meta information is unnecessary resolved, while we only needed `trakt_collected, trakt_watched`.

It would also help if discover could directly use a filter after the input plugin and before feeding to the search plugin.

**Comment by gazpachoking** [comment]
Since lazy fields are references to code, we can't really store them to the database that well. Digest plugin gets around that by just looking them up. (Something could be done, but we'd probably have to refactor quite a bit to get it clean.)

> It would also help if discover could directly use a filter after the input plugin and before feeding to the search plugin.

Yeah, I've wanted some good way to do this for a while. I toyed with a branch a long time ago where instead of just input plugins discover accepted any regular plugins in the 'what' section, such that you could filter/manipulate/whatever before the search went through. I was never quite happy with how it was implemented though enough to release. If we can come up with a nice way to do this, I'm for it.

**Comment by Andy2244** [comment]
I mean can't we just disable lazy lookup, when the copy is made to the out entry_list?
In my case i literally hammer trakt with 8 additional requests per episode, just because i want to reject already collected entries.

The only other way i could think of was to, directly add a filter to the trakt_list, but that only works for trakt_list. How about disabling lazy lookup by default for out lists and have a option to enable it if that's really what you wanted.

**Comment by gazpachoking** [comment]
> I mean can't we just disable lazy lookup, when the copy is made to the out entry_list?

That might be a good plan actually. One could always just put the lookup plugin in whatever task its outputting to if you need the lookups again.

> The only other way i could think of was to directly add a filter to the trakt_list plugin

Yeah, let's avoid this.

**Comment by Andy2244** [comment]
The only main problem, that you maybe should experiment is a way to better steer when the lazy inserts happens. As example i had to add special meta-lookup logic in my search plugin, just because there was to way to insert the lookup between the input generation of next_episode and the actual search plugin use.

Maybe there is a clever way to config/define when lookups should be happening, maybe something like:
```
trakt_lookup:
  before:
     - newsnab
  after: 
    - all_series
```
So in this config the metalookup happens before newsnab plugin is used/requested and/or after the all_series filer has accepted the entries.

Just a idea.

**Comment by cvium** [comment]
That's awful and requires intricate knowledge of the inner workings of every plugin. Very user unfriendly and not the right way to go about it.

It would be better to have lazy lookups on a task-level such that _any new_ entry receives the lazy lookup fields that are configured in the task (as we have already discussed a bit on our Gitter channel).

**Comment by paranoidi** [comment]
Yeah, we have toyed with the idea about that recently with relation to I think it was yours metainfo requirement during discover.

So each task metainfo usage would be configured at task level:

```
task:
  test:
    metainfo:
      - thetvdb
      - trakt
    discover:
      ...
```

The metainfo plugin would instruct given plugins to register into Entry class or somewhere .. regardless the end result would be that each entry created in that task would always have the given metainfo/lazyfields available.
