### ISSUE TITLE
Form plugin says "Unable to post login form"

### ISSUE THREAD

**Issue by adamwinn** [Flexget/Flexget#1576]
### Expected behaviour:
Form plugin executes commands and succeeds

### Actual behaviour:
Form plugin says "Unable to post login form"

### Steps to reproduce:
Be on flexget 2.8.6.  
Use form plugin with below config
Form plugin will say "Unable to post login form"
Note:  I downgraded to flexget 2.6.1 and it works great, so something broke recently.

#### Config:
```
templates:

  transmission:
    transmission:
      host: localhost
      port: 9091
      username: ****
      password: ****

tasks:
  tyt_highlight_shows:
    form:
      url: http://tenyardtracker.com/members.php?action=login
      username: ****
      password: ****
    html:
      url: http://tenyardtracker.com/browse.php?page=0  #the browse homepage is listed in order by upload date
      title_from: link
    regexp:
      accept:
        - The.Blitz
        - Football.Night.in.America
        #- College.Football.Final
        #- College.Gameday
        - Inside.the.NFL
        - Monday.QB
        - GameDay.Highlights
      reject:
        - french
    #quality:
    #  - 720p
    urlrewrite:
      sitename:
        regexp: details.php\?id=(?P<id>\d+).*
        format: download.php?torrent=\g<id>
    template:
      - transmission
    transmission:
      path: /Volumes/TV
      ratio: 1.0
      bandwidthpriority: 1
```
  
#### Log:
```
http://pastebin.com/vsGWG37F
```

### Additional information:

- Flexget Version:  2.8.6
- Python Version:  2.7.12
- Installation method: pip
- OS and version: macOS 10.12.2
- Link to crash log:  http://pastebin.com/vsGWG37F
