### ISSUE TITLE
Secrets plugin breaks jinja default filter

### ISSUE THREAD

**Issue by thomasbrandon** [Flexget/Flexget#1578]
When a secrets file is used the jinja default filter displays the default value even when the entry exists. Occurs even if the secrets file is empty

#### Config:
```
secrets: secrets.yml
tasks:
  test:
    disable:
      - seen
    filesystem:
      path: ~/flexget/
      mask: '*.yml'
    accept_all: yes
    set:
      test1: "{{ title }}"
      test2: "{{ title|default('bla') }}"
    exec:
      - echo "{{test1}}{{test2}}"
```
  
#### Log:
With secrets file:
```
-- Accepted: ---------------------------
title            : config
url              : file:///home/user/flexget/config.yml
...
test1            : config
test2            : bla
```
Without secrets file (expected output):
```
-- Accepted: ---------------------------
title            : config
url              : file:///home/user/flexget/config.yml
...
test1            : config
test2            : config
```

### Additional information:

- Flexget Version: 2.8.7
- Python Version: 2.7.12+
- Installation method: pip in virtualenv
- OS and version: Ubuntu 16.10
