### ISSUE TITLE
`series_year` should exist similar to `movies_year`

### ISSUE THREAD

**Issue by Andy2244** [Flexget/Flexget#1582]
As already discussed, a `series_year` field should exist and be populated if available, similar to `movies_year`.

The main reason is that depending on the task, plugin (set/if/sort) you might need this information in a general available field. So that file rename, search, if, sort plugins/tasks can use it. Atm you need specific knowledge of possible field names to use/test, to extract it.

**Comment by liiight** [comment]
the problem with that is that `series` plugin can only set that field if it's a part of the series name, which it usually isn't.

**Comment by Andy2244** [comment]
I'm really confused on why there seems to-be a distinct difference how this is handled. I mean my file/folder names include the year for series and movies. The meta lookups also provide a year for series, movies. I let flexget store series, movies in the db using the 'title + year' format.
So from my point as user, i see no reason why i can use `movies_year`, but not `series_year`?

Should the series plugin not utilize the year fields of the different input plugins if provided, instead of relying on title parsing, splitting?

If i do this i would expect a valid `series_year` field.
```
configure_series:
  from:
    thetvdb_list:
      username: <username>
      account_id: <account identifier>
  from:
    trakt_list:
        account: <username>
        list: <account identifier>
        type: shows
```

I can only speak for myself, but all my inputs come from some web-list that have separated 'name' and 'year' fields. So to me not having the 'year' is the unusual case.
