### ISSUE TITLE
divxatope plugin is outdated

### ISSUE THREAD

**Issue by atekoa** [Flexget/Flexget#1601]
### Expected behaviour:
Download from RSS, but since the divxatope moved to divxatope1 it doesn't work :'(

### Actual behaviour:
REJECTED by retry_failed plugin because waiting before retrying entry which has failed in the past. (failure reason: Unexpected html content received from `http://divxatope1.com/pictures/c/1469_series-alta-definicion-hd.jpg` - maybe a login page?)

### Steps to reproduce:
- Step 1: ...
PREVIOUS >> url: http://divxatope.com/feeds.xml
NEW URL >>   url: http://divxatope1.com/feeds.xml

**Comment by cvium** [comment]
While I can see that divxatope plugin is outdated, the links seem fine. I'm not sure why you decided to ignore most of the issue template, but we really do need your config.

The feed contains links to newpct1 and the urlrewriter for newpct1 is working fine, so you've misconfigured the RSS plugin in such a way that it grabs the jpg instead of the newpct1 link.

**Comment by atekoa** [comment]
The config works fine until the URL was divxatope.com
Sorry for missing the config. The divxatope plugin is not the problem, I think is their own feed, but not sure...
Thanks.

```
templates:
  torrent:
    transmission:
      enabled: yes
      host: x.x.x.x
      port: xxx
      username: user
      password: pass
  series-dir:
    thetvdb_lookup: yes
    series:
      agroup:
        - The Grand Tour
        - The IT Croud
  tv-series:
    template: torrent
    thetvdb_lookup: yes
    exists_series:
      - /series/{{ tvdb_series_name }}
    series:
      settings:
        normales:
          ep_regexp:
            - Cap.(\d+)(\d\d)
          quality: hdtv
          path: /download/{{series_name}}/s{{series_season}}/
        highdef:
          ep_regexp:
            - Cap.(\d+)(\d\d)
          upgrade: yes
          quality: 720p+
          path: /download/{{series_name}}/s{{series_season}}/
      normales:
        - The Grand Tour
      highdef:
        - The IT Croud
    set:
      path: /download/{{ tvdb_series_name|default(series_name) }}
      main_file_only: yes
      content_filename: "{{tvdb_series_name|default(series_name)}} - s{{tvdb_season|default(series_season)}}.e{{ tvdb_episode|default(series_episode)}}"
      rename_like_files: yes
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*.url'
        - '*[sS]ample*'
        - '*.txt'
      include_subs: yes
tasks:
  torrent-series:
    priority: 20
    template:
      - tv-series
    rss:
      url: http://divxatope1.com/feeds.xml
    regexp:
      reject:
        - V.O.:
            from: title
```

**Comment by atekoa** [comment]
The RSS feed just now looks like this...

```
<item>
<title>
The Grand Tour - Temporada 1 [HDTV 720p][Cap.106][AC· 5.1 Español Castellano]
</title>
<link>
http://newpct1.com/descargar-seriehd/the-grand-tour/capitulo-16/hdtv-720p-ac3-5-1/
</link>
<description>
<![CDATA[
<img src='http://divxatope1.com/pictures/c/1469_series-alta-definicion-hd.jpg' alt='Torrent The Grand Tour - Temporada 1 [HDTV 720p][Cap.106][AC· 5.1 Español Castellano]' width='120' height='170' class='float:left;margin:0px 4px 4px 0px;'/><span style='float:left;'>Reparto Jeremy Clarkson Richard Hammond James May
 Genero Serie de TV Comedia
 
 Veremos a Jeremy Clarkson James May y Richard Hammond enfrascarse en aventuras mucho mas ambiciosas que las vividas en la BBC Algunas imagenes y videos se han comenzado a filtrar a modo de calentar motores y hacer mas amena la espera Entre lo que sabemos que sucedera en la serie esta el campamento una gran carpa que reemplazara las tomas de estudio y sera alzada en cada pais que el trio este recorriendo Sin embargo la prueba con la que The Grand Tour nos tiene a todos en el borde de nuestros asientos es una deuda pendiente que quedo con Top Gear la prueba triple del McLaren P1 versus el Porsche 918 y LaFerrari de Ferrari</span>
]]>
</description>
<author>888632</author>
<category>Series Alta Definicion HD</category>
<pubDate>Tue 27 Dec 2016 22:38:24</pubDate>
<enclosure url="http://divxatope1.com/pictures/c/1469_series-alta-definicion-hd.jpg" length="23898" type="image/jpeg"/>
</item>
```

**Comment by cvium** [comment]
You can try with
```
rss:
  url: http://divxatope1.com/feeds.xml
  link:
    - link
```
