### ISSUE TITLE
After the new notification system: "Task doesn't have any output plugins, you should add (at least) one!"

### ISSUE THREAD

**Issue by antivirtel** [Flexget/Flexget#1634]
### Expected behaviour:
Task should run without any warning...

### Actual behaviour:
Notification is working. However on every run I have these:
```
WARNING  task          TaskName1     Task doesn't have any output plugins, you should add (at least) 
one!
WARNING  task          TaskNameN     Task doesn't have any output plugins, you should add (at least) 
one!
```
### Steps to reproduce:
- Step 1: Have the config above.
- Step 2: Start daemon...

#### Config:
```yaml
schedules:
  - tasks: '*'
    interval:
      minutes: 16

variables: secrets.yml

templates:
  dwn:
    notify:
      entries:
        title: '{{title}}'
        message: '  ^ {{ rss_pubdate|formatdate("%H:%M:%S %a, %d.") }} {{task}}'
        via:
          - pushbullet:
              api_key: '{? var.pushbullet.apikey ?}'
              url: '{{url}}'

  site_rss:
    rss:
      url: https://example.com
    headers:
      Cookie: "nick={? var.site.nick ?}; pass={? var.site.pass ?}"

tasks:
  site_auto:
    template:
      - dwn
      - site_rss
    regexp:
      reject_excluding:
        - Sls \(LNG
      reject:
        - xvid
    series:
      settings:
        sls:
          upgrade: yes
          timeframe: 3 days
          target: h264 1080p
          quality: h264 360p+

      sls:
        - Sls1
```
  
#### Log:
see above

### Additional information:

- Flexget Version: From 2.9.0...
- Python Version: 2.7.9
- Installation method: pip
- OS and version: Raspbian 8
