### ISSUE TITLE
rutracker_auth plugin does not work anymore after recent changes in rutracker's login page

### ISSUE THREAD

**Issue by dchubkov** [Flexget/Flexget#1656]
### Expected behaviour:
Accepted torrents from rutracker.org gets downloaded

### Actual behaviour:
Accepted torrents from rutracker.org fails to download

### Steps to reproduce:
- Step 1: define rutracker_auth with correct credentials in config file
- Step 2: execute task with rutracker_auth plugin

#### Config:
```
...
rutracker_task
  accept_all: yes
  rutracker_auth:
    username: '{? rutracker.username ?}'
    password: '{? rutracker.password ?}'

  inputs:
    - rss: http://feed.rutracker.org/atom/f/313.atom

  deluge: yes
```
  
#### Log:
Missed log with exception since I fixed it already. See below

### Additional information:
```
Flexget version is 2.9.8 installed by pip
Python version 2.7.12
OS: Ubuntu 16.04
```

I already fixed it myself:
Edit /usr/local/lib/python2.7/dist-packages/flexget/plugins/sites/rutracker.py
change login URL in this line:
```
s.post("http://login.rutracker.org/forum/login.php", data=payload)
```
to
```
s.post("http://rutracker.org/forum/login.php", data=payload)
```
and URL in this line
```
r.prepare_url(url='http://dl.rutracker.org/forum/dl.php?t=' + id, params=None)
```
to this
```
r.prepare_url(url='http://rutracker.org/forum/dl.php?t=' + id, params=None)
```

Please add this fix to the next public Flexget versions. Thanks!
