### ISSUE TITLE
Rapidpush always returns invalid API key error

### ISSUE THREAD

**Issue by gkovacsp** [Flexget/Flexget#1665]
### Expected behaviour:
Should send a Rapidpush message based on the attached API key

### Actual behaviour:
Error message appears in log: 

2017-01-31 04:00
WARNING
notify
RapidTestHD Error while sending notification to `rapidpush`: Invalid API-Key

The API key works, checked with a simple pyrapidpush based script:
p = PyRapidPush('APIKEY)
p.notify("Hello", "Test", "Owner")

#### Config:
```yaml 
  RapidTest:
    template: downloader
    thetvdb_lookup: yes
    set:
      path: "/mnt/HD/HD_a2/Media/Sorozatok/Gábor/{{series_name|replace(\"'\",\".\")|replace(\":\",\".\")}}/Season {{series_season|pad(2)}}"
      skip_files:
        - '*[sS]ample*'
    notify:
      entries:
        title: "Sorozat: {{series_name}}"
        message: "{{series_name}} - {{ series_season }}x{{ series_episode|pad(2) }} - {{ tvdb_ep_name|default('?')}}"
        what: accepted
        via:
          - rapidpush:
              api_key: PLkNekzkKUpt8iqWMk8WVVDRURkh8awk4kE0QJYEcLlh3F8RYuuAwNMEOF1RLBiD
    inputs:
      - rss:
          url: https://rarbg.to/rssdd.php?category=1;41
    series:
      shows:
        - Shadowhunters:
            begin: s02e05
```

  
#### Log:
entire verbose log: http://pastebin.com/KGwyCpSh

### Additional information:

- Flexget Version: 2.9.11
- Python Version: 2.7.9
- Installation method: pip
- OS and version: Raspbian GNU/Linux 8
- Link to crash log: -
