### ISSUE TITLE
no `failed` template after upgrade

### ISSUE THREAD

**Issue by kudrevatykh** [Flexget/Flexget#1705]
### Expected behaviour:
email sent on failures
### Actual behaviour:
no email sent
### Steps to reproduce:
- Step 1: configure notification plugin with `failed` template
- Step 2: wait for failure

#### Config:
```
 notify:
      task:
        template: failed
        via:
          - email:
```
  
#### Log:
```
CRITICAL plugin        tbbt            Cannot locate template on disk: failed
```

### Additional information:

- Flexget Version: 2.10.2
- Python Version: Python 2.7.9
- Installation method: globally with pip
- OS and version: debian jessie
