### ISSUE TITLE
Email notification with subject "Task [TaskName] did not produce any entries" although the content actually is accepted entries.

### ISSUE THREAD

**Issue by programatix** [Flexget/Flexget#1708]
### Expected behaviour:
Usually the subject was "[TaskName]: xx new entries downloaded.

### Actual behaviour:
The email subject is occasionally shows "Task [TaskName] did not produce any entries". However the content of the email contain "Accepted Entries:" followed with list of accepted entries. Sometimes it's correct.

![emailnotify](https://cloud.githubusercontent.com/assets/3293865/23327755/f8d56172-fb4c-11e6-9da1-c9171596844b.png)

### Steps to reproduce:
Upgraded to latest Flexget starting from version 2.9.15 where the email plugin is now using notify plugin.

#### Config:
```
templates:
  global:
    notify:
      task:
        template: html
        always_send: no
        via:
          - email:
              from: ...
              to:
                - ...
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: ...
              smtp_password: ...
              smtp_tls: true
              html: yes
tasks:
  NyaaTorrents:
    thetvdb_lookup: yes
    series:
        ...
    discover:
      what:
        - next_series_episodes:
            backfill: yes
            from_start: yes
      from:
        - nyaa:
            category: anime eng
            filter: trusted only
      release_estimations: ignore
      interval: 1 hour
```
  
#### Log:
```
None
```

### Additional information:

- Flexget Version: 2.10.6
- Python Version: 3.6.0
- Installation method: pip
- OS and version: AsusWrt
