### ISSUE TITLE
Not detecting episode number with ep_regexp

### ISSUE THREAD

**Issue by juanfcocontreras** [Flexget/Flexget#1714]
I'm trying to identify the episode number with the following pattern:

`'show_name' [Sea. 'season_number'] ['quality_tags'] ['episode_number' / 'total_episodes']
`

For example:

`Homeland [Sea. 6] [HDiT 720p H264 AC3] [2 / 12]
`

I would like to identify `season_number` and `episode_number`. I'm using `ep_regexp` for that.

But I've tried a lot of patterns but with no luck. For example:

`Sea\.?\s*(\d+).*(\d+)\s*\/
`

This regular expression works in plain python, but not in Flexget.

**Comment by liiight** [comment]
this is a question for the [forums](https://discuss.flexget.com/), not an issue.

**Comment by juanfcocontreras** [comment]
I published the question in the forum several several weeks ago, and I got no answer. So, I'm not sure if ep_regexp is working well, that's the reason I created an issue.

https://discuss.flexget.com/t/not-detecting-episode-number-with-ep-regexp/3194

**Comment by liiight** [comment]
Ok, please do not ignore the issue template next time as it is there for a reason. 

Paste config and debug logs

**Comment by juanfcocontreras** [comment]
Sorry for the missing information. Here it is. Please, tell me if you need more to find out what is happening. Thanks.

### Expected behaviour:
Einstein S01E04

### Actual behaviour:
Title `[Series]  ||Einstein [Temp. 1] [HDiT 720p H264 AC3 Dual] [4 / 11]` looks like series `Einstein` but cannot find a(n) `ep` style identifier.

According to documentation, ep_regexp must return TWO groups, both being numeric values

Simple test:

```
import re

searchString = 'Einstein [Temp. 1] [HDiT 720p H264 AC3 Dual] [4 / 11]'
m = re.search('Temp\\.?\\s*(\\d+)\\]\\s*\\[.*\\]\\s*\\[(\\d+)\\s*\\/', searchString)

print 'Number of groups: ' + str(len(m.groups()))
print 'First match (season): ' + m.group(1)
print 'Second match (episode): ' + m.group(2)
```

Output:
```
Match size: 2
First match: 1
Second match: 4
```

#### Config:
```
variables: variables.yml
tasks:
  tracker_one:
    rss: '{? rss.url ?}'
    series:
      series_list:
        - 'Einstein'
      settings:
        series_list:
          identified_by: ep
          ep_regexp:
            - Temp\.?\s*(\d+)\]\s*\[.*\]\s*\[(\d+)\s*\/
    template:
      - tvshow
templates:
  tvshow:
    verify_ssl_certificates: no
    series:
      settings:
        set:
          path: '{? location.path ?}''{{series_name}}'
    thetvdb_lookup: yes
    transmission:
      host: localhost 
      port: 9091
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'
```
  
#### Log:
http://pastebin.com/raw/a7AiJjWp

### Additional information:

- Flexget Version: 2.10.9
- Python Version: 2.7.6
- Installation method: pip
- OS and version: Linux Mint 17.3 x86_64
- Link to crash log:
