### ISSUE TITLE
 BUG: Unhandled error in plugin transmission: 'utf8' codec can't decode byte 0xf5 in position 0: invalid start byte

### ISSUE THREAD

**Issue by txolovinsky** [Flexget/Flexget#1715]
### Steps to reproduce:
- Step 1: flexget execute

#### Config:
config.yml
############
```
variables: variables.yml

templates:
  torrent_server:
    transmission:
      host: localhost
      port: 9091
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'
      addpaused: no

web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: yes

tasks:
  mis_series:
    template:
      - torrent_server
    include:
      - series_divxatope.yml
    notify:
      task:
        via:
          - email:
              from: xxxxxx@gmail.com
              to: xxxxxxx@gmail.com
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? correo.usr ?}'
              smtp_password: '{? correo.pwd ?}'
              smtp_tls: yes

#EOF

####################
series_divxatope.yml

rss:
  url: http://www.newpct1.com/feeds.xml
  link: link
series:
  settings:
    en_hd:
      ep_regexp:
        - Cap.(\d+)(\d\d)
      quality: 720p-1080p
      identified_by: auto
  en_hd:
    - Black Mirror
    - El Tirador (Shooter)
    - Fear The Walking Dead
    - Gomorra
    - Homeland
    - House of Cards
    - Juego De Tronos
    - Minority Report
    - Mr Robot
    - Narcos
    - Sense8
    - Stranger Things
    - Prison Break
    - The Americans
    - The Blacklist
    - The Strain
    - The Walking Dead
    - Westworld
regexp:
  reject:
    - V.O.:
        from: title

```
#### Log:
http://pastebin.com/419m6L8p

### Additional information:

- Flexget Version: 2.10.9
- Python Version: Python 2.7.9
- Installation method: pip
- OS and version: Raspbian GNU/Linux 8.0 (jessie)
- Link to crash log: http://pastebin.com/419m6L8p
