### ISSUE TITLE
notify: task does not run when notify: entries is also present

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1726]
### Expected behaviour:
When configured like this:
```
    notify:
      entries:
        ...
      task:
        always_send: yes
        ...
```
Whatever notifications are configured under each ``entries`` and ``task`` will be sent, with the ``task`` notification(s) always being sent.
### Actual behaviour:
Despite the presence of rejected entries, ``task`` never generates a notification. I believe this is because of [line 118](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/notifiers/notify.py#L118) of notify.py. (I do realize that ``task`` normally only triggers for accepted or failed entries, hence my use of ``always_send``. Even if ``always_send`` was ignored, at the very least the log entry on [line 132](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/notifiers/notify.py#L132) should be present if the ``task`` block is executing at all, but the log line never appears.)

### Steps to reproduce:
- Step 1: Configure both ``entries`` and ``task`` in the ``notify`` plugin.
- Step 2: Take some action that should cause ``task`` to send a notification.

#### Config:
(This is used as a template.)
```
    notify:
      entries:
        title: '{{title}}'
        message: 'Accepted entry {{title}}'
        what: accepted
        via:
          - pushover:
              user_key: '{? pushover.user_key ?}'
      task:
        always_send: yes
        title: 'Rejected premieres'
        template: rejected_premieres
        via:
          - pushover:
              user_key: '{? pushover.user_key ?}'
```
  
#### Log:
Below is the [only reference](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/notifiers/notify.py#L117) to ``notify_entry`` in the debug log.
```
2017-03-10 03:13 VERBOSE  details       rss_btn_all-premieres Summary - Accepted: 0 (Rejected: 295 Undecided: 5 Failed: 0)
2017-03-10 03:13 DEBUG    notify_entry  rss_btn_all-premieres No entries to notify about.
2017-03-10 03:13 DEBUG    series        rss_btn_all-premieres on_task_learn
2017-03-10 03:13 DEBUG    disable       rss_btn_all-premieres Re-enabled builtin plugin(s): retry_failed
```

### Additional information:

- Flexget Version: 2.10.9
- Python Version: 2.7.10
- Installation method: pip
- OS and version: macOS v10.11.6
- Link to crash log: n/a
