### ISSUE TITLE
morethan.tv plugin error

### ISSUE THREAD

**Issue by skyway22** [Flexget/Flexget#1729]
### Expected behaviour:
Find series episode and download, sometime it works, sometimes it doesn't
### Actual behaviour:
Break because of an error
### Steps to reproduce:
- Step 1: ...

#### Config:
```
  mtv:
    template: [mtv-seriale, telegram, rtorrent]
    discover:
      what:
        - next_series_episodes: yes
      from:
        - morethantv:
            username: '{? mtv.username ?}'
            password: '{? mtv.password ?}'
            category: TV
            all_tags: yes
      interval: 1 hour
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
    list_add:
      - subtitle_list:
          list: rosubbed
          path: "{{path}}/"
          allow_dir: True
    priority: 3
    plugin_priority:
      set: 240
      path_by_space: 250
    path_by_space:
      select: most_free
      within: 20GiB
      paths:
        - /mnt/samsung/shows
        - /mnt/wd/shows
    set:
      path: "{{path}}/{{series_name}}/Sezonul {{series_season}}/"
```  
#### Log:
http://paste.osmc.io/iwotoharun.py
### Additional information:

- Flexget Version: 2.10.10
- Python Version: Python 2.7.9
- Installation method: pip
- OS and version: osmc
