### ISSUE TITLE
kitsu plugin stopped working

### ISSUE THREAD

**Issue by hjri** [Flexget/Flexget#1735]
### Expected behaviour:
Kitsu plugin successfully fetches actual data
### Actual behaviour:
HTTP 500 error occurs, cache is used.
### Steps to reproduce:
- Step 1: set up kitsu.io plugin or have it already set up
- Step 2: try to execute tasks with it

#### Config:
```
templates:
  anime:
    headers:
      ## Prevent 403 / Cloudflare captcha
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
      Connection: "keep-alive"
      Upgrade-Insecure-Requests: "1"
      Pragma: "no-cache"
      Cache-Control: "no-cache"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.5"
      Accept-Encoding: "gzip, deflate, br"
      DNT: "1"

    configure_series:
      from:
        kitsu:
          username: [redacted]
          lists:
            - current
            - planned
```
Headers (and also cookies, not shown in config) are present to bypass cloudflare protection in a semi-automatic manner due to some services used being blocked in my country and I have to resort to using systemwide tor proxy via redsocks. Headers were put quite a long time ago and weren't an issue for kitsu, left them here just in case.

#### Log:
```
2017-03-13 20:00 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2017-03-13 20:00 ERROR    input_cache   search series   There was an error during kitsu input (Error getting list from https://kitsu.io/api/edge/users/[userid]/library-entries?filter%5Bmedia_type%5D=Anime&include=media&page%5Blimit%5D=20&filter%5Bstatus%5D=current%2Cplanned status: 500), using cache instead.
```

### Additional information:

- Flexget Version: 2.10.13
- Python Version: 2.7.9
- Installation method: pip
- OS and version: Debian 8.7 + very few packages from testing and sid
- Link to crash log: none

I think Kitsu just changed their API which broke the relevant plugin.
