### ISSUE TITLE
Plex Cloud Connection

### ISSUE THREAD

**Issue by crack00r** [Flexget/Flexget#1742]
```
tasks:
  watchlist:
    priority: 1
    plex:
      section: F1
      server: '***.ric.plex.services'
      selection: all
      token: ***
#      username: ***
#      password: ****
    accept_all: yes
    seen: local
    list_add:
      - movie_list: watchlist
```

i just get

> root@vps****:~/flexget# flexget execute
> 2017-03-18 19:14 WARNING  manager                       Your locale declares ascii as the filesystem encoding. Any plugins reading filenames from disk will not work properly for filenames containing non-ascii characters. Make sure your locale env variables are set up correctly for the environment which is launching FlexGet.
> 2017-03-18 19:14 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
> 2017-03-18 19:15 WARNING  requests.packages.urllib3.connectionpool                 Retrying (Retry(total=0, connect=None, read=None, redirect=0)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f416494dc50>, 'Connection to *****.ric.plex.services timed out. (connect timeout=30)')': /library/sections/?X-Plex-Token=******
> 2017-03-18 19:15 CRITICAL plugin        watchlist       Error retrieving source: HTTPConnectionPool(host='*****.ric.plex.services', port=32400): Max retries exceeded with url: /library/sections/?X-Plex-Token=**** (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f416494dd50>, 'Connection to ******.ric.plex.services timed out. (connect timeout=30)'))
> 2017-03-18 19:15 WARNING  task          watchlist       Aborting task (plugin: plex)
> 

flexget -V
2.10.17

anyone know some help?
