### ISSUE TITLE
movedone does not work

### ISSUE THREAD

**Issue by furier** [Flexget/Flexget#1743]
### Expected behaviour:
When a series has a configuration to be moved to a path on completion it should be moved after download to the specified path.

      settings: 
        1080p: 
          quality: 1080p
          set: 
            label: serie
            movedone: "/mnt/datastore/series/%(series_name)s/Season %(series_season)s/"
            path: /mnt/datastore/torrents/new
          target: 1080p

here is a small portion of the settings, and one expect `%(series_season)s` to be replaced with the series name and `%(series_season)s` to be replaced with the season number.

eg: `/mnt/datastore/series/The Originals/Season 4`

### Actual behaviour:
However the actual behaviour is that it does not replace the placeholders `%(series_name)s` and `%(series_season)s` with the series and season number, it just used the string without replacing. So in fact it is moving all the series when done to the following path: `/mnt/datastore/series/%(series_name)s/Season %(series_season)s/`

### Steps to reproduce:
I have no idea, but its version `2.10.11`.

#### Config:
```
templates: 
  tv: 
    deluge: 
      host: localhost
      password: deluge
      port: *****
      username: deluge
    series:
      1080p: 
        - "The Originals"
      settings: 
        1080p: 
          quality: 1080p
          set: 
            label: serie
            movedone: "/mnt/datastore/series/%(series_name)s/Season %(series_season)s/"
            path: /mnt/datastore/torrents/new
          target: 1080p
```
  
#### Log:
There is absolutely nothing indicating an error in the logs.
```
2017-03-18 18:37
INFO
download
hdbits
Downloading: The Originals S04E01 1080p WEBRip DD+5.1 x264-DONNA
2017-03-18 18:37
INFO
deluge
hdbits
Connecting to daemon at localhost:******..
2017-03-18 18:37
INFO
deluge
hdbits
Connected to daemon at 127.0.0.1:******..
2017-03-18 18:37
INFO
deluge
hdbits
The Originals S04E01 1080p WEBRip DD+5.1 x264-DONNA successfully added to deluge.
2017-03-18 18:37
INFO
deluge
hdbits
Connection lost to daemon at localhost:58846 reason: Connection was closed cleanly.
```

### Additional information:

- Flexget Version: `2.10.11`
- Python Version: `Python 2.7.3`
- Installation method: `pip`
- OS and version: `Ubuntu Server 12.04`
- Link to crash log: N/A
