### ISSUE TITLE
list_match crashes with trakt_lookup in task

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1745]
### Expected behaviour:
``list_match`` matches episodes in ``from: trakt_list`` list ([Trakt link](https://trakt.tv/users/tubedogg/lists/missing-episodes)) against RSS feed and accepts them. The RSS feed includes episodes that are on the trakt list and should therefore be matched

### Actual behaviour:
``list_match`` makes no decisions. Adding ``trakt_lookup`` to the task as suggested by @liiight causes a crash referencing ``tmdb_id``.

### Steps to reproduce:
Create task including both ``list_match``/``trakt_list`` and ``trakt_lookup``.

#### Config:
```
  rss_test_btn_missing:
    disable: [seen]
    list_match:
      from:
        - trakt_list:
            account: '{? trakt.account ?}'
            list: 'missing episodes'
            type: episodes
      remove_on_match: no
      action: accept
    inputs:
      - rss: 'http://plex/testrss.rss'
    trakt_lookup:
      account: '{? trakt.account ?}'
    all_series:
      parse_only: yes
```
  
#### Log:
http://pastebin.com/9t9RdsxV

### Additional information:

- Flexget Version: v2.10.14
- Python Version: v2.7.10
- Installation method: pip
- OS and version: macOS El Capitan v10.11.6
- Link to crash log: http://pastebin.com/9t9RdsxV
