### ISSUE TITLE
rtorrent plugin: The key `timeout` is not valid here

### ISSUE THREAD

**Issue by lingfish** [Flexget/Flexget#1755]
### Expected behaviour:
Documentation says this should be an accepted option.

### Actual behaviour:
Fails to run.

#### Config:
```
  template-rtorrent:
    rtorrent:
      uri: *****
      path: *****
      start: no
      custom2: "{{url|replace('/download/', '/details/')}}"
      timeout: 10
```
  
#### Log:
```
2017-03-26 12:51 CRITICAL manager                       [/tasks/*****/rtorrent] The key `timeout` is not valid here.
```

### Additional information:

- Flexget Version: 2.10.20
- Python Version: Python 2.7.9
- Installation method: virtualenv
- OS and version: Linux 4.7.0-0.bpo.1-amd64
