### ISSUE TITLE
Request: More settings when importing to Sonarr needed

### ISSUE THREAD

**Issue by L0cTus** [Flexget/Flexget#1757]
While trying to import my series to Sonarr from My Anime List, i encountered some settings I needed to manually do in Sonnar after the import, something that i know kan be done with some extra plugin settings in the sonarr-list to get it fully automatic.

#### Whats missing when importing to Sonarr:
- Enable "Monitored" (and maybe choose how to monitor, like when adding new series manually)
  - Its disabled by default
- Enable "Use Season Folder"
  - Its disabled by default
- Choose "Series Type"
  - Its just choosing "Standard" (Not optimal for anime when downloading)
- An option for Path and Profile. I dont need it, bout maybe someone will later? 
  - Its more or less choosing the first ting in the list atm.

#### Config:
```
tasks:
  MAL to Sonarr:
    all_series: yes
    my_anime_list:
      username: ******
      status:
        - watching
        - on_hold
        - dropped
        - plan_to_watch
      type: series
    list_add:
      - sonarr_list:
          base_url: http://localhost
          port: 8989
          api_key: ******
```
  
### Additional information:

- Flexget Version: 2.10.22 
- Python Version: 3.6
- Installation method: pip
- OS and version: Windows 10
