### ISSUE TITLE
Allow using set plugin to override notification settings

### ISSUE THREAD

**Issue by teancom** [Flexget/Flexget#1767]
### Expected behaviour:
Using the `set` plugin to override things like prowl's api_key, on a per-section basis. In the example config, the default should be set, then overridden for the 'wife' and 'daughter' sections. The 'family' and 'dad' should use the default. If there's a way to not have to have the entire notify -> entries -> via -> prowl chain for each override, that would be nice, but not essential.

### Actual behaviour:
It does not work, and whatever the api_key is set to first, "wins" for every notification.

#### Config:
```
tasks:
  tv-shows:
    notify:
      entries:
        via:
          - prowl:
              api_key: xxxxxxxxxxx
    series:
      settings:
        wife:
          set:
            notify:
              entries:
                via:
                  - prowl:
                      api_key: yyyyyy
        daughter:
          set:
            notify:
              entries:
                via:
                  - prowl:
                      api_key: zzzzzz
    wife:
      - "Murder Death Kill"
    daughter:
      - "Ponies and Kittens"
    family:
      - "Innuendo and Laugh Tracks"
    dad:
      - "Actual Good TV"
```

### Additional information:

- Flexget Version: 2.10.7
- Python Version: 2.7.13
- Installation method: pip
- OS and version: Debian 9.0/4.9.0-2-amd64

**Comment by tubedogg** [comment]
It's because ``notify`` is not written to be compatible with ``set``. Also, ``set`` just sets fields (see below), so even if it was compatible, you'd use
```
set:
  api_key: XXX
```
(You can use certain plugins _above_ ``set``, such as ``series`` or ``if``.)

Basically the way to understand how ``set`` operates is that with Flexget, there is a task-level configuration that contains general details (such as RSS feed URL or notification) and then a pool of entries, each of which contain fields about that entry (title, URL, so on). ``set`` inserts the field you specify into each entry that matches the conditions you have applied to it - so in this case, filtered by series name. Compatible plugins then read each entry as its being processed to see if there are any fields that have been inserted into the entry to dictate how the plugin operates for that specific entry. For the ``move`` plugin, you can ``set`` the ``path``, and ``move`` will alter the destination as configured for each entry. If you run Flexget with the ``--dump`` option on the command line, you'll see the fields in each entry. If you use ``set`` with ``path``, you'll see ``path`` as a field in the entries.

Not all plugins are compatible with ``set``, as they have to explicitly be designed to look at the entry as an alternate source of configuration information (instead of the task). I don't think there is an easy way to find out which plugins support it, beyond mentions in the wiki (which are not exhaustive).

It probably wouldn't be that hard to add this in for yourself, though I haven't really looked in-depth at the notification system since it changed.

**Comment by teancom** [comment]
Thank you! That's a really good explanation of the set plugin, which I was missing. In this particular case, I opened the ticket at the behest of @liiight based off a thread from the forums: https://discuss.flexget.com/t/overriding-notify-settings-per-user/3343/2 as a sort of 'place holder' for some work that he apparently wants to do to help 'genericize' the set plugin beyond what it current does. I'm uncertain exactly what that would look like.

**Comment by liiight** [comment]
@teancom can you pull from github and check this?

**Comment by teancom** [comment]
Works like a champ!

```
set:
  prowl_api_key: xxxxxx
```
did exactly what I needed it to. Thank you!

**Comment by liiight** [comment]
cool, ill update the rest of the plugins

**Comment by liiight** [comment]
sorry to disappoint, but this will probably never happen. this calls for a deeper integration of setting entry field outside of task phases, and it does not play nice at all with notify plugin,..

**Comment by teancom** [comment]
@liiight The general case won't happen, or the specific fix that I tested (and has been working fine for the last couple of weeks) has problems that I just haven't noticed?

**Comment by liiight** [comment]
it can work for the most part, but it gets ugly when trying to do something like this:
```yaml
set:
  pushover_foo: bar
notify:
  entries:
    title: {{ foo }}
    via:
    - pushover:
        user_key: key
```
the rendering for `foo will fail in the title since that happens before the entry is even passed to the plugin. changing that means either redoing notifier framework (again) or thinking of how to render all entry data per plugin on a root level, which is not an easy task.
unfortunately, flexget framework does not currently support a way to override config values via entry data
