### ISSUE TITLE
Adding season_packs to all_series running alongside series causes crash

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1774]
### Expected behaviour:
No crash

### Actual behaviour:
A crash occurs:
```
  File "/usr/local/lib/python2.7/site-packages/flexget/utils/tools.py", line 173, in merge_dict_from_to
    k, type(v).__name__, type(d2[k]).__name__))
MergeException: u"Merging key season_packs failed, conflicting datatypes 'bool' vs. 'dict'."
```

This _only_ happens if there are multiple entries. Single entries passed through just fine. If either the ``series`` or ``all_series`` plugin is removed, or even just the ``season_packs`` option from one of them, it doesn't crash.

This exact config worked fine on prior versions (2.10.25). It's just adding ``season_packs`` that crashes it.

### Steps to reproduce:
- Step 1: Configure ``all_series`` alongside ``series`` and use the ``season_packs`` option in each.

#### Config:
```
  downloads_tv:
    include: [ includes/series.yml ]
    template: 
      - download_priorities
      - deluge-connect_move
      - notify_tv
      - aria2_tv
      - disable_all_seen
      - from_deluge-connect
    no_entries_ok: yes
    series:
      settings:
        regular_shows:
          parse_only: yes
          tracking: no
          season_packs: yes
    all_series:
      parse_only: yes
      tracking: no
      season_packs: yes
    thetvdb_lookup: yes
    accept_all: yes
    plugin_priority:
      all_series: 79
      thetvdb_lookup: 78
    if:
      - "('S01E01' in title.upper() or (series_id and series_id.upper() == 'S01E01')) and content_files|length == 1":
          set:
            is_premiere: 'y'
      - tvdb_genres is defined and 'Documentary' in tvdb_genres and 'Reality' not in tvdb_genres:
          set:
            is_doc: 'y'
      - tvdb_genres is defined and 'Mini-Series' in tvdb_genres and ('Documentary' not in tvdb_genres or ('Documentary' in tvdb_genres and 'Reality' not in tvdb_genres)):
          set:
            is_mini: 'y'
    set:
      tracker: tv
      step: '2'
      notify_title: 'TV - Deluge to aria'
      ended_doc_premiere: >
        {%- if is_doc is defined or is_mini is defined -%}
          {%- if is_doc is defined -%}Documentaries/
          {%- elif is_mini is defined -%}Miniseries/{%- endif -%}
          {%- if is_premiere is defined -%}Premieres
          {%- elif is_doc is defined -%}TV{%- endif -%}
        {%- elif is_premiere is defined -%}TV/Premieres
        {%- elif tvdb_status is defined and tvdb_status == "Ended" %}TV/Ended
        {%- else -%}TV/Current{%- endif -%}
      path: '{? deluge.tor_path2 ?}/tv'
    from_deluge_mod:
      filter:
        label: tv-1
        state: seeding
    modify_content_files: keep_list
```
  
#### Log:
https://gist.github.com/tubedogg/b1e4aff7de547a5f1eca652da9236a69

### Additional information:

- Flexget Version: 2.10.27
- Python Version: 2.7.13
- Installation method: pip
- OS and version: macOS El Capitan 10.11.6
- Link to crash log: https://gist.github.com/tubedogg/b1e4aff7de547a5f1eca652da9236a69

**Comment by liiight** [comment]
Whye are you sing both `series` and `all_series` in the same task?

**Comment by tubedogg** [comment]
Primarily for name_regexps for certain series.

**Comment by liiight** [comment]
I don't think you understand how all series works. It just "automatically" configures series plugin to accept any series that it successfully parses in the feed. It can take any setting that series uses. I don't see any scenario requiring to use both, it basically does nothing anyway. 

Also, I doubt that I'll fix this issue. Season pack setting creates a dict config under the hood, that's why the merge clash. Since I don't see a valid scenario where this is a problem, I don't think I'll try to change that

**Comment by tubedogg** [comment]
I understand exactly how all_series works. I also understand that for obvious reasons, you cannot in fact use _every_ series setting in all_series ... name_regexp makes no sense unless it's being applied to a particular series.

You can't see how wanting to accept everything in a feed, but ensuring certain series are matched as particular titles would be useful?

Or for that matter, applying certain settings to certain series? e.g. yes I generally want to accept everything in this feed, but for Galapagos I only want to accept it if it's 1080p. Yes that exact scenario could be handled with "if" but for more complex quality scenarios, especially ranges, I don't believe you could.

Or more to the point, differing thresholds for accepting season packs. Maybe I generally want to accept all of them but for this series I only want to accept them if I've downloaded 2 or less episodes from the season.

**Comment by liiight** [comment]
Ok, I stand corrected. I'll look into making this work. 
Also, if I came across as condescending I apologize, your contribution is greatly appreciated

**Comment by tubedogg** [comment]
No problem. I appreciate your work on this - I've been looking forward to season pack support for quite a while! :)

**Comment by gazpachoking** [comment]
I was having trouble reproducing, and I think it's because this isn't actually to do with all_series directly. We have the same problem with this series config
```
tasks:
  test:
    series:
      settings:
        regular_shows:
          season_packs: no
      regular_shows:
      - Show 1:
          season_packs:
            threshold: 5
```
The normalizing of forms is only happening after the series settings are merged with the group settings, which fails in this case.
