### ISSUE TITLE
next_series_* does not take task series config into account when determining identified_by

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1785]
### Expected behaviour:
A series in the database that has an 'identified by' type of 'auto' will still be recognized as 'ep' type when it is configured as 'ep' with ``series`` (or ``configure_series``) setting ``identified_by`` in the task.

### Actual behaviour:
The settings in the task series config are ignored and the series is rejected due to 'auto' identified by type.

### Steps to reproduce:
- Step 1: 
```
flexget inject "My Show S01E01 720p hdtv h264 dd5.1" --tasks learn_eps --learn --force --disable-tracking
```
- Step 2: Run test_task.

#### Config:
```
  learn_eps:
    all_series:
      season_packs: always
    manual: yes

  test_task:
    series:
      - My Show:
          identified_by: ep
    discover:
      what:
        - next_series_seasons:
      from:
        - btn: 'blah'
```
  
#### Log:
```
2017-04-10 03:03 TRACE    next_series_seasons test_task evaluating My Show
2017-04-10 03:03 TRACE    next_series_seasons test_task unsupported identified_by scheme
2017-04-10 03:03 VERBOSE  next_series_seasons test_task Series `My Show` with identified_by value `auto` are not supported.
```

### Additional information:

- Flexget Version: 2.10.30
- Python Version: 2.7.13
- Installation method: pip
- OS and version: macOS El Capitan 10.11.6
- Link to crash log: n/a
