### ISSUE TITLE
BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'number'

### ISSUE THREAD

**Issue by dunfy** [Flexget/Flexget#1799]
### Expected behaviour:
For the task to complete successfully 

### Actual behaviour:
The task crashes with 
 BUG: Unhandled error in plugin discover: 'NoneType' object has no attribute 'number'

### Steps to reproduce:
Use the following config below. 

#### Config:

  ```
My-TV-Shows:
    priority: 10
    template: [tv-global]
    discover:
      what:
        - next_trakt_episodes:
            account: '{? trakt.account ?}'
            context: collected
            position: next
            list: 'TV Shows'
            strip_dates: yes
        - next_series_episodes: 
            backfill: yes
            from_start: yes
      from:
        - torrentleech:
            rss_key: '{? torrentleech.rss_key ?}'
            username: '{? torrentleech.username ?}'
            password: '{? torrentleech.password ?}'
            category: ['Episodes HD', 'Episodes']
        - flexget_archive: [tv]
        - rarbg:
            category: [41]
            use_tvdb: true
            min_seeders: 10
    sequence:
      - configure_series:
          settings:
            target: 720p+ webrip+
            timeframe: 14 days
            quality: 480p+ webrip+
            tracking: backfill
          from:
            trakt_list:
              account: '{? trakt.account ?}'
              list: TV Shows
              type: shows
              strip_dates: yes

```
It's basically a copy of https://github.com/jawilson/dotfiles/blob/master/flexget/config.yml 

  
#### Log:
https://pastebin.com/9cjmkDH3

### Additional information:

- Flexget Version: 2.10.33
- Python Version: 2.7.12
- Installation method: pip 
- OS and version: Ubuntu 16.04.2 LTS
- Link to crash log: https://pastebin.com/9cjmkDH3
