### ISSUE TITLE
Backreferences do not work correctly in Jinja filter re_replace

### ISSUE THREAD

**Issue by tubedogg** [Flexget/Flexget#1802]
### Expected behaviour:
Given a Jinja expression of ``{{title|re_replace('(.*)','--\1')}}`` and an entry title of ``My Show``, the rendered string is ``--My Show``.

### Actual behaviour:
The rendered string is ``--`` unless you use the alternate backreference syntax of ``\g<1>``. I posted this on the [forum](https://discuss.flexget.com/t/re-replace-not-including-backreferences-in-replaced-string/3311) a month ago thinking I was doing something wrong, but somebody else has now said they're having the same issue.

### Steps to reproduce:
- Step 1: Run ``test_jinja_task`` with ``--dump``.

#### Config:
```
tasks:
  test_jinja_task:
    mock:
      - {title: 'My Show', g_title: 'My Show'}
    set:
      g_title: '{{g_title|re_replace("(.*)","--\g<1>")}}'
      title: '{{title|re_replace("(.*)","--\1")}}'
```
  
#### Log:
```
-- Undecided: --------------------------
title            : --
url              : mock://localhost/mock/-3282609583174991258
original_url     : mock://localhost/mock/-3282609583174991258
g_title          : --My Show
quality          : <LazyField - value will be determined when it is accessed>
task             : test_jinja_task
```

### Additional information:

- Flexget Version: 2.10.30
- Python Version: 2.7.13
- Installation method: pip
- OS and version: macOS El Capitan 10.11.6
- Link to crash log: n/a
