### ISSUE TITLE
Error searching with piratebay - flexget-20.10.42

### ISSUE THREAD

**Issue by bengt-a** [Flexget/Flexget#1816]
### Actual behaviour:
```
2017-05-08 17:00 ERROR    discover      trakt_movies_search Error searching with piratebay: Tried to set title to <span class="__cf_email__" data-cfemail="14597b7b7a3a2624242d3a56786166756d3a25242c24643a504047395c503a6c2622203953666d795456405a5140">[email\xa0protected]</span>
```

### Steps to reproduce:
- Step 1: ...

#### Config:
```
  trakt_movies_search:
  #
    template: movie
    priority: 3 # run after the movie queue fill task
    discover:
      what:
        - movie_list: traktmovielist
      from:
        - extratorrent:
            category: movies
        - iptorrents:
            rss_key: '{? iptorrents.passkey ?}'
            uid: '{? iptorrents.uid ?}'
            password: '{? iptorrents.pass ?}'
            category: Movie-HD-Bluray
        - piratebay:
            category: "highres movies"
            sort_by: seeds
        - rarbg:
            category: [ 42, 44, 45 ]
      interval: 1 hour
    list_match:
      from:
        - movie_list: traktmovielist

```
Full config: https://pastebin.com/4znLdZpY

#### Log:
```
2017-05-08 17:00 ERROR    discover      trakt_movies_search Error searching with piratebay: Tried to set title to <span class="__cf_email__" data-cfemail="14597b7b7a3a2624242d3a56786166756d3a25242c24643a504047395c503a6c2622203953666d795456405a5140">[email\xa0protected]</span>
```

### Additional information:

- Flexget Version: 2.10.42
- Python Version: 2.7.3
- Installation method: pip 
- Using Daemon? no
- OS and version: Raspbian Jessie
- Link to crash log:
