### ISSUE TITLE
Webui Log section rendering off screen 

### ISSUE THREAD

**Issue by Mondo100** [Flexget/Flexget#1819]
I have encountered an issue where the Log section of the web ui renders and keeps rendering off screen to the right off to infinity. 

I have found a fix to this by adjusting the App.css so the width is 99% instead of 100% this forces the section to fit within the screen.  see the highlighted sections below. I have also attached a copy of my edited css. 
```css
.layout-fill {
    margin: 0;
    **width: 99%;**
    min-height: 100%;
    height: 100%
}

@-moz-document url-prefix() {
    .layout-fill {
        margin: 0;
        **width: 99%;**
        min-height: 100%;
        height: 100%
    }
}
```
[app.zip](https://github.com/Flexget/Flexget/files/999240/app.zip)
