### ISSUE TITLE
Task ignoring multiple templates - Flexget broken or invalid torrent 

### ISSUE THREAD

**Issue by hhiru** [Flexget/Flexget#1826]
### Expected behaviour:
Check for torrent in the first template, then go on with the second template and terminate the operation. Checking for rss entries and downloading every magnet that match the filters.

### Actual behaviour:
It checks for torrents from the first template, it gets two errors for magnets not valid (working magnets I tested manually) and other three errors for torrents already downloaded. Then it stops not checking the second template for the second rss link.

### Steps to reproduce:
- Step 1: Structure your template with series and rss addresses
- Step 2: Make a single task that manage every template, set transmission parameters and finally specify which template the task will affect (in my case the first two templates mentioned above)
- Step 3: Check the config file for errors
- Step 4: Execute Flexget

#### Config:
```
templates:
  horriblesubs:
    series:
      - Busou Shoujo Machiavellianism
      - Re-Creators
      - Saekano S2
      - Sagrada Reset
      - Sakura Quest
      - Shingeki no Bahamut - Virgin Soul
      - Tsuki ga Kirei
    rss: https://nyaa.si/?page=rss&q=%5BHorribleSubs%5D+720p&c=1_2&f=0
  asenshi:
    series:
      - Little Witch Academia
    rss: https://nyaa.si/?page=rss&q=%5BAsenshi%5D+Little+Witch+Academia&c=1_2&f=0

tasks:
  anime:
    transmission:
      host: localhost
      port: 9091
      username: MY_USERNAME
      password: MY_PASSWORD
      path: MY_PATH
    template:
      - horriblesubs
      - asenshi

```
  
### Additional information:

- FlexGet version: 2.10.47
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Linux | Solus 2017.04.18.0 64-bit
- Link to crash log:
