### ISSUE TITLE
"trailing junk - broken or invalid torrent file received" for Nyaa RSS Feeds

### ISSUE THREAD

**Issue by hhiru** [Flexget/Flexget#1827]
### Expected behaviour:
Download every torrent in the RSS entries since I can add and download them manually with my client.

### Actual behaviour:
It gets two errors for torrents not valid (working magnets I tested manually) and other three errors for torrents already downloaded. The two torrents it can't download are mentioned in the logs.

### Steps to reproduce:
- Step 1: Copy and paste my config editing configs for the torrent client you are using for tests
- Step 2: Check for errors in the config file
- Step 3: Execute Flexget
- Step 4: Waiting for 3 + 19 downloads from both the rss links and 2 errors from the first rss link (hs)

#### Config:
```
tasks:
  hs:
    template: trantemp
    rss: https://nyaa.si/?page=rss&q=%5BHorribleSubs%5D+720p&c=1_2&f=0
    series:
      - Busou Shoujo Machiavellianism
      - Re-Creators
      - Saekano S2
      - Sagrada Reset
      - Sakura Quest
      - Shingeki no Bahamut - Virgin Soul
      - Tsuki ga Kirei

  asenshi:
    template: trantemp
    rss: https://nyaa.si/?page=rss&q=%5BAsenshi%5D+Little+Witch+Academia&c=1_2&f=0
    series:
      - Little Witch Academia

templates:
  trantemp:
    transmission:
      host: localhost
      port: 9091
      username: MY_USERNAME
      password: MY_PASSWORD
      path: MY_PATH

```
  
### Additional information:

- FlexGet version: 2.10.47
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Linux | Solus 2017.04.18.0 64-bit
- Link to crash log:
