### ISSUE TITLE
Missing notifications - g-io-error-quark: Cannot autolanch dbus

### ISSUE THREAD

**Issue by hhiru** [Flexget/Flexget#1830]
### Expected behaviour:
Receiving notifications when new entries are accepted

### Actual behaviour:
No notification sent

#### Config:
```
templates:
  global:
    notify:
      entries:
        title: New episode downloading!
        what: accepted
        via:
          - toast: yes
```
  
### Additional information:

- FlexGet version: 2.10.47
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Solus
- Link to crash log:
