### ISSUE TITLE
api_bluray Error refreshing movie details

### ISSUE THREAD

**Issue by programatix** [Flexget/Flexget#1832]
--->
### Expected behaviour:
Finds the correct item in blu-ray.com. Current movies not found by api_bluray but found if searched manually from blu-ray.com are,

1. Logan 2017
2. Beauty and the Beast 2017
3. The Boss Baby 2017 

### Actual behaviour:
api_bluray is unable to find some movies in blu-ray.com. However on manual search in blu-ray.com, the movie is available.

Manual search result url is http://www.blu-ray.com/movies/Logan-Blu-ray/169931/

I tried setting release_estimations to both 'loose' and 'optimistic' but it doesn't work because somehow, it seems that there is a cached date in the db.

### Steps to reproduce:
- Step 1: Add 'Logan (2017)' into 'discover' list

#### Config:
```
    discover:
      what:
        - movie_list: movies
      from:
        - rarbg:
            category:
              - x264 720p
              - x264 1080p
            ranked: false
      interval: 1 hour
      release_estimations: loose
      #release_estimations:
      #  optimistic: 30 days
```
  
#### Log:
```
2017-05-20 05:12 ERROR    api_bluray    Movies          Error refreshing movie details for Logan from blu-ray.com, cached info being used. No search results found for Logan (2017) on blu-ray.com
2017-05-20 05:12 VERBOSE  discover      Movies          Logan (2017) hasn't been released yet (Expected: 2017-12-31 00:00:00)
```

### Additional information:

- FlexGet version: 2.10.47
- Python version: 3.6.1
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Linux RT-N66U 2.6.22.19 #1 Tue May 16 22:59:36 EDT 2017 mips ASUSWRT-Merlin
