### ISSUE TITLE
Path issue: list_match + transmission + subtitle_list

### ISSUE THREAD

**Issue by programatix** [Flexget/Flexget#1834]
### Expected behaviour:
Path to downloaded torrent is added to the subtitle_list.

I have 2 download types, movies and tv series. For the tv series, subtitle_list works fine but not the movies. I believe the problem is due to the `path` variable defined in both `tvseries` and `movies` templates.

The `path` in `tvseries` is set inside `configure_series` (and `series`), but the `path` in `movies` is set in `transmission`. I believe the config in `movies` doesn't have `path` defined which caused the problem. Is there a way to add the paths of each files in a torrent content into `subtitle_list`? If yes, how?
```
path: '{{path}}'
```

### Actual behaviour:
```
(UndefinedError) 'path' is undefined
```
occurred.

### Steps to reproduce:
- Step 1: Combine `list_match`, `transmission` and `subtitle_list`

#### Config:
```
templates:
  tvseries:
    thetvdb_lookup: yes
    configure_series:
      from:
        filesystem:
          path:
            - '/mnt/storage1/Videos/TV Series/'
        trakt_list:
          username: [username]
          account: [account]
          list: watchlist
          type: shows
          strip_dates: yes
      settings:
        identified_by: ep
        tracking: backfill
        exact: yes
        propers: 3 days
        quality: webrip+ <=720p
        set:
          path: '/mnt/storage1/Videos/TV Series/{{series_name}}/S{{series_season|pad(2)}}'
    template: transmissionRPC

  movie:
    thetvdb_lookup: yes
    list_match:
      from:
        - movie_list: movies
    template: transmissionRPC
    transmission:
      path: "/mnt/storage1/Videos/Movies/DVD"

tasks:
  TV Series:
    template:
      - tvseries
    discover:
      what:
        - next_series_episodes:
            backfill: false
            from_start: yes
      from:
        - rarbg:
            category: [41]
            sorted_by: seeders
            ranked: false
            use_tvdb: true
      interval: 2 hour
    list_add:
      - subtitle_list:
          # this one works fine
          list: subtitles
          languages:
            - en
          path: '{{path}}'
          allow_dir: true
          remove_after: "4 weeks"
          check_subtitles: yes

  Movies:
    template:
      - movie
    discover:
      what:
        - movie_list: movies
      from:
        - rarbg:
            category:
              - x264 720p
              - x264 1080p
      interval: 1 hour
      release_estimations:
        optimistic: 30 days
    list_add:
      - subtitle_list:
          # this one doesn't work
          list: subtitles
          languages:
            - en
          path: '{{path}}'
          allow_dir: true
          remove_after: "8 weeks"
          check_subtitles: yes
```
  
#### Log:
```
2017-05-20 06:15 VERBOSE  list_add      Movies          adding accepted entries into subtitle_list - {'list': 'subtitles', 'languages': ['en'], 'path': '{{path}}', 'allow_dir': True, 'remove_after': '8 weeks', 'check_subtitles': True, 'recursion_depth': 1, 'force_file_existence': True}
2017-05-20 06:15 ERROR    subtitle_list Movies          (UndefinedError) 'path' is undefined
2017-05-20 06:15 ERROR    subtitle_list Movies          Entry %s does not represent a local file/dir.
2017-05-20 06:15 ERROR    subtitle_list Movies          (UndefinedError) 'path' is undefined
2017-05-20 06:15 ERROR    subtitle_list Movies          Entry %s does not represent a local file/dir.
2017-05-20 06:15 ERROR    subtitle_list Movies          (UndefinedError) 'path' is undefined
2017-05-20 06:15 ERROR    subtitle_list Movies          Entry %s does not represent a local file/dir.
```

### Additional information:

- FlexGet version: 2.10.47
- Python version: 3.6.1
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: asuswrt
