### ISSUE TITLE
Posters for movies in HTML template

### ISSUE THREAD

**Issue by Cholaloula** [Flexget/Flexget#1844]
Hi, 

I'm using and getting used to the (not that) new version of mail alerts of Flexget and I must say that after some adaptation I'm quite happy with it.

The HTML template is great for tv shows (I get the poster and all information), but for movies I only get information, no poster, and I'd like to know how to have it as the wiki says there should be pictures for movies alson in the mail alert.

I'm with the last flexght version on Raspbian.

Here's my movie config: 

```
  VonRicht:
    html:
      url: https://thepiratebay.red/user/vonRicht/0/7/0
      title_from: url
      links_re: [ magnet ]
    manipulate:
      - title:
          from: url
          extract: '&dn=([^&]+)'
      - filename:
          from: title
      - title:
          extract: '(.*19\d{2}).*|(.*20\d{2}).*'
          replace:
            regexp: '[.|+]'
            format: ' '
    transmission: yes
    archive: yes
    imdb:
      min_score: 7.0
      min_votes: 50
    transmission:
      host: XXX
      port: XXX
    tmdb_lookup: yes
    imdb_lookup: yes
    set:
      path: /XXX/Videos_Movies/{{ imdb_name|replace('/', '_')|replace(':', ' -') }} ({{ imdb_year }}) - {{ quality }}
    notify:
      task:
        template: html
        via:
          - email:
              from: XXX@gmail.com
              to: XXX@gmail.com
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: XXX
              smtp_password: XXX
              smtp_tls: yes
              html: yes
```

I'm scratching my head and finally ask you.

thanks!
