### ISSUE TITLE
Error downloading from newpct - "maybe a login page"

### ISSUE THREAD

**Issue by javifm86** [Flexget/Flexget#1853]
### Expected behaviour:
Download last episodes from my series from newpct feed.

### Actual behaviour:
Download from newpct is not working. I get this message: "maybe a login page?" 2 weeks ago it was working.

### Steps to reproduce:
- Step 1: flexget execute

#### Config:
```
tasks:
  series_sigo:
    rss: http://feeds2.feedburner.com/newpctorrent
    regexp:
      reject:
        - V.O. Subt. Castellano
    series:
      settings:
        calidadnormal:
          sequence_regexp: Cap.(\d+)
          quality: <720p
        calidadhd:
          sequence_regexp: Cap.(\d+)
          quality: 720p+
      calidadhd:
        - The Walking Dead
        - Prison Break
        - Mentes Criminales
    transmission:
      host: 192.168.1.60
      port: 9091
      ratio: 50
      path: /media/TOSHIBA/Series/{{series_name}}
      username: myUserName
      password: myPassword
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '[sS]ample*'
        - '*.txt'
        - '*.url'
        - '*.html'
        - '*.htm'
```
  
#### Log:
```
2017-05-31 15:25 VERBOSE  details       series_sigo     Produced 263 entries.2017-05-31 15:25 VERBOSE  task          series_sigo     REJECTED: `Prison Break - Temporada 5 [HDTV 720p][Cap.504][AC3 5.1 Español Castellano]` by retry_failed plugin because has already failed 4 times in the past. (failure reason: Unexpected html content received from `http://www.newpct.com/torrents/344829.torrent` - maybe a login page?)
2017-05-31 15:25 VERBOSE  task          series_sigo     REJECTED: `Mentes Criminales - Temporada 12 [HDTV 720p][Cap.1221][AC3 5.1 Español Castellano]` by retry_failed plugin because has already failed 4 times in the past. (failure reason: Unexpected html content received from `http://www.newpct.com/torrents/344829.torrent` - maybe a login page?)
```

### Additional information:

- FlexGet version: 2.10.56
- Python version: 2.7.9
- Installation method: pip repository (also tried github install with virtualenv, from develop and same result)
- Using daemon (yes/no):
- OS and version: Raspbian on raspberry pi 3
