### ISSUE TITLE
Unhandled error in plugin ...: %d format: a number is required, not list

### ISSUE THREAD

**Issue by DickVicious** [Flexget/Flexget#1860]
### Expected behaviour:
Expected to scan a folder, determine some info (show, season), then pass that info on to a uploader script

### Actual behaviour:
I get this error
BUG: Unhandled error in plugin metainfo_series: %d format: a number is required, not list

so I disabled the metainfo_series plugin by commenting it out and then I get this:
BUG: Unhandled error in plugin all_series: %d format: a number is required, not list

### Steps to reproduce:
- Step 1: Fill folder with TV shows
- Step 2: Execute task

#### Config:
```
templates:
  maintenance-global:
    disable:
      - seen
      - retry_failed
    no_entries_ok: yes
  tv-global:
    # Fill in extra info
    thetvdb_lookup: yes
    trakt_lookup: yes
    #metainfo_series: yes
    set:
      path: "{? transmission.download_path ?}/TV/{{tvdb_series_name}}/Season {{tvdb_season}}"

tasks:
  # Sort TV shows into their final destinations
  Upload-Series-to-ACD:
    priority: 10
    template:
      - maintenance-global
      - tv-global
    filesystem:
      path: '{? transmission.download_path ?}/TV'
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    regexp:
      reject:
        - 'sample'
        - 'RARBG.com'
        - '^ETRG.mp4'
    parsing:
      series: guessit
    all_series:
      # for some reason all_series rejects all episodes here, even with seen: local, so parse_only must be added
      parse_only: yes
    exec:
      on_output:
        for_accepted:
          - '{? rclone.path ?} -v --config {? rclone.config_file ?} --low-level-retries 3 move "{{location}}" GDrive-Enc:"/TV/{{tvdb_series_name}}/Season {{tvdb_season}}" > {? rclone.log_file ?}'
          - 'echo "/gdrive-enc/TV/{{tvdb_series_name}}/Season {{tvdb_season}}" >> /tmp/series-refresh.plex'
      on_exit:
        phase:
          - 'sort -u /tmp/series-refresh.plex | while read p; do sudo su -c "export LD_LIBRARY_PATH=/usr/lib/plexmediaserver; echo Scanning: \"$p\"; /usr/lib/plexmediaserver/Plex\ Media\ Scanner --scan --refresh$
          - 'find "{? transmission.download_path ?}/TV" -mindepth 1 -type d -empty -delete'
          - 'rm /tmp/series-refresh.plex'
    run_task:
      when: accepted
      task: Clean-Transmission
```
  
#### Log:
[Debug log](https://pastebin.com/HnEAKHq9)

### Additional information:

- FlexGet version: 2.10.56
- Python version: 2.7.12
- Installation method: pip virtualenv
- Using daemon (yes/no): no
- OS and version: Ubuntu 16.04
- Link to crash log: [Crash log](https://pastebin.com/rXTVizqZ)
