### ISSUE TITLE
Tons of crash logs - status plugin related?

### ISSUE THREAD

**Issue by Nihim** [Flexget/Flexget#1865]
OS: Debian 8
flexget: 2.10.56 , has happened on recent - older ones.
python 2.7 / 3.4
Installed via virtualenv latest with: python2/3 ./virtualenv/virtualenv.py my/flexget/dir
and with: pip install flexget
Using daemon.

I am running the same config and with the same setup on multiple machines. On this specific machine I keep getting tons of crash logs and at some random point flexget stops to work without any extra error or the daemon stopping.

There doesn't seem to be a specific cause that triggers this, it might happen every few minutes or at all for many hours. Machine's load is extremely load be it cpu / disk wise.

I have tried multiple times to recreate the virtualenv enviroment as well as use a new db.

Output of --debug --debug-sessions:

[flex-l.txt](https://github.com/Flexget/Flexget/files/1050668/flex-l.txt)

Config though as I mentioned it works fine on other machines:

```
schedules:
  - tasks: [Hor_mag]
    interval:
      minutes: 1
  - tasks: [local]
    interval:
      minutes: 2
  - tasks: [TokyoTosho]
    interval:
      minutes: 20

tasks:
  local:
    csv: 
      url: path
      values:
        title: 1
        url: 2
    download: /home/loke/rtorrent/watch_main/
    template:
      - glopr

  Horrible:
    rss: url
    download: /home/loke/rtorrent/watch_main/
    rtorrent_magnet: /home/loke/rtorrent/watch_main/
    template:
      - glopr

  NyaaTorrents:
    rss: url
    download: /home/loke/rtorrent/watch_main/
    rtorrent_magnet: /home/loke/rtorrent/watch_main/
    urlrewrite:
      imaginary:
        regexp: 'http://www.nyaa.se/\?page=torrentinfo&tid=(?P<id>\d+)'
        format: 'http://www.nyaa.se/?page=download&tid=\g<id>'
    template:
      - glopr

  TokyoTosho:
    rss: url
    download: /home/loke/rtorrent/watch_main/
    rtorrent_magnet: /home/loke/rtorrent/watch_main/
    urlrewrite:
      imaginary:
        regexp: 'http://www.nyaa.eu/?page=torrentinfo&tid=(?P<id>\d+)'
        format: 'http://www.nyaa.se/?page=download&tid=\g<id>'
    template:
      - glopr

  Hor_mag:
    rss: url
    rtorrent_magnet: /home/loke/rtorrent/watch_main/
    verify_ssl_certificates: no
    seen_info_hash: no
    template:
      - glopr

templates:
  glopr:
    regexp:
      accept:
        -lots of regex filter entries
      reject:
        filters
      from: title
    content_size:
      max: 10240
      strict: no
    content_filter:
      require_mainfile: yes


```
