### ISSUE TITLE
Error while sending notification to `telegram`: missing python-telegram-bot pkg

### ISSUE THREAD

**Issue by hhiru** [Flexget/Flexget#1872]
### Expected behaviour:
Loading python-telegram-bot module

### Actual behaviour:
Error in logs prompting that the pkg is missing even if it's installed

### Steps to reproduce:
- Step 1: install pkg via `sudo pip install python-telegram-bot`
- Step 2: execute flexget if it's not running already
- Step 3: waiting for errors in the output message or in the logs

#### Config:
```
templates:
  anime:
    notify:
      entries:
        message: '{{title}} has been added!'
        via:
          - telegram:
              bot_token: 'token_string'
              parse_mode: markdown
              recipients:
                - username: 'my_username'
```
  
#### Log:
```
2017-06-12 16:35 INFO     download      horriblesubs    Downloading: [HorribleSubs] Atom - The Beginning - 08 [720p].mkv
2017-06-12 16:35 INFO     transmission  horriblesubs    "[HorribleSubs] Atom - The Beginning - 08 [720p].mkv" torrent added to transmission
2017-06-12 16:35 WARNING  notify        horriblesubs    Error while sending notification to `telegram`: missing python-telegram-bot pkg
```

#### pip freeze output:
```
pi@flexget:~ $ pip freeze
aniso8601==1.2.1
APScheduler==3.3.1
babelfish==0.5.5
beautifulsoup4==4.6.0
certifi==2017.4.17
chardet==3.0.3
cheroot==5.5.0
CherryPy==10.2.2
click==6.7
colorama==0.3.2
colorclass==2.2.0
dnspython==1.12.0
feedparser==5.2.1
Flask==0.12.2
Flask-Compress==1.4.0
Flask-Cors==3.0.2
Flask-Login==0.4.0
Flask-RESTful==0.3.6
flask-restplus==0.8.6
FlexGet==2.10.60
funcsigs==1.0.2
functools32==3.2.3.post2
future==0.16.0
futures==3.1.1
guessit==2.0.4
html5lib==0.999999999
idna==2.5
itsdangerous==0.24
Jinja2==2.9.6
jsonschema==2.6.0
MarkupSafe==1.0
ndg-httpsclient==0.3.2
path.py==10.3.1
pathlib==1.0.1
plumbum==1.6.3
portend==1.8
pyasn1==0.1.7
pycrypto==2.6.1
pynzb==0.1.0
pyOpenSSL==0.13.1
pyparsing==2.2.0
PyRSS2Gen==1.1
python-apt==0.9.3.12
python-dateutil==2.6.0
python-telegram-bot==6.0.3
pytz==2017.2
PyYAML==3.12
rebulk==0.8.2
requests==2.16.5
RPi.GPIO==0.6.3
rpyc==3.3.0
six==1.10.0
SQLAlchemy==1.1.10
tempora==1.7
terminaltables==3.1.0
transmissionrpc==0.11
tzlocal==1.4
urllib3==1.21.1
virtualenv==15.1.0
webencodings==0.5.1
Werkzeug==0.12.2
zxcvbn-python==4.4.14
```

### Additional information:

- FlexGet version: 2.10.60
- Python version: 2.7.9
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Raspbian
- Link to crash log: http://sprunge.us/EahM
