### ISSUE TITLE
Inaccurate exists_series reject message

### ISSUE THREAD

**Issue by shotfirer** [Flexget/Flexget#1902]
The original issue was solved on forums: https://discuss.flexget.com/t/quality-upgrade-doesnt-working/3642 but I've been asked to add an issue here because of the _inaccurate error message_.
### Expected behaviour:
Download better quality

### Actual behaviour:
Rejecting by exists_series plugin because proper already exists (but there's no proper release)
 
#### Config:
```
  tv:
    series:
      settings:
        tvhd:
          quality: 720p+ !h265 !10bit
          propers: 15 hours
          upgrade: no
          specials: no
          special_ids: e00
          set:
            path: /TV/{{series_name}}/Season {{series_season}}
            include_subs: yes
      tvhd:    
        - Killjoys:
            upgrade: yes
    exists_series: 
      - /TV/{{series_name}}
```
  
#### Log:
```
2017-08-01 11:03 VERBOSE  task          RARBG           ACCEPTED: `Killjoys.S03E05.Attack.the.Rack.1080p.WEBRip.DDP5.1.x264-GRP` by series plugin because is an upgrade to existing quality
2017-08-01 11:03 VERBOSE  task          RARBG           REJECTED: `Killjoys.S03E05.Attack.the.Rack.1080p.WEBRip.DDP5.1.x264-GRP` by exists_series plugin because proper already exists

```

### Additional information:

- FlexGet version: 2.10.74
- Python version: 2.7.9
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu 15.04
