### ISSUE TITLE
Input pogcal did not return anything

### ISSUE THREAD

**Issue by lepinkainen** [Flexget/Flexget#1958]
### Expected behaviour:

I receive my show list from pogcal

### Actual behaviour:

No pogcal series list is produced

### Steps to reproduce:

A flexget config with pogcal input enabled

#### Config:
```
  shows_from_pogcal:
    configure_series:
      settings:
        timeframe: 6 hours
        propers: 12 hours
        target: "sdtv+ 720p !2160p"
      from:
        pogcal:
          username: '{? pogcal.username ?}'
          password: '{? pogcal.password ?}'
```
  
#### Log:

```
017-09-04 22:56 WARNING  configure_series eztv            Input pogcal did not return anything
2017-09-04 22:56 INFO     configure_series eztv            Did not get any series to generate series configuration
```

### Additional information:

- FlexGet version: 2.10.84
- Python version: 2.7.12
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu LTS
