### ISSUE TITLE
series_premiere and series do not work properly in conjunction

### ISSUE THREAD

**Issue by cerberii** [Flexget/Flexget#1960]
Series_premiere is parsing over series plugin, reproducible by placing series_premier in a task with an entry, example Big Brother US
```
DEBUG parser_internal tv Parsing series: Big Brother US S04E13 kwargs: {'identified_by': u'auto', u'date_regexps': [], 'strict_name': False, 'name': u'Big Brother US', 'prefer_specials': None, 'special_ids': [], 'alternate_names': [], u'sequence_regexps': [], 'date_dayfirst': None, u'id_regexps': [], 'assume_special': None, 'name_regexps': [], 'date_yearfirst': None, 'allow_groups': [], u'ep_regexps': []}
```
example config:
```
template:    
  tv:
    thetvdb_lookup: yes
    series_premiere: yes
    exists_series: /TV Shows/{{ tvdb_series_name }}
    series:
      - Big Brother US
 
tasks:
 tv:
  rss:
  template:
    -tv
```
some name matching works but some doesnt about 31 days ago. (aug 7th,2017)
