### ISSUE TITLE
Flexget Daemon Error: unable to open database file

### ISSUE THREAD

**Issue by rmccu** [Flexget/Flexget#1976]
When I start flexget in 'daemon' mode (`flexget daemon start -d`), I am getting a lot of errors in the log:

`2017-09-27 08:14 WARNING  apscheduler.scheduler                 Error getting due jobs from job store u'default': (sqlite3.OperationalError) unable to open database file`

And it does not process my tasks. If I run flexget normally (`flexget execute`) it runs fine.

I just restarted it in a `screen` session with the `--debug` and without the `-d` parameter to see if additional information is available.

I am running on Ubuntu 16.04.3 LTS and I am using an encrypted home directory.

### Expected behaviour:

The daemon should be able to run unattended, should not have read errors to the database, and should process my tasks.

### Actual behaviour:
My tasks are not executed, and the log contains the error:
`2017-09-27 08:14 WARNING  apscheduler.scheduler                 Error getting due jobs from job store u'default': (sqlite3.OperationalError) unable to open database file`

### Steps to reproduce:
- Step 1: Install Flexget
- Step 2: configure config.yaml with tasks and a schedule:
```---
schedules:
  - tasks: '*'
    interval:
      hours: 1
tasks:
  EZTV:
    rss: https://REMOVED/REMOVED
    series:
      - REMOVED:
          quality: 720p
    download: /mnt/personal/Torrents/
```
- Step 3: Start flexget in daemon mode: `flexget daemon start -d`
- Step 4: Check log later (I was checking it the next day) and notice errors

#### Config:
```
---
schedules:
  - tasks: '*'
    interval:
      hours: 1
tasks:
  EZTV:
    rss: https://REMOVED/REMOVED
    series:
      - REMOVED:
          quality: 720p
# several more lines like the above
    download: /mnt/personal/Torrents/
```
  
#### Log:
I lost the log when I restarted the daemon, but here is the line with the error:
```
2017-09-27 08:14 WARNING  apscheduler.scheduler                 Error getting due jobs from job store u'default': (sqlite3.OperationalError) unable to open database file
```
I am now running it with the `--debug` parameter and will paste an update log.

### Additional information:

- FlexGet version: 2.10.92
- Python version: 2.7.12
- Installation method: virtual env?
- Using daemon (yes/no): Yes
- OS and version: Ubuntu 16.04.3 LTS
- Link to crash log:
