### ISSUE TITLE
Pending list support in WebUI

### ISSUE THREAD

**Issue by andrey-yantsen** [Flexget/Flexget#1995]
In PR#1661 new plugin `pending_list` was introduces, and the old one — `pending_approval`, was deprecated. But current WebUI supports only `pending_approval`, and this is actually stops me from comfortable switching from deprecated plugin.

I know, that you're currently rewriting the WebUI, so this issue probably will be addressed during this rewrite. I just would like to get a notification whenever this will be done :)

### Actual behaviour:
When I open `Pending` item in navigation menu there is no items :(

### Steps to reproduce:
1. Create configuration, according to [pending_list documentation](https://flexget.com/Plugins/List/pending_list)
2. Run some tasks, so the list will be populated
3. Open `pending` page in WebUI and you'll see nothing

#### Config:
```
tasks:
  test_fill:
    headers:
      cookie: lf_session=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;
    lostfilm: yes
    accept_all: yes
    list_add:
      - pending_list: test_list
    seen: local

  test_pending:
    pending_list: test_list
    list_match:
      - pending_list: test_list
    list_remove:
      - pending_list: test_list
    download: ~/Downloads
```

### Additional information:

- FlexGet version: 2.10.104
- Python version: 2.7.13
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Debian Stretch
