### ISSUE TITLE
Search and download from newpct

### ISSUE THREAD

**Issue by euod92** [Flexget/Flexget#2011]
### Actual behaviour:
Newpct:
 just not return any result if i try to serch something. If i search from the websites, is working. 

### Steps to reproduce:
- Step 1: just try to search something in newpct 

#### Config:
```
.........
tasks:  
  spanish task:
    disable:
    - retry_failed
    - seen
    - seen_info_hash
    rss: http://feeds2.feedburner.com/newpctorrent
    regexp:
      accept:
        - American horror story: {from: title}
      reject:
        - V.O.: {from: title}
    series:
      - La que se avecina:
          quality: 720p+
          propers: no
      - Modern Family:
          quality: 720p+
      - The walking dead:
          quality: 720p+
      - American horror story:
          quality: 720p+
    download: [path]
  subtitulado task:
    disable:
    - retry_failed
    - seen
    - seen_info_hash
    rss: http://feeds2.feedburner.com/newpctorrent
    series:
      - American horror story:
          quality: 720p+
    download: [path]
  paradescargaspanishname_movie_list:
    priority: 1
    imdb_watchlist:
      user_id: id
      list: list
      force_language: es-es # Optional - Force Specified Language
    accept_all: yes
    list_add:
      - movie_list: imdb_movies
    notify:
      task:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]
      abort:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]
`bajar_pelis_spainname:
    priority: 10
    disable:
      - seen
    discover:
      interval: 1000 minutes
      what:
        - movie_list: 
            list_name: imdb_movies
            strip_year: yes
#        - emit_movie_queue: yes
      from:
        - divxatope: yes
        - newpct: yes
#        - limetorrents: yes
#        - elitetorrent: yes
#            category: all
#        - torrentdownloadws: true
#        - kat: yes
#            category: movies
#            verified: no
        - piratebay:
            category: video
            sort_by: default
#        - torrentz: verified
#      interval: 1 hours
      release_estimations:
        optimistic: 7 days
    imdb_lookup: yes
    tmdb_lookup: yes
#    trakt_lookup: yes
    quality:
      1080p+
      remux|bluray
    content_size:
      min: 5000
    set:
      path: [path]
    download: [path]
#      - proxyy
    list_match:
      from:
        - movie_list: imdb_movies
    regexp:
      reject:
        - 'sub[s][\s\._]'
        - dublado
        - Dublado
        - DUBLADO
        - '[Ll]atino'
        - '[Ss]creener'
        - '[Ss]creener':
            from: url
        - Screeener
        - Screeener:
            from: url
        - 3D
      from: title
    notify:
      task:
        via:
          - telegram:
              bot_token:  [token]
              parse_mode: markdown
            #parse_mode: html
              recipients:
                - username: [username]
      abort:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]`
```
  
```
```
  
#### Log:
```
### NEWPCT:
``2017-11-13 11:54 VERBOSE  notify_entry  paradescargaspanishname_movie_list No accepted or failed entries, not sending a notification.
2017-11-13 11:54 VERBOSE  discover      bajar_pelis_spainname Discovering 3 titles ...
2017-11-13 11:54 VERBOSE  discover      bajar_pelis_spainname Searching for `titlename1` with plugin `newpct` (1 of 3)
2017-11-13 11:54 VERBOSE  discover      bajar_pelis_spainname No search results for `title name 1`
2017-11-13 11:54 VERBOSE  discover      bajar_pelis_spainname Searching for `title name 2` with plugin `newpct` (2 of 3)
2017-11-13 11:54 VERBOSE  discover      bajar_pelis_spainname No search results for `title name 2`
2017-11-13 11:54 VERBOSE  discover      bajar_pelis_spainname Searching for `title name 3` with plugin `newpct` (3 of 3)
2017-11-13 11:54 VERBOSE  discover      bajar_pelis_spainname No search results for `title name 3`
2017-11-13 11:54 VERBOSE  details       bajar_pelis_spainname Task didn't produce any entries.
2017-11-13 11:54 VERBOSE  details       bajar_pelis_spainname Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0)
2017-11-13 11:54 VERBOSE  notify_entry  bajar_pelis_spainname No accepted or failed entries, not sending a notification.``


### Additional information:

- FlexGet version: *2.10.109
- Python version: *2.7.14
- Using daemon (yes/no): no
- OS and version: W7
