### ISSUE TITLE
Series plugin reject as nuked correct episodes

### ISSUE THREAD

**Issue by euod92** [Flexget/Flexget#2013]
### Expected behaviour:
Accept the episode because is valid and not ignore the propers: no flag.

### Actual behaviour:
Series plugin reject as nukedvalid episodes, maybe, because the previus episode in this season has a proper version.
### Steps to reproduce:
download La que se avecina season 10 episode 7 from newpct rss:  http://feeds2.feedburner.com/newpctorrent

#### Config:
```
.........
tasks:  
  spanish task:
    disable:
    - retry_failed
    - seen
    - seen_info_hash
    rss: http://feeds2.feedburner.com/newpctorrent
    regexp:
      accept:
        - American horror story: {from: title}
      reject:
        - V.O.: {from: title}
    series:
      - La que se avecina:
          quality: 720p+
          propers: no
      - Modern Family:
          quality: 720p+
      - The walking dead:
          quality: 720p+
      - American horror story:
          quality: 720p+
    download: [path]
  subtitulado task:
    disable:
    - retry_failed
    - seen
    - seen_info_hash
    rss: http://feeds2.feedburner.com/newpctorrent
    series:
      - American horror story:
          quality: 720p+
    download: [path]
  paradescargaspanishname_movie_list:
    priority: 1
    imdb_watchlist:
      user_id: id
      list: list
      force_language: es-es # Optional - Force Specified Language
    accept_all: yes
    list_add:
      - movie_list: imdb_movies
    notify:
      task:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]
      abort:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]
`bajar_pelis_spainname:
    priority: 10
    disable:
      - seen
    discover:
      interval: 1000 minutes
      what:
        - movie_list: 
            list_name: imdb_movies
            strip_year: yes
#        - emit_movie_queue: yes
      from:
        - divxatope: yes
        - newpct: yes
#        - limetorrents: yes
#        - elitetorrent: yes
#            category: all
#        - torrentdownloadws: true
#        - kat: yes
#            category: movies
#            verified: no
        - piratebay:
            category: video
            sort_by: default
#        - torrentz: verified
#      interval: 1 hours
      release_estimations:
        optimistic: 7 days
    imdb_lookup: yes
    tmdb_lookup: yes
#    trakt_lookup: yes
    quality:
      1080p+
      remux|bluray
    content_size:
      min: 5000
    set:
      path: [path]
    download: [path]
#      - proxyy
    list_match:
      from:
        - movie_list: imdb_movies
    regexp:
      reject:
        - 'sub[s][\s\._]'
        - dublado
        - Dublado
        - DUBLADO
        - '[Ll]atino'
        - '[Ss]creener'
        - '[Ss]creener':
            from: url
        - Screeener
        - Screeener:
            from: url
        - 3D
      from: title
    notify:
      task:
        via:
          - telegram:
              bot_token:  [token]
              parse_mode: markdown
            #parse_mode: html
              recipients:
                - username: [username]
      abort:
        via:
          - telegram:
              bot_token: [token]
              parse_mode: markdown
              #parse_mode: html
              recipients:
                - username: [username]`
```
  
```
```
  
#### Log:
```
2017-11-14 17:08 VERBOSE  series        spanish task    identified by is currently on `auto` for La que se avecina. Multiple id types may be accepted until it locks in on the appropriate type.
2017-11-14 17:08 VERBOSE  series        spanish task    Ignored `La Que Se Avecina (PROPER) - Temporada 10 [HDTV][Cap.1006][Español Castellano]`. Does not meet quality requirement `720p+`.
2017-11-14 17:08 VERBOSE  series        spanish task    Ignored `La Que Se Avecina - Temporada 10 [HDTV][Cap.1007][Español Castellano]`. Does not meet quality requirement `720p+`.
2017-11-14 17:08 VERBOSE  task          spanish task    REJECTED: `La Que Se Avecina - Temporada 10 [HDTV 720p][Cap.1007][AC3 5.1 Español Castellano]` by series plugin because nuked
2017-11-14 17:08 VERBOSE  task          spanish task    REJECTED: `La Que Se Avecina (PROPER) - Temporada 10 [HDTV 720p][Cap.1006][AC3 5.1 Español Castellano]` by series plugin because quality already downloaded
2017-11-14 17:08 VERBOSE  details       spanish task    Summary - Accepted: 0 (Rejected: 25 Undecided: 305 Failed: 0)
```

### Additional information:

- FlexGet version: *2.10.109
- Python version: *2.7.14
- Using daemon (yes/no): no
- OS and version: W7
