### ISSUE TITLE
Drive letters are case sensitive when adding to uTorrent on Windows

### ISSUE THREAD

**Issue by antonioribeiro** [Flexget/Flexget#2038]
### Expected behaviour:

Automatically add torrents to uTorrent Web UI using uppercase or lowercase on drive letters and/or path.

### Actual behaviour:

If drive letter (z:) is configured as lowercase in one end and uppercase (Z:) in the other end, Flexget fails to add torrents to the proper directory and adds them to the root. 

#### configure Flexget with a lowercase drive letter
    utorrent:
      url: http://172.17.0.120:8087/gui/
      username: admin
      password: mypassword
      path: z:\videos\tv\

#### configure uTorrent Web UI with an uppercase drive letter:

![image](https://user-images.githubusercontent.com/3182864/33835227-f0d72b5a-de6c-11e7-9d02-007273229c2d.png)

####  Wait for a torrent to be available and you should get this message:

path z:\videos\tv\ShowName\Season 3 (or one of its parents)is not added to utorrent webui allowed download directories. You must add it there before you can use it from flexget. Adding to default download directory instead.

#### All details of this problem are in this thread:

https://discuss.flexget.com/t/configuring-utorrent-webui-allowed-download-directories-for-flexget/3895/3

**Comment by liiight** [comment]
I pushed a suggested fix. Can you wait for next release/pull from git and verify?

**Comment by liiight** [comment]
Assuming this is closed

**Comment by antonioribeiro** [comment]
Problem got back on newer versions:

**Comment by liiight** [comment]
Did you confirm it was solved before?

**Comment by liiight** [comment]
Did you check that nothing changed on your utorrent setup? There was nothing on flexget side that could affect this

**Comment by antonioribeiro** [comment]
Like what? The only change was to update Flexget. Did not change Flexget config. Other than WebUI "download directories" and Flexget config, what else could cause a `path [name] (or one of its parents)is not added to utorrent webui allowed download directories`?

This is still my WebUI config:

![image](https://user-images.githubusercontent.com/3182864/34799967-082ccb0e-f649-11e7-97cf-3019b1ceca60.png)

And the related Flexget config:

```
  tv-task:
    rss: https://<ulr>
    series:
      settings:
        seriesgroup:
          set:
            path: Z:\videos\tv\{{series_name}}\Season {{series_season}}

    ...

    utorrent:
      url: http://172.17.0.120:8087/gui/
      username: admin
      password: [redacted]
      path: Z:\videos\tv\  # Either c:\stuff, or c:\stuff\here must be added to your allowed download folders
```
