### ISSUE TITLE
BUG: Invalid response received from Sonarr: This series has already been added

### ISSUE THREAD

**Issue by JourneyOver** [Flexget/Flexget#2041]
### Expected behaviour:

Skip any shows that are already added on sonarr.

### Actual behaviour:

Doesn't skip the shows that are already added on sonarr so it keeps throwing the error -
`Invalid response received from Sonarr: b'[\r\n {\r\n "propertyName": "TvdbId",\r\n "errorMessage": "This series has already been added",\r\n "attemptedValue": 295829,\r\n "formattedMessageArguments": [],\r\n "formattedMessagePlaceholderValues": {\r\n "propertyName": "Tvdb Id",\r\n "propertyValue": 295829\r\n }\r\n }\r\n]'` whenever the task is executed and done.

The "attemptedValue" and the "propertyValue" are always different, so far it has hit on every show that I already have in sonarr.. It's acting like the shows don't exist at all on sonarr when in reality they do.

### Steps to reproduce:
- Step 1:  Add a show to sonarr
- Step 2: Add same show to a trakt list
- Step 3: Try to import said list into sonarr with the Trakt to Sonarr plugin.

#### Config:

```
variables: secrets.yml

web_server:
  bind: 0.0.0.0
  port: 9091
  web_ui: yes
  
schedules:
##### Import Trakt list "Sonarr-TV" to sonarr
  - tasks: ['import-trakt-to-sonarr']
    interval:
      weeks: 1

tasks:

##### Import Trakt list "Sonarr-TV" to sonarr
  import-trakt-to-sonarr:
    trakt_list:
      username: "{? trakt.account ?}"
      account: "{? trakt.account ?}"
      list: "{? trakt.series ?}"
      type: shows
    accept_all: yes
    list_add:
       - sonarr_list:
          base_url: http://localhost
          port: 8989
          api_key: "{? sonarr.api_key ?}"
          ignore_episodes_with_files: true
          ignore_episodes_without_files: true
          search_missing_episodes: false
```

#### Log:
Running daemon with webUI --
https://pastebin.com/LUV6Jzyq

Running without daemon and not on the webUI  (running through CLI) --
https://pastebin.com/mc3C1FsD

### Additional information:

- FlexGet version: Flexget: 2.11.11  
- Python version: 3.6.3 but have tried with python 2.7 as well
- Installation method: pip
- Using daemon (yes/no): yes but have tried with not running the daemon as well.
- OS and version: Windows 10 Pro x64 bit, 1709 build 16299.64
- Link to crash log:
