### ISSUE TITLE
Internal parser: Episode titles that start with numbers are parsed as a pack

### ISSUE THREAD

**Issue by cvium** [Flexget/Flexget#2051]
### Expected behaviour:
It parses the title as an episode and not a pack.
### Actual behaviour:
It parses the episode as a pack eg. Some.Show.S01E01.90.days is parsed as S01E01-90.
### Steps to reproduce:
- Step 1: Run the config.

#### Config:
```
tasks:
  test_parser:
    mock:
      - {title: 'Some.Show.2017.S01E01.11.27.1080p.H.264-NOGRP'}
    series:
      - Some Show (2017)
```
  
#### Log:
Away at the moment, but to paraphrase: It is being parsed as a pack and rejected for being too large eg. S01E01-11. https://github.com/Flexget/Flexget/blob/develop/flexget/utils/titles/series.py#L329-L330

**Comment by shotfirer** [comment]
Any update on this? Still not working, entries undecided.
Config:
```
tasks:
  test_parser:
    mock:
      - {title: 'Gotham.S05E06.13.Stitches.1080p.NF.WEBRip.DDP5.1.x264-CasStudio[rartv]'}
    series:
      - Gotham
```
Log:
http://dpaste.com/14P15W1
