### ISSUE TITLE
Incorrect handling on parentheses in the latest versions

### ISSUE THREAD

**Issue by gsapient** [Flexget/Flexget#2057]
### Expected behaviour:
An entry under the series plugin that looks like this:
` - (xxx) yyy`
should match releases that look something like this:
`xxx.yyy.web.x264`

### Actual behaviour:

There is no match. The release is not "seen"

### Steps to reproduce:
- Step 1: Use a config with parenteses
- Step 2: use an input with entries that match the text in and out of the parenteses
- Step 3: verify the lack of match using the `flexget series show yyy` command

#### Config:
```
templates:
  tv:
    series:
      - (xxx) yyy
    transmission: {path: 'd:/.....'}
tasks:
  NewTV:
    inputs:
      - rss: https://......
    template: tv
```
  
#### Log:
Nothing to see here, there is just no match. It would look something like this:

```
2018-01-07 14:40 VERBOSE  task_queue                    There is 1 task to execute. Shutdown will commence when they have completed.
2018-01-07 14:40 VERBOSE  details       NewTV          Produced 99 entries.
2018-01-07 14:40 VERBOSE  details       NewTV          Summary - Accepted: 0 (Rejected: 0 Undecided: 99 Failed: 0)
```

### Additional information:

- FlexGet version: 2.11.21
- Python version: 2.7.14
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: windows 10 x64
