### ISSUE TITLE
no_entries_ok not suppressing warning in log

### ISSUE THREAD

**Issue by zosky** [Flexget/Flexget#2060]
### Expected behaviour:

it says [here](https://flexget.com/Plugins/no_entries_ok) `no_entries_ok: yes` is suppose to make the "no input" msg VERBOSE instead of WARNING 

### Actual behaviour:
the WARNING Is still getting into the log

### Steps to reproduce:
- Step 1: 
```
    flexget execute --tasks 'tr*'
    # console shows WARNING AND VERBOSE
    # log file gets WARNING line
```

#### Config:
```  
  tr-rm-seed:
    no_entries_ok: yes #*should* suppress no input warning
    accept_all: no #suppress no filter warning
    clean_transmission:
      finished_for: 84 hours
      delete_files: Yes
      directories:
        - \A/+home/+zosky/+links/+torrs/+2.seed(\Z|/+.*)
    disable: details
```
  
#### Log:
```
2018-01-19 16:29 WARNING  task          tr-rm-seed      Task doesn't have any input plugins, you should add (at least) one!
```

### Additional information:

- FlexGet version: 2.11.23
- Python version: 2.7.12
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: ubuntu 16.04.03 xenial 
- Link to crash log: no crash
