### ISSUE TITLE
Changed Indetifier after removing episode series

### ISSUE THREAD

**Issue by MaHoCNC** [Flexget/Flexget#2067]
--->
### Actual behaviour:

Plugin next series episode wont download any episode of this series after deleting by API. 

`next_series_episodes tv_search       Series `Star Trek: Discovery` with identified_by value `auto` are not supported. `

when enter command:
`flexget series show 'Star Trek: Discovery'`

at the end the shows Identifier is suddenly set to auto

`Series plugin is still learning which episode numbering mode is 
 correct for this series (identified_by: auto).
 Few duplicate downloads can happen with different numbering schemes
 during this time. 
 See `identified_by` option for more information.`

To solve this i have to:
- Stop deamon
- disable(#) the line `identified_by: ep` in my config
- run task `flexget execute --task tv_search --discover-now --now --no-cache --debug` (same error)
- enable (remove #) the line `identified_by: ep` in my config
- start deamon or run task again. Indentifier is set again to episode and downloads resume

### Steps to reproduce:
- run in deamon
- delete episode in API
- run next_series_episode in debug

#### Config:
```
`templates:
  global:
    regexp:
      reject:
        - (?i)[ .]french[ .]
        - (?i)[ .]spanish[ .]
        - (?i)[ .]swedish[ .]
        - (?i)[ .]cam[ .]
        - (?i)[ .]bdscr[ .]
        - (?i)[ .]dvdscr[ .]
        - (?i)[ .]preair[ .]
        - (?i)[ .]ppvrip[ .]
        - (?i)[ .]r5[ .]
        - (?i)[ .]tc[ .]
        - (?i)[ .]ts[ .]
        - (?i)[ .]ecc[ .]
        - (?i)[ .]avc[ .]
        - (?i)[ .]qebs[ .] 
        - (?i)[ .]trailer[ .]
        - (?i)[ .]Subs[ .]
        - (?i)[ .]subbed[ .]
        - (?i)[ .]subtitles[ .] 
        - (?i)[ .]x265[ .]
        - (?i)[ .]HC[ .]
        - (?i)[ .]KORSUB[ .]
        - (?i)[ .]Blurred[ .]
        - (?i)[ .]KOR[ .]
        - (?i)[ .]mSD[ .]
        - (?i)[ .]THEPIRATEBRAZIL[ .]
        - (?i)[ .]CtrlHD[ .]
        - (?i)[ .]SWESUB[ .]
        - (?i)[ .]Degrees[ .]
        - (?i)[ .]POOP[ .]
        - (?i)[ .]ExYu-Subs[ .]
        - (?i)[ .]Subtitulado[ .]
        - (?i)[ .]Hindi[ .]
        - Subtitulado
        - ExYu-Subs
        - VOSTFR
        - HDTC
        - HQTC
        - HD-TC
        - UPTOTAL
        - PLUTONiUM
        - Cyphanix
        - Manning
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
      reject: 
        - '*.wmv'
        - '*.wma'

  transmissionrpc:
    transmission:
      host: localhost
      port: ...
      username: ...
      password: ...
    

  tv:
    thetvdb_lookup: yes
    metainfo_series: yes
    exists_series:
      path: /path/to/Series/
      allow_different_qualities: yes
    regexp:
      reject:
        - (?i)[ .]french[ .]
        - (?i)[ .]spanish[ .]
        - (?i)[ .]swedish[ .]
        - (?i)[ .]cam[ .]
        - (?i)[ .]bdscr[ .]
        - (?i)[ .]dvdscr[ .]
        - (?i)[ .]preair[ .]
        - (?i)[ .]ppvrip[ .]
        - (?i)[ .]r5[ .]
        - (?i)[ .]tc[ .]
        - (?i)[ .]ts[ .]
        - (?i)[ .]ecc[ .]
        - (?i)[ .]avc[ .]
        - (?i)[ .]qebs[ .] 
        - (?i)[ .]trailer[ .]
        - (?i)[ .]Sub[ .]
        - (?i)[ .]Subs[ .]
        - (?i)[ .]subbed[ .]
        - (?i)[ .]subtitles[ .] 
        - (?i)[ .]x265[ .]
        - VOSTFR
        - HDTC
        - HQTC
        - HD-TC
        - UPTOTAL
    configure_series:
      from:
        entry_list: tvseries
      settings:
        identified_by: ep
        quality: webrip hdtv+ <=720p !h265
        tracking: backfill
        season_packs: no

    set:
      path: /path/to//autodownloadtv/


  tv_search_request:
    template:
      - tv
    discover:
      what:
        - next_series_episodes:
            from_start: yes
            backfill: yes
      from:
#        - search_rss: https://kickass.unblocked.la/usearch/{{search_term}}/?rss=1
        - piratebay: yes 
        - rarbg:
            category: [1, 18, 41, 49]
#        - extratorrent:
#            category: tv
#        - search_rss: https://kickass.unblocked.pe/usearch/{{search_term}}/?rss=1
      release_estimations: 
        optimistic: 30 days
    torrent_alive: 5
##########################################################################################

tasks:

  Fill_series_list:
    priority: 10
    list_remove:
      - entry_list: tvseries
    accept_all: yes
    disable: seen
    trakt_list:
      username: ...
      account: ...
      list: following shows
      type: shows
      strip_dates: yes
    set:
      title: "{{title|escape|replace('&#39;', '')}}"
    list_add:
      - entry_list: tvseries

   
    

  tv_search:
    priority: 12
    template:
      - tv_search_request
      - transmissionrpc
    interval: 3 hour # Search for expected episodes again every hour

  sort-tvseries:
    priority: 30
    filesystem:
      path: /path/to/autodownloadtv/
      regexp: '.*\.(mkv|mp4|m4v|avi)$'
      recursive: yes
    thetvdb_lookup: yes
    metainfo_series: yes
    seen: local
#    template: tv
    disable: retry_failed
#    series:
#      settings:
#        group 1:
    configure_series:
      from:
        trakt_list:
          username: ...
          account: ...
          list: following shows
          type: shows
          strip_dates: yes
      settings:
        parse_only: yes
    regexp:
      reject: 
        - sample
    require_field: series_name
    accept_all: yes
    copy:
      to: /path/to/{{series_name}}/{{series_name}} - Season {{series_season}}
    list_add:
      - subtitle_list:
          list: subtitles
          path: "{{location}}"
          remove_after: 10 days
    digest: daily_email_series

  Fetch subs:
    priority: 50 
    disable:
      - retry_failed
      - seen
    no_entries_ok: yes
    subtitle_list:
      list: subtitles
      recursion_depth: 3
    list_match:
      from:
        - subtitle_list:
            list: subtitles
    subliminal:
      languages:
        - nld
      alternatives:
        - en
      providers: 
        - addic7ed
        - opensubtitles
        - podnapisi
        - tvsubtitles
      single: no  # will append the language code to the subtitle file
      exact_match: yes

  housekeeping:
    priority: 60
    template: transmissionrpc
    clean_transmission:
      host: localhost
      port: ...
      username: ...
      password: ...
      finished_for: 5 days
      enabled: Yes

  daily-email-series:
    priority: 70
    interval: 1 days
    from_digest:
      list: daily_email_series
    seen: local
    accept_all: yes
    notify:
      task:
        via:
          - email:
              from: ...

`
paste FULL config and remove any personal info
use paste service like http://dpaste.de or http://pastebin.com if config is too long
```
  
#### Log:
```
flexget execute --task tv_search --discover-now --now --no-cache --debug 
2018-01-26 19:02 INFO     performance                   Enabling plugin and SQLAlchemy performance debugging
2018-01-26 19:02 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2018-01-26 19:02 INFO     interval      tv_search       Ignoring interval because of --now
2018-01-26 19:02 VERBOSE  next_series_episodes tv_search       Series `Star Trek: Discovery` with identified_by value `auto` are not supported. 
2018-01-26 19:02 VERBOSE  discover      tv_search       Discovering 302 titles ...
2018-01-26 19:02 INFO     discover      tv_search       Ignoring interval because of --discover-now
2018-01-26 19:02 INFO     task          tv_search       Plugin next_series_episodes has requested task to be ran again after execution has completed. Reason: Look for next season

```

### Additional information:

- FlexGet version: 2.11.23
- Python version: 2.7.12+
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Lubuntu (ubuntu 16.10
