### ISSUE TITLE
Convert timestamp to Date Object

### ISSUE THREAD

**Issue by samuelmaurer** [Flexget/Flexget#2106]
I have a task which gets entries from "from_rtorrent". In an if_statement i want to reject entries which are 7 days younger than "timestamp.finished". Problem is, that the field "timestamp.finished" from rtorrent contains a Unix Timestamp and the statement "now" and "timedelta()" are Date Objects. Is there a way to convert the field "timestamp.finished" to a Date Object?

#### Config:
```
Clean_WEB:
    manual: yes
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    from_rtorrent:
      uri: '{? rtorrent.site ?}'
      username: '{? rtorrent.usr ?}'
      password: '{? rtorrent.pwd ?}'
    if:
      - "'path to Series' in path": accept
      - timestamp.finished > now - timedelta(days=7): reject
    rtorrent:
      uri: '{? rtorrent.site ?}'
      username: '{? rtorrent.usr ?}'
      password: '{? rtorrent.pwd ?}'
      action: update
      custom1: del_cue

```
  
#### Log:
```
Error occurred while evaluating statement `timestamp.finished > now - timedelta(days=7)`. (can't compare datetime.datetime to int)

```

### Additional information:

- FlexGet version: 2.13.4
- Python version: 2.7
- Installation method: Synology entware-ng pip
- Using daemon (yes/no): yes
- OS and version: Synology DSM 6
