### ISSUE TITLE
The torrentleech plugin is not working with their V5 api 

### ISSUE THREAD

**Issue by carlba** [Flexget/Flexget#2115]
### Expected behaviour:
The first episode of the series is downloaded

### Actual behaviour:
No results are found from the torrentleech search plugin

### Steps to reproduce:
- Step 1: Run flexget with the config supplied in the issue

#### Config:
```
tasks:
  test task:
    series:
      - Rick and Morty:
          begin: S02E01
    discover:
      what:
        - next_series_episodes:
            backfill: yes
      from:
        - torrentleech:
            rss_key: ***********
            username: ***********
            password: ***********
    download: ~/downloads

schedules:
  # Run every 30 minutes
  - tasks: '*'
    schedule:
      minute: "*/20"
```
  
### Additional information:
This seems to be a result of the upgrade to the Torrentleech V5 api. I modified the plugin to use the V4 api and this is working for now as long as they don't remove support for it. Would it be reasonable to put a PR with a Torrentleech plugin that uses the V4 api until support for the V5 api has been implemented? 

- FlexGet version: 2.13.8.dev
- Python version: Python 2.7.14
- Installation method: Latest git version
- Using daemon (yes/no): no
- OS and version: MacOS and Ubuntu Server
