### ISSUE TITLE
sftp_download fails to download file with ';' in the file name

### ISSUE THREAD

**Issue by ksurl** [Flexget/Flexget#2124]
### Expected behaviour:

download file via sftp_download plugin

### Actual behaviour:

does not download the file due to filename containing ';' character
all other files download normally (alphanumeric with some containing dashes)

### Steps to reproduce:
- Step 1: ...

have a config with sftp_download task to accept all files
run `flexget execute --tasks sync-series`
series name has a ';' in the name (Steins;Gate 0)

#### Config:
```
paste FULL config and remove any personal info
if config is too long, attach the file to the ticket
```
 
```
variables: variables.yml

templates:

  global:
    no_entries_ok: yes

  anchors:
    _sftp_list: &sftp_list
      host: '{? sftp.host ?}'
      username: '{? sftp.username ?}'
      private_key: '{? sftp.private_key ?}'
      private_key_pass: '{? sftp.private_key_pass ?}'

  notify-sync:
    notify:
      entries:
        title: 'FlexGet'
        message: "Downloaded {{title|replace('.mkv','')|replace('.mp4','')}}"
        via:
          - pushbullet:
              api_key: '{? pushbullet.apikey ?}'

tasks:

  sync-series:
    sftp_list:
      <<: *sftp_list
      dirs:
        - '{? remote.downloads ?}/series/'
    accept_all: yes
    sftp_download:
      to: '{? local.downloads ?}/series/'
    template: notify-sync

  sort-series:
    filesystem: '{? local.downloads ?}/series/'
    configure_series:
      from:
        filesystem: '{? local.videos ?}/series/'
    move:
      to: "{? local.videos ?}/series/{{series_name}}/"

schedules:
  - tasks: sync-series
    schedule:
      minute: "*/30"
      hour: 8-23
  - tasks: sort-series
    schedule:
      minute: 10,40
      hour: 8-23
```
 
#### Log:
```
paste log output
if log output is too long, attach the file to the ticket
```

from flexget.log: Remote path does not exist: /home/$user/downloads/flexget/series/Steins

### Additional information:

- FlexGet version: 2.13.3
- Python version: 2.7.12
- Installation method: pip install inside a virtualenv based on python2
- Using daemon (yes/no): yes
- OS and version: ubuntu 16.04.3 LTS 64 bit
- Link to crash log:
