### ISSUE TITLE
my_anime_list plugin is no longer functional

### ISSUE THREAD

**Issue by viggy96** [Flexget/Flexget#2152]
### Expected behaviour:
plugin retrieves list of anime from your animelist.

### Actual behaviour:
Returns error: 
`Error during input plugin my_anime_list: Error finding list on url: https://myanimelist.net/malappinfo.php?status=all&type=anime&u=viggy96`
'viggy96' being my MAL username.
### Steps to reproduce:
 run 'flexget execute' on any config that uses the my_anime_list plugin.

### Config
```
variables: variables.yml

templates:
  global:
    transmission:
      host: localhost
      port: 9091
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'
      addpaused: no
      magnetization_timeout: 120
      ratio: 20.0
    content_filter:
      require:
        - '*.mkv'
      reject:
        - '*.wmv'
        - '*.mp4'
        - '*.avi'
        - '/\W*(raws)\W*/gi'
        - '/\W*(multi)\W*/gi'

  seasonal_anime_and_specials:
    transmission:
      path: /home/box/Downloads/Anime/{{series_name | pathscrub('windows') | trim}}
      content_filename: "{{series_name}} - {{series_id}} [{{quality | replace('h264', '') | replace('aac', '') | trim}}]"
    trakt_lookup: yes
    configure_series:
      settings:
        quality: 720p
        ep_regexp:
          - (\d+)
        season_packs: yes
      from:
        my_anime_list:
          username: '{? mal.username ?}'
          status:
            - watching
            - plan_to_watch
          type: 
            - series
            - ova
            - special
            - ona
    series:
      settings:
        groupa:
          quality: 720p
          ep_regexp:
            - (\d+)
          season_packs: yes 
      groupa:
        - 'Gintama'
        - 'Shokugeki no Souma: San no Sara - Toutsuki Ressha-hen':
            alternate_name: 'Shokugeki no Soma S3'

  anime_movies:
    transmission: 
      path: /home/box/Downloads/Anime/{{movie_name | pathscrub('windows') | trim}}
      content_filename: "{{movie_name | pathscrub('windows')}} - [{{quality | replace('webdl', '') | replace('dts', '') | replace('ac3', '') |  replace('aac', '') | trim}}]"
    configure_series:
      settings:
        timeframe: 24 hours
        target: 1080p h265
        quality: 720p
      from:
        my_anime_list:
          username: '{? mal.username ?}'
          status:
            - watching
            - plan_to_watch
          type: movie

  tv_shows:
    transmission:
      path: /home/box/Downloads/TV/{{series_name}}
      main_file_only: yes
      main_file_ratio: 0.90
      content_filename: "{{series_name}} - {{series_id}} [{{quality | replace('hdtv', '') | replace('webrip', '') | replace('webdl', '') | trim}}]"
    series:
      - 'Adam Ruins Everything'
      - 'Altered Carbon'
      - 'Archer (2009)'
      - 'BattleBots'
      - 'Bill Nye Saves the World'
      - 'Black Mirror'
      - 'Elementary'
      - 'Last Week Tonight With John Oliver'
      - 'Our Cartoon President'
      - 'Sherlock'
      - 'Star Trek: Discovery'
      - 'The Grand Tour'
      - 'The Orville'
      - 'The Simpsons'
      - 'Westworld'

tasks:
  horriblesubs:
    rss: http://horriblesubs.info/rss.php?res=720
    template: seasonal_anime_and_specials
    remember_rejected: yes
    version_checker: yes
    priority: 1
  nyaa_movies:
    rss: https://nyaa.si/?page=rss&c=1_2&f=0
    template: anime_movies
    remember_rejected: yes
    priority: 2
  tv:
    rss: http://showrss.info/user/159252.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    template: tv_shows
    remember_rejected: yes
    priority: 3
```

### Additional information:

- FlexGet version:
- Python version: 2.7.14
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Ubuntu Server 16.04.3 LTS
