### ISSUE TITLE
with guessit plugin: series: list index out of range

### ISSUE THREAD

**Issue by kfirufk** [Flexget/Flexget#2176]
Hi :)
I'm using latest flexget from git on develop branch on gentoo linux ~amd64 with Python 3.5.5

running `flexget check` returns no warnings or errors
after I enabled the guessit plugin for series when I run a task i named tv-sort, for sorting my tv-shows,  flexget crashes.

the crash report is at https://paste.pound-python.org/show/FzJA3quGxCUg6iS0CJmt/
my config.yml is at https://paste.pound-python.org/show/fj7yoiAsyBSlujXyVfVa/

thanks! :)

**Comment by kfirufk** [comment]
sorry! :)

attached the crash report
and this is my config.yml

```
templates:
  downloads:
    nzbget:
      url: http://127.0.0.1:6789/xmlrpc
    transmission:
      host: 127.0.0.1
      port: 9091
      addpaused: No
  my-tv-shows:
    series:
      settings:
        shows:
          identified_by: ep
          tracking: backfill
          quality: 1080p 720p
          season_packs: yes
      shows:
        - 30 rock
        - future man
        - new girl
        - the good place
        - mr robot
        - rick and morty
        - that 70s show
        - the magicians
        - westworld
        - how i met your mother
        - two and a half men
        - Friends:
            name_regexp:
              - ^Friends$
tasks:
  delete-dups-tv-shows:
    assume_quality:
      h264: 1080p
    configure_series:
      from:
        filesystem: /mnt/storage-btrfs/media/tv-shows
    filesystem:
      recursive: True
      path:
        - /mnt/storage-btrfs/media/tv-shows
      retrieve: files
    if:
      - has_field('series_episode'):
          exec:
            on_output:
              for_undecided: echo {{series_name}} {{series_id}} {{quality}}  {{location}} >> `date +%y%m%d`.dups.out
  tv-sort:
    parsing:
      series: guessit
    filesystem:
      path:
        - /mnt/storage-btrfs/downloads/
      recursive: True
    seen: local
    template: [my-tv-shows]
    series:
      settings:
        agroup:
          parse_only: yes
    regexp:
      reject:
        - sample
      accept:
        - '.*\.(avi|mkv|mp4)$'
    require_field: series_name
    accept_all: yes
    move:
      to: /mnt/storage-btrfs/media/tv-shows/{{series_name}}/Season {{series_season|pad(2)}}
  tv-search:
    exists_series: /mnt/storage-btrfs/media/tv-shows
    template: [my-tv-shows, downloads]
    discover:
      what:
        - next_series_episodes:
            from_start: yes
            backfill: yes
      from:
        - newznab:
            website: https://api.nzbplanet.net
            apikey:  <KEY>
            category: tv
        - newznab:
            website: https://simplynzbs.com
            apikey: <KEY>
            category: tv
        - piratebay:
            category: video
            sort_by: seeds
            url: https://zombay.org
      interval: 1 hour
```


[crash_report.2018.07.20.000942885382.log](https://github.com/Flexget/Flexget/files/2214256/crash_report.2018.07.20.000942885382.log)
