### ISSUE TITLE
REJECTED: <filename> by require_field plugin because required field series_name is not present

### ISSUE THREAD

**Issue by kfirufk** [Flexget/Flexget#2177]
Hello :)

I'm not sure this is a bug.. maybe I don't understand the error message properly.

my config.yml file contains 'mr robot' as a series name and i use the guessit plugin for a task i called 'tv-sort' to sort my series videos.

when I run the task I encountered the following error:

> 2018-07-22 23:28 VERBOSE  task          tv-sort         REJECTED: `Mr.Robot.S01.m4king_of_mr_robot.mov.720p.BluRay.DD2.0.x264-VietHD` by require_field plugin because required field series_name is not present

does it mean that it could not parse the name of the tv series from the filename for some reason? (with is odd) or it means that it doesn't find 'mr robot' in the configured series name ? (which it is)

so first.. I need clearification :)
next.... i need some info how to investigate this issue ? if anyone can point me to the relevant lines of code so i can understand more properly what is the problem and how to resolve it.

any information regarding the issue would be greatly appreciated.

thanks!

this is my full config.yml

```
templates:
  downloads:
    nzbget:
      url: http://127.0.0.1:6789/xmlrpc
    transmission:
      host: 127.0.0.1
      port: 9091
      addpaused: No
  my-tv-shows:
    series:
      settings:
        shows:
          identified_by: ep
          tracking: backfill
          quality: 1080p 720p
          season_packs: yes
      shows:
        - community
        - 30 rock
        - future man
        - new girl
        - the good place
        - mr robot
        - rick and morty
        - that 70s show
        - the magicians
        - westworld
        - how i met your mother
        - two and a half men
        - friends:
            exact: yes
tasks:
  delete-dups-tv-shows:
    assume_quality:
      h264: 1080p
    configure_series:
      from:
        filesystem: /mnt/storage-btrfs/media/tv-shows
    filesystem:
      recursive: True
      path:
        - /mnt/storage-btrfs/media/tv-shows
      retrieve: files
    if:
      - has_field('series_episode'):
          exec:
            on_output:
              for_undecided: echo {{series_name}} {{series_id}} {{quality}}  {{location}} >> `date +%y%m%d`.dups.out
  tv-sort:
    parsing:
      series: guessit
    filesystem:
      regexp: '.*.(avi|mkv|mp4)$'
      path:
        - /mnt/storage-btrfs/downloads/
      recursive: yes
      retrieve:
        - files
        - dirs
    template: [my-tv-shows]
    series:
      settings:
        agroup:
          parse_only: yes
    regexp:
      reject:
        - sample
      from: content_filename
    require_field: series_name
    accept_all: yes
    move:
      to: /mnt/storage-btrfs/media/tv-shows/{{series_name}}/Season {{series_season|pad(2)}}

  tv-search:
    exists_series: /mnt/storage-btrfs/media/tv-shows
    template: [my-tv-shows, downloads]
    discover:
      what:
        - next_series_episodes:
            from_start: yes
            backfill: yes
      from:
        - newznab:
            website: https://api.nzbplanet.net
            apikey:  <API>
            category: tv
        - newznab:
            website: https://simplynzbs.com
            apikey: <API>
            category: tv
        - piratebay:
            category: video
            sort_by: seeds
            url: https://zombay.org
      interval: 1 hour
```

**Comment by kfirufk** [comment]
i'm trying to understand the guessit parser to investigate this issue further.

so it seems that the error means that the guessit parser could not fetch the series name.

i just want to understand one thing. when I use the guessit parser does it change the variable names that are being detected from the series file ?

at https://github.com/guessit-io/guessit i saw the following example:

```
$ guessit "Treme.1x03.Right.Place,.Wrong.Time.HDTV.XviD-NoTV.avi"
For: Treme.1x03.Right.Place,.Wrong.Time.HDTV.XviD-NoTV.avi
GuessIt found: {
    "title": "Treme",
    "season": 1,
    "episode": 3,
    "episode_title": "Right Place, Wrong Time",
    "source": "HDTV",
    "video_codec": "Xvid",
    "release_group": "NoTV",
    "container": "avi",
    "mimetype": "video/x-msvideo",
    "type": "episode"
}
```

does it mean that it changes the detected variables names ?
for example instead of "series_name" is it called "title" now or the variable names keep their original name even when I use the guessit parser?

thanks

**Comment by luizoti** [comment]
Have you tried removing the "exact" options? In the tests I did the guessit was running normally, so much so that I'm using to move my movies.

Did you test disable guessit?

```
  MOVE:
    priority: 15
    disable:
      - seen
      - seen_info_hash
      - torrent_alive
      - retry_failed  
    parsing:
      movie: guessit     
    metainfo_movie: yes
    imdb_lookup: yes
    require_field: 
      - imdb_year
      - imdb_name
    filesystem:
      path:
        - 'E:\MOVIE_TEMP'
      recursive: yes  
      retrieve:  
        - files
        - dirs
      regexp: '.*\.(avi|mkv|mp4|m4v|iso)$'
    accept_all: yes
    move:
      to: 'D:\FILMES\{{imdb_name}} ({{imdb_year}})'
      rename: '{{imdb_name}} ({{imdb_year}})'      
    template: 
      - push5 

  MOVE2:
    priority: 20
    disable:
      - seen
      - seen_info_hash
      - torrent_alive
      - retry_failed    
    metainfo_series: yes
    thetvdb_lookup: yes
      # language: pt-br
    accept_all: yes
    require_field: 
      - series_name
      - tvdb_season
    filesystem:
      path:
        - 'E:\SERIES_TEMP'
      recursive: yes
      retrieve:
        - files
        - dirs
      regexp: '.*\.(avi|mkv|mp4|m4v|iso)$'
    move:
      to: 'D:\SERIES\{{series_name}}\Season {{tvdb_season}}'
      rename: '{{series_id}} - {{tvdb_ep_name}}'

```
