### ISSUE TITLE
BUG: Unhandled error in plugin metainfo_movie: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by effemmeffe** [Flexget/Flexget#2214]
### Expected behaviour:
All the movies from a letterboxd list are mirrored on a trakt list.

### Actual behaviour:
Some movies are fetched from the letterboxd list and then an error occour.

### Steps to reproduce:
Simply run the task a few times

#### Config:
The full congif is here: https://github.com/effemmeffe/flexget/blob/master/config.yml

The task that fails is this:

```
  letterboxd-to-trakt:
    disable: seen
    letterboxd:
      username: "{? letterboxd.user ?}"
      list: $LETTERBOXD-LIST
    sort_by: added
    accept_all: yes
    list_add:
      - trakt_list:
          account: "{? trakt.account ?}"
          username: "{? trakt.user ?}"
          list: $TRAKT-LIST

```
  
#### Log:
https://pastebin.com/hbwHdP4i

### Additional information:

- FlexGet version:
2.14.25

- Python version:
Python 2.7.15rc1

- Installation method:
pip

- Using daemon (yes/no):
yes

- OS and version:
Ubuntu 18.04.1 LTS

- Link to crash log:
https://pastebin.com/hbwHdP4i
