### ISSUE TITLE
flexget thinks www.descargas2020.com on title is a season

### ISSUE THREAD

**Issue by Aokromes** [Flexget/Flexget#2221]
### Expected behaviour:

it downloads torrents properly :)

### Steps to reproduce:
add this rss http://feeds.feedburner.com/descargas2020new
flexget execute
you will get:
REJECTED: `American Horror Story - Temporada 8  [HDTV 720p][Cap.804][V.O. Subt. Castellano][www.descargas2020.com]` by series plugin because season pack support is turned off
because flexget thinks s2020 is a season, maybe there is a way to ignore urls on titles?

#### Config:
```
tasks:
  series_sigo:
    rss:
      url: http://feeds.feedburner.com/descargas2020new
      link: link
    all_series: yes
    seen: local
    regexp:
      reject:
        - PCDVD
    accept_all: yes
    thetvdb_lookup: yes
    no_entries_ok: yes
    set:
      filename: "{{title|pathscrub}}.torrent"
    download: /home/flexget/torrent/
```
  
#### Log:
```
2018-10-09 23:48 VERBOSE  task          series_sigo     REJECTED: `Arma Letal - Temporada 3  [HDTV][Cap.301][Castellano][www.descargas2020.com]` by series plugin because season pack support is turned off
2018-10-09 23:48 VERBOSE  task          series_sigo     REJECTED: `American Horror Story - Temporada 8  [HDTV 720p][Cap.804][V.O. Subt. Castellano][www.descargas2020.com]` by series plugin because season pack support is turned off
```

### Additional information:

- FlexGet version: 2.15.1
- Python version: 2.7.13
- Installation method: i don't remember
- Using daemon (yes/no): no
- OS and version: debian 9 x64
- Link to crash log:
