### ISSUE TITLE
Incorrect timeframe plugin behaviour when loading items from an entry_list

### ISSUE THREAD

**Issue by andrey-yantsen** [Flexget/Flexget#2242]
### Expected behaviour:
The 1080p is downloaded

### Actual behaviour:
The plugin ignores 1080p and sees only 720p

### Steps to reproduce:
- Step 1: Add movies from rss http://rutor.info/rss.php?cat=7 to list movies_list

#### Config:
```
schedules:
  - tasks: ["download *"]
    interval:
      minutes: 15

web_server: yes

tasks:
  download good movies:
    entry_list: movies_list
    seen_movies:
      scope: local
    seen: local
    seen_info_hash: local
    timeframe:
      wait: 14 day
      on_reached: do_nothing
      target: 1080p
    priority: 5
    imdb:
      min_score: 6.3
      min_votes: 1000
      reject_genres:
        - documentary
        - musical
        - music
        - history
        - biography
        - war
    list_remove:
      - entry_list: movies_list
    download: /downloads
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2018-10-26 09:16 VERBOSE  task          download good movies REJECTED: `Incredibles 2 (2018) WEB-DL 720p от селезень | iTunes` by timeframe plugin because timeframe waiting
2018-10-26 09:16 VERBOSE  task          download good movies REJECTED: `Incredibles 2 (2018) WEB-DL 1080p от TeamHD | iTunes` by timeframe plugin because timeframe waiting
2018-10-26 09:16 INFO     timeframe     download good movies `incredibles 2 2018`: timeframe waiting for 321h:59min. Currently best is `Incredibles 2 (2018) WEB-DL 720p от селезень | iTunes`.
```

<details><summary>--dump output excerpt</summary>
720p:

```
title            : Incredibles 2 (2018) WEB-DL 720p от селезень | iTunes
url              : http://d.rutor.is/download.php?rss=661218
original_url     : http://d.rutor.is/download.php?rss=661218
accepted_by      : imdb
content-length   : 82000
content_files    : [Incredibles.2.2018.720p.WEB-DL.selezen.mkv]
content_size     : 4012.526089668274
description      : Мультипликация
filename         : [rutor.is]Incredibles.2.2018.720p.WEB-DL.selezen.mkv.torrent
id               : incredibles 2 2018
imdb_id          : tt3606756
quality          : 720p webdl
reason           : timeframe waiting
rejected_by      : timeframe
```

1080p:
```
title            : Incredibles 2 (2018) WEB-DL 1080p от TeamHD | iTunes
url              : http://d.rutor.is/download.php?rss=661219
original_url     : http://d.rutor.is/download.php?rss=661219
accepted_by      : imdb
content-length   : 90640
content_files    : [Incredibles.2.2018.1080p.WEB-DL.TeamHD.mkv]
content_size     : 4444.096870422363
description      : Мультипликация
filename         : [rutor.is]Incredibles.2.2018.1080p.WEB-DL.TeamHD.mkv.torrent
id               : incredibles 2 2018
imdb_id          : tt3606756
quality          : 1080p webdl
raw_title        : Суперсемейка 2 / Incredibles 2 (2018) WEB-DL 1080p от TeamHD | iTunes
reason           : timeframe waiting
rejected_by      : timeframe
```

</details>
</details>

### Additional information:

- FlexGet version: 2.17.5 (first time noticed on 2.17.0, but probably is here for long time)
- Python version: 3.5.3
- Installation method: pip3 install (+docker)
- Using daemon (yes/no): yes
- OS and version: Debian Stretch
