### ISSUE TITLE
`pushbullet`: Account has not been used for over a month. 

### ISSUE THREAD

**Issue by chewy74** [Flexget/Flexget#2244]
### Expected behaviour: 
Push notification to pushbullet app when an item is approved and downloaded 

### Actual behaviour:
No notification is sent 

### Steps to reproduce:
- Step 1: ...
Run task and wait for a match 

#### Config:
```
web_server: yes
variables: secret.yml
templates:
  global:
    no_entries_ok: yes
    notify:
      abort:
        via:
          - pushbullet:
              api_key: '{? pushbullet.api ?}'



##################################################################
#    DOWNLOAD NOTIFICATION TEMPLATE
##################################################################




  movie_notify:
    imdb_lookup: yes
    notify:
      entries:
        title: "{{imdb_name}}"
        message: "{{imdb_url}}\nIMDB SCORE: {{imdb_score}}\nSize: {{content_size}}MB\n\n {{imdb_plot_outline}}"
        via:
          - pushbullet:
              api_key: '{? pushbullet.api ?}'


#################################################################
#    TORRENT CLIENT
##################################################################
  
  torrent_client:
    transmission:
      enabled: yes
      host: localhost
      port: xxxx
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'




##################################################################
#   MOVIE TEMPLATE
##################################################################

  movie:
    tmdb_lookup: yes 
    proper_movies: no
    content_size:
      max: 5000
      strict: no
    content_filter: 
      reject:
        - '*.zip'
        - '*.wmv'
        - '*.wma'
        - '*[cC]odec*'
        - '*[rR]eadme*'
    exists_movie:
      - /media/xxxxxx/xxxxxxx/Videos/Movies



#################################################################
#    FILTERS TEMPLATES
##################################################################

  filters:
    regexp:
      reject:
        - \bmsd\b: {from: title}
        - \bgreek\b: {from: title}
        - \bgerman\b: {from: title}
        - \bfrench\b: {from: title}
        - \brussian\b: {from: title}
        - \bswedish\b: {from: title}
        - \bspanish\b: {from: title}
        - \bhindi\b: {from: title}
        - \barabic\b: {from: title}
        - \bitalian\b: {from: title}
        - \bpolish\b: {from: title}
        - \bromanian\b: {from: title}
        - \bdutch\b: {from: title}
        - \bczech\b: {from: title}
        - \bturkish\b: {from: title}
        - \brmvb\b: {from: title}
#        - \bkorean\b: {from: title}
        - \bwmv\b: {from: title}
#        - (s|d)ub(s|bed)?\b: {from: title}
        - \bFRENCH\b: {from: title}
        - \bSPANiSH\b: {from: title}
        - \bLatino\b: {from: title}
        - \btrailer\b: {from: title}
        - \bHDcam\b: {from: title} 
        - \bR5\b: {from: title}
        - \b3-?D\b: {from: title}                             # I don't have any 3D displays
        - \btrailer\b: {from: title}                          # I've gotten a few trailers that matched as movies. VERY annoying
        - \bTS\b: {from: title}
        - \bCam\b: {from: title}
        - '{C_P}': {from: title}                              # The following are groups with poor quality releases
        - TrTd TeaM: {from: title}
        - \[TNTVillage\]: {from: title}
#        - \bFLEET\b: {from: title}
        - \b0SEC\b: {from: title}
        - \[facepalm\]: {from: title}
        - FASTSUB: {from: title}
        - VOSTFR: {from: title}
        - Subtitulado: {from: title}
        - \bNORDiC\b: {from: title}
        - \biPad\b: {from: title}
#        - \b(ita|ger|fra|spa|swe|nor|nordic|fr|kor|uk|esp|nl|pl|spanish)\b: {from: title}
        - \bR6\b: {from: title}
        - \bTemporada\b: {from: title}
        - \bDual\b: {from: title}
        - \bTamil\b: {from: title}
        - \bJapanese\b: {from: title}
        - \bJajji!\b: {from: title}
        - \bdragons.den.(ca|uk)\b: {from: title}
        - \bx265\b: {from: title}
        - \Telugu\b: {from: title}
#        - \HC\b: {from: title}
        - \b480p\b: {from: title}



#################################################################
#    TRACKER FILTERS TEMPLATES
##################################################################

  public:
    imdb_lookup: yes
    set:
      main_file_only: yes
      maxupspeed: 50
      ratio: .00001
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*[sS]ample*'
        - '*.txt'
        - '*.iso' 


##################################################################
#    TASK SCHEDULES
##################################################################


schedules:


  - tasks: [IMDB]
    interval:
      minutes: 30


  - tasks: [movies, trash]
    interval:
      hours: 1


##################################################################
#    TASKS 
##################################################################


tasks:


  IMDB:
    imdb_list:
      login: '{? imdb.usr ?}'
      password: '{? imdb.pwd ?}'
      list: watchlist
    accept_all: yes
    seen: 
      fields: [title]
    list_add:
      - movie_list: vic_movies
    priority: 2



  movies:
    priority: 5
    template:
      - movie
      - public
      - movie_notify
      - torrent_client
      - filters
    discover:
      release_estimations: 
        optimistic: 60 days
      what:
        - movie_list: vic_movies
      from:
        - rarbg:
            category: [14, 15, 16, 17, 21, 22, 42, 44, 45, 46, 47, 48]
        - 1337x: yes
#        - piratebay:
#            category: movies
    interval: 1 hour
    quality: hdrip+
    list_match:
      from:
        - movie_list: vic_movies
    list_add:
      - entry_list: downloaded_movies
    torrent_alive: 10
    verify_ssl_certificates: no
    set:
      path: /media/xxxxxx/xxxxxxx/Videos/Movies/



```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2018-11-03 15:20 DEBUG    notify        movies          Sending a notification to `pushbullet`
2018-11-03 15:20 DEBUG    utils.requests movies          POSTing URL https://api.pushbullet.com/v2/pushes with args () and kwargs {'headers': {u'Content-Type': u'application/json', u'Accept': u'application/json', u'Authorization': 'Basic xxxxxxxxxxxxxxx==', u'User-Agent': u'Flexget'}, 'json': {u'body': u"https://www.imdb.com/title/tt6023386/nIMDB SCORE: 5.2nSize: 713.566264153MBnn When a capricious young author hiding a dark secret returns home for her brother's graduation, she finds herself haunted by the past and tormented by grim night terrors.", u'type': u'note', u'title': u'All Light Will End'}, 'data': None, u'timeout': 30}
2018-11-03 15:20 WARNING  notify        movies          Error while sending notification to `pushbullet`: Account has not been used for over a month.

```
</details>

### Additional information:

- FlexGet version: 2.17.7
- Python version: Python 2.7.13
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Raspberry Pi stretch 
- Link to crash log:
