### ISSUE TITLE
descargas2020 plugin broken

### ISSUE THREAD

**Issue by Aokromes** [Flexget/Flexget#2280]
### Expected behaviour:
it downloads torrent properly.

### Steps to reproduce:
add this rss http://feeds.feedburner.com/descargas2020new
flexget execute
you will get:
2018-12-20 07:45 WARNING  urlrewriter   series_sigo     URL rewriting descargas2020 failed: Unable to locate torrent ID from url http://descargas2020.com/descargar/serie-en-hd/9-1-1/temporada-2/capitulo-10/
2018-12-20 07:45 ERROR    entry         series_sigo     Failed 9-1-1 - Temporada 2  [HDTV 720p][Cap.210][AC3 5.1 Castellano][www.pctnew.com]9-1-1 - Temporada 2 [HDTV 720p][Cap.210][AC3 5.1 Castellano][www.pctnew.com] (None)
2018-12-20 07:45 INFO     task          series_sigo     Rerunning the task in case better resolution can be achieved.

#### Config:

```
tasks:
  series_sigo:
    rss:
      url: http://feeds.feedburner.com/descargas2020new
      link: link
    all_series: yes
    seen: local
    regexp:
      reject:
        - PCDVD
    accept_all: yes
    thetvdb_lookup: yes
    no_entries_ok: yes
    set:
      filename: "{{title|pathscrub}}.torrent"
    download: /home/flexget/torrent/
```
  
#### Log:

2018-12-20 07:45 WARNING  urlrewriter   series_sigo     URL rewriting descargas2020 failed: Unable to locate torrent ID from url http://descargas2020.com/descargar/serie-en-hd/9-1-1/temporada-2/capitulo-10/
2018-12-20 07:45 ERROR    entry         series_sigo     Failed 9-1-1 - Temporada 2  [HDTV 720p][Cap.210][AC3 5.1 Castellano][www.pctnew.com]9-1-1 - Temporada 2 [HDTV 720p][Cap.210][AC3 5.1 Castellano][www.pctnew.com] (None)
2018-12-20 07:45 INFO     task          series_sigo     Rerunning the task in case better resolution can be achieved.

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 2.17.20
- Python version: 2.7.13
- Installation method: i don't remember
- Using daemon (yes/no): no
- OS and version: debian 9 x64
- Link to crash log:
