### ISSUE TITLE
kodi_library plugin does not allow localhost, only full address http://1.2.3.4

### ISSUE THREAD

**Issue by zilexa** [Flexget/Flexget#2285]
This is just a minor one, when flexget and kodi are installed on the same device.
works (only with http://):
```
    kodi_library:
      action: clean
      category: video
      url: http://192.168.1.10
      port: 8080    
```
does not work:
```
    kodi_library:
      action: clean
      category: video
      url: localhost
      port: 8080
```
other plugins like transmission allow `localhost` instead of full address.
