### ISSUE TITLE
Dupe Notifications "(pushover, pushbullet, email,etc)

### ISSUE THREAD

**Issue by xInsertx** [Flexget/Flexget#2316]
This randomly started happening about 2 weeks ago. I've reset db and update to the latest version (using pip), still happens.

### Expected behaviour:
Only send a single notification for each entry.
### Actual behaviour:
Flexget seems to be firing it off twice for each notifies plugin causing duplicates. This appears to be happening 90% of the time, when a single item is added. If flexget added multiple only 1 notification is sent per plugin (ie: 1 for pushover, 1 for pushbullet).

#### Config:
```
schedules:
  - tasks: '*'
    interval:
      minutes: 10
variables: variables.yaml
tasks:
  nyaa:
    rss:
      url: "https://nyaa.si/?page=rss&q=720p&c=0_0&f=0&u=HorribleSubs"
      all_entries: no
    notify:
      entries:
        title: "Flexget - Episode Downloading"
        message: "{{series_name}} {{series_id}}" 
        via:
          - pushbullet:
              api_key: '{? credentials.pushbullet.api ?}'
          - pushover:
              user_key: '{? credentials.pushover.user ?}'
              api_key: '{? credentials.pushover.api ?}'
    series:
      ongoing:
        - "One Piece"
        - "Black Clover"
        - "Fairy Tail Final Season"
      fall_2018:
        - "Toaru Majutsu no Index III"
        - "Sword Art Online - Alicization"
        - "Tensei Shitara Slime Datta Ken"
      winter_2019:
        - "Mob Psycho 100 S2"
        - "Tate no Yuusha no Nariagari"
        - "Yakusoku no Neverland"
        - "Go-toubun no Hanayome"
        - "Kaguya-sama wa Kokurasetai"
        - "Doukyonin wa Hiza"
    transmission:
      host: '{? credentials.transmission.host ?}'
      port: '{? credentials.transmission.port ?}'
      username: '{? credentials.transmission.user ?}'
      password: '{? credentials.transmission.pass ?}'
      ratio: 0
    clean_transmission:
      host: '{? credentials.transmission.host ?}'
      port: '{? credentials.transmission.port ?}'
      username: '{? credentials.transmission.user ?}'
      password: '{? credentials.transmission.pass ?}'
      tracker: nyaa
      preserve_tracker: '{? settings.tracker_preserve ?}'
      delete_files: no
```
  
#### Debug Log:
<details>
Still trying to capture it happening
</details>

### Additional information:

- FlexGet version: was running 2.17.24, now 2.18.12
- Installation method: PIP
- Using daemon (yes/no): Yes (with reload arg)
- OS and version: FreeBSD 11.2
