### ISSUE TITLE
descargas2020 plugin broken (again)

### ISSUE THREAD

**Issue by Aokromes** [Flexget/Flexget#2335]
### Expected behaviour:
it downloads torrent properly.

### Steps to reproduce:
add this rss http://feeds.feedburner.com/descargas2020new
flexget execute
you will get:
2019-02-09 16:00 INFO     download      series_sigo     Downloading: Single Parents (Proper) - Temporada 1  [HDTV 720p][Cap.109][AC3 5.1 Castellano][]
2019-02-09 16:00 ERROR    entry         series_sigo     Failed Single Parents (Proper) - Temporada 1  [HDTV 720p][Cap.109][AC3 5.1 Castellano][] (Unexpected html content received from https://descargas2020.com/descargar/serie-en-hd/single-parents/temporada-1/capitulo-09/ - maybe a login page?)
2019-02-09 16:00 INFO     task          series_sigo     Rerunning the task in case better resolution can be achieved.

#### Config:

```
tasks:
  series_sigo:
    rss:
      url: http://feeds.feedburner.com/descargas2020new
      link: link
    all_series: yes
    seen: local
    regexp:
      reject:
        - PCDVD
    accept_all: yes
    thetvdb_lookup: yes
    no_entries_ok: yes
    set:
      filename: "{{title|pathscrub}}.torrent"
    download: /home/flexget/torrent/
```
  
#### Log:

2019-02-09 16:00 INFO     download      series_sigo     Downloading: Single Parents (Proper) - Temporada 1  [HDTV 720p][Cap.109][AC3 5.1 Castellano][]
2019-02-09 16:00 ERROR    entry         series_sigo     Failed Single Parents (Proper) - Temporada 1  [HDTV 720p][Cap.109][AC3 5.1 Castellano][] (Unexpected html content received from https://descargas2020.com/descargar/serie-en-hd/single-parents/temporada-1/capitulo-09/ - maybe a login page?)
2019-02-09 16:00 INFO     task          series_sigo     Rerunning the task in case better resolution can be achieved.

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 2.19.5
- Python version: 2.7.13
- Installation method: i don't remember
- Using daemon (yes/no): no
- OS and version: debian 9 x64
- Link to crash log:
