### ISSUE TITLE
2 tasks with seen local can "see" each other

### ISSUE THREAD

**Issue by Shadok** [Flexget/Flexget#2352]
Hello,

I am running flexget 2.17.23 (upgraded now to 2.20.13).

I have 2 tasks, allowing me to get some tv-shows in 720p AND 1080p (my rss will provide entries for my show in both format for some of them).

But once the 720p has been downloaded by tv-shows-720, tv-shows-1080 says it has already been seen and doesn't download the 1080p one.

Isn't local supposed to isolate seen entries between tasks ?

```
tasks:
  tv-shows-720:
    rss:
      url: 'rss'
    all_series: yes
    verify_ssl_certificates: no
    magnets: yes
    seen: local
    quality: 720p
  tv-shows-1080:
    rss:
      url: 'rss'
    all_series: yes
    verify_ssl_certificates: no
    magnets: yes
    seen: local
    quality: 1080p
```

Thanks.
