### ISSUE TITLE
Lostfilm plugin is broken after implementing DDoS protection on site

### ISSUE THREAD

**Issue by Karlson2k** [Flexget/Flexget#2371]
### Expected behaviour:
Lostfilm new series download
### Actual behaviour:
```2019-04-24 12:58 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=136&e=21&s=9
2019-04-24 12:58 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=258&e=19&s=4
2019-04-24 12:58 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=214&e=17&s=6
```
### Steps to reproduce:
run flexget with config in daemon mode

#### Config:
```
schedules:
  - tasks: 'lostfilm-dwnld'
    interval:
      minutes: 3
  - tasks: 'clean-torr'
    interval:
      minutes: 15

templates:
  tv-show-std:
    series:
      settings:
        '720p':
          identified_by: ep
        '1080p':
          identified_by: ep
    transmission:
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'
      path: '/the path/{{series_name|re_replace("^[ ]*((The) )(.+?)[ ]*$","\\3, \\2")|re_replace("[<>:\"/\\\\|?*]+","-")|re_replace("^[. ]+|[. ]+$", "")}}/{{ series_season | pad(2) }}'
    exec:
      on_exit:
        for_accepted: >
          /the_path2/new_ep_not.sh
          "{{series_name}}" "{% if series_name_rus is defined %}{{series_name_rus}}{%endif%}"
          "{{series_season}}" "{{series_episode}}"
          "{{series_id}}"
          "{% if episode_name_eng is defined %}{{episode_name_eng}}{%endif%}"
          "{% if episode_name_rus is defined %}{{episode_name_rus}}{%endif%}"
          "{{content_size}}"

tasks:
  clean-torr:
    from_transmission:
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'
    disable: [seen, seen_info_hash]
    if:
      - transmission_progress < 100: reject
      - transmission_date_done + timedelta(minutes=40) > now: reject
      - transmission_date_added + timedelta(minutes=95) < now: accept
    transmission:
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'
      action: remove
  lostfilm-dwnld:
    version_checker: yes
    headers:
      cookie: '{? lostfilm.cookie1 ?}'
      cookie: '{? lostfilm.cookie2 ?}'
      cookie: '{? lostfilm.cookie3 ?}'
    lostfilm: yes
    template: tv-show-std
    series:
      '720p':
        - 'Better Call Saul'
      '1080p':
        - 'Game of Thrones'
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=258&e=19&s=4
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=214&e=17&s=6
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=425&e=8&s=1
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=424&e=3&s=1
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=421&e=4&s=1
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=422&e=3&s=1
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=65&e=19&s=14
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=412&e=10&s=1
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 WARNING  details       lostfilm-dwnld  Task didn't produce any entries. This is likely due to a mis-configured or non-functional input.
апр 24 13:40:18 headless-srv flexget[25982]: 2019-04-24 13:40 WARNING  details       clean-torr      Task didn't produce any entries. This is likely due to a mis-configured or non-functional input.
```
</details>

### Additional information:

- FlexGet version: 2.20.21
- Python version: Python 2.7.15rc1
- Installation method: pip install
- Using daemon (yes/no): yes
- OS and version: Ubuntu 18.04.2 LTS

@Danfocus Maybe remove additional info download and use direct RSS feed parsing only? Or make additional info download optional.

**Comment by Danfocus** [comment]
> ### Expected behaviour:
> Lostfilm new series download
> 
> ### Actual behaviour:
> ```
> 2019-04-24 12:58 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=258&e=19&s=4
> 2019-04-24 12:58 ERROR    lostfilm      lostfilm-dwnld  Could not connect to redirect url: 503 Server Error: Service Temporarily Unavailable for url: http://www.lostfilm.tv/v_search.php?c=214&e=17&s=6
> ```
> ### Steps to reproduce:
> run flexget with config in daemon mode
> 
> #### Config:
> ```
> schedules:
>   - tasks: 'lostfilm-dwnld'
>     interval:
>       minutes: 3
>   - tasks: 'clean-torr'
>     interval:
>       minutes: 15
> 
> templates:
>   tv-show-std:
>     series:
>       settings:
>         '720p':
>           identified_by: ep
>         '1080p':
>           identified_by: ep
>     transmission:
>       username: '{? transmission.usr ?}'
>       password: '{? transmission.pwd ?}'
>       path: '/the path/{{series_name|re_replace("^[ ]*((The) )(.+?)[ ]*$","\\3, \\2")|re_replace("[<>:\"/\\\\|?*]+","-")|re_replace("^[. ]+|[. ]+$", "")}}/{{ series_season | pad(2) }}'
>     exec:
>       on_exit:
>         for_accepted: >
>           /the_path2/new_ep_not.sh
>           "{{series_name}}" "{% if series_name_rus is defined %}{{series_name_rus}}{%endif%}"
>           "{{series_season}}" "{{series_episode}}"
>           "{{series_id}}"
>           "{% if episode_name_eng is defined %}{{episode_name_eng}}{%endif%}"
>           "{% if episode_name_rus is defined %}{{episode_name_rus}}{%endif%}"
>           "{{content_size}}"
> 
> tasks:
>   clean-torr:
>     from_transmission:
>       username: '{? transmission.usr ?}'
>       password: '{? transmission.pwd ?}'
>     disable: [seen, seen_info_hash]
>     if:
>       - transmission_progress < 100: reject
>       - transmission_date_done + timedelta(minutes=40) > now: reject
>       - transmission_date_added + timedelta(minutes=95) < now: accept
>     transmission:
>       username: '{? transmission.usr ?}'
>       password: '{? transmission.pwd ?}'
>       action: remove
>   lostfilm-dwnld:
>     version_checker: yes
>     headers:
>       cookie: '{? lostfilm.cookie1 ?}'
>       cookie: '{? lostfilm.cookie2 ?}'
>       cookie: '{? lostfilm.cookie3 ?}'
>     lostfilm: yes
>     template: tv-show-std
>     series:
>       '720p':
>         - 'Better Call Saul'
>       '1080p':
>         - 'Game of Thrones'
> ```
> #### Log:
> (click to expand)
> ### Additional information:
> * FlexGet version: 2.20.21
> * Python version: Python 2.7.15rc1
> * Installation method: pip install
> * Using daemon (yes/no): yes
> * OS and version: Ubuntu 18.04.2 LTS
> 
> @Danfocus Maybe remove additional info download and use direct RSS feed parsing only? Or make additional info download optional.

Try using Cloudflare Scraper plugin
https://flexget.com/Plugins/cfscraper

**Comment by Karlson2k** [comment]
I solved it by replacing scraping with 'lostfilm' plugin with simple configuration.
Actually line
```` yml
    lostfilm: yes
````
was replaced with
```` yml
    headers:
      cookie: 'uid=9999999;usess=9999999999999999999999aaaaaaaaaa'
    rss:
      url: http://retre.org/rssdd.xml
    manipulate:
      - series_name_rus:
          from: title
          extract: '^(.+) \(.+\)\. .+ \(S\d\dE\d\d\) \[.+\]$'
      - episode_name_rus:
          from: title
          extract: '^.+ \(.+\)\. (.+) \(S\d\dE\d\d\) \[.+\]$'
      - title:
          replace:
            regexp: '\[SD\]$'
            format: '[480p]'
      - title:
          replace:
            regexp: '\[MP4\]$'
            format: '[720p]'
      - title:
          replace:
            regexp: '^.+ \((.+)\)\. .+ \((S\d\dE\d\d)\) \[(.+)\]$'
            format: '\1.\2.\3'
````
which gives exactly the same result except `series_name_eng` is not populated and processing is **much** faster.
Also it uses single small HTTP GET instead of ~15 large HTTP GETs for every check.
