### ISSUE TITLE
descargas 2020 broken (again)

### ISSUE THREAD

**Issue by Aokromes** [Flexget/Flexget#2377]
### Expected behaviour:
it downloads torrent properly.

### Steps to reproduce:
add this rss http://feeds.feedburner.com/descargas2020new
flexget execute
you will get:
2019-04-28 23:00 WARNING  urlrewriter   series_sigo     URL rewriting descargas2020 failed: Unable to locate torrent ID from url http://descargas2020.com/descargar-torrent/121574_-1556477420-55-pasos--blurayrip/
2019-04-28 23:00 ERROR    entry         series_sigo     Failed 55 Pasos  [BluRay Rip][AC3 2.0 Castellano][2019][] (None)

#### Config:

```
tasks:
  series_sigo:
    rss:
      url: http://feeds.feedburner.com/descargas2020new
      link: link
    all_series: yes
    seen: local
    regexp:
      reject:
        - PCDVD
    accept_all: yes
    thetvdb_lookup: yes
    no_entries_ok: yes
    set:
      filename: "{{title|pathscrub}}.torrent"
    download: /home/flexget/torrent/
```
  
#### Log:

2019-04-28 23:00 WARNING  urlrewriter   series_sigo     URL rewriting descargas2020 failed: Unable to locate torrent ID from url http://descargas2020.com/descargar-torrent/121574_-1556477420-55-pasos--blurayrip/
2019-04-28 23:00 ERROR    entry         series_sigo     Failed 55 Pasos  [BluRay Rip][AC3 2.0 Castellano][2019][] (None)

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 2.20.23
- Python version: 2.7.13
- Installation method: i don't remember
- Using daemon (yes/no): no
- OS and version: debian 9 x64
- Link to crash log:
