### ISSUE TITLE
Series name_regexp is broken

### ISSUE THREAD

**Issue by roeebar** [Flexget/Flexget#2400]
### Expected behaviour:
`name_regexp` in the series plugin should try matching the received entry using regular expression

### Actual behaviour:
It works only when the received title begins with the actual series title (i.e. "BBC.Series Title" will not work, but "Series Title.BBC" will work for `name_regexp: Series Title`).

### Steps to reproduce:
`flexget --test execute name_regexp`
See config below. 

#### Config:
```
  tasks:
    name_regexp:
      mock:
        - title: the show s09e05 hdtv
      series:
        - show:
            name_regexp: show
```

 ### Additional information:
It looks like this commit broke it:
https://github.com/Flexget/Flexget/commit/2b6326c985918458376c441cd114be63ff865853

In this commit it changed to use the first letter of the received entry and the series name to decide whether to attempt parsing. This doesn't take into account that regular expression can match on any word within the entry.

- FlexGet version: Latest (2.21.2)
- Python version: 2.7
- Installation method: freebsd pkg
- Using daemon (yes/no): both
- OS and version: Freebsd
