### ISSUE TITLE
[trakt_list] strip_dates does not work with language

### ISSUE THREAD

**Issue by c4tz** [Flexget/Flexget#2417]
### Expected behaviour:

I noticed a small bug while trying to set up Flexget for the first time today. If one tries to use `language` in conjunction with `strip_dates` on a `trakt_list` with the type `movies`, the title will be the english/default one without the year.

### Actual behaviour:

As you can see in the log, the entry's title is just `Avatar` instead of the german (and correctly translated) `Avatar - Aufbruch nach Pandora`. The date/year is stripped, but the title is "reset".

### Steps to reproduce:
- Step 1: `flexget execute --discover-now --no-cache`

#### Config:
```yaml
tasks:
  download_movies:
    discover:
      what:
        - trakt_list:
            account: someuser
            list: somelist
            type: movies
            language: de
            strip_dates: yes
      from:
        - someplugin
```
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-06-16 19:39 VERBOSE  trakt_list    download_movies Found `de` translation for movie `Avatar`: Avatar - Aufbruch nach Pandora
2019-06-16 19:39 VERBOSE  discover      download_movies Discovering 1 titles ...
2019-06-16 19:39 INFO     discover      download_movies Ignoring interval because of --discover-now
2019-06-16 19:39 VERBOSE  discover      download_movies Searching for `Avatar` with plugin `someplugin` (1 of 1)
```
</details>

### Additional information:

- FlexGet version: 2.20.27
- Python version: 3.7.3
- Installation method: AUR package
- Using daemon (yes/no): no
- OS and version:  Arch Linux x86_64 @ Linux Kernel 5.1.7

In general, I'd like to be able to format the entry title generated by `trakt_list` myself (not quite sure if thats possible already, but I didn't find examples or documentation about this), so that I can for example still pass the year to my search plugin, but without parentheses, e.g: `Somemovie 2001` instead of the "hardcoded" `Somemovie (2001)`

But this I just a wild idea I had and has nothing to do with this issue. ;)

PS: You might want to consider to add `yaml` syntax highlighting to the issue template, so that the given configs are better readable.
