### ISSUE TITLE
Crash when using anidb_list

### ISSUE THREAD

**Issue by christian-0s** [Flexget/Flexget#2418]
### Expected behaviour:
Flexget should get series from anidb wishlist

### Actual behaviour:
An error message appears and no serie title has been retrieved from wishlist

### Steps to reproduce:
- Step 1: configure flexget to use anidb_list plugin, then run it

#### Config:
```yaml
# define templates to use into our tasks
templates:
  global:
    # default config.yml
    plugin_priority:
      headers: 250
    headers:
      User-Agent: "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:33.0) Gecko/20100101 Firefox/33.0"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      Accept-Charset: "utf-8;q=0.7,*;q=0.3"
      Accept-Language: "it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4"
      Cache-Control: "max-age=0"
      Connection: "keep-alive"
      Cookie: "uid=94769971; pass=878ef42be543608524be5a98ef1b22e52300619d; authKey=430f8d902a308ef495d0f7a9bb783361"

    # Make there's 10 GB free before adding more downloads
    free_space:
      path: /media/Dati
      space: 10000
    # Make sure all filenames are Windows safe (for samba)
    pathscrub: windows

    regexp:
      reject_excluding:
      - (HorribleSubs|Erai-raws|BakedFish|DeadFish|Mirrored|"Non Nobis Translate")

  # configuration of transmission
  # -> each accepted feed item will be piped to transmission
  # read doc: http://flexget.com/wiki/Plugins/transmission
  transmissionrpc:
    transmission:
      host: localhost
      port: 9091
      username: REMOVED
      password: REMOVED
      ratio: 3.0
      # define a path to store our files
      path: /media/Dati/plexmedia
      main_file_only: yes
      include_subs: yes
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*.txt'
 
  # configure anime template
  anime:
    # read doc: http://flexget.com/wiki/Plugins/exists_series
    exists_series:
      # define a path to store our files
      path: '/media/Dati/plexmedia/{{series_name}}/'    

    configure_series:
      from:
        anidb_list:
          user_id: 134144
          type: shows
    quality: 1080p
    set:
      path: '/media/Dati/plexmedia/{{series_name}}/'
      propers: no
tasks:
  animetosho:
    # define our rss url
    rss:
      url: https://feed.animetosho.org/rss2
    no_entries_ok: yes
    template:
      - transmissionrpc
      - anime

  anidex:
    # define our rss url
    rss:
      url: https://anidex.info/rss/?cat=1&lang_id=1
    verify_ssl_certificates: no
    no_entries_ok: yes
    template:
      - transmissionrpc
      - anime

  acgnx:
    rss:
      url: https://www.acgnx.se/rss-sort-2.xml
    no_entries_ok: yes
    template:
      - transmissionrpc
      - anime

# schedules
# Used to specify interval to execute our tasks
# '*' means every task
schedules:
  - tasks: '*'
    interval:
      minutes: 30

web_server:
  bind: 0.0.0.0 
  port: 3539
  web_ui: yes
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2019-07-06 07:22 WARNING  configure_series anidex          Input anidb_list did not return anything
2019-07-06 07:22 CRITICAL task          acgnx           BUG: Unhandled error in plugin configure_series: u'pass'
2019-07-06 07:22 CRITICAL manager       acgnx           An unexpected crash has occurred. Writing crash report to /home/chris
tian/.flexget/crash_report.2019.07.06.072212852522.log. Please verify you are running the latest version of flexget by using 
"flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currentl
y using version 2.21.10
2019-07-06 07:22 WARNING  task          acgnx           Aborting task (plugin: configure_series)
```
</details>

### Additional information:

- FlexGet version: 2.21.10
- Python version: 2.7.15rc1
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: ARMBIAN 5.73 stable Ubuntu 18.04.2 LTS 4.4.174-rockchip64
- Link to crash log: [crash_report.2019.07.06.072212852522.log](https://github.com/Flexget/Flexget/files/3364643/crash_report.2019.07.06.072212852522.log)
