### ISSUE TITLE
imdb_list 'Login to IMDB failed. Check your credentials.'

### ISSUE THREAD

**Issue by luizoti** [Flexget/Flexget#2421]
### Actual behaviour:

2019-07-19 00:15 WARNING  utils                         Error during input plugin imdb_list: Login to IMDB failed. Check your credentials.

### Steps to reproduce:
- Step 1: ...
flexget execute --no-cache --discover-now --task FILMES-IMDB

#### Config:
```
  FILMES-IMDB:
    priority: 8    
    imdb_lookup: yes    
    exists_movie:
      path:
        - '/media/luiz/HD/MIDIA/FILMES/'
        - '/media/luiz/HD/TORRENTS'
        - '/media/luiz/HD/.FLEXGET/MOVIE_TEMP'
        - '/media/luiz/HD/.FLEXGET/BAIXANDO'
      type: files
      allow_different_qualities: better
      lookup: imdb
    discover:
      release_estimations:
        optimistic: 30 days        
      what:
        - imdb_list:
            login: *******
            password: *******
            list: FilmesParaBaixar
            force_language: pt-br # Optional - Force Specified Language
      from:
        - piratebay:
            sort_by: seeds
            # url: https://thepiratebay.asia
            # url: https://baypirateproxy.org/       
        - 1337x:
            order_by: seeders
        - rarbg:
            min_seeders: 5
    convert_magnet:
      timeout: 40 seconds
    torrent_alive:
      min_seeds: 5
      reject_for: 5 hour
    quality: 720p+
    list_match:
      from:
        - imdb_list:
            login: *******
            password: *******
            list: FilmesParaBaixar
            force_language: pt-br # Optional - Force Specified Language
      remove_on_match: no            
      single_match: yes
    list_remove:
      - imdb_list:
          login: *******
          password: *******
          list: FilmesParaBaixar
          force_language: pt-br # Optional - Force Specified Language
    list_add:
      - trakt_list:
          username: *******
          account: ******* # required if list is not public
          list: watchlist
          type: movies     
    deluge:
      label: "FILMES"
      path: '/media/luiz/HD/.FLEXGET/BAIXANDO/'
      content_filename: '{{imdb_name|replace(":","")}} ({{imdb_year|replace(":","")}})/{{imdb_name|replace(":","")}} ({{imdb_year|replace(":","")}})'
      move_completed_path: '/media/luiz/HD/MIDIA/FILMES/'
    template:
      - MOVIE-NORMALIZER
      - GERAL
      - DELUGE
      - push1
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 2.21.14
- Python version: Python 2.7.15+
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Kubuntu 18.04.02
- Link to crash log:

**Comment by snickers2k** [comment]
not a bug. it's IMDb API limitations .. better use trakt instead.

Altough i think a good workaround solution would be the .csv-export of imdb-lists.
https://www.imdb.com/list/ls074762520/export?ref_=nmls_exp

**Comment by luizoti** [comment]
That's the problem, I already use the layout, but I'm Brazilian, and the movies are too, the problem is, businesses are searched via trakt, are searched with English, but it's almost impossible to find BR movies with title In English, IMDB won the show the original title in BR and flexget.

I'll check this CSV scheme.

**Comment by snickers2k** [comment]
use
```
trakt_lookup:
  language: br
```

**Comment by luizoti** [comment]
I will try, look for something like this on the wiki and the nearest was using imdb.

**Comment by luizoti** [comment]
I tested it, but `trakt_lookup` doesn't seem to support the `language:` option.

`trakt_list` with the `language:` option also cannot search with the correct BR title.

`Lisbela and the Prisoner (2003)` should be in BR: `Lisbela e o Prisioneiro (2003)`


```

2019-08-02 14:22 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2019-08-02 14:22 VERBOSE  trakt_list    FILMES-IMDB     Retrieving `movies` list `Brasil`
2019-08-02 14:22 WARNING  trakt_list    FILMES-IMDB     No translation data returned from trakt for movie Lisbela and the Prisoner (2003).
2019-08-02 14:22 VERBOSE  discover      FILMES-IMDB     Discovering 1 titles ...
2019-08-02 14:22 INFO     discover      FILMES-IMDB     Ignoring interval because of --discover-now
2019-08-02 14:22 VERBOSE  api_bluray    FILMES-IMDB     Searching from blu-ray.com `Lisbela and the Prisoner`
2019-08-02 14:22 VERBOSE  discover      FILMES-IMDB     Searching for `Lisbela and the Prisoner (2003)` with plugin `piratebay` (1 of 1)
2019-08-02 14:22 VERBOSE  discover      FILMES-IMDB     Searching for `Lisbela and the Prisoner (2003)` with plugin `1337x` (1 of 1)
2019-08-02 14:22 VERBOSE  discover      FILMES-IMDB     Searching for `Lisbela and the Prisoner (2003)` with plugin `rarbg` (1 of 1)
2019-08-02 14:22 VERBOSE  discover      FILMES-IMDB     Searching for `Lisbela and the Prisoner (2003)` with plugin `nyaa` (1 of 1)
2019-08-02 14:22 VERBOSE  discover      FILMES-IMDB     Searching for `Lisbela and the Prisoner (2003)` with plugin `limetorrents` (1 of 1)
2019-08-02 14:23 VERBOSE  details       FILMES-IMDB     Produced 30 entries.
```

**Comment by snickers2k** [comment]
```
  ######################################## Movie-Global
  movies_lookup:
    plugin_priority:
      manipulate: 255       # manipulate must fix the titles before metainfo_series.
    metainfo_movie: yes
    tmdb_lookup:
      language: de
    imdb_lookup: yes
    trakt_lookup:
      account: '{? trakt.acc ?}'
#    rottentomatoes_lookup: yes #Buggy - 403 Client Error: Forbidden
  ######################################## Series-Global
  series_lookup:
    plugin_priority:
      manipulate: 255       # manipulate must fix the titles before metainfo_series.
    metainfo_series: yes
    thetvdb_lookup:
      language: de
    trakt_lookup:
      account: '{? trakt.acc ?}' 
    set:
      tvdb_language: de

```

> 2019-08-02 14:22 WARNING  trakt_list    FILMES-IMDB     No translation data returned from trakt for movie Lisbela and the Prisoner (2003).

maybe trakt has no BR translations?

trakt_list
