### ISSUE TITLE
Symlink fails when parent directory doesn't exist

### ISSUE THREAD

**Issue by zeidoo** [Flexget/Flexget#2438]
### Expected behaviour:
symlink:
      to: /data/Plex/Movies/{{imdb_name}} ({{imdb_year}})/

It should create a folder in Movies with the "movie name (year)", then create a symlink to the original directory where the actual movie resides inside this new folder.

### Actual behaviour:

Currently it fails with: FAILED: '<movie directory>' by symlink plugin because failed to create softlink, [Errno 2] No such file or directory: <movie directory> -> <symlink path with non exiting parent>

### Steps to reproduce:
- Step 1: Create a job that tries to symlink as follows
symlink:
      to: /data/Plex/Movies/{{imdb_name}} ({{imdb_year}})/

- Step 2: Run the job.

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 3539

tasks:
  sort-movies:
    priority: 2
    disable: [seen, retry_failed]
    filesystem:
      path: /data/Originals
    imdb_lookup: yes
    accept_all: yes
    symlink:
      to: /data/Plex/Movies/{{imdb_name}} ({{imdb_year}})/
```
  
#### Log:
(movie name removed for privacy reasons)

2019-09-06 12:49 VERBOSE  filesystem    sort-movies     Starting to scan folders.
2019-09-06 12:49 VERBOSE  filesystem    sort-movies     Scanning folder /data/Originals. Recursion is set to False.
2019-09-06 12:49 VERBOSE  details       sort-movies     Produced 1 entries.
2019-09-06 12:49 VERBOSE  task          sort-movies     ACCEPTED: `<Movie Title (year) [quality]>` by accept_all plugin
2019-09-06 12:49 VERBOSE  details       sort-movies     Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2019-09-06 12:49 VERBOSE  symlink       sort-movies     softlink `/data/Originals/<Movie Title (year) [quality]>` to `/data/Plex/Movies/<Movie Title (year)>/<Movie Title (year) [quality]>`
2019-09-06 12:49 ERROR    entry         sort-movies     Failed <Movie Title (year) [quality]>(Failed to create softlink, [Errno 2] No such file or directory: '/data/Originals/<Movie Title (year) [quality]>' -> '/data/Plex/Movies/<Movie Title (year)>/<Movie Title (year) [quality]>')
2019-09-06 12:49 VERBOSE  task          sort-movies     FAILED: `<Movie Title (year) [quality]>` by symlink plugin because failed to create softlink, [Errno 2] No such file or directory: '/data/Originals/<Movie Title (year) [quality]>' -> '/data/Plex/Movies/<Movie Title (year)>/<Movie Title (year) [quality]>'
</details>

### Additional information:

- FlexGet version: 2.21.18 , API: 1.4.3
- Python version: 3
- Installation method: docker (https://hub.docker.com/r/wiserain/flexget/)

Issue has been fixed in my fork https://github.com/zeidoo/Flexget, can do a PR after review.
