### ISSUE TITLE
Content renaming with Deluge issue

### ISSUE THREAD

**Issue by ray73864** [Flexget/Flexget#2459]
Have been running Flexget + Deluge on a VM for a couple of months now trying to get everything working nicely before I dump it on a Raspberry Pi, and I keep having issues with regards to 'No files in "torrent" are > 90% of content size, no files renamed.

My config is
```
schedules:
  # Run task_a every 30 minutes
  - tasks: [rarbg]
    interval:
      minutes: 10
templates:
  tv:
    thetvdb_lookup: yes
    metainfo_series: yes
    exists_series:
      - '/mnt/plex/TV Shows/{{tvdb_series_name}}'
      - /root/Downloads/
    configure_series:
      from:
        thetvdb_list:
          username: xxx
          account_id: xxx
          api_key: xxx
      settings:
        propers: 2 days
        timeframe: 12 hours
        target: 1080p
        quality: "1080p"
    set:
      content_filename: "{{tvdb_series_name}} - {{tvdb_ep_id}} - {{tvdb_ep_name|default('MissingTitle')}}"
      path: /root/Downloads/
      movedone: /mnt/plex/TV Shows/{{tvdb_series_name}}/Season {{tvdb_season|pad(2)}}/
      removeatratio: yes
      magnetization_timeout: 120
      regexp: '.*\.(avi|mkv|mp4)$'
    deluge: yes
tasks:
  rarbg:
    template: tv
    rss: http://rarbg.to/rssdd.php?categories=41

  sort-series:
    thetvdb_lookup: yes
    metainfo_series: yes
    require_field: tvdb_series_name
    filesystem:
      path: /root/Downloads/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    seen: local
    regexp:
      reject:
        - sample
    accept_all: yes
    move:
      to: /mnt/plex/TV Shows/{{tvdb_series_name}}/Season {{tvdb_season|pad(2)}}/
      rename: "{{tvdb_series_name}} - {{tvdb_ep_id}} - {{tvdb_ep_name|default('MissingTitle')}}"
    exec:
      on_exit:
        phase: "/bin/rm -rf /root/Downloads/*"
```

Flexget successfully adds the torrents to Deluge, and if I log onto the web interface for Deluge (Deluge is running in daemon mode) I can see that they are there, problem is, when they are finished, they don't get moved to the correct location afterwards.

If I run 'flexget execute --now', it successfully runs the 'sort-series' task and moves them, adding in the correct extension afterwards, it just won't do it normally.

Getting them from Rarbg (I had to set the interval to 10mins since Rarbg only lists the top 25 in the RSS feed), they have 3 files in them (generally speaking), the .mkv, an exe and a txt file about not putting their torrents up on other sites.

I have tried setting the ratio to something other than the default of 0.9 (such as 0.1 up to 0.8) but nothing ever seems to work.

I know i'm doing something wrong, I just can't work it out and searching on Google hasn't been very helpful as a lot of the tutorials seem to be for really old versions of Flexget.

Versions:

Flexget: 2.21.16
Deluge: 2.0.4.dev8

**Comment by ray73864** [comment]
Updated Flexget to 2.21.26, though the changelog doesn't mention anything that might fix it.

**Comment by ray73864** [comment]
Should probably add the rest of this stuff.

FlexGet version: 2.21.26
Python version: Python 2.7.16
Installation method: PIP
Using daemon (yes/no): yes
OS and version: Debian 10.1 (Buster)

**Comment by Arghh** [comment]
Hi ray,

hard to say, what the problem is without a log file. Set your logging to verbose maybe it will give some more info.

Anyways I have the same setup and here is my sort-series task:

  ```
# sorting task
  sort-series:
    priority: 3
    filesystem:
      # directory with the files to be sorted
      path: /mnt/D4B811C9B811AB4E/torrents/completed
      # fetch all avi, mkv and mp4 files, skips the .part files (unfinished torrents)
      regexp: '.*\.(avi|mkv|mp4|m4v|)$'
      recursive: yes
    accept_all: yes
    seen: local
    regexp:
      reject: 
        - sample      
    # this is needed for the episode names
    list_match: 
      from:
        - entry_list: series_list
    thetvdb_lookup: yes    
    metainfo_series: yes
    require_field:
      - tvdb_series_name
      - tvdb_ep_id
      - tvdb_ep_name
    parsing:
      series: guessit
    disable:
      - seen
      - seen_info_hash
      - rejected  
    move:
      # this is where the series will be put
      to: /mnt/D4B811C9B811AB4E/series/{{ tvdb_series_name }}/Season {{tvdb_season|pad(2)}}
      # save the file as "Series Name - SxxEyy - Episode Name.ext"
      rename: "{{ tvdb_series_name }} - {{ tvdb_ep_id|d(series_id, True) }} - {{ tvdb_ep_name|d(series_name, True) }}"
      along:
        extensions:
          - sub
          - srt
        subdirs:
          - Subs

```
It works just fine. Hope it helps.
