### ISSUE TITLE
Deluge rename error

### ISSUE THREAD

**Issue by luizoti** [Flexget/Flexget#2473]
### Expected behaviour:
Add the torrents, renames and place them in the correct folders.

### Actual behaviour:

I reported the same issue here and had no feedback so far:

I'm having this problem, flexget manipulates the title and so far so good, but when adding in deluge it "loses" the name and episode of the series and replaces with "Nome".

The goal is to generate titles like this: "Kanata no Astra - S01E01 - 1080p 10bit.mkv" and it generates titles like this: "Nome - S01E01 - Nome 1080p 10bit.mkv"

### Steps to reproduce:
- Step 1: ...
1. feed download a torrent
2. add to deluge 
2. rename file
#### Config:
<details>
 <summary>(click to expand)</summary>

```
#
# flexget execute --no-cache --discover-now --task FILMES-TRAKT-DOWNLOAD
# 
tasks:

################################ EP RSS ##################################

  animes-episodes-rss:
    priority: 4
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    rss: 'https://ru.erai-raws.info/rss-1080/'
    accept_all: yes
    download: /home/luiz/.flexget/animes/episodes

  animes-episodes-rss-filter:
    disable:
      - seen
      - seen_info_hash
      - retry_failed    
    priority: 5
    filesystem: /home/luiz/.flexget/animes/episodes
    regexp:
      reject:
        - '\[Multiple Subtitle\]'
      from: title
      rest: accept
    delete: yes

  animes-episodes-rss-download:
    priority: 6
    metainfo_series: yes
    thetvdb_lookup: yes
    inputs:
      # - rss: 'https://nyaa.si/?page=rss&q=Darkanimes&c=0_0&f=0'
      - rss: 'https://nyaa.si/?page=rss&q=1080p+PT-BR&c=0_0&f=0'
      - rss: 'https://nyaa.si/?page=rss&u=Seicher'
      # - rss: 'https://tracker.uniotaku.com/rss.php?cat=28,50&incldead=1&dllink=1&passkey=1168844ad8169c174d28c265d813bcbf'
    filesystem:
      path: /home/luiz/.flexget/animes/episodes
      mask: '*.torrent'
    deluge:
      label: "ANIMES"
      path: '/media/luiz/HD/.FLEXGET/BAIXANDO/'
      move_completed_path: '/media/luiz/HD/MIDIA/SERIES/{{tvdb_series_name|replace(":","")}}/Season {{series_season}}'
      content_filename: '{{tvdb_series_name|replace(":","")}} - {{series_id}} - {{tvdb_ep_name|replace(":","")}}'
    template:
      - GERAL
      - ANIMES
      - ANIMES-TITLE-NORMALIZE
      - ANIMES-TITLE-EP
      - DELUGE
      - push1

templates:           
  ANIMES:
    trakt_lookup: yes
    thetvdb_lookup: yes
    metainfo_series: yes
    configure_series:
      from:
        trakt_list:
          account: kingkiller
          list: animes
          type: shows
          strip_dates: yes          
        my_anime_list:
          username: luizoti
          status: all
          airing_status: all
          type: all
      settings:
        qualities:
          - 480p+ !720p
          - 480p 10bit !720p
          - 1080p+ !720p
          - 1080p 10bit !720p
        upgrade: yes
        season_packs: yes
        identified_by: ep
        special_ids:
          - OVA      
          - ONA 
          - Special
          - S00

  GERAL:
    cfscraper: yes   
    decompress:
      keep_dirs: no
      delete_archive: yes
    urlrewrite:
      torrentz2:
        regexp: 'https:\/\/torrentz2\.eu\/(?P<id>\w*)'
        format: 'magnet:?xt=urn:btih:\g<id>'
      yts:
        regexp: 'https\:\/\/yts\.lt\/torrent\/download\/(?P<id>\w*)'
        format: 'magnet:?xt=urn:btih:\g<id>'
    manipulate:
    - filename:
        from: title
    - title:
        replace:            
          regexp: '\+'
          format: ' '
    - title:
        replace:            
          regexp: '(?i)(?<![\w\d])\(.*\)(?![\w\d])'
          format: ' '
    - title:
        replace:            
          regexp: '(?i)(?<![\w\d])(ETRG|(YTS|\.AM|\.LT)|VPPV|RARBG|VXT|YIFY|WWW|COMANDOTORRENTS|COM|RK|AVC|Nacional|TPF|GRATIS|Complete|Eng|Sub|HARD)(?![\w\d])'
          format: ' '
    - title:
        replace:            
          regexp: '(?i)(?<![\w\d])(avi|mkv|mp4|m4v|iso|srt|ass|ssa|png|jpg|idx|sub|rar|r0+[01](/01)|zip)(?![\w\d])'
          format: ' '
    - title:
        replace:            
          regexp: '(?i)WWW\..*\.(COM|org)'
          format: ' '  
    - title:
        replace:            
          regexp: '(?i)(Extras|Acesse (o ORIGINAL|)|NACIONAL|COMPACTA(?:ÇÃO|cao))'
          format: ' '          
    - title:
        extract: '\[\d+\](.*)'
    - title:
        replace:            
          regexp: '^(\[.+?\])'
          format: ''
    - title:
        replace:
          regexp: '(_|-_-)'
          format: ' '
    - title:
        replace:
          regexp: '(–)'
          format: '-'
    - title:
        replace:
          regexp: '(?i)(((?:\d*)x(?:DTS|FLAC))|hardsub|Softsub|DTS-HD|DL|WEB|rip|AAC|FLAC|HEVC|HDTV|truehd|dual|audio|PT-BR|Dublado|TV|\(TV\))'
          format: ''
    - title:
        replace:            
          regexp: '(?i)(AVC\-YUV444P10|Hi444PP|Hi10P|(10(?:|\s)Bit(?:s|)))'
          format: '10bit'
    #       acentuação brasil
    - title:
        replace:
          regexp: 'Ã'
          format: 'a'
    - title:
        replace:
          regexp: 'ã'
          format: 'a'
    - title:
        replace:
          regexp: 'Ç'
          format: 'c'
    - title:
        replace:
          regexp: 'ç'
          format: 'c'
    #       acentuação brasil
    - title:
        replace:
          regexp: 'Á'
          format: 'A'
    - title:
        replace:
          regexp: 'É'
          format: 'E'
    - title:
        replace:
          regexp: 'Í'
          format: 'I'
    - title:
        replace:
          regexp: 'Ó'
          format: 'O'
    - title:
        replace:
          regexp: 'Ú'
          format: 'U'
    - title:          
        replace:
          regexp: 'á'
          format: 'a'
    - title:
        replace:
          regexp: 'é'
          format: 'e'
    - title:
        replace:
          regexp: 'í'
          format: 'i'
    - title:
        replace:
          regexp: 'ó'
          format: 'o'
    - title:
        replace:
          regexp: 'ú'
          format: 'u' 
    regexp:
      reject:
        # - '(?i)((?:extra|sample)(?:.*|s))|(Deleted|Making Of)'
        - '(?i)((sample)(?:.*|s))|(Deleted|Making Of)'
        - '(?i)^.*\.exe$'
        - '(?i)Vol\.\d+'
        - '(?i)Wallpapers'
        - '(?i)(?<![\w\d])(Hindi|Tamil|ru|RUS|RUSS|RUSSIAN)(?![\w\d])'
        - '(?i)(?<![\w\d])(HQ|HDTC|mp3|RBG|REWARD|HDTS|hdtv|HDTC|HQTC|HC|HDRip|hqts|dsr)(?![\w\d])'
        - '(?i)(?<![\w\d])(tc|HD-TC|TC H264|dvdscr|bdscr|360p|368p)(?![\w\d])'
        - '(?i)(?<![\w\d])(bdscr|dvdscr|sdtv|dsr|tvrip|preair|ppvrip|r5|tc|ts|cam|workprint)(?![\w\d])'

  MOVIE-NORMALIZE:
    manipulate:
    - filename:
        from: title
    - title:
        replace:            
          regexp: '(?i)((?<![\w\d])1080(?![\w\d])|\[1080\]|(?<![\w\d])1080p(?![\w\d])|\[1080p\]|FULL HD|FULLHD|\[FullHD\])'
          format: ' 1080p '
    - title:
        replace:            
          regexp: '(?i)((?<![\w\d])720(?![\w\d])|\[720\]|(?<![\w\d])720p(?![\w\d])|\[720p\]|HD|hdrip|720|688)'
          format: ' 720p '
    - title:
        replace:            
          regexp: '(?i)((?<![\w\d])480(?![\w\d])|\[480\]|(?<![\w\d])480p(?![\w\d])|\[480p\]|DVDrip|DVD|480)'
          format: ' 480p '        
    - title:
        replace:            
          regexp: '\.|\{|\}'
          format: ' '
    - title:
        replace:
          regexp: '(?i)(BD)'
          format: 'Bluray'
    - title:
        replace:
          regexp: '[ ]{2,}'
          format: ' '

  ANIMES-TITLE-NORMALIZE:
    manipulate:
    - filename:
        from: title
    - title:
        replace:
          regexp: '(?i)(?:h|x)(.|)(?:264|265)'
          format: ' '        
    - title:
        replace:   
          regexp: '(?<![\w\d])(\!|\:|\?|\.)(?![\w\d])'
          format: ' '
    - title:
        replace:            
          regexp: '(\d*) ~ (\d*)'
          format: ' '
    - title:
        replace:            
          regexp: '(?i)((?:nd|rd|th)\s(?:Season))'
          format: ' episode'
    - title:
        replace:            
          regexp: '(?i)(season)\s*'
          format: 'S0'
    - title:
        replace:
          regexp: '(?i)Book '
          format: 'S0'
    - title:
        replace:
          regexp: '\s(?i)(end)'
          format: ' '
    - title:
        replace:            
          # regexp: '\(\d{4}\)'
          regexp: '(?<![\w\d])((?:1|2|3|4|5|6|7|8)(?:[0-9])\d\d)(?![\w\d])'
          format: ' '
    - title:
        replace:            
          regexp: '(?i)(v\d*)\s'
          format: ' '
    - title:
        replace:
          regexp: '(?i)\[Multiple Subtitle\]|Audio|Subs|Multi'
          format: ' '
    - title:
        replace:
          regexp: '(?i)(BD|bdrip|DVD)'
          format: ''
    - title:
        replace:
          regexp: '(?i)(E-AC-3|EAC3|AC3)'
          format: ''
    - title:
        replace:
          regexp: '(?i)(8(?:\s|)bit(?:s|))'
          format: '' 
    - title:
        replace:
          regexp: '(\]\[)'
          format: '] ['
    - title:
        replace:
          regexp: '(\[\])'
          format: ' '
    - title:
        replace:
          regexp: '(\]\s*)'
          format: ']  '
    - title:
        replace:
          regexp: '(\s*\])'
          format: ']'
    - title:
        replace:
          regexp: '(\[\s*|\[)'
          format: ' ['
    - title:
        replace:
          regexp: '(?i)((?:6|12|19)(?:\d*)x)'
          format: ''
    - title:
        replace:
          regexp: '((?<![\w\d])\-(?![\w\d])|\(|\))'
          format: '  '
    - title:
        replace:            
          regexp: '(?<![\w\d])(1080|\[1080\]|1080p|\[1080p\]|FULL HD|FULLHD)(?![\w\d])'
          format: '- [1080p]'
    - title:
        replace:            
          regexp: '(?<![\w\d])(720|\[720\]|720p|\[720p\]|HD|hdrip)(?![\w\d])'
          format: '- [720p]'
    - title:
        replace:            
          regexp: '(?<![\w\d])(480|\[480\]|480p|\[480p\]|DVDrip|DVD)(?![\w\d])'
          format: '- [480p]'
    - title:
        replace:
          regexp: '\[\-'
          format: '-'
    - title:
        replace:
          regexp: 'bit\]'
          format: 'bit'
    - title:
        replace:
          regexp: '(?<![\w\d])I(?![\w\d])'
          format: '1'
    - title:
        replace:            
          regexp: '(?<![\w\d])II(?![\w\d])'
          format: '2'
    - title:
        replace:            
          regexp: '(?<![\w\d])III(?![\w\d])'
          format: '3'
    - title:
        replace:            
          regexp: '(?<![\w\d])IV(?![\w\d])'
          format: '4'
    - title:
        replace:            
          regexp: '(?<![\w\d])V(?![\w\d])'
          format: '5'
    - title:
        replace:            
          regexp: '(?<![\w\d])VI(?![\w\d])'
          format: '6'
    - title:
        replace:            
          regexp: '(?<![\w\d])VII(?![\w\d])'
          format: '7'
    - title:
        replace:            
          regexp: '(?<![\w\d])VIII(?![\w\d])'
          format: '8'
    - title:
        replace:            
          regexp: '(?<![\w\d])IX(?![\w\d])'
          format: '9'
    # - title:
    #     replace:            
    #       regexp: '(?<![\w\d])X(?![\w\d])'
    #       format: '10'
    - title:
        replace:
          regexp: 'S((?:1|2|3|4|5|6|7|8)(?:[0-9])\d\d)'
          format: 'S01'
    - title:
        replace:
          regexp: '[ ]{2,}'
          format: ' '
    # - title:
    #     extract: (.*)\[.+?\]

  ANIMES-TITLE-EP:
    manipulate:
    - title:    
        replace:
          # Bungou Stray Dogs 3 episode 10 - [720p]
          regexp: '(.*[a-zA-Z]) (\d*) (episode) (\d*) - (?:\[((?:1080|720|480|)p(?:| \d*bit))\])'
          format: '\1 - S0\2E\4 - \5'          
    - title:    
        replace:
          # Shingeki no Kyojin S03 09 - [1080p]
          regexp: '(.*[a-zA-Z]) (S\d*) (\d*) - (?:\[((?:1080|720|480)p(?:| \d*bit))\])'
          format: '\1 - \2E\3 - \4'
    - title:    
        replace:            
        # Soul Eater 02
        # The Animatrix 07 [4DB588FC]
        # Enen no Shouboutai 04 - [1080p] [4DB588FC]
          regexp: '(.+?) (\d*)\s'
          format: '\1 - S01E\2'

  ANIMES-ANIMES-BATH:
    manipulate:  
    - title:    
        replace:    
          # BanG Dream S2 - [1080p]
          regexp: '(.*[a-zA-Z]) (\d*) - (?:\[((?:1080|720|480)p(?:| \d*bit))\])'
          format: '\1 - S0\2 - \3'    
    - title:    
        replace:    
          # BanG Dream S2 - [1080p]
          regexp: '(.*[a-zA-Z]) (S\d*) - (?:\[((?:1080|720|480)p(?:| \d*bit))\])'
          format: '\1 - S0\2 - \3'  
    - title:    
        replace:    
          # BanG Dream 2 episode 01 ~ 12 - [1080p]
          regexp: '(.*[a-zA-Z]) (?<![\w\d])(\d*) (episode)(?![\w\d]) (?:(.*)|)(?:\[((?:1080|720|480)p(?:| \d*bit))\])'
          format: '\1 \4 S0\2 - \5'
    - title:    
        replace:    
          # Owarimonogatari - [1080p]
          regexp: '(?i)(.*[a-z0-99]) - (?:\[((?:1080|720|480)p(?:| \d*bit))\])'
          format: '\1 - S01 - \2'          

  DELUGE:
    deluge:
      host: localhost
      port: 58846
      username: localclient
      password: admin
      main_file_only: yes
      auto_managed: true
      ratio: 2
      remove_at_ratio: yes
      queue_to_top: yes
      keep_subs: yes

              ############# TELEGRAN PUSH #############

  push0:
    metainfo_series: yes
    trakt_lookup: yes
    thetvdb_lookup: yes
    notify:
      entries:
        title: '[ANIMES-BATH] {{task}}'
        message: "     TEMPORADA     \r\n- Anime: {{trakt_series_name}}\r\n- Temporada: {{series_season}}\r\n- Ano: {{trakt_series_year|default('0')}}\r\n- Torrent: {{title}}\r\n- Hash:\n {{deluge_id}}"
        what: accepted
        via:
          - telegram:
              bot_token: 'XXXXXXX'
              parse_mode: markdown
              recipients:
                - username: 'luizoti'

# ____________________

  push1:
    metainfo_series: yes
    trakt_lookup: yes
    thetvdb_lookup: yes
    notify:
      entries:
        title: '[ANIMES-EP] {{task}}'
        message: "     EPSODIO     \r\n- Anime: {{trakt_series_name}}\r\n- Nome do EP: {{trakt_ep_name}}\r\n- Temporada: {{series_season}}\r\n- Episódio: {{series_episode}}\r\n- Ano: {{trakt_series_year|default('0')}}\r\n- Torrent: {{title}}\r\n- Hash:\n {{deluge_id}}"
        what: accepted
        via:
          - telegram:
              bot_token: 'XXXXXXX'
              parse_mode: markdown
              recipients:
                - username: 'luizoti'

              ############# SERIES #############    
  push2:
    metainfo_series: yes
    trakt_lookup: yes
    thetvdb_lookup: yes
    notify:
      entries:
        title: '[SERIES-EPS] - {{task}}'
        message: "     EPSODIO     \r\n- Serie: {{trakt_series_name}}\r\n- Nome do EP: {{trakt_ep_name}}\r\n- Temporada: {{series_season}}\r\n- Episódio: {{series_episode}}\r\n- Ano: {{trakt_series_year|default('0')}}\r\n- Dia de exibição: {{trakt_series_air_day}}\r\n- Torrent: {{title}}\r\n- Hash:\n {{deluge_id}}"
        what: accepted
        via:
          - telegram:
              bot_token: 'XXXXXXX'
              parse_mode: markdown
              recipients:
                - username: 'luizoti'
  push2.1:
    metainfo_series: yes
    trakt_lookup: yes
    thetvdb_lookup: yes
    notify:
      entries:
        title: '[SERIES-PAKS] - {{task}}'
        message: "     TEMPORADA     \r\n- Serie: {{trakt_series_name}}\r\n- Temporada: {{series_season}}\r\n- Ano: {{trakt_series_year|default('0')}}\r\n- Torrent: {{title}}\r\n- Hash:\n {{deluge_id}}"
        what: accepted
        via:
          - telegram:
              bot_token: 'XXXXXXX'
              parse_mode: markdown
              recipients:
                - username: 'luizoti'

              ############# FILMES #############            
  push3:
    metainfo_series: yes
    imdb_lookup: yes
    notify:
      entries:
        title: '[FILMES] - {{task}}'
        message: "- Torrent: {{title}}\r\n- Titulo: {{imdb_name}}\r\n- IMDB URL: {{imdb_url}}\r\n- Ano: {{imdb_year}}\r\n- Torrent: {{title}}\r\n- Hash:\n {{deluge_id}}"
        what: accepted
        via:
          - telegram:
              bot_token: 'XXXXXXX'
              parse_mode: markdown
              recipients:
                - username: 'luizoti'

  push4:
    metainfo_series: yes
    imdb_lookup: yes
    notify:
      entries:
        title: '[DELETADO] - {{task}}'
        message: "DELETADO\r\n\n- Torrent: {{title}}\r\n- Estado: {{deluge_state}}\r\n- Hash:\n {{deluge_id}}" 
        what: accepted
        via:
          - telegram:
              bot_token: 'XXXXXXX'
              parse_mode: markdown
              recipients:
                - username: 'luizoti'


   ####################################################################  TAMPLATES  ######################################################################################################
    
schedules:
  - tasks: [animes-*]
    interval:
      minutes: 20
```

</details>
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
download_location': u'/media/luiz/HD/.FLEXGET/SERIES_TEMP', u'stop_ratio': 2.5, u'remove_at_ratio': True}) kwargs:{}
2019-07-04 18:17 INFO     deluge        animes-episodes-rss-download Kanata no Astra - S01E01 - 1080p 10bit.mkv successfully added to deluge.
2019-07-04 18:17 DEBUG    deluge_client.client animes-episodes-rss-download Calling reqid 10 method u'core.set_torrent_move_completed' with args:(u'458df38c0caa67ea3fb65964a96560bc623755c6', True) kwargs:{}
2019-07-04 18:17 DEBUG    deluge_client.client animes-episodes-rss-download Calling reqid 11 method u'core.set_torrent_move_completed_path' with args:(u'458df38c0caa67ea3fb65964a96560bc623755c6', u'/media/luiz/HD/.FLEXGET/SERIES_TEMP') kwargs:{}
2019-07-04 18:17 DEBUG    deluge        animes-episodes-rss-download Kanata no Astra - S01E01 - 1080p 10bit.mkv move on complete set to /media/luiz/HD/.FLEXGET/SERIES_TEMP
2019-07-04 18:17 DEBUG    deluge_client.client animes-episodes-rss-download Calling reqid 12 method u'label.set_torrent' with args:(u'458df38c0caa67ea3fb65964a96560bc623755c6', u'animes') kwargs:{}
2019-07-04 18:17 DEBUG    deluge_client.client animes-episodes-rss-download Calling reqid 13 method u'core.queue_top' with args:([u'458df38c0caa67ea3fb65964a96560bc623755c6'],) kwargs:{}
2019-07-04 18:17 DEBUG    deluge        animes-episodes-rss-download Kanata no Astra - S01E01 - 1080p 10bit.mkv moved to top of queue
2019-07-04 18:17 DEBUG    deluge_client.client animes-episodes-rss-download Calling reqid 14 method u'core.get_torrent_status' with args:(u'458df38c0caa67ea3fb65964a96560bc623755c6', [u'files', u'total_size', u'save_path', u'move_on_completed_path', u'move_on_completed', u'progress']) kwargs:{}
2019-07-04 18:17 DEBUG    deluge        animes-episodes-rss-download Not moving storage for Kanata no Astra - S01E01 - 1080p 10bit.mkv, as this will prevent move_completed_path.
2019-07-04 18:17 DEBUG    deluge_client.client animes-episodes-rss-download Calling reqid 15 method u'core.rename_files' with args:(u'458df38c0caa67ea3fb65964a96560bc623755c6', [(0, u'/None - S01E01 - None - 1080p 10bit.mkv')]) kwargs:{}
2019-07-04 18:17 DEBUG    deluge        animes-episodes-rss-download File [Seicher-Raws] Kanata no Astra - 01 [WEB 1080p 10bit E-AC-3].mkv in Kanata no Astra - S01E01 - 1080p 10bit.mkv renamed to /None - S01E01 - None - 1080p 10bit.mkv
2019-07-04 18:17 DEBUG    deluge_client.client animes-episodes-rss-download Calling reqid 16 method u'core.set_torrent_file_priorities' with args:(u'458df38c0caa67ea3fb65964a96560bc623755c6', [1]) kwargs:{}
2019-07-04 18:17 DEBUG    if            animes-episodes-rss-download Kanata no Astra - S01E01 - 1080p 10bit.mkv matched requirement '1080p 10bit' in title
2019-07-04 18:17 DEBUG    if            animes-episodes-rss-download Grand Blue 1080p 10bit matched requirement '1080p 10bit' in title
2019-07-04 18:17 DEBUG    if            animes-episodes-rss-download Asobi Asobase 1080p 10bit matched requirement '1080p 10bit' in title
2019-07-04 18:17 DEBUG    if            animes-episodes-rss-download Kanata no Astra - S01E01 - 1080p 10bit.mkv matched requirement 'Kanata no Astra' in title
2019-07-04 18:17 DEBUG    flexget.components.trakt.api_trakt animes-episodes-rss-download Found Kanata no Astra in previous search results as Astra Lost in Space
2019-07-04 18:17 DEBUG    notify        animes-episodes-rss-download Sending a notification to `telegram`
2019-07-04 18:17 DEBUG    telegram      animes-episodes-rss-download token=687368195:AAFkTwtKUl_Tx-yF0eJR7isqsHJM49MNIUY, parse_mode=markdown, disable_previews=False, usernames=[u'luizoti'], fullnames=[], groups=[]
2019-07-04 18:17 DEBUG    telegram.bot  animes-episodes-rss-download Entering: get_me
2019-07-04 18:17 DEBUG    telegram.vendor.ptb_urllib3.urllib3.connectionpool animes-episodes-rss-download Starting new HTTPS connection (1): api.telegram.org
2019-07-04 18:17 DEBUG    telegram.vendor.ptb_urllib3.urllib3.connectionpool animes-episodes-rss-download https://api.telegram.org:443 "GET /bot687368195:AAFkTwtKUl_Tx-yF0eJR7isqsHJM49MNIUY/getMe HTTP/1.1" 200 101
2019-07-04 18:17 DEBUG    telegram.bot  animes-episodes-rss-download {'username': u'ANIMES_luizbot', 'first_name': u'ANIMES', 'is_bot': True, 'id': 687368195}
2019-07-04 18:17 DEBUG    telegram.bot  animes-episodes-rss-download Exiting: get_me
2019-07-04 18:17 DEBUG    telegram      animes-episodes-rss-download loading cached chat ids
2019-07-04 18:17 DEBUG    telegram      animes-episodes-rss-download found 1 cached chat_ids: [u'id=683314295 username=luizoti firstname=Luiz surname=Ant\xf4nio Lazoti']
2019-07-04 18:17 DEBUG    telegram      animes-episodes-rss-download all chat ids found in cache
2019-07-04 18:17 DEBUG    telegram      animes-episodes-rss-download chat_ids=[<flexget.components.notify.notifiers.telegram.ChatIdEntry object at 0x7f9feabb6e50>]
2019-07-04 18:17 DEBUG    telegram      animes-episodes-rss-download sending msg to telegram servers: - Anime: None
- Ano: 2019
```
</details>

### Additional information:

- FlexGet version: 2.21.32
- Python version: 
Python 2.7.15+ end 3.6.8
If I'm not mistaken Flexget is running on 3.6.8.
- Installation method: normal, not virtualenv
- Using daemon (yes/no): yes
- OS and version: kubuntu 18.04
- Link to crash log: https://pastebin.com/B84c7h2a
The error occurs with deluge 1.3.x and 2.0.x.
Deluge version: 

2.0.3-2-201906121747-ubuntu18.04.1
A peer-to-peer file sharing program
utilizing the BitTorrent protocol.

Client: 2.0.3-2-201906121747-ubuntu18.04.1
Server: 2.0.3-2-201906121747-ubuntu18.04.1
