### ISSUE TITLE
Flexget and TheTVDB

### ISSUE THREAD

**Issue by ray73864** [Flexget/Flexget#2498]
Checked my Flexget logfile today only to find that it was littered with 
```
Error during input plugin thetvdb_list: Error retrieving favorites from thetvdb: 401 Client Error: Unauthorized for url: https://api.thetvdb.com/login
```

Found there was a newer version of Flexget (I was still running the latest 2.x release), took a bit of work to upgrade from 2.x to 3.x (I might have missed something with regards to an upgrade path guide?)

Fired up the Flexget daemon, checked the logfile, still shows the error.

Did a search and it looks like TheTVDb has released a new API, and I couldn't find my old account_id on the site anymore, instead it is a new one that is different to the one I told Flexget about.

Is there any changes I need to do to make thetvdb_list work again? I couldn't see anything, but this tvdb change I'm guessing only just happened in the last day or so, since it was all working fine on Wednesday (13/11/2019).

**Comment by BrutuZ** [comment]
There's the following warning on TheTVDB's [API v3 release post](https://forums.thetvdb.com/viewtopic.php?f=3&t=60048):
> We know your favorites are gone, we are migrating them over soon.

So I guess nothing else to do for the time being but hold tight and wait for their newest *updatecalypse* to settle down.
A lot of programs are being affected by this change in different levels

**Comment by ray73864** [comment]
Ahh, I didn't even look that far.

Will have to re-add the favourites too then. Guess for the time being I will go back to manually downloading until they have finished things off.

**Comment by bewell** [comment]
Would it be nice to have a fallback list to reference in such cases? i.e. when the tvdb is not available for whatever reasons (server down, API upgrades, etc).
Flexget has an offline list already from the `flexget seriest list all`. So referencing that list instead of directly the web service would save a lot of headaches when something fails. 
The flow is pretty straight forward just like with the movie lists:
- flexget pulls the series from webservice (tvdb) and updates the offline list
- when taking the RSS items we compare the offline list against RSS

does that make sense?

**Comment by ray73864** [comment]
> Would it be nice to have a fallback list to reference in such cases? i.e. when the tvdb is not available for whatever reasons (server down, API upgrades, etc).
> Flexget has an offline list already from the `flexget seriest list all`. So referencing that list instead of directly the web service would save a lot of headaches when something fails.
> The flow is pretty straight forward just like with the movie lists:
> 
> * flexget pulls the series from webservice (tvdb) and updates the offline list
> * when taking the RSS items we compare the offline list against RSS
> 
> does that make sense?

Is this possible already? Because if so, I'll gladly update my config to utilise it

**Comment by bewell** [comment]
@ray73864 I'm not sure about it.
I guess it would be a feature request. Maybe someone will be faster than me to make a PR :))

**Comment by vincentdh** [comment]
The new API is now returning the series name instead of a series ID when you request the favorites list.

I've patched the following lines on my installation, but I'm in no way an expert of Flexget and Python ... Therefore I suggest that someone else take a look at it and do a PR

```python
// file flexget/components/managed_lists/lists/thetvdb_list.py line 66
series_ids = [f_id for f_id in req['favorites'] if f_id!= '']
```
```python
// file flexget/components/managed_lists/lists/thetvdb_list.py line 74
name=series_id, language=self.config.get('language')
```

I hope this can help to fix the issues with the API update ...

**Comment by gazpachoking** [comment]
> The new API is now returning the series name instead of a series ID when you request the favorites list.

I think this is a mistake and will be moving back to IDs once tvdb does some more work on the api.

**Comment by vincentdh** [comment]
> 
> I think this is a mistake and will be moving back to IDs once tvdb does some more work on the api. https://forums.thetvdb.com/viewtopic.php?f=122&t=60183

Thanks, I've looked for this info, but didn't found it.  So, my "patch" is a good temporary fix ;)

**Comment by bewell** [comment]
Seems the guys on tvdb solved the issue:
https://forums.thetvdb.com/viewtopic.php?p=166033#p166033

**Comment by snickers2k** [comment]
for a few days, i'm not getting any data from tvdb anymore - is this related to this issue here?

**Comment by bewell** [comment]
@snickers2k I was frustrated by it so I just switched to `tvmaze` plugin. Works exactly the same as `tvdb`

**Comment by snickers2k** [comment]
tvmaze is not really working for me ... :/
does anyone know why this happens? one day its working, the other day not.. :(

**Comment by snickers2k** [comment]
okay, this must be tvdb related .. right now, not even the search directly on their site is working

**Comment by BrutuZ** [comment]
It happens, which is why using `entry-list` as a buffer is a great idea.

**Comment by snickers2k** [comment]
yeah, but not working for lookups ..  :( on the other hand, plex is still getting metadata .. so maybe it is flexget .. i dont know

**Comment by BrutuZ** [comment]
Plex is a different beast, especially after the chaos from early v3 migration they said more contingencies were put in place on their end to account for TheTVDB downtime (my guess is a cache proxy if the redirect fails).
Regardless, I had no problem with them in a while. My 4 Flexget lookups of the day had no issues and I even dabbled a little on the portal for a change today, without a hitch either.

**Comment by ray73864** [comment]
I've been seeing a lot of TheTVDB related warnings / errors recently in my flexget.log file.

```
2020-01-18 09:17 ERROR    api_tvdb      rarbg           Could not get update information from tvdb: HTTPSConnectionPool(host='api.thetvdb.com', port=443): Read timed out. (read timeout=30)
2020-01-18 09:17 ERROR    api_tvdb      rarbg           Could not get update information from tvdb: Requests to this site (api.thetvdb.com) have timed out recently. Waiting before trying again.

2020-01-21 02:17 WARNING  configure_series rarbg           Error during input plugin thetvdb_list: Error retrieving favorites from thetvdb: 502 Server Error: Bad Gateway for url: https://api.thetvdb.com/user/favorites
```

Those are basically the 3 messages I see throughout my logfile, only just started happening in the last couple of weeks.

**Comment by bewell** [comment]
I don't know how you guys utilising tvdb, but when I switched to tvmaze all the problems went away. My extract how I'm sorting my series:

```yml
####################################
# Organizing the movies and series #
####################################
  copy-episodes:
    priority: 15
    tvmaze_lookup: yes
    metainfo_series: yes
    seen: local
    #disable: [seen, seen_info_hash]
    accept_all: yes
    filesystem:
      path: /......../local.transmission/incomplete/series
      regexp: '.*.(avi|mkv|mp4|m4v)$'
      recursive: yes
    copy:
      to: "/......../homenas.transmission/Downloads/!series/{{ series_name|replace(' ','.') }}/{{ series_name|replace(' ','.') }}.-.Season.{{series_season}}/"
      rename: "{{ series_name|replace(' ','.') }}.{{ series_id }}.{{ tvmaze_episode_name|replace(' ','.')|replace(':','.')|default('Unknown') }}.{{ quality.resolution }}{{ location|pathext }}"
      along:
        extensions:
          - sub
          - srt
        subdirs:
          - Subs
```
