### ISSUE TITLE
Missing categories from Alpharatio plugin

### ISSUE THREAD

**Issue by frankyw** [Flexget/Flexget#2502]
### Expected behaviour:

Alpharatio plugin support all categories listed on website

### Actual behaviour:

Task fails when using missing category

### Steps to reproduce:

Run task with categories missing (TvUHD, TvPackUHD, MovieUHD, MoviePackUHD)

#### Config:
```yaml
tasks:

  search-tv:
    priority: 2
    template:
      - global-settings
      - tv-settings
    discover:
      what:
        - next_series_episodes: yes
      from:
        - alpharatio:
            <<: *alpharatio_credentials
            category: TvHD, TvUHD
        - iptorrents: 
            <<: *iptorrents_credentials
            category: [22, 5, 99]
        - torrentleech: 
            <<: *torrentleech_credentials
            category: [32]
      interval: 3 hours
    cfscraper: yes

  search-movies:
    priority: 3
    template:
      - global-settings
      - movie-settings
    discover:
      release_estimations:
        optimistic: 30 days
      what:
        - movie_list: Movies
      from:
        - alpharatio:
            <<: *alpharatio_credentials
            category: MovieHD, MovieUHD
        - torrentleech: 
            <<: *torrentleech_credentials
            category: [14, 37, 47]
        - iptorrents: 
            <<: *iptorrents_credentials
            category: [48, 20, 100, 101]
      interval: 3 hours
    cfscraper: yes
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

[/tasks/search-tv/discover/from/0/alpharatio/category] Must be one of the following: tvsd, tvhd, tvdvdrip, tvpacksd, tvpackhd, moviesd, moviehd, moviepacksd, moviepackhd, moviexxx, mvid, gamespc, gamesxbox, gamesps3, gameswii, appspc, appsmac, appslinux, appsmobile, 0dayXXX, ebook, audiobook, music, misc

</details>

### Additional information:

Missing categories are:
TvUHD, TvPackUHD, MovieUHD, MoviePackUHD

- FlexGet version: 3.0.4
- Python version: Python 3.7.5
- Installation method: Docker wiserain/flexget:latest
- Using daemon (yes/no): yes
- OS and version:
- Link to crash log:
