### ISSUE TITLE
checking lazy lookup for None value

### ISSUE THREAD

**Issue by astrotee** [Flexget/Flexget#2516]
with the current tvdb problems i tried to check for when some tvdb entries are not available (when they are None)

so i tried different if conditions but none of them worked
here is what i tried

```yaml
if:
  - tvdb_ep_name != 'None':
      set:
        content_filename: '{{ tvdb_series_name }} {{ tvdb_absolute_number }} - {{tvdb_ep_name }}'
```
this check passes for some reason even though it returns None when setting the filename
also tried those
`tvdb_ep_name is not None`
and 
`tvdb_ep_name is defined`
but they gave an error!

is there something that i am doing wrong? something i am missing?

**Comment by BrutuZ** [comment]
> has_field(’<field_name>’)  -  Returns true if the entry has the field field_name.
> https://flexget.com/Plugins/if
```yaml
if:
  - has_field(tvdb_ep_name):
      set:
        content_filename: '{{ tvdb_series_name }} {{ tvdb_absolute_number }} - {{tvdb_ep_name }}'
```

Also could probably be solved in Jinja instead and skip the `if` plugin entirely:
```yaml
set:
  content_filename: '{% if tvdb_ep_name is defined %}{{ tvdb_series_name }} {{ tvdb_absolute_number }} - {{tvdb_ep_name}}{% endif %}'
```
Use a default value if `tvdb_ep_name` is not set:
```yaml
set:
  content_filename: '{{ tvdb_series_name }} {{ tvdb_absolute_number }} - {{tvdb_ep_name|d('Untitled Episode')}}'
```

**Comment by astrotee** [comment]
> ```yaml
> if:
>   - has_field(tvdb_ep_name):
>       set:
>         content_filename: '{{ tvdb_series_name }} {{ tvdb_absolute_number }} - {{tvdb_ep_name }}'
> 
> ```

so i tried this with both tvdb_ep_name and tvdb_absolute_number and in both cases it didn't pass even though
```
tvdb_ep_name     : The Strongest Man in the World! Shutenmaru, the Thieves Brigade Chief!
tvdb_absolute_number: None
```

also why didn't my original attempts work too?!

**Comment by BrutuZ** [comment]
Tried both as in
```yaml
if:
  - has_field(tvdb_ep_name):
      ...
  - has_field(tvdb_absolute_number):
      ...
```
or
```yaml
if:
  - has_field(tvdb_ep_name) and has_field(tvdb_absolute_number):
      ...
```
The first will check one field at a time, try to set `content_filename` twice and fail as soon as tries to use an undefined field that wasn't the one checked.
The latter will check both at once and if either fail, skip the definition of `content_filename`

I'd recommend using fallback fields instead.
```yaml
tvdb_lookup: yes
tvmaze_lookup: yes
trakt_lookup: yes

set:
  - content_filename: '{{ tvdb_series_name|d(trakt_series_name)|d(tvmaze_series_name)|d(series_name) }} ...
```
Can't recall all equivalent field names from the top of my head while afk, nothing a quick check on the wiki pages for `tvmaze_lookup` and `trakt_lookup` can't solve.
