### ISSUE TITLE
Clean transmission rewriting fails on regexp

### ISSUE THREAD

**Issue by bewell** [Flexget/Flexget#2531]
### Expected behaviour:

The new version of clean transmission would filter out items from a defined directory

### Actual behaviour:
The items existing in the defined directory are not taken into account.
What am I doing wrong in my config?

I'm following the notes in [here ](https://flexget.com/Cookbook/TorrentCleanup)

#### Config:
```yaml
tasks:
  remove stale torrents:
    from_transmission:
      host: 192.168.10.5
      port: 8181
      username: admin
      password: admin
    disable: [seen, seen_info_hash]
    if:
      - transmission_progress == 100: accept
      - transmission_ratio < 1.0: reject
    regexp:
      reject_excluding:
        - "/data/Transmission/Incomplete/series"
    transmission:
      host: 192.168.10.5
      port: 8181
      username: admin
      password: admin
      action: remove
```
  
#### Log:
Log says that 
```
REJECTED by regexp plugin because regexp '/data/Transmission/Incomplete/series' didn't match
```

### Additional information:

- FlexGet version: newest
- Python version: 3.6.9
- Installation method: pip
- Using daemon (yes/no): No
- OS and version: Ubuntu

**Comment by gazpachoking** [comment]
I think you missed a bit from that wiki page:
```
    regexp:
      reject_excluding:
        - "/data/Transmission/Incomplete/series":
            from: transmission_downloadDir
```
https://flexget.com/Cookbook/TorrentCleanup#directories
