### ISSUE TITLE
limit not working with discover?!

### ISSUE THREAD

**Issue by snickers2k** [Flexget/Flexget#2540]
even quadrouple limit is not working... there is no further output neither. sorry.
```
    limit:
      amount: 200
      from:
        discover:
          what:
            - entry_list: Default
          limit:
            amount: 200
          from:
            - newznab:
                website: https://url.com
                apikey: '{? url.api ?}'
                category: 'movie'
          release_estimations: ignore
          limit: 20
```
