### ISSUE TITLE
Webui is "started" even when explicitly disabled

### ISSUE THREAD

**Issue by paranoidi** [Flexget/Flexget#2561]
### Expected behaviour:

No log messages about webui

### Actual behaviour:

```
2020-01-08 18:09:58 INFO     web_server                    Web interface available at http://127.0.0.1:3539
```

#### Config:
```
web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: no
```

Probably just a simple logging issue?
