### ISSUE TITLE
CRITICAL plugin LostFilm Received not 200 (OK) status

### ISSUE THREAD

**Issue by GreyKat** [Flexget/Flexget#2577]
> \# bin/flexget -V
>3.1.6
>You are on the latest release.

### Issue:
Since yesterday was getting this eror in log

> 2020-01-14 12:55:04 CRITICAL plugin        LostFilm        Received not 200 (OK) status
2020-01-14 12:55:04 WARNING  task          LostFilm        Aborting task (plugin: lostfilm)

### Fix:
https://github.com/Flexget/Flexget/pull/2576

**Comment by UglyAnimal** [comment]
I use 2.21.35 version and fix does not help. I get an error:
```
2020-01-15 19:49 CRITICAL task          lostfilm.tv     BUG: Unhandled error in plugin lostfilm: unsupported format string passed to HTTPError.__format__
Traceback (most recent call last):
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://www.lostfilm.tv/v_search.php?c=260&e=10&s=4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
TypeError: unsupported format string passed to HTTPError.__format__
``` 

My config is:
```
variables: private/secrets.yml
web_server:
  bind: 0.0.0.0 
  port: 8081 
  web_ui: yes
schedules:
  - tasks: '*'
    interval:
      minutes: 10
templates:
  notification:
    notify:
      entries:
        message: |+
          *{{series_name_rus|d(tvdb_series_name)|d(series_name)}}* рейтинг: {{tvdb_ep_rating|d('-')}}
          *{{episode_name_rus|d(tvdb_ep_name)|d('')}}*
          _{{series_season}} сезон {{series_episode}} серия_
          [Постер]({{tvdb_banner|d(tvdb_ep_image)}})
        via:
          - telegram:
             bot_token: '{? telegram.bot_token ?}'
             parse_mode: markdown
             recipients:
               - username: '{? telegram.username ?}'
             socks_proxy:
               url: '{? socks.url ?}'
               username: '{? socks.username ?}'
               password: '{? socks.password ?}'
  transmissionrpc:
   transmission:
      host: '{? transmissionlogin.host ?}'
      port: 9091
      username: '{? transmissionlogin.username ?}'
      password: '{? transmissionlogin.password ?}'
  tvshows:
    thetvdb_lookup: yes
    set:
      path: /volume1/video/TV Shows/{{series_name}}/{{series_season}}_Season
      label: TV Shows
    series_premiere: no
tasks:
  lostfilm.tv:
#    cfscraper: yes
#    verify_ssl_certificates: no
    template:
      - tvshows
      - transmissionrpc
      - notification
    headers:
      cookie:  '{? lostfilm.cookie_new ?}'
#      user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
    lostfilm: yes
    #lostfilm:
    #  url: http://retre.org/rssdd.xml
    #  url: https://lostfilm.tv/rss.xml
    regexp:
      reject:
        - The Complete
    quality: 
      - 1080p
    series:
       settings:
          main:
             tracking: yes
       series:
       - Elementary
       - Animal Kingdom
       - Lucifer
       - Billions
       - Supergirl
       - The Walking Dead
       - Six
       - I'm Dying Up Here
       - 13 Reasons Why
       - The 100
       - The Flash
       - Hawaii Five-0
       - Fear the Walking Dead
       - Modern Family
       - Blindspot
       - Agents of S.H.I.E.L.D.
       - Supernatural
       - Gotham
       - Arrow
       - The Blacklist
       - 9-1-1
       - Lethal Weapon
       - Homeland
       - Jessica Jones
       - Legends of Tomorrow
       - The Magicians
       - The Path
       - The Good Doctor
       - American Crime Story
       - This Is Us
       - McMafia
       - Knightfall
       - The Librarians
       - Vikings
       - Black Mirror
       - The Frankenstein Chronicles
       - Peaky Blinders
       - Dirk Gently's Holistic Detective Agency
       - Mr. Robot
       - Mindhunter
       - Stranger Things
       - American Horror Story
       - The Last Ship
       - Narcos
       - Preacher
       - Fargo
       - Better Call Saul
       - It's Always Sunny in Philadelphia
       - Sherlock
       - The Man in the High Castle
       - Scream
       - Riverdale
       - Ordeal by Innocence
       - The Looming Tower
       - Queen Of The South
       - The Purge
       - Mayans MC
       - Snatch
       - Ozark
       - The Rookie
       - Escape at Dannemora
```
