### ISSUE TITLE
Templates are not merged into tasks during execution

### ISSUE THREAD

**Issue by kozo8603** [Flexget/Flexget#2587]
### Expected behaviour:

When executing a task via CLI the template is merged into it, template's content is used within the task.

### Actual behaviour:
There is no template merging at all when executing the task. 
I use templates to match meta info to series, but when running the task, the execution simply ignores all templates, like if they weren't part of the config. 
This happens only on Ubuntu. My other machine is a Mac, which has the very same version of python and flex get, but everything runs normally.

### Steps to reproduce:
Starting the task from CLI:
`flexget --debug execute --task sort_series`

This behaviour appears on Ubuntu 18.04LTS, but when I try to run the very same config on osX, it runs normally, also the result is good.

#### Config:
```
templates:  
  series_meta_data:
    metainfo_series: yes
    thetvdb_lookup: yes
    imdb_lookup: yes
    trakt_lookup: yes

  series_guessit:
    parsing:
      series: guessit

  disable_seen_retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed

tasks:
  sort_series:
    template:
      - disable_seen_retry
      - series_metadata
      - series_guessit
    filesystem:
      path: "{? local.download_path ?}"
      regexp: '.*\.(rar|avi|mkv|mp4|m4v)$'
      recursive: yes
    accept_all: yes
    regexp:
      reject:
        - sample
        - trailer
    # proper_movies: yes
    require_field: [tvdb_series_name,tvdb_ep_name]
    copy:
      to: "{? local.series_target_dir ?}/{{ tvdb_series_name }}/Season {{ series_season|pad(2) }}/"
      rename: 'S{{ series_season|pad(2) }}E{{ series_episode|pad(2) }} - {{ tvdb_ep_name }}'
      along:
        extensions:
          - sub
          - srt
    list_clear:
      what:
        - entry_list: existing_series_list
    list_add:
      - entry_list: existing_series_list
```

#### --dump-config:
```
htpc@htpc:~$ ~/flexget/bin/flexget execute --debug --task sort_series --dump-config
2020-02-01 00:30:53 INFO     performance                   Enabling plugin and SQLAlchemy performance debugging
2020-02-01 00:30:53 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2020-02-01 00:30:53 VERBOSE  list_clear    sort_series     clearing all items from entry_list - existing_series_list
--- config from task: sort_series
accept_all: true
copy:
  along:
    extensions:
      - sub
      - srt
  rename: S{{ series_season|pad(2) }}E{{ series_episode|pad(2) }} - {{ tvdb_ep_name
    }}
  to: /mnt/MediaStore/Media/Series/{{ tvdb_series_name }}/Season {{ series_season|pad(2)
    }}/
disable:
  - seen
  - seen_info_hash
  - retry_failed
filesystem:
  path: /mnt/Data/Downloads
  recursive: true
  regexp: .*\.(rar|avi|mkv|mp4|m4v)$
imdb_lookup: true
list_add:
  - entry_list: existing_series_list
list_clear:
  phase: start
  what:
    - entry_list: existing_series_list
metainfo_series: true
parsing:
  series: guessit
regexp:
  reject:
    - sample
    - trailer
require_field:
  - tvdb_series_name
  - tvdb_ep_name
template:
  - disable_seen_retry
  - series_metadata
  - series_guessit
thetvdb_lookup: true
trakt_lookup: true

---
```
#### Log:
```
2020-02-01 00:43:10 INFO     performance                   Enabling plugin and SQLAlchemy performance debugging
2020-02-01 00:43:10 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2020-02-01 00:43:10 VERBOSE  list_clear    sort_series     clearing all items from entry_list - existing_series_list
2020-02-01 00:43:10 VERBOSE  filesystem    sort_series     Starting to scan folders.
2020-02-01 00:43:10 VERBOSE  filesystem    sort_series     Scanning folder /mnt/Data/Downloads. Recursion is set to True.
2020-02-01 00:43:11 VERBOSE  details       sort_series     Produced 875 entries.
2020-02-01 00:43:12 VERBOSE  series        sort_series     Found different quality for `Black.Mirror.S02.Special.White.Christmas.1080p.WEB-DL.DD2.0.H.264-CS`. Was `1080p webdl h264 dd5.1`, overriding with `1080p webdl h264`.
2020-02-01 00:43:13 VERBOSE  series        sort_series     Found different quality for `Fear.the.Walking.Dead.S03E09.WEB-DLRip.x264.HUN.ENG-Drew`. Was `webdl h264`, overriding with `webrip h264`.

```
### Additional information:

- FlexGet version: 3.1.15
- Python version: 3.6.9
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Ubuntu 18.04.3 LTS
- Link to crash log: N/A (not crashing, but doesn't functioning)
