### ISSUE TITLE
Cannot use variable number

### ISSUE THREAD

**Issue by junpet** [Flexget/Flexget#2592]
### Expected behaviour:
Insert number variable like `8090` into config.

### Actual behaviour:
You can insert only string with the Variables plugin.
### Steps to reproduce:
- Step 1: Set a number variable with the Variables plugin. Fort example, I'd like  to use save qBittorrent credentials. My variables look like:
```yml
qbittorrent:
  host: myhostname
  password: mypassword
  port: 8090
  username: myusername
```
- Step 2: Try the variables in the config. Without the `'` character the config file is invalid, with the `'` character there's an error, because the qBittorrent plugin expects integer, not string.
```yml
templates:
  qbittorrent:
    qbittorrent:
      host: '{? qbittorrent.host ?}'
      port: '{? qbittorrent.port ?}'
      username: '{? qbittorrent.username ?}'
      password: '{? qbittorrent.password ?}'
```

#### Config:
`variables.yml`
```yml
qbittorrent:
  host: myhostname
  password: mypassword
  port: 8090
  username: myusername
```
`config.yml`
```yml
templates:
  qbittorrent:
    qbittorrent:
      host: '{? qbittorrent.host ?}'
      port: '{? qbittorrent.port ?}'
      username: '{? qbittorrent.username ?}'
      password: '{? qbittorrent.password ?}'
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
[/templates/qbittorrent/qbittorrent/port] Got `{? qbittorrent.port ?}`, expected: integer
```
</details>

### Additional information:

- FlexGet version: 3.1.15 / 3.0.31
- Python version: 3.8.1 / 3.8.0
- Installation method: Docker
- Using daemon (yes/no): yes
- OS and version: Debian 10
- Link to crash log:
