### ISSUE TITLE
warning says task doesn't have any output plugins when sftp_download is set

### ISSUE THREAD

**Issue by ksurl** [Flexget/Flexget#2630]
### Expected behaviour:

no warning when running sftp task

### Actual behaviour:

2020-03-19 13:00:14 WARNING  task          sync-tv         Task doesn't have any output plugins, you should add (at least) one!

### Steps to reproduce:
- Step 1: run flexget task: flexget execute --tasks sync-tv

#### Config:
```
tasks:
  sync-tv:
    sftp_list:
      <<: *sftp_list
      dirs:
        - '{? remote.downloads ?}/tv/'
      recursive: true
    regexp:
      accept:
        -  '.*\.mkv$'
    free_space:
      <<: *free_space
      space: 1500
    sftp_download:
      to: '{? local.downloads ?}/tv/'
```

  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-03-19 13:00:14 WARNING  task          sync-tv         Task doesn't have any output plugins, you should add (at least) one!
```
</details>

### Additional information:

- FlexGet version: 3.1.25
- Python version: 3.6.9
- Installation method: virtualenv
- Using daemon (yes/no): yes
- OS and version: ubuntu 18.04.4
