### ISSUE TITLE
QbitTorrent Plugin is not setting use_ssl or verify_cert

### ISSUE THREAD

**Issue by salsa2k** [Flexget/Flexget#2655]
### Expected behaviour:

[QBitTorrent Plugin](https://flexget.com/Plugins/qbittorrent) has 2 properties that are not able to be set: **use_ssl** and **verify_cert**

### Actual behaviour:
`Message: The keys `use_ssl`, `verify_cert` are not valid here.`

### Steps to reproduce:
- Set **use_ssl** and **verify_cert** for qbittorrent plugin

#### Config:
```yaml
tasks:
 books:
    rss: https://my-feed.com/rss.php?cat=121,112&dllink=1
    accept_all: yes
    download: /downloads/books/

    qbittorrent:
        label: books
        host: 192.168.2.20
        port: 8080
        username: ******
        password: ******
        use_ssl: False
        verify_cert: False
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-04-19 13:45:27,208 DEBG 'flexget-script' stdout output:
2020-04-19 13:45 CRITICAL manager [/tasks/books/qbittorrent] The keys `use_ssl`, `verify_cert` are not valid here.
```
</details>

### Additional information:

- FlexGet version: 2.10.61 
- Installation method: https://registry.hub.docker.com/r/activ/arch-flexget/
