### ISSUE TITLE
No way to get filename from from_transmission anymore

### ISSUE THREAD

**Issue by afranke** [Flexget/Flexget#2659]
I used to run an old version of flexget and I am trying to upgrade to a current release. My old config relied on `location` from `from_transmission` to then do a `move`, but the newer flexget is not giving me `location` anymore. I looked at the current code and [there is a comment](https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/clients/transmission.py#L207) stating that location is only valid on local filesystems, so it’s not returning the file location in other cases. I was using `manipulate` to fix the location from remote path to local path (as the directory is mounted locally as well) so even if the location is not “valid” locally I still want it.

### Expected behaviour:

`from_transmission` gives me the `location` even if it’s not a local path. An acceptable substitute would be a `remote_location` or something similar to reflect the fact that it is not a local path.

### Actual behaviour:

`from_transmission` just drops `location` when transmission does not run locally.

### Steps to reproduce:

- Step 1: run transmission on a remote host
- Step 2: mount the download directory locally
- Step 3: try to configure flexget to move files when they’re done downloading

#### Config:

This is the configuration that used to work before the upgrade:
```yaml
accept_all: true
disable:
  - seen_info_hash
  - seen
from_transmission:
  host: 192.168.0.123
  username: myuser
  password: mypassword
  port: 9091
  only_complete: true
manipulate:
  - location:
      replace:
        format: /media/seedbox/
        regexp: /remote_path/
thetvdb_lookup: true
metainfo_series: true
move:
  rename: '{{ series_name }} {{ series_id }}{% if tvdb_ep_name %} - {{ tvdb_ep_name
    }}{% endif %}{{ location|pathext }}'
  to: "/media/seedbox/Vid\xE9os/S\xE9ries"
transmission:
  host: 192.168.0.123
  username: myuser
  password: mypassword
  port: 9091
  action: remove

```
</details>

### Additional information:

- FlexGet version: 3.1.51
- Python version: 3.7.6
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Fedora 31
