### ISSUE TITLE
Schedule Improvement

### ISSUE THREAD

**Issue by hrlmartins** [Flexget/Flexget#266]
Hi all,

Is it a feasible idea to extend the Schedule with an option to run a task within a range of hours (for instance 10am-5pm) and optionally its periodicity.

Lets take the following configuration as an example (with the new keys **between** and **with_interval**):

```
schedules:
  # Run any task starting with 'weekly_' on tuesdays hourly between 1pm and 3pm
  - tasks: 'weekly_*'
    interval:
      weeks: 1
      on_day: tuesday
      between: 1:00 pm - 3:00 pm
      with_interval: 60m #minutes which could be the default
```

This is an example, because I don't really know if its better to create new keys or use existing keys in different contexts, i.e., with_interval could be replaced with the existing minutes key, and the possibility to use in other scheduling combinations.

Thanks!
