### ISSUE TITLE
configure_series doesn't pass along alternate names from anilist

### ISSUE THREAD

**Issue by chbachman** [Flexget/Flexget#2672]
### Expected behaviour:

If a entry in a list has alternate names associated with it, those get passed along to the `alternate_name` field in the series created with configure_series.

### Actual behaviour:

No passing occurs.

### Steps to reproduce:
- Step 1: Have a plugin that generates alternate_names (anilist in this case, but it should work with others)
- Step 2: Pass the entries from that plugin into configure_series.
- Step 3: Note that the series doesn't have alternate names associated with it.

For example, anilist produces this entry:

```
title            : Kami no Tou: Tower of God
url              : https://anilist.co/anime/115230
original_url     : https://anilist.co/anime/115230
accepted_by      : accept_all
al_banner        : https://s4.anilist.co/file/anilistcdn/media/anime/banner/115230-wjDIxW77TLv3.jpg
al_cover         : https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx115230-aHcNrjMJkPnx.png
al_episodes      : 13
al_format        : TV
al_genres        : [Action, Adventure, Drama, Fantasy, Mystery]
al_idMal         : 40221
al_links         : [{'site': 'Twitter', 'url': 'https://twitter.com/anime_ToG'}, {'site': 'Twitter', 'url': 'https://twitter.com/tog_anime'}, {'site': 'Official Site', 'url': 'https://tog-anime.com/'}, {'site': 'VRV', 'url': 'https://vrv.co/series/G6J0G49DR/Tower-of-God'}, {'site': 'Crunchyroll', 'url': 'https://www.crunchyroll.com/tower-of-god'}]
al_list          : Watching
al_list_status   : Current
al_release_status: Releasing
al_tags          : [Tragedy, Super Power, Male Protagonist, Magic, Shounen, Circus, Conspiracy, Cultivation, Coming of Age, Ensemble Cast, Battle Royale, Politics, Tsundere, Swordplay]
al_title         : {'romaji': 'Kami no Tou: Tower of God', 'english': 'Tower of God'}
al_trailer       : https://www.youtube.com/embed/RNyClma6awo
alternate_name   : [Tower of God, タワーオブ・ゴッド, 신의 탑, Sinui Tap, Kami no Tou]
media_id         : None
original_title   : Kami no Tou: Tower of God
quality          : unknown
task             : fill-anilist
```

Which has the `alternate_name` field. This is then passed into configure_series, which doesn't add 'Tower of God' to the `alternate_name` fields of the series, making the later searches lose that information and not search for the alternate name.

#### Config:
```yaml
tasks:
  fill-anilist:
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    priority: 1
    list_clear:
      what:
        - entry_list: anime-tv
    anilist:
      username: username
      status:
        - current
    accept_all: yes
    list_add:
      - entry_list: anime-tv

  download-anime-tv-al:
    priority: 10
    configure_series:
      from:
        entry_list: anime-tv
      settings:
        identified_by: sequence
        special_ids:
          - OVA
    discover:
      release_estimations: ignore
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - nyaa:
            category: anime eng
```

### Additional information:

- FlexGet version: 3.1.51
- Python version: Python 3.7.3
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: macOS 10.15.4
- Link to crash log: N/A
