### ISSUE TITLE
Uning Trakt list with sequence in configure_series saves cache with last entry name

### ISSUE THREAD

**Issue by soloam** [Flexget/Flexget#2683]
### Expected behaviour and Actual behaviour:

This made me bump my head into walls for months, Sometimes I have entries form other lists entering the wrong task, and now I know that the problem is the cache from a task that configures the series (with parse_only: yes) with sequence, because I need to test with all my list. When I do this the cache form all the list is stored in the last list. Making that it's used later with that list is acceded in other tasks, returning all entries when it only should return the entries from that list

### Steps to reproduce:

Run Task1, and then Task2... In the task 2, the entries loaded form configure_series will be from cache and will be the result from list1 and list2, the actual name of the cache source file "Storing cache trakt_list_..." will be the same in both tasks.

#### Config:
```yaml

  Task1:
    configure_series:
      from:
        sequence:
          - trakt_list:
              account: '{? trakt.user ?}'
              type: shows
              list: 'list1'
          - trakt_list:
              account: '{? trakt.user ?}'
              type: shows
              list: 'list2'               
      settings:
        parse_only: yes

  Task2:
    configure_series:
      from:
        trakt_list:
          account: '{? trakt.user ?}'
          type: shows
          list: 'list2'          
      settings:
        parse_only: yes

```

### Additional information:

- FlexGet version: 3.1.56
- Python version: Python 3.7.3
- Installation method: venv
- Using daemon (yes/no): yes
- OS and version: Debian10

**Comment by soloam** [comment]
I was able to make a workarround (a little hack) creating a dummy list in trakt (that I don't use in any task) and put it in last in the sequence, this makes the content from the cache to be stored in reference to that list.
```yaml

  Task1:
    configure_series:
      from:
        sequence:
          - trakt_list:
              account: '{? trakt.user ?}'
              type: shows
              list: 'list1'
          - trakt_list:
              account: '{? trakt.user ?}'
              type: shows
              list: 'list2'           
          - trakt_list:
              account: '{? trakt.user ?}'
              type: shows
              list: 'dummy_list'       
      settings:
        parse_only: yes
```

**Comment by plittlefield** [comment]
I am wondering whether this is happening to me.

I'm trying out Trakt as a source of my list of TV Shows I watch and want to watch.

I created a Trakt list called (rather imaginatively) 'flexget' to add TV Shows I would like.

```
templates:
  tv:
    series_premiere: no
    magnets: yes
    configure_series:
      from:
        trakt_list:
          username: xxxxxxx
          account: xxxxxxx
          list: flexget
          type: shows
      settings:
        quality: 720p
```

It worked first time, picking up a show and adding it to Transmission... great! I thought.

`2020-05-21 10:44:21 VERBOSE  trakt_list    eztvio-tv       Retrieving shows list flexget`

I've since added 2 more shows and know that there are torrents in my source RSS feeds but Flexget is not showing anything in the log.

I have cheked my Authentication with this and it passes...

`~/flexget3/bin/flexget trakt list`

What am I doing wrong?

How can I test that Flexget is grabbing the 3 TV shows I have in that list?

Thanks,

Paully
