### ISSUE TITLE
sftp fails to connect with pysftp 0.2.9

### ISSUE THREAD

**Issue by ksurl** [Flexget/Flexget#2686]
### Expected behaviour:

successful sftp connection with latest version of pysftp, 0.2.9.

### Actual behaviour:

fails to connect. works on pysftp 0.2.8.

### Steps to reproduce:
- Step 1: create ssh key: `ssh-keygen -t rsa -b 2048`
- Step 2: `flexget --loglevel debug execute sync`

#### Config:
```yaml
sync:
  sftp_list:
    host: '{? sftp.host ?}'
    port: '{? sftp.port ?}'
    username: '{? sftp.username ?}'
    private_key: '{? sftp.private_key ?}'
    dirs:
      - '{? remote.downloads ?}/'
    recursive: true
  regexp:
    accept:
      -  '.*\.mkv$'
  free_space:
    <<: *free_space
    space: 1500
  sftp_download:
    to: '{? local.downloads ?}/'
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-05-26 08:28:04 DEBUG    sftp_client   sync         Caught exception: No hostkey for host $IP_ADDRESS found.
2020-05-26 08:28:04 WARNING  sftp_client   sync         Failed to connect to $IP_ADDRESS; waiting 15 seconds before retrying.
```
</details>

### Additional information:

- FlexGet version: 3.1.57
- Python version: 3.6.9
- Installation method: virtualenv
- Using daemon (yes/no): yes
- OS and version: Ubuntu 18.04.4
- Other info: hostkey can be ignored or set to a custom file with CnOpts attributes in pysftp connection object according to the docs. it defaults to ~/.ssh/known_hosts. I've manually ssh'd from the flexget server to my target server before so it should have already cached the host key in known_hosts
