### ISSUE TITLE
YAML validator misses type issues on values injected by Variables plugin

### ISSUE THREAD

**Issue by ianstalk** [Flexget/Flexget#2687]
If you use the variables plugin, you can specify a string in a number-valued field, and it will pass validation so long as the string value is numeric (e.g. `"22"` will pass validation but `"aaa"` will not). Passing in the wrong type can sometimes produce subtle bugs such as the one described in https://github.com/Flexget/Flexget/issues/2686 .

### Expected behaviour:
I would expect to see an error like this on task start:
```
2020-05-26 13:23:39 CRITICAL manager                       [/tasks/sftp_list/sftp_list/port] Got `22`, expected: integer
```

The above is the behavior I see when the value is specified directly in my configuration.

### Actual behaviour:
The task starts

### Steps to reproduce:
- Specify a variable and reference it in a number-valued config field

#### Config:
 `variables.yml`
```yaml
sftp:
    port: "22"
```

`config.yml`
```yaml
variables: variables.yml

tasks:
    sftp_list_test:
        sftp_list:
            host: 192.168.182.3
            username: ieaston
            private_key: ~/.ssh/id_rsa
            dirs: test
            port: '{? sftp.port ?}'
```
