### ISSUE TITLE
Failure when adding already existing torrents to qBittorrent

### ISSUE THREAD

**Issue by grainz** [Flexget/Flexget#2701]
### Expected behaviour:
Skip already added torrents

### Actual behaviour:
Entire task errors when attempting to add torrents to qBittorrent
### Steps to reproduce:
- Step 1: Add torrents to qBittorrent that are new
- Step 2: Add the same torrents to qBittorrent

#### Config:
```yaml
templates:
  TT:
    if:
      - rss_pubdate|formatdate("%d")|int >= 1 and rss_pubdate|formatdate("%d")|int <= 7:
          qbittorrent:
            label: "{{category|replace('Singles - ','')}}/{{rss_pubdate|formatdate('%Y/%m')}}/01"
            path: /mnt/user/TT/{{category|replace('Singles - ','')}}/{{rss_pubdate|formatdate("%Y/%m")}}/01
      - rss_pubdate|formatdate("%d")|int >= 8 and rss_pubdate|formatdate("%d")|int <= 14:
          qbittorrent:
            label: "{{category|replace('Singles - ','')}}/{{rss_pubdate|formatdate('%Y/%m')}}/02"
            path: /mnt/user/TT/{{category|replace('Singles - ','')}}/{{rss_pubdate|formatdate("%Y/%m")}}/02
      - rss_pubdate|formatdate("%d")|int >= 15 and rss_pubdate|formatdate("%d")|int <= 21:
          qbittorrent:
            label: "{{category|replace('Singles - ','')}}/{{rss_pubdate|formatdate('%Y/%m')}}/03"
            path: /mnt/user/TT/{{category|replace('Singles - ','')}}/{{rss_pubdate|formatdate("%Y/%m")}}/03
      - rss_pubdate|formatdate("%d")|int >= 22 and rss_pubdate|formatdate("%d")|int <= 31:
          qbittorrent:
            label: "{{category|replace('Singles - ','')}}/{{rss_pubdate|formatdate('%Y/%m')}}/04"
            path: /mnt/user/TT/{{category|replace('Singles - ','')}}/{{rss_pubdate|formatdate("%Y/%m")}}/04
      - "now|formatdate('%Y') in title": accept
tasks:
  Trance:
    rss:
      url: <url>
      other_fields: [rss_pubdate,category]
      all_entries: no
    template: TT
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2020-06-18 07:56:33 CRITICAL plugin        Trance          Error when trying to send request to qBittorrent: Failed to add file to qBittorrent
```
</details>

### Additional information:

- FlexGet version: 3.1.64
- Python version: Python 3.8.3
- Installation method: virtualenv from install guide
- Using daemon (yes/no): both
- OS and version: Debian unstable
- Link to crash log:
