### ISSUE TITLE
Pyload, error when checking version.

### ISSUE THREAD

**Issue by luizoti** [Flexget/Flexget#2711]
When there are accepted entries and the version check, an error occurs, I put it in the pastbin, the error aparently is related with this PR  #2642

### Expected behaviour:
Add entries and download.

### Actual behaviour:
PASTBIN: https://pastebin.com/R3Hk3zSh

### Steps to reproduce:
- Step 1: ...
When I run a task with the pyload plugin and there are accepted entries.

#### Config:
```yaml--- config from task: pyload
accept_all: true
metainfo_series: true
pyload:
  api: http://localhost:8000/api
  enabled: true
  folder: /media/luiz/HD/Downloads
  hoster:
    - MegauploadComFolder
    - MegauploadCom
    - ZippyshareCom
  package: '{{series_name}} - {{tvdb_series_name}}'
  parse_url: true
  password: admin
  queue: true
  username: luiz
rss:
  all_entries: true
  ascii: false
  escape: false
  group_links: false
  silent: false
  url: /home/luiz/.flexget/rss.xml
thetvdb_lookup: true
trakt_lookup: true

---

```
  
#### Log:
<details>
 <summary>https://pastebin.com/R3Hk3zSh</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 3.1.67.dev
- Python version: Python 3.8.2
- Installation method: git venv
- Using daemon (yes/no): yes
- OS and version: Linux HP 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Link to crash log: https://pastebin.com/R3Hk3zSh
