### ISSUE TITLE
Html plugin does not catch the torrent urls on eztv

### ISSUE THREAD

**Issue by FranPregernik** [Flexget/Flexget#272]
Hi,

because of this line:
https://github.com/Flexget/Flexget/blob/develop/flexget/plugins/input/html.py#L171

the torrent links on eztv pages (e.g. http://eztv.it/shows/481/game-of-thrones/) are skipped. See the config below.

Can this check be enabled/disabled by a flag on the html plugin config? Or even if title_from == 'url' then to skip this check altogether.

```yml
tasks:
  task name:
    html:
      url: http://eztv.it/shows/481/game-of-thrones/
      title_from: url
      links_re:
        - piratebaytorrents\.info.*\.torrent
        - extratorrent\.cc.*\.torrent
        - rarbg\.com.*\.torrent
    download: .
```
