### ISSUE TITLE
trakt_list occasionally caused exception 

### ISSUE THREAD

**Issue by programatix** [Flexget/Flexget#2741]
### Expected behaviour:

I have 2 tasks to fill the movie list from traktv.

### Actual behaviour:

The first one always runs successful but the 2nd one may fail with exception. From the logs, there seems to be 2 types of exceptions.

```requests.exceptions.HTTPError: 521 Server Error: Web Server Is Down for url: https://api.trakt.tv/sync/watchlist/movies?limit=1000&page=1```
and
```requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.trakt.tv/sync/watchlist/movies?limit=1000&page=1```

### Steps to reproduce:
- Step 1: run the tasks.

#### Config:
```yaml
tasks:
  fill-movies-queue:
    priority: 32
    trakt_list:
      username: "{? trakt.username ?}"
      account: "{? trakt.account ?}"
      list: "{? trakt.list ?}"
      type: movies
    accept_all: yes
    list_add:
      - movie_list: movies

  fill-movies-2nd-queue:
    priority: 32
    trakt_list:
      username: "{? trakt_2nd.username ?}"
      account: "{? trakt_2nd.account ?}"
      list: "{? trakt_2nd.list ?}"
      type: movies
    accept_all: yes
    list_add:
      - movie_list: movies

schedules:
  - tasks: ['fill-*','*-discover']
    schedule:
      hour: '*/2'
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>
2020-09-29 08:00:02 DEBUG    task          fill-movies-queue executing fill-movies-queue
2020-09-29 08:00:02 DEBUG    template      fill-movies-queue Merging template notifyFailedEntriesViaEmail into task fill-movies-queue
2020-09-29 08:00:02 DEBUG    input_cache   fill-movies-queue cache name: trakt_list_...(has: )
2020-09-29 08:00:02 DEBUG    input_cache   fill-movies-queue storing entries to cache trakt_list_...
2020-09-29 08:00:02 VERBOSE  trakt_list    fill-movies-queue Retrieving `movies` list `watchlist`
2020-09-29 08:00:02 DEBUG    utils.requests fill-movies-queue GETing URL https://api.trakt.tv/sync/watchlist/movies with args () and kwargs {'params': {'limit': 1000, 'page': 1}, 'allow_redirects': True, 'timeout': 30}
2020-09-29 08:00:03 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.
2020-09-29 08:00:03 DEBUG    scheduler                     task finished executing: fill-movies-2nd-queue
Traceback (most recent call last):
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/components/trakt/trakt_list.py", line 203, in get_items
    db.get_api_url(endpoint), params={'limit': limit_per_page, 'page': page}
  File "/var/packages/python3/target/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/utils/requests.py", line 265, in request
    result.raise_for_status()
  File "/var/packages/python3/target/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.trakt.tv/sync/watchlist/movies?limit=1000&page=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/task.py", line 80, in wrapper
    return func(self, *args, **kw)
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/task.py", line 710, in execute
    self._execute()
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/task.py", line 676, in _execute
    self.__run_task_phase(phase)
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/task.py", line 505, in __run_task_phase
    for e in response:
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/utils/cached_input.py", line 220, in __iter__
    for item in self.iterable:
  File "/var/packages/python3/target/lib/python3.7/site-packages/flexget/components/trakt/trakt_list.py", line 311, in get_items
    raise plugin.PluginError('Could not retrieve list from trakt (%s)' % e)
flexget.plugin.PluginError: Could not retrieve list from trakt (502 Server Error: Bad Gateway for url: https://api.trakt.tv/sync/watchlist/movies?limit=1000&page=1)
</details>

### Additional information:

- FlexGet version: 3.1.71
- Python version: 3.5.1
- Installation method: pip install
- Using daemon (yes/no): yes
- OS and version: Synology DSM 6
