### ISSUE TITLE
TorrentDay search result empty or malformed

### ISSUE THREAD

**Issue by programatix** [Flexget/Flexget#2742]
### Expected behaviour:

Search result
![image](https://user-images.githubusercontent.com/3293865/94644622-67c71500-031c-11eb-86d9-a9cd983dee1f.png)

### Actual behaviour:

Search result empty or malformed.

### Steps to reproduce:
- Step 1: run task

#### Config:
```yaml
  download-childrenshow-discover:
    template:
      - cartoon-metainfo
      - reject
      - children_show
      - notifyViaEmail
    discover:
      what:
        - next_series_seasons:
            from_start: yes
        - next_series_episodes:
            backfill: true
            from_start: yes
      from:
        - torrentday:
            uid: "'{? torrentday.uid ?}'"
            passkey: "{? torrentday.passkey ?}"
            cfduid: "{? torrentday.cfduid ?}"
            rss_key: "{? torrentday.rss_key ?}"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

2020-09-30 12:39:49 VERBOSE  discover      download-childrenshow-discover Searching for `Vampirina S02` with plugin `torrentday` (1 of 7)
2020-09-30 12:39:49 DEBUG    utils.requests download-childrenshow-discover GETing URL https://www.torrentday.com/t with args () and kwargs {'params': {'cata': 'yes', 'c7': 1, 'clear-new': 1, 'q': 'Vampirina S02'}, 'cookies': {'uid': '...', 'pass': '...', '__cfduid': '...'}, 'allow_redirects': True, 'timeout': 30}
2020-09-30 12:39:50 ERROR    discover      download-childrenshow-discover Error searching with torrentday: Search returned by torrentday appears to be empty or malformed.
2020-09-30 12:39:50 VERBOSE  discover      download-childrenshow-discover No search results for `Vampirina S02`

</details>

### Additional information:

- FlexGet version: 3.1.71
- Python version: 3.5.1
- Installation method: pip install
- Using daemon (yes/no): yes
- OS and version: Synology DSM 6
