### ISSUE TITLE
BUG: Unhandled exception during task queue run loop.

### ISSUE THREAD

**Issue by specie77** [Flexget/Flexget#2768]
### Expected behaviour:
Populate the seen db with everything already on my server.

### Actual behaviour:
When running from Synology Task Scheduler this log entry is returned:
2020-10-27 15:56:34 CRITICAL task_queue                    BUG: Unhandled exception during task queue run loop.

Crash Report:
Two crash reports created but both are blank, which is very strange.

### Steps to reproduce:

Error only occurs when run by Synology Task Scheduler

(Ran with --loglevel TRACE for issue reporting benefit, typically run with --loglevel INFO
Synology Task Scheduler: 
#!/bin/sh
exec /opt/bin/flexget --loglevel TRACE execute --tasks Populate_TV_DB

When run with SSH CLI, everything is fine:
flexget --loglevel TRACE execute --tasks Populate_TV_DB

[Log - SSH Shell Worked Successfully.txt.zip](https://github.com/Flexget/Flexget/files/5448089/Log.-.SSH.Shell.Worked.Successfully.txt.zip)

#### Config:
<details>
 <summary>Config</summary>

```yaml
schedules: no

#schedules:
##correct syntax: [task1, task2] all tasks go inside one set of brackets, separated by commas
#  - tasks: [Populate_TV_DB, Get_TV]
#    interval:
#      hours: 2
#  - tasks: [Populate_Movie_DB, Get_Movies]
#    interval:
#      hours: 12
#  - tasks: Trans_Clean_Up
#    interval:
#      hours: 6

templates:
  C_Find_TV:
#    content_size:
#      min: 85
    discover:
      what:
        - next_series_episodes:
            from_start: yes
            backfill: yes
      from:
        - piratebay:
            category: video
            sort_by: seeds
            url: https://openpirate.org
        - rarbg:
            category: [18]
          #  category: [18, 41]
            use_tvdb: True
            ranked: False
            min_seeders: 2

  C_Transmit_TV:
    transmission:
      host: xxxxxx
      port: xxxxxx
      username: xxxxxx
      password: xxxxxx
      path: /torrents/completed/xxxxxx/TV

  C_Transmit_Movies:
    transmission:
      host: xxxxxx
      port: xxxxxx
      username: xxxxxx
      password: xxxxxx
      path: /torrents/completed/xxxxxx/Movies

  C_Get_Movies:
    discover:
      what:
        - movie_list: xxxxxx_IMDB_Movies
      from:
        - piratebay:
            category: 207 #HD - Movies #originally: highres movies
            sort_by: seeds
            url: https://openpirate.org
        - rarbg: 
            category: [44, 45, 48]
            ranked: False
            min_seeders: 2
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.m4v'
        - '*.mp4'
      reject:
        - 'password.txt'
        - '*.rar'
        - '*.r00'
        - '*.zip'
        - '*.wmv'
    imdb_lookup: yes
    list_match:
      from:
        - movie_list: xxxxxx_IMDB_Movies
    
tasks:
  Populate_TV_DB:
    #Note: can't use manual, must run before GET_TV
    #Note: or GET_TV will find duplicates
    priority: 1
    seen: local
    filesystem:
      path: /volume1/Media/TV
      recursive: yes
      retrieve: 
        - files
        - dirs
      regexp: .*\.(avi|mkv|m4v|mp4)$
    accept_all: yes
    configure_series:
      from:
        filesystem:
          path: /volume1/Media/TV
          recursive: yes
          retrieve: dirs
      settings:
        season_packs: yes
        tracking: no #means flexget will allow files in any order
        identified_by: ep

  Get_TV:
    priority: 2
    template:
      - C_Find_TV
      - C_Transmit_TV
    configure_series:
      from:
        filesystem:
          path: /volume1/Media/TV
          recursive: yes
          retrieve: dirs
      settings:
        season_packs: yes
        tracking: no #means flexget will allow files in any order
        quality: 576p webrip-dvdrip h264-h265
        target: 720p h265
        timeframe: 4 hours
        upgrade: yes
        identified_by: ep
    assume_quality:
      hdtv: 576p hdtv
      webrip: 576p webrip
      webdl: 576p webdl
      xvid: 576p xvid
    regexp:
      reject:
        - SweSub
        - NorSub
        - ShAaNiG
        - FreSub
        - NLSubs
        - SUB
        - FRENCH
        - iTALiAN
        - GERMAN
        - CENSORED
        - SCREENER
        - LATINO
        - DUAL
        - Subtitulado
        - dublado
        - torrenting.
        - Torrenting.
        - torrentday.
        - ultimate-torrent.
        - FASTSUB #French
        - VOSTFR #French
        - Subtitulado #Spanish
        - Special-Wicked #Special trailer episodes from Once Upon a Time

  Populate_Movie_DB:
    priority: 3
    imdb_watchlist:
      user_id: xxxxxx
      list: xxxxxx
      force_language: en-us
    accept_all: yes
    list_add:
      - movie_list: xxxxxx_IMDB_Movies
    exists_movie:
      path: 
        - /volume1/Media/Movies
      type: files
      lookup: imdb

  Get_Movies:
    priority: 50
    template:
      - C_Get_Movies
      - C_Transmit_Movies
    content_size:
      max: 3072 # 3.0 GB
      min: 1024 # 1.0 GB
    quality: 
      1080p webrip+ h265

  Trans_Clean_Up:
    from_transmission:
      host: xxxxxx
      port: xxxxxx
      username: xxxxxx
      password: xxxxxx
    disable: [seen, seen_info_hash]
    if:
      - transmission_progress == 100: accept
    transmission:
      host: xxxxxx
      port: xxxxxx
      username: xxxxxx
      password: xxxxxx
      action: remove

```
</details>

#### Log:
<details>
 <summary>Run with trace, very long log files, sorry</summary>

```
See attached files
```
[flexget.2020-10-27_15-55-34_346948.log](https://github.com/Flexget/Flexget/files/5448038/flexget.2020-10-27_15-55-34_346948.log)
[flexget.2020-10-27_15-55-39_818923.log](https://github.com/Flexget/Flexget/files/5448039/flexget.2020-10-27_15-55-39_818923.log)
[flexget.2020-10-27_15-55-44_959540.log](https://github.com/Flexget/Flexget/files/5448040/flexget.2020-10-27_15-55-44_959540.log)
[flexget.2020-10-27_15-55-51_300070.log](https://github.com/Flexget/Flexget/files/5448041/flexget.2020-10-27_15-55-51_300070.log)
[flexget.2020-10-27_15-55-56_367600.log](https://github.com/Flexget/Flexget/files/5448042/flexget.2020-10-27_15-55-56_367600.log)
[flexget.2020-10-27_15-56-05_091885.log](https://github.com/Flexget/Flexget/files/5448044/flexget.2020-10-27_15-56-05_091885.log)
[flexget.2020-10-27_15-56-09_079870.log](https://github.com/Flexget/Flexget/files/5448045/flexget.2020-10-27_15-56-09_079870.log)
[flexget.2020-10-27_15-56-12_849082.log](https://github.com/Flexget/Flexget/files/5448046/flexget.2020-10-27_15-56-12_849082.log)
[flexget.2020-10-27_15-56-16_787647.log](https://github.com/Flexget/Flexget/files/5448047/flexget.2020-10-27_15-56-16_787647.log)
[flexget.log](https://github.com/Flexget/Flexget/files/5448048/flexget.log)

</details>

### Additional information:

- FlexGet version: 3.1.82
- Python version: 3.6.2
- Installation method: pip following these instructions: https://flexget.com/InstallWizard/SynologyNAS/PythonPackage
- Using daemon (yes/no): not for this failure but the same thing happens with daemon
- OS and version: Synoogy DSM 6.2.3-25426 Update 2
- Link to crash log: they came out blank for some reason, github wouldn't let me upload blank files.
