### ISSUE TITLE
PTP Plugin parameters have no impact on search results

### ISSUE THREAD

**Issue by bagobones** [Flexget/Flexget#2788]
### Expected behaviour:

The following parameters should have drastic impact on the results returned.
 order_by: see below
 order_desc: yes|no (default yes)
 grouping: yes|no (default yes)

### Actual behaviour:

 order_by: see below
 order_desc: yes|no (default yes)
 grouping: yes|no (default yes)

No change in order of results, grouping of results happens.. It seems that results are always returned in the same order which often results in the lowest quality versions to be the first to fill up the results.

### Steps to reproduce:
- Step 1: ...

#### Config:
```yaml

  test_ptp:
    manual: yes
    disable: seen
    imdb_lookup: yes
    tmdb_lookup: yes
    quality: 720p-1080p
    domain_delay:
      passthepopcorn.me: 5 seconds
    discover:
      release_estimations: ignore
      what:
        - mock:
          - {title: 'The Thing 1982'}
      from:
        - passthepopcorn:
            username: '{? ptp.username ?}'
            password: '{? ptp.password ?}'
            passkey: '{? ptp.passkey ?}'
            order_by: Seeders
            grouping: no

    if:
      - torrent_seeds <= 0 : reject
    set:
      label: Movies
      path: /media/Video/Movies/
      title: "{{original_title|replace('4K','')}} [ {{ptp_source}} {{ptp_resolution|replace('PAL','576p')|replace('NTSC','480p')|replace('x','p ')}} {{ptp_codec}} ]"
    exec: echo "Found T:{{title}} Q:{{quality}} L:[{{label}}] P:[{{path}}] G:{{tmdb_genres}}" 
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 3.1.91
- Python version:
- Installation method:
- Using daemon (yes/no): yes
- OS and version: docker
- Link to crash log:
