### ISSUE TITLE
transmission-rpc and "skip_files" option skipped everything

### ISSUE THREAD

**Issue by programatix** [Flexget/Flexget#2806]
### Expected behaviour:
Only skipped the files in the list.

### Actual behaviour:
All files are skipped, thus the torrent is immediately put into seeding mode with no file selected. Removing the `skip_files` option resolved the issue.

This issue start after I updated flexget and it requires `transmission-rpc`. After uninstalling `transmissionrpc` and installed `transmission-rpc` this issue is seen because I have the `skip_files` option in `transmission`

### Steps to reproduce:
- Step 1: Add the following and run
```
    transmission:
      ratio: 0
      skip_files:
        - 'RARBG.mp4'
        - 'RARBG.txt'
        - 'RARBG.com.txt'
        - 'RARBG.COM.mp4'
        - 'RARBG.COM.txt'
        - 'RARBG.COM.exe'
        - '[sS]ample'
```

#### Config:
```
  transmissionRPC:
    transmission:
      host: '{? transmission.host ?}'
      port: '{? transmission.port ?}'
      username: '{? transmission.usr ?}'
      password: '{? transmission.pwd ?}'
      ratio: 0
      skip_files:
        - 'RARBG.mp4'
        - 'RARBG.txt'
        - 'RARBG.com.txt'
        - 'RARBG.COM.mp4'
        - 'RARBG.COM.txt'
        - 'RARBG.COM.exe'
        - '[sS]ample'
```
  
### Additional information:

- FlexGet version: 3.1.98
- Python version: 3.7.7
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: synology dsm 6
