### ISSUE TITLE
Bug: Quality plugin DTS > DTS-HD

### ISSUE THREAD

**Issue by frankyw** [Flexget/Flexget#2808]
### Expected behaviour:

You could argue this is a bug (quality plugin does not work as intended) or a feature request (works as implemented)...

DTS-HD files are higher quality that DTS, and so setting quality to "dts+" should result in files tagged "dts-hd" being accepted

http://www.differencebetween.net/technology/protocols-formats/differences-between-dts-and-dts-hd

> To be more precise, DTS is usually found on a DVD Disc whereas DTS HD is found on a Blu-ray Disc. The latter is for sure superior to the former in terms of quality.

Also incorrectly sorted at https://flexget.com/Qualities

### Actual behaviour:

DTS-HD files are rejected.

### Steps to reproduce:
Step 1: Set audio quality to DTS+
Step 2: Files with audio quality DTS-HD are rejected.

#### Config:
```yaml
root@3d0e9c41428e:/config# flexget execute --task search-movies --dump-config
There is a FlexGet process already running for this config, sending execution there.
--- config from task: search-movies
cfscraper: true
content_size:
  max: 80000
  min: 8000
  strict: false
discover:
  from:
    - torrentleech:
        category:
          - 14
          - 37
          - 47
        password: xxxx
        rss_key: xxxxx
        username: xxxxx
    - iptorrents:
        category:
          - 48
          - 20
          - 100
          - 101
        free: false
        password: xxxx
        rss_key: xxxx
        uid: xxxx
  interval: 6 hours
  release_estimations: loose
  what:
    - movie_list: Movies
free_space:
  allotment: -1
  path: /storage
  port: 22
  space: 20000
if:
  - trakt_collected: reject
  - trakt_watched: reject
imdb_lookup: true
include: reject.yml
list_match:
  action: accept
  from:
    - movie_list: Movies
  remove_on_match: true
  single_match: true
pathscrub: windows
priority: 20
proper_movies: false
quality: 2160p webdl+ dts+
regexp:
  reject:
    - \bR5\b:
        from: title
    - \bWEBSCR\b:
        from: title
    - \bscreener\b:
        from: title
    - \bTS\b:
        from: title
    - \bCam\b:
        from: title
    - \bITA\b:
        from: title
    - \bGERMAN\b:
        from: title
    - \bFRENCH\b:
        from: title
    - \bRUS\b:
        from: title
    - \bHC\b:
        from: title
    - \bREMUX\b:
        from: title
    - \bBDRiP\b:
        from: title
    - \bSUBFRENCH\b:
        from: title
sort_by:
  field: quality
  reverse: true
template:
  - global-settings
  - movie-settings
tmdb_lookup: true
trakt_lookup:
  account: xxxx
  username: xxxx
transmission:
  host: transmission
  password: xxxx
  port: 9091
  username: xxxxx
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2021-01-16 09:57:07 VERBOSE  task          search-movies   REJECTED: `Tenet 2020 IMAX 2160p BluRay HEVC DTS-HD MA 5 1-ESiR` by quality plugin because `2160p bluray h265 dtshd` does not match any of quality requirements: `2160p webdl+ dts+`
2021-01-16 09:57:07 VERBOSE  task          search-movies   REJECTED: `Tenet 2020 2160p UHD BluRay DTS-HD MA 5 1 HDR x265-CtrlHD` by quality plugin because `2160p bluray h265 dtshd` does not match any of quality requirements: `2160p webdl+ dts+`
```
</details>

### Additional information:

- FlexGet version: 3.1.98
- Python version:
- Installation method:
- Using daemon (yes/no):
- OS and version:
- Link to crash log:
