### ISSUE TITLE
 Could curl commands be added to the docker version？

### ISSUE THREAD

**Issue by Oscar1011** [Flexget/Flexget#2810]
### Expected behaviour:

 I want to use  curl  in  “exec:” on docker . Because some third notify use a url.
### Actual behaviour:
  docker version doesn't have curl commands.

### Steps to reproduce:
- Step 1: ...
  just use curl in exec

#### Config:
```yaml
    exec:
      auto_escape: yes
      on_output:
        for_accepted:  curl "url"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
INFO exec move-episodes Stdout: /bin/sh: curl: not found
```
</details>

### Additional information:

- FlexGet version:
- Python version:
- Installation method:
- Using daemon (yes/no):
- OS and version:
- Link to crash log:
