### ISSUE TITLE
trakt_lookup plugin doesn't honor the CLI argument --no-cache

### ISSUE THREAD

**Issue by girtsl** [Flexget/Flexget#2823]
This might not be a bug per-se but rather a missing feature or undesired behavior. I would also be happy if somebody described to me a better approach for what I'm after. Might be related to #2667 in some way. 

### Expected behaviour:

I guess it can be boiled down to "trakt_lookup plugin honors the CLI argument `--no-cache`" as that was the solution I thought of when attempting to fix my issue and dropping down to the CLI. My expectation was that cache would be skipped and trakt lookup would be performed directly against trakt.

### Actual behaviour:

In my specific scenario I have a daily task that checks my trakt watchlist and moves all ended/canceled shows to an "ended" list. 
Troubles start when trakt make a mistake and incorrectly mark a returning show as e.g. ended - this has happened before and more recently it happened to "True Detective". When I noticed it had happened I checked their presumed sources - TVDB and TMDB (also imdb, wiki, etc.) and this show was not marked as ended, so who knows how/why they did that. Some time later trakt corrected their error and set the show back as "returning series". At that time I manually moved the show back to the watchlist only for it to be picked up by my cleanup task again and moved to the "ended" list. 
This was unexpected and made me check the logs and eventually lead me to finding this bit of code - https://github.com/Flexget/Flexget/blob/develop/flexget/components/trakt/db.py#L750-L755. The comment and caching strategy make perfect sense in a normal scenario but unfortunately not when trakt make an error - as described above.
I haven't checked but there is probably a way out of this by fiddling with the db (e.g. deleting the cache entry if I could find it), however, I would prefer a bit more user-friendly approach - a possibility to disable the cache for a task or something CLI-based.

### Steps to reproduce:
I guess the scenario could be reproduced by first preparing the cache in a certain way. I.e. put a show entry in the cache with status=ended while the trakt API would return "returning series".

#### Config:
```yaml
  clean-up-ended-shows:
    priority: 2   
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.tv_watchlist ?}'
      type: shows
    trakt_lookup: yes
    disable: seen #is necessary to not get cross-contamination effects with caching
    if:
      - trakt_series_status in ['ended', 'canceled']: accept
    list_add:
      - trakt_list:
          account: '{? trakt.account ?}'
          list: '{? trakt.collected_shows ?}'
          type: shows
    list_remove:
      - trakt_list:
          account: '{? trakt.account ?}'
          list: '{? trakt.tv_watchlist ?}'
```
  
#### Log:

```
2021-01-26 17:13:19 DEBUG    api_trakt     clean-up-ended-shows show `True Detective` age 7 expires in 37 days
2021-01-26 17:13:19 DEBUG    if            clean-up-ended-shows True Detective (2014) matched requirement trakt_series_status in ['ended', 'canceled']
2021-01-26 17:13:19 VERBOSE  task          clean-up-ended-shows ACCEPTED: `True Detective (2014)` by if plugin because matched requirement: trakt_series_status in ['ended', 'canceled']
```

### Additional information:

- FlexGet version: 3.1.100
- Python version: 3.7.7
- Installation method: container
- Using daemon (yes/no): yes
