### ISSUE TITLE
descargas2020.py is broken

### ISSUE THREAD

**Issue by tonika1** [Flexget/Flexget#2824]
[descargas2020.txt](https://github.com/Flexget/Flexget/files/5875174/descargas2020.txt)

### Actual behaviour:
Hi!!!
The website descargas2020.org doesn't exist. The new websites are pctmix.com and pctmix1.com 
### Steps to reproduce:
- Step 1: ...
Use this rss: https://www.synologia.com/rss/pctmix.com

#### Config:
```yaml
templates:
  global:
    free_space:
      path: /media/multi
      space: 3000
    regexp:
      reject:
        - WEBRip: {from: title}
        - Subt: {from: title}
        - subtitulo: {from: title}
        - HDTV: {from: title}
  tv:
    upgrade:
      tracking: yes
    timeframe:
      wait: 1 minutes
      target: 720p+
    series:
      - Servant
    set:
      path: /media/multi/descargando/
      content_filename: "{{series_name}} {{series_season|pad(2)}}x{{series_episode|pad(2)}}"
      move_completed_path: /media/multi/videos/SERIES/{{series_name}}/
      main_file_only: yes
      hide_sparse_files: yes
      keep_subs: yes
    deluge: yes
tasks:
  tv:
    rss:
      url: https://www.synologia.com/rss/pctmix.com
    template: tv
    manipulate:
      - title:
          replace:
            regexp: 'Temp. '
            format: 'S'
      - title:
          replace:
            regexp: ' Capitulo '
            format: 'E'
      - title:
          replace:
            regexp: 'Temp. \d+'
            format: ''
      - title:
          replace:
            regexp: '\[Cap.(\d?\d)(\d\d)\]'
            format: ' S\1E\2'
      - title:
          replace:
            regexp: '\[Cap.(\d?\d)(\d\d) Final\]'
            format: ' S\1E\2'
      - title:
          replace:
            regexp: '\[HDTV 720p\]'
            format: ' 720p'
      - title:
          replace:
            regexp: '\(HDTV 720p\)'
            format: ' 720p'
      - title:
          replace:
            regexp: '\[HDTV 720\]'
            format: ' 720p'
      - title:
          replace:
            regexp: '\(HDTV 720\)'
            format: ' 720p'
      - title:
          replace:
            regexp: '\(HDTV 720p AC3 5.1\)'
            format: '720p'
      - title:
          replace:
            regexp: 'HDTV 720p'
            format: '720p'
      - title:
          replace:
            regexp: '\[HDTV 1080p\]'
            format: ' 1080p'
      - title:
          replace:
            regexp: '\(HDTV 1080p\)'
            format: ' 1080p'
      - title:
          replace:
            regexp: '\[HDTV 1080\]'
            format: ' 1080p'
      - title:
          replace:
            regexp: '\(HDTV 1080\)'
            format: ' 1080p'
      - title:
          replace:
            regexp: '\[HDTV\]'
            format: ' HDTV'
      - title:
          replace:
            regexp: '\(HDTV\)'
            format: ' HDTV'
      - title:
          replace:
            regexp: '\[V.O.Sub. Español Castellano\]'
            format: ' subtitulo'
      - title:
          replace:
            regexp: '\[V.O. Subt. Castellano\]'
            format: ' subtitulo'
      - title:
          replace:
            regexp: '\[[^\]]*\]'
            format: ''
      - title:
          replace:
            regexp: '-  '
            format: ''
      - title:
          replace:
            regexp: '  '
            format: ' '
      - title:
          replace:
            regexp: 'S(\d)E'
            format: 'S0\1E'

  
#### Log:

It says like "Unable to locate torrent ID from url xxxx"
Sorry, I don't save it

```

### Additional information:

- FlexGet version:3.1.102 
- Python version: 3.8.5
- Installation method: pip
- Using daemon (yes/no): yes
- OS and version: Ubuntu 20.04

The solution is attached in descargas.2020.txt:

Change
REWRITABLE_REGEX = re.compile(
    r'https?://(www.)?(descargas2020|tvsinpagar|tumejortorrent|torrentlocura|torrentrapid).(org|com)/'
)

for:
REWRITABLE_REGEX = re.compile(
    r'https?://(www.)?(descargas2020|tvsinpagar|tumejortorrent|torrentlocura|torrentrapid|pctmix|pctmix1).(org|com)/'
)

Change:
            if match:
                torrent_id = match.group(2).rstrip('/')

for:
            if match:
                torrent_id = match.group(2).rstrip('/')
            else:
                scripts = soup.findAll('script', attrs={'type':'text/javascript'})
                for script in scripts:
                    if "window.location.href" in script.text: #script with window.location.href captured
                       resultado = re.search('window.location.href = "(.*)";', script.text).group(1)
                if resultado:
                    if resultado.startswith('//pctmix'):
                       direccion = 'https:' + resultado
                       return direccion  

After this changes I have THIS log:
"Error while registering plugin descargas2020. A plugin with the same name is already registered"
I think I have to register the plugin but I don't know how to register it. 
With this changes decargas2020.py work.
 
All the best,
Toni

(Sorry for my English)
