### ISSUE TITLE
torrentday pluging winth uid secret gets error expecting string

### ISSUE THREAD

**Issue by soloam** [Flexget/Flexget#2857]
### Expected behaviour:

Setting uid from secrets file should work and update config

### Actual behaviour:

When setting the uid from a secret file, since uid is a number, it's converted to integer on the config, this makes a error in the config compilation of:

/tasks/xTV_TorrentDay/discover/from/0/torrentday/uid] Got `1234567`, expected: string

### Steps to reproduce:
- Step 1: Add config and run flexget check

#### Config:
```yaml
  TV_TorrentDay:
    discover:
      what:
        - next_series_episodes: yes
      from:
        - torrentday:
            uid: "{? torrentday.uid ?}"
            passkey: '{? torrentday.passkey ?}'
            cfduid: '{? torrentday.cfduid ?}'
            rss_key: '{? torrentday.rss_key ?}'
            category: 'tvBRD'
```
secrets.yaml
```yaml
torrentday:
  uid: "1234567"
  passkey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  cfduid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  rss_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2021-02-16 01:29:54 CRITICAL manager                       [/tasks/xTV_TorrentDay/discover/from/0/torrentday/uid] Got `1234567`, expected: string
2021-02-16 01:29:54 CRITICAL manager                       Failed to load config file: Did not pass schema validation.

```
</details>

### Additional information:

- FlexGet version: 3.1.102
- Python version: 3.7.3
- Installation method: venv
- Using daemon (yes/no): yes
- OS and version: debian 10
