### ISSUE TITLE
Compatibility issues between imdb and flexget-nexusphp plugin 

### ISSUE THREAD

**Issue by terrellgf** [Flexget/Flexget#2866]
When I use the nexusphp plugin to filter free torrents, the imdb plugin does not seem to work.
The link to the nexusphp plugin project is: Juszoe/flexget-nexusphp
I did not see the process of filtering imdb in the log. But after deleting the configuration of the flexget-nuxesphp plugin, the imdb plugin works. I have been debugging for a month, but it still doesn't seem to work. Please help to see if there is a problem with my configuration, or is it incompatible? 
```
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  BBB:
    template: 
      - movie
      - AAA 
    nexusphp:
      cookie: 'xxx'
      user-agent: 'xxx'
      discount:
        - free
        - 2xfree
    priority: 1
schedules:
  - tasks: [BBB]
    interval:
      minutes: 5

templates:
  global:
    retry_failed:
      retry_time: 5 minutes
      retry_time_multiplier: 1
      max_retries: 12
    no_entries_ok: yes
  movie:
    transmission:
      host: x.x.x.x
      port: xxxx
      username: xxxxxx
      password: xxxxxx
      path: /xxx/xx/x
    seen_movies:
      matching: strict
    proper_movies: no
    imdb_lookup: yes
    imdb:
      min_year: 1990
      min_score: 6
    list_match:
      from:
        - movie_list: mymovies
    regexp:
      from: title
      reject:
        - msd
        - afg
        - line
        - hc
        - korsub
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'
        - '*.iso'
  AAA:
    inputs:
      - rss:
          url: https://xxxx/xxxx
          all_entries: yes
          other_fields:
            - link
```
