### ISSUE TITLE
Anime title "86" breaks MyAnimeList plugin

### ISSUE THREAD

**Issue by christian-0s** [Flexget/Flexget#2901]
### Expected behaviour:
Flexget should get shows list from MAL user list

### Actual behaviour:
There's an error retrieving list and the following error message is written in the log:
ERROR    input_cache   nyaa            There was an error during my_anime_list input (Tried to set title to 86), using cache instead.

### Steps to reproduce:
- Step 1: add anime title "86" to MAL user list

#### Config:
```yaml

# define templates to use into our tasks
templates:
  global:
    # default config.yml
    plugin_priority:
      headers: 250
    headers:
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
      Accept-Language: "it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3"
      Cache-Control: "max-age=0"
      Connection: "keep-alive"
      User-Agent: "User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
    cookies:
      file: /home/user/.flexget/cookies.txt
      type: mozilla

    # Make there's 10 GB free before adding more downloads
    free_space:
      path: /path/destination
      space: 5000
    # Make sure all filenames are Windows safe (for samba)
    pathscrub: windows

    regexp:
      reject:
       - (\[KRP\])
       - (\[SSA\])
       - (\[FFA\])
       - (\[MiniFreeza\])
       - (\[MiniAnimes\])
       - (\[Anime Time\])
       - (\[Hakata Ramen\])
       - (\[HR\])
       - (Judas)
       - (\[EMBER\])
       - (\[AkihitoSubs\])
       - (10[Bb]it)
       - (10\-[Bb]it)
       - (FuniDub)
       - (GJM)
       - (AppleRips)

  # configuration of transmission
  # -> each accepted feed item will be piped to transmission
  # read doc: http://flexget.com/wiki/Plugins/transmission
  transmissionrpc:
    transmission:
      host: localhost
      port: 9091
      username: username
      password: password
      ratio: 3.0
      #addpaused: No
      # define a path to store our files
      path: /path/destination/plexmedia
      main_file_only: yes
      include_subs: yes
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*.txt'
      magnetization_timeout: 30
 
  # configure anime template, we will need to list our shows or use a plugin like https://github.com/edhaker13/myanimelist
  anime:
    # read doc: http://flexget.com/wiki/Plugins/exists_series
    exists_series:
      # define a path to store our files
      path: "/path/destination/plexmedia/"
      #allow_different_qualities: yes
    
    # list animes
    series:
      - "Kyuukyoku Shinka shita Full Dive RPG ga Genjitsu yori mo Kusoge Dattara":
          alternate_name:
            - "Full Dive"
      - "Isekai Maou to Shoukan Shoujo no Dorei Majutsu Ω":
          alternate_name:
            - "Isekai Maou to Shoukan Shoujo no Dorei Majutsu S2"
            - "Isekai Maou to Shoukan Shoujo no Dorei Majutsu Omega"
          path: "/path/destination/plexmedia/Isekai Maou to Shoukan Shoujo no Dorei Majutsu/S02/"
      - "Boku no Hero Academia 5th Season":
          path: "/path/destination/plexmedia/Boku no Hero Academia/S05/"

    configure_series:
      from:
        my_anime_list:
          username: username
          status:
            - watching
            - plan_to_watch
          airing_status:
            - airing
            - finished
          type: 
            - tv
            - ova
            - ona
            - special
            - movie


    # read doc: http://flexget.com/wiki/Plugins/content_size
    # We can't use quality to find our animes since some titles don't contain "720p" or 1080p but HD / FHD
    #content_size:
    #  min: 200
    # set path where files will be downloaded
    quality: 1080p
    set:
      path: "/path/destination/plexmedia/{{ series_name | replace('/', ' ') | replace(':', ' - ') }}/"
      propers: no
 
# tasks section:
tasks:
  nyaa:
    # define our rss url
    rss: https://nyaa.si/?page=rss&c=1_2&f=0
    no_entries_ok: yes
    template:
      - transmissionrpc
      - anime

  anidex:
    # define our rss url
    rss:
      url: https://anidex.info/rss/?cat=1&lang_id=1
    verify_ssl_certificates: no
    no_entries_ok: yes
    template:
      - transmissionrpc
      - anime

# schedules
# Used to specify interval to execute our tasks
# '*' means every task
schedules:
  - tasks: '*'
    interval:
      minutes: 30

web_server:
  bind: 0.0.0.0 
  port: 3539
  web_ui: yes

```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2021-04-15 12:59:26 ERROR    input_cache   nyaa            There was an error during my_anime_list input (Tried to set title to 86), using cache instead.
2021-04-15 13:29:27 ERROR    input_cache   nyaa            There was an error during my_anime_list input (Tried to set title to 86), using cache instead.
```
</details>

### Additional information:

- FlexGet version: 3.1.108
- Python version: Python 3.6.8
- Installation method: pip in virtualenv
- Using daemon (yes/no): yes
- OS and version: Ubuntu Bionic with Armbian Linux 4.4.182-rockchip64
