### ISSUE TITLE
Crash: Unhandled error in plugin proper_movies: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by Perrylicious** [Flexget/Flexget#3025]
### Expected behaviour:

Run task to completion checking if movie is of "PROPER" release type against plugin proper_movies.

### Actual behaviour:

Task crashes after getting IMDB data and running plugin proper_movies with "unhandled error: 'NoneType' object has no attribute 'find'" for different specific movies in an RSS feed. Task completes successfully with other movies. Failure is not limited to a single data source (i.e. RSS feed) but seems to trigger on specific movies found on IMDB.

The common thread with the problematic movies that I gathered from >20 crash logs over the past few days seems to be no year found on IMDB lookup:

2021-05-31 10:03:23 VERBOSE  imdb_lookup   mov_hd_tracker1       Parsing imdb for `Tres.metros.sobre.el.cielo.2010.720p.BluRay.DTS.x264-Ivandro`
2021-05-31 10:03:23 DEBUG    utils.requests mov_hd_tracker1       Waiting 2.47 seconds until next request to imdb.com
2021-05-31 10:03:25 DEBUG    utils.requests mov_hd_tracker1       GETing URL https://www.imdb.com/title/tt1648216/ with args () and kwargs {'allow_redirects': True, 'timeout': 30}
2021-05-31 10:03:30 DEBUG    imdb.utils    mov_hd_tracker1       No year found for tt1648216
2021-05-31 10:03:30 CRITICAL task          mov_hd_tracker1       BUG: Unhandled error in plugin proper_movies: 'NoneType' object has no attribute 'find'

### Steps to reproduce:
- Step 1: Try to parse an RSS feed with any of the following releases in it:
Poklosie.2012.720p.BluRay.DD.5.1.x264-tranc
flame-deliver.us.from.evil.2020.720p.bluray.x264
Deliver.Us.From.Evil.2020.720p.BluRay.x264-FLAME
Later.Spring.1949.REMASTERED.720p.BluRay.x264-JRP
New.York.Vampire.1991.720p.AMZN.WEB-DL.DDP2.0.H.264-SymBiOTes
Da.nao.tian.gong.2012.720p.BluRay.DD5.1.x264-VietHD
Tres.metros.sobre.el.cielo.2010.720p.BluRay.DTS.x264-Ivandro
(can pull more examples from the crash logs if needed)
- Step 2: Attempt to run any of those movies against a task that uses the plugin proper_movies

The issue started suddenly appearing on 2021-05-26 which may have coincided with a flexget update to the then latest version. Issue persists through update to current latest 3.1.129

#### Config:
```yaml
flexget execute --tasks "mov_hd_tracker1" --dump-config
There is a FlexGet process already running for this config, sending execution there.
--- config from task: mov_hd_tracker1
delay: 30 minutes
disable: tmdb_lookup
if:
  - '''BluRay'' not in title':
      list_add:
        - movie_list: upgrade_high
list_match:
  action: accept
  from:
    - movie_list: mov_get_high
  remove_on_match: true
  single_match: true
notify:
  entries:
    message: '{% if series_name is defined %} {{task}} hit {{series_name}} {{series_id}}
      {{quality}} {% elif imdb_name is defined %} {{task}} hit {{movie_name}} {{quality}}
      {% else %} {{task}} hit {{title}} {% endif %}

      '
    title: '{% if task in ["local*"]%} Wishlist {{movie_name}} {% else %} {{title}}
      {% endif %}

      '
    via:
      - pushover:
          api_key: redacted
          user_key: redacted
nzbget:
  category: ''
  priority: 100
  top: false
  url: redacted
priority: 50
proper_movies: true
quality:
  - 720p webdl|bluray h264 !ac3 !mp3 !aac !flac
regexp:
  from: title
  reject:
    - \.NL
    - \.Dubbed
    - \.Subbed
    - \.Multi
    - \.Hebsub
    - \.DKSubs
    - 2160p
    - \.HC
    - \.RUS
    - \.Dirfix
    - (NL Sub)
    - \.German
    - \.Finnish
    - \.French
    - \.NORWEGIAN
    - \.POLISH
    - \.ITALIAN
    - \.Subfrench
    - \.Nordic
    - \-RSG
    - \.TrueHD
    - \-SDI
    - newzNZB
    - SUBPACK
    - \-20\-40
    - \.BRRip
    - \.AMBC
    - \-NhaNc3
    - \.nSD\.
    - XviD
    - HiSD
rss:
  all_entries: true
  ascii: false
  escape: false
  group_links: false
  silent: false
  url: redacted
template:
  - spamguard
  - nzbget
  - push-notification
  - movie-high
  - imdb-check
tmdb_lookup: false
trakt_lookup: true

---
```
  
#### Log:
Since I can't reproduce the issue with changing RSS feeds (that does not contain one of the movies that crash the task), I can't reproduce debug logs but I have attached crash logs. Can provide more crash logs if needed.

### Additional information:

- FlexGet version: 3.1.129
- Python version: 3.8.5
- Installation method: pip3
- Using daemon (yes/no): yes
- OS and version: Ubuntu 20.04.2 LTS
- Link to crash log:
https://perrylicious.com/git/sanitized_crash_report.2021.05.30.190335516056.log
https://perrylicious.com/git/sanitized_crash_report.2021.06.01.011839298747.log
https://perrylicious.com/git/sanitized_crash_report.2021.06.01.031842361857.log
