### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by screw** [Flexget/Flexget#3062]
### Expected behaviour:

Flexget downloads torrent from RSS, matches it with a series and adds it to deluge.

### Actual behaviour:
Flexget crashes when processing a torrent belonging to a series. 

### Steps to reproduce:
- Step 1: Start flexget container.
- Step 2: Schedule task
- Step 3: Flexget crashes when processing torrent belonging to a series.

#### Config:
```yaml
schedules:
  - tasks: [<task-name>]
    interval:
      minutes: 3

  <task-name>:

    rss: <RSS-URL>
    template:
      - tv
      - pushme
      - deluge-ui
    series:
      settings:
        tvseries:
          timeframe: 12 hours
          target: 1080p webdl
#          quality: 720p-1080p webdl
          set:
            path: /my/path
            move_completed_path: "/my/path/{{series_name}}/Season {{series_season}}/"
            label: tvseries
templates:
  deluge-ui:
    deluge:
      host: deluge # 127.0.0.1
      username: localclient
        #password: password
      password: password
  tv:
    series:
      settings:
        tvseries:
          season_packs: yes
          set:
            move_completed_path: "/my/path/Season {{series_season}}/"
            label: tvseries

      tvseries:
        - Shameless (US)
        - Workaholics
        - Stranger Things
        - Baskets
        - Bob's Burgers
        - QI
        - Peep Show
        - Brooklyn Nine-Nine
        - Saturday Night Live
        - The Walking Dead
        - The Big Bang Theory
        - Parks and Recreation
        - The Last Man on Earth
        - Backstrom
        - It's Always Sunny in Philadelphia   
        - 8 Out of 10 Cats Does Countdown
        - Orange is the new black
        - Better Call Saul
        - Westworld
        - Curb Your Enthusiasm
        - Borderline (2016)
        - Rick and Morty
        - Game of Thrones
        - Letterkenny
        - BoJack Horseman
        - Resident Alien
        - Disenchantment
        - Eastbound & Down
        - Man Down
        - Mare of Easttown
        - "Star Wars: The Bad Batch"
        - Loki
  pushme:
    notify:
      entries:
        via:
          - pushbullet:
              api_key: key


Paste FULL config and remove any personal info if config is too long, attach the file to the ticket.
If issue is with a single task, you can get get resulting configuration by running:
  flexget execute --task <NAME> --dump-config
Make sure to redact any personal information (passwords, api keys, etc) !
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2021-06-29 23:06:39 CRITICAL task          <task-name> BUG: Unhandled error in plugin series: '<' not supported between instances of 'int' and 'NoneType'
flexget    | Traceback (most recent call last):
flexget    |
flexget    |   File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
flexget    |     self._bootstrap_inner()
flexget    |     |    -> <function Thread._bootstrap_inner at 0x7f023352a5f0>
flexget    |     -> <Thread(task_queue, started daemon 139647331453728)>
flexget    |   File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
flexget    |     self.run()
flexget    |     |    -> <function Thread.run at 0x7f023352a3b0>
flexget    |     -> <Thread(task_queue, started daemon 139647331453728)>
flexget    |   File "/usr/lib/python3.7/threading.py", line 870, in run
flexget    |     self._target(*self._args, **self._kwargs)
flexget    |     |    |        |    |        |    -> {}
flexget    |     |    |        |    |        -> <Thread(task_queue, started daemon 139647331453728)>
flexget    |     |    |        |    -> ()
flexget    |     |    |        -> <Thread(task_queue, started daemon 139647331453728)>
flexget    |     |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7f022dd29810>>
flexget    |     -> <Thread(task_queue, started daemon 139647331453728)>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/task_queue.py", line 46, in run
flexget    |     self.current_task.execute()
flexget    |     |    |            -> <function Task.execute at 0x7f0231245830>
flexget    |     |    -> <flexget.task.Task object at 0x7f022c231810>
flexget    |     -> <flexget.task_queue.TaskQueue object at 0x7f022dd29810>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/task.py", line 87, in wrapper
flexget    |     return func(self, *args, **kw)
flexget    |            |    |      |       -> {}
flexget    |            |    |      -> ()
flexget    |            |    -> <flexget.task.Task object at 0x7f022c231810>
flexget    |            -> <function Task.execute at 0x7f02312457a0>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/task.py", line 722, in execute
flexget    |     self._execute()
flexget    |     |    -> <function Task._execute at 0x7f0231245710>
flexget    |     -> <flexget.task.Task object at 0x7f022c231810>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/task.py", line 688, in _execute
flexget    |     self.__run_task_phase(phase)
flexget    |     |                     -> 'filter'
flexget    |     -> <flexget.task.Task object at 0x7f022c231810>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/task.py", line 514, in __run_task_phase
flexget    |     response = self.__run_plugin(plugin, phase, args)
flexget    |                |                 |       |      -> (<flexget.task.Task object at 0x7f022c231810>, {'tvseries': [{'Shameless (US)': {'timeframe': '12 hours', 'target': '1080p we...
flexget    |                |                 |       -> 'filter'
flexget    |                |                 -> <PluginInfo(name=series)>
flexget    |                -> <flexget.task.Task object at 0x7f022c231810>
flexget    | > File "/usr/lib/python3.7/site-packages/flexget/task.py", line 547, in __run_plugin
flexget    |     result = method(*args, **kwargs)
flexget    |              |       |       -> {}
flexget    |              |       -> (<flexget.task.Task object at 0x7f022c231810>, {'tvseries': [{'Shameless (US)': {'timeframe': '12 hours', 'target': '1080p we...
flexget    |              -> <Event(name=plugin.series.filter,func=on_task_filter,priority=128)>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/event.py", line 20, in __call__
flexget    |     return self.func(*args, **kwargs)
flexget    |            |    |     |       -> {}
flexget    |            |    |     -> (<flexget.task.Task object at 0x7f022c231810>, {'tvseries': [{'Shameless (US)': {'timeframe': '12 hours', 'target': '1080p we...
flexget    |            |    -> <bound method FilterSeries.on_task_filter of <flexget.components.series.series.FilterSeries object at 0x7f022dd85950>>
flexget    |            -> <Event(name=plugin.series.filter,func=on_task_filter,priority=128)>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/components/series/series.py", line 562, in on_task_filter
flexget    |     self.process_series(task, series_entries, series_config)
flexget    |     |    |              |     |               -> {'timeframe': '12 hours', 'target': '1080p webdl', 'set': {'path': '/mnt/videos/downloads/', 'move_completed_path': '/mnt/vid...
flexget    |     |    |              |     -> <unprintable dict object>
flexget    |     |    |              -> <flexget.task.Task object at 0x7f022c231810>
flexget    |     |    -> <function FilterSeries.process_series at 0x7f022e071320>
flexget    |     -> <flexget.components.series.series.FilterSeries object at 0x7f022dd85950>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/components/series/series.py", line 778, in process_series
flexget    |     threshold=ep_threshold,
flexget    |               -> 0
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/components/series/series.py", line 914, in process_entity_tracking
flexget    |     latest = db.get_latest_release(entity.series)
flexget    |              |  |                  |      -> <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f022db44230>
flexget    |              |  |                  -> <unprintable Season object>
flexget    |              |  -> <function get_latest_release at 0x7f022e05e680>
flexget    |              -> <module 'flexget.components.series.db' from '/usr/lib/python3.7/site-packages/flexget/components/series/db.py'>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/components/series/db.py", line 1135, in get_latest_release
flexget    |     return max(latest_season, latest_ep)
flexget    |                |              -> <unprintable Episode object>
flexget    |                -> <unprintable Season object>
flexget    |   File "/usr/lib/python3.7/site-packages/flexget/components/series/db.py", line 230, in __lt__
flexget    |     return self.season < other.season
flexget    |            |    |        |     -> <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f022e0a49b0>
flexget    |            |    |        -> <unprintable Episode object>
flexget    |            |    -> <sqlalchemy.orm.attributes.InstrumentedAttribute object at 0x7f022e091dd0>
flexget    |            -> <unprintable Season object>
flexget    |
flexget    | TypeError: '<' not supported between instances of 'int' and 'NoneType'
flexget    | 2021-06-29 23:15:39 CRITICAL manager       <task-name> An unexpected crash has occurred. Writing crash report to /root/.flexget/crash_report.2021.06.29.231539259010.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.130
flexget    | 2021-06-29 23:15:39 WARNING  task          <task-name> Aborting task (plugin: series)
```
</details>

### Additional information:

- FlexGet version: 3.1.130
- Python version: 3.7.7
- Installation method: docker image from cpoppema/docker-flexget
- Using daemon (yes/no): yes
- OS and version: `Linux 7b75869eac2d 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux`
- Link to crash log:
