### ISSUE TITLE
getting shows that don't match anything in my config file

### ISSUE THREAD

**Issue by mark-hahn** [Flexget/Flexget#3107]
I'm getting a lot of shows that couldn't possibly match anything in my config file.  For example I got a 46GB file of all six seasons of the Drew Carey show.  My config file does not have "drew" or "carey" in it.  How can it download a file that doesn't match?  

#### Did you recently upgrade? 
no
#### Are you running FlexGet as a daemon? 
Yes.  It has been restarted many times.

#### Expected behaviour:
Get only shows that match something in config file.
#### Actual behaviour
Getting many unwanted shows like Drew Carey, Japanese language lessons, etc.

#### Steps to reproduce:
I don't know how to reproduce.  The problem just happens.

#### Config:
```yaml
templates:
  tv:
    regexp:
      reject:
        - 9JKL
        - Apocalypse.Code.The.Bible.Prediction
        - ^Babylon
        - Baskets
        - Castle Builders
        - The Champions
        - Class Act
        - Drunk History UK
        - Easy Japanese
        - Gotham Comedy Live
        - Lacheys Bar
        - Married At First Sight
        - Married To Medicine
        - Oprah Behind The Scenes
        - uin.15
        - Uncle Grandpa
        - Undercover Boss
        - Undercover High
        - Undercover In Nederland
        - White Collar Brawlers
        - german
        - swedish
        - flemish
        - french
        - japanese
        - chinese
        - farsi
        - italian
        - complete
        - s01
        - s02
        - s03
        - s01-02
        - s01-03
        - s02-03
        - s1-s2
        - s1-s3
        - s2-s3
        - season

    series:
      - A Touch Of Cloth
      - After Life
      - Alma’s Not Normal
      - American Woman
      - Amy Schumer
      - Anger Management
      - Angie Tribeca
      - Archer
      - B Positive
      - Back
      - Bad Move
      - Barry
      - Behind The Filter
      - Big Little Lies
      - Big School
      - Bisexual
      - Black Mirror
      - Black Summer
      - Bloods
      - Bob's Burgers
      - Bob Hearts Abishola
      - Brassic
      - Breaking Greenville
      - Breeders
      - Brockmire
      - Brooklyn Nine-Nine
      - Brotherhood
      - By the Book
      - Call Me Kat
      - Call Your Mother
      - Calls
      - Case Histories
      - Casual
      - Catastrophe
      - Champions
      - Charlie Brooker's Weekly Wipe
      - Chinese Burn
      - The Cleaner
      - Cleaning Up
      - The Cockfields 
      - Code 404
      - Comedians in Cars Getting Coffee
      - Comedy Bang Bang
      - Connecting
      - The Cool Kids
      - Corporate
      - The Crew
      - Crisis
      - The Crown
      - The Curse
      - Dead Pixels
      - Dead Set
      - Dead to Me
      - Delicious
      - Des
      - Detour
      - Detroiters
      - deutschland 83
      - Disjointed
      - Dispatches from Elsewhere
      - Documentary Now!
      - The Dress Up Gang
      - Drunk History
      - Drunk History US
      - The Duchess
      - Enlightened
      - Episodes
      - euphoria
      - The Expanse
      - Exes
      - Family Guy
      - Fargo
      - The Fast Show
      - Feel Good
      - Film Club
      - Finding Alice
      - Five
      - Flack
      - Flaked
      - The Flight Attendant
      - Flowers
      - Forever
      - Frayed
      - Free Agents
      - Fresh Meat
      - Friends with Better Lives
      - GameFace
      - Get Shorty
      - Ghosts
      - Ginge, The Geordie & The Geek
      - Ginny & Georgia
      - GirlsEmily Atack
      - Give Out Girls
      - The Good Fight
      - Good Girls
      - Good Place
      - Grace and Frankie
      - The Great North
      - Guilt
      - Gunpowder Milkshake
      - Gurney Slade
      - Hailmakers
      - Hang Ups
      - Happy Together
      - Harley Quinn
      - Harrow
      - The Haunting of Bly Manor
      - The Haunting of Hill House
      - High & Dry
      - Hitmen
      - Home From Home
      - Homecoming
      - Home Economics
      - How To with John Wilson
      - Humans
      - Hunderby
      - I Am Not Okay With This
      - I Feel Bad
      - I Hate Suzie
      - I Know This Much Is True
      - I Live With Models
      - I Want My Wife Back
      - i'm sorry
      - Idiotsitter
      - Impastor
      - Imposters
      - In My Skin
      - In the Dark
      - In the Long Run
      - Inbetweeners
      - Increasingly Poor Decisions Of Todd Margaret
      - Inside Amy Schumer
      - Inside No. 9
      - Intelligence
      - Its Always Sunny in Philadelphia
      - iZombie
      - Job Lot
      - Jonathan Strange & Mr Norrell
      - Josh
      - Kate & Koji
      - Kenan
      - Key & Peele
      - Killing Eve
      - King Gary
      - The Kominsky Method
      - LA to Vegas
      - The Last O.G.
      - The Last Ship
      - Lee & Dean
      - Legion
      - Liar
      - Life Sentence
      - The Little Drummer Girl
      - Little Fires Everywhere
      - Living with Yourself
      - Love
      - Love Island
      - Love, Nina
      - Lucifer
      - Luther
      - Madam Secretary
      - Made for Love
      - Making History
      - Mandy
      - Maniac
      - Married
      - Mary Kills People
      - Master of None
      - Match Game
      - McCarthys
      - Medical Police
      - Meet the Richardsons
      - Men at Work
      - Mick
      - Midnight, Texas
      - Mindy Project
      - Miracle Workers
      - Mom
      - Moonbase 8
      - The Morning Show
      - Motherland
      - Mr. Mayor
      - Murder City
      - Murder Most Horrid
      - Mystery Road
      - The Neighborhood
      - Never Have I Ever
      - The Nevers
      - New Amsterdam
      - Newsreaders
      - No Offence
      - Not Going Out
      - "NTSF:SD:SUV::"
      - Nurse Jackie
      - Orville
      - The Other One
      - The Other Two
      - Our Ex Wife
      - Peep Show
      - People Of Earth
      - Peppa Pig
      - Perfect Couples
      - Playing House
      - Plebs
      - The Politician
      - Porters
      - Pramface
      - Psychobitches
      - Pulling
      - Pure
      - The Queen's Gambit
      - Raising Dion
      - Ratched
      - Red Oaks
      - Rick And Morty
      - The Righteous Gemstones
      - Roadkill
      - Robot Chicken
      - Rotters
      - Russell Howard's Good News
      - Santa Clarita Diet
      - Scarborough
      - Servant
      - Sherlock
      - Siblings
      - Sick Note
      - Silicon Valley
      - The Sinner
      - Shakespeare & Hathaway
      - Slings & Arrows
      - Social Distance
      - Some Girls
      - South Park
      - The South Westerlies
      - Space Force
      - Splitting Up Together
      - Staged
      - Starstruck
      - StartUp
      - State of the Union
      - Stranger Things
      - Sunny D
      - Sunnyside
      - Superstore
      - SurrealEstate
      - Ted Lasso
      - Tell Me Your Secrets
      - The Thin Blue Line
      - This Is Us
      - This Way Up
      - Tick
      - Timewasters 
      - Titty Bang Bang
      - Toast
      - Toast of America
      - Toast of London
      - Top Chef
      - traffic light
      - True Detective
      - Truth Be Told
      - Trying
      - The Tuckers
      - The Twilight Zone
      - Two Guys and a Girl
      - Two Weeks to Live
      - Ultra City Smiths
      - Uncle
      - Undateable
      - The Undoing
      - The Unicorn
      - UnReal
      - Upload
      - Upright
      - Vera
      - Vice Principals
      - Vicious
      - Walliams And Friend
      - WandaVision
      - Wannabe
      - The Watch
      - We Hunt Together
      - Weird Loners
      - Wet Hot American Summer
      - What We Do In The Shadows 
      - White Gold
      - Why Women Kill
      - Witless
      - Woke
      - Workaholics
      - Wrecked
      - Wrong Door
      - Year Of The Rabbit
      - Yellowstone
      - You're The Worst
      - The Young Offenders
      - Young Rock
      - Young Sheldon
      - Younger
      - Zapped
      - Zomboat

    transmission:
      username: xobtlu
      password: "90-BNMoiuxcv"
      port: 13410

schedules:
  - tasks: '*'
    interval:
      minutes: 15

tasks:
  ipt:
    rss: https://iptorrents.com/t.rss?u=<snipped>;tp=<snipped>;download;new
    template: tv

  tl:
    rss: https://rss24h.torrentleech.org/<snipped>
    template: tv
```
  
#### Log:
I can't find any log file

#### FlexGet version:
3.1.67

#### Python version:
Python 3.8.5

#### Installation method:
Seedbox support installed it

#### OS and version:
Linux version 4.19.0-0.bpo.17-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)) #1 SMP Debian 4.19.194-3~deb9u1 (2021-07-19)
