### ISSUE TITLE
[BUG] Aria2 Plugin not downloading to the specified series path

### ISSUE THREAD

**Issue by stranger-danger-zamu** [Flexget/Flexget#3217]
### Expected behaviour:

```yaml
templates:
  dler:
    aria2:
      path: /path/to/anime/
      secret: "password"
      options:
        continue: "true"
  subsplease:
    if:
      - "'batch' in title.lower()": reject
    series:
      settings:
        anime:
          identified_by: sequence
          quality: 1080p
    rss:
      url: https://nyaa.si/?page=rss&q=subsplease+1080p&c=1_2&f=0
      link:
        - link
        - magneturi

tasks:
  Anime-SubsPlease:
    template:
      - subsplease
      - dler
    series:
      anime:
        - mushoku tensei:
            path: /path/to/anime/mushoku-tensei/
        - shinka no mi:
            path: /path/to/anime/shinka-no-mi/
        - sekai saikou no ansatsusha:
            path: /path/to/anime/sekai-saikou-no-ansatsusha-isekai/
        - saihate no paladin:
            path: /path/to/anime/saihate-no-paladin/
        - ousama ranking:
            path: /path/to/anime/ousama-ranking/
        - ganbare douki-chan:
            path: /path/to/anime/ganbare-douki-chan/
```

Given the above configuration, I expect all the files for their respective series to download in the specified directories.

### Actual behaviour:

Given the above configuration, all files download to the path specified in the aria2 configuration segment (in this case `/path/to/anime`).

### Steps to reproduce:

1. Use the above configuration and run `flexget execute`.

#### Config:

Dump'd config `flexget execute --dump-config`.

```yaml
aria2:
  options:
    continue: 'true'
    seed-time: 10
  password: ''
  path: /path/to/anime/
  port: 6800
  secret: 'password'
  server: localhost
  username: ''
if:
  - '''batch'' in title.lower()': reject
rss:
  all_entries: true
  ascii: false
  escape: false
  group_links: false
  link:
    - link
    - magneturi
  silent: false
  url: https://nyaa.si/?page=rss&q=subsplease+1080p&c=1_2&f=0
series:
  anime:
    - mushoku tensei:
        path: /path/to/anime/mushoku-tensei/
    - shinka no mi:
        path: /path/to/anime/shinka-no-mi/
    - sekai saikou no ansatsusha:
        path: /path/to/anime/sekai-saikou-no-ansatsusha-isekai/
    - saihate no paladin:
        path: /path/to/anime/saihate-no-paladin/
    - ousama ranking:
        path: /path/to/anime/ousama-ranking/
    - ganbare douki-chan:
        path: /path/to/anime/ganbare-douki-chan/
  settings:
    anime:
      identified_by: sequence
      quality: 1080p
template:
  - subsplease
  - dler
```
  
#### Log:

N/A. The tasks executes and performs the correct function, just fails to download to the right directory. Nothing in the log is helpful with respect to debugging this.

### Additional information:

- FlexGet version: 3.1.149
- Python version: 3.8.10
- Installation method: pip (`python3 -m pip install --user --upgrade flexget`)
- Using daemon (yes/no): no
- OS and version: Ubuntu 20.04.3 LTS, Linux 5.4.0-1044-raspi aarch64
- Link to crash log: N/A
