### ISSUE TITLE
Reruns are not considering "pathscrub: windows"

### ISSUE THREAD

**Issue by diogosena** [Flexget/Flexget#3254]
Reruns aren't considering the pathscrub specified in global template, or in the task itself.
The first execution is ok.

Maybe related to:
"skipping phase prepare during rerun"
"skipping phase start during rerun"

**Comment by gazpachoking** [comment]
I was unable to reproduce this using a simple test. Maybe there is a bit more to it? How are you using pathscrub? What is the plugin causing reruns?

This is the test I tried, and the 'scrubbed' field was scrubbed in linux mode both times (even though I ran it on a windows machine.)

```yaml
  task2:
    rerun: 1
    pathscrub: linux
    mock:
    - title: blah blah
      path: /home/chase/e:nd/
    set:
      scrubbed: "{{path|pathscrub}}"
```

**Comment by diogosena** [comment]
I was testing using this simple config,
Flexget running in linux 

```
variables: secrets.yml

tasks:

  test:
    pathscrub: windows
    series:
      - "Dexter: New Blood (2021)":
          quality: 1080p
          identified_by: ep
    discover:
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - piratebay: yes
      interval: 5 hours
    qbittorrent: 
      host: '{? qbittorrent.host ?}'
      port: '{? qbittorrent.port ?}'
      username: "'{? qbittorrent.username ?}'"
      password: "'{? qbittorrent.password ?}'"
      path: /media/sda1/series_test/{{series_name | pathscrub}}/Season {{series_season}}/
      label: 'series'
```
