### ISSUE TITLE
Add an option to run a task for free_space, besides abort. 

### ISSUE THREAD

**Issue by ProteinPig** [Flexget/Flexget#3264]
### Expected behaviour:

Run the task when free_space on a given drive is getting low. 

It is useful when we clean the old seeds, movies, etc...

### Actual behaviour:

For now, it will always abort.

### Steps to reproduce:
Normal configuration.

#### Config:
```yaml
  clean.check_free_space:
    priority: 9
    free_space:
      path: /mnt/Disk1/Downloads
      space: 30000
    mock: [{title: "Check.Free.Space"}]
    accept_all: yes
    exec: echo "Check free space."
    disable: [seen]
    run_task:
      when: aborted
      task: purge.finished_seeds

  purge.finished_seeds:
    limit_new: 2
    <<: *from_transmission
    if:
      - transmission_progress != 100.0: reject
    <<: *clean_transmission
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
No need
```
</details>

### Additional information:

- FlexGet version: latest
- Python version: 
- Installation method: docker/wiserain
- Using daemon (yes/no):
- OS and version:
- Link to crash log:
