### ISSUE TITLE
Wrong parsing of TV series by tvdb_lookup

### ISSUE THREAD

**Issue by ktaragorn** [Flexget/Flexget#3303]
### Expected behaviour:
 Blackish S08E01 Thats What Friends Are For HDTV x264 CRiMSON should parse to series_name Blackish and get correct TVDB ep name.

### Actual behaviour:
series_name parses correctly, but tvdb_series_name is Blackspace and tvdb_ep_name is blank.
This is despite trying to hard code the tvdb_id

### Steps to reproduce:
- Step 1: ...

#### Config:
```yaml
all_series:
  propers: 1 hour
convert_magnet: true
deluge:
  content_filename: '{{ tvdb_series_name  }} - S{{ series_season|pad(2) }}E{{ series_episode|pad(2)
    }} - {{ tvdb_ep_name |default("") }} '
  keep_subs: true
  magnetization_timeout: 100
  main_file_only: true
  move_completed_path: /media/ubuntu/Chest/Torrent/TV Shows/{{series_name}}/
  path: /media/ubuntu/Chest/Torrent/
  ratio: 0.1
  remove_at_ratio: true
notify:
  entries:
    message: '[{{task}}] {{series_name}} - {{series_id}}'
    title: '{{ title }}'
    via:
      - telegram:
          REDACTED
    what: accepted
rss:
  all_entries: true
  ascii: false
  escape: false
  group_links: false
  silent: false
  url: http://showrss.info/user/8928.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
series:
  - Blackish:
      set:
        tvdb_id: 281511
  - Blackish:
      set:
        tvdb_id: 281511
template:
  - fix_riverdale_detection
  - deluge_download
  - deluge_tv
  - notify_tv
thetvdb_lookup: true

```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2022-01-05 04:01:53 INFO     convert_magnet showrss-dload   Converting entry Blackish S08E01 Thats What Friends Are For HDTV x264 CRiMSON magnet URI to a torrent file
2022-01-05 04:01:56 INFO     download      showrss-dload   Downloading: Blackish S08E01 Thats What Friends Are For HDTV x264 CRiMSON
2022-01-05 04:01:56 INFO     deluge_client.client showrss-dload   Connecting to localhost:58846
2022-01-05 04:01:59 INFO     deluge        showrss-dload   Blackish S08E01 Thats What Friends Are For HDTV x264 CRiMSON successfully added to deluge.
```
</details>

Logs are all as expected, but the file downloads to `TV Shows/Blackish/Blackish.S08E01.Thats.What.Friends.Are.For.HDTV.x264-CRiMSON[rarbg]/Black Space S08E01 -.mkv`

### Additional information:

- FlexGet version: 3.1.110
- Python version:  2.7.18 ( i think it uses this, thought i have python3 3.8.10 installed)
- Installation method: apt get
- Using daemon (yes/no): yes
- OS and version: armbian / (Ubuntu 20.04.3 LTS)
- Link to crash log:

**Comment by soloam** [comment]
Normal what I do is to get more than one lookup provider and I use the as default:

```yaml
file_mask: '{{ series_name|re_replace("[ ]?\([0-9]{4}\)$","")|pathscrub}} - {{ series_id }}{% if tvdb_ep_name|default(False) and tvdb_ep_name != "TBA"  %} - {{ tvdb_ep_name|pathscrub}}{% elif trakt_ep_name|default(False) %} - {{ trakt_ep_name|pathscrub}}{% elif tvdb_ep_name|default(False) %} - {{ tvdb_ep_name|pathscrub}}{% endif %}'
```

**Comment by ktaragorn** [comment]
> it failed to call "the tv db".
That doesnt really sound like it, as my other shows work fine, and also even this one does get data, just the wrong data. Let me try the test/mock stuff on mine and see what I can.. didnt know about those.. also I should get more verbose logs

**Comment by ktaragorn** [comment]
using 
```
 test:
    disable:
      - seen
    seen: local
    mock:
      - { "title": "Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON", "url": "mock://myurl" }
    exec: echo "found {{tvdb_series_name}} at {{url}}"
    series:
      - Blackish:
          set:
            tvdb_id: 281511
    thetvdb_lookup: true
```

and `flexget daemon reload && flexget series forget Blackish S09E02 &&  flexget execute --tasks test --disable-tracking --verbose`

gets me 

```
There is a FlexGet process already running for this config, sending execution there.
2022-01-17 21:12:37 INFO     manager                       Reloading config from disk.
2022-01-17 21:12:37 INFO     manager                       Config successfully reloaded from disk.
There is a FlexGet process already running for this config, sending execution there.
Unknown identifier `S09E02` for series `Blackish`
There is a FlexGet process already running for this config, sending execution there.
2022-01-17 21:12:46 VERBOSE  details       test            Produced 1 entries.
2022-01-17 21:12:46 INFO     series.db     test            identified_by has locked in to type `ep` for Blackish
2022-01-17 21:12:46 VERBOSE  task          test            ACCEPTED: `Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON` by series plugin because choosing first acceptable match
2022-01-17 21:12:46 VERBOSE  details       test            Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2022-01-17 21:12:49 VERBOSE  exec          test            Executing: echo "found Black Space at mock://myurl"
2022-01-17 21:12:49 INFO     exec          test            Stdout: found Black Space at mock://myurl

```

so still broken..

gonna try updating flexget just in case this was fixed as a part of something else.. I dont see your logs that you show too.. so maybe relevent changes are in the diff

**Comment by ktaragorn** [comment]
Nope.. upgrading to 3.2.9 didnt change anything, still black space..

**Comment by BrutuZ** [comment]
Can't repro 😕

```yaml
tasks:
  test:
    mock:
      - title: "Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON"
    series:
      - Blackish:
          set:
            tvdb_id: 281511
    thetvdb_lookup: yes
    exec: echo "found {{tvdb_series_name}} at {{url}}"
```
Output:
```
$ flexget -l "logs\test.log" -c "test.yml" --test execute --dump accepted eval

2022-01-17 19:42:12 VERBOSE  details       test            Produced 1 entries.
2022-01-17 19:42:12 VERBOSE  series.db     test            identified by is currently on `auto` for Blackish. Multiple id types may be accepted until it locks in on the appropriate type.
2022-01-17 19:42:12 VERBOSE  task          test            ACCEPTED: `Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON` by series plugin because choosing first acceptable match
2022-01-17 19:42:12 VERBOSE  details       test            Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2022-01-17 19:42:13 INFO     exec          test            Would execute: echo "found black-ish at mock://localhost/mock/-2375112487638961207"
-- Accepted: ---------------------------
title            : Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON
url              : mock://localhost/mock/-2375112487638961207
original_url     : mock://localhost/mock/-2375112487638961207
accepted_by      : series
imdb_id          : tt3487356
imdb_url         : http://www.imdb.com/title/tt3487356
media_id         : blackish s09e02
original_title   : Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON
proper           : False
proper_count     : 0
quality          : hdtv h264
reason           : choosing first acceptable match
release_group    : None
season_pack      : None
series_episode   : 2
series_episodes  : 1
series_exact     : False
series_id        : S09E02
series_id_type   : ep
series_identified_by: auto
series_name      : Blackish
series_parser    : <SeriesParseResult(data=Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON,name=Blackish,id=(9, 2),season=9,season_pack=None,episode=2,quality=hdtv h264,proper=0,special=False,status=OK)>
series_releases  : [1]
series_season    : 9
task             : test
tvdb_absolute_number: None
tvdb_actors      : [Anthony Anderson, Tracee Ellis Ross, Marcus Scribner, Marsai Martin, Miles Brown, Jenifer Lewis, Laurence Fishburne, August and Berlin Gross, Yara Shahidi, Katlyn Nichol]
tvdb_air_time    : 9:30 PM
tvdb_airs_day_of_week: Tuesday
tvdb_banner      : http://thetvdb.com/banners/graphical/281511-g.jpg
tvdb_content_rating: TV-PG
tvdb_ep_air_date : None
tvdb_ep_directors: None
tvdb_ep_id       : None
tvdb_ep_image    : None
tvdb_ep_name     : None
tvdb_ep_overview : None
tvdb_ep_rating   : None
tvdb_episode     : None
tvdb_first_air_date: 2014-09-24 00:00:00
tvdb_genres      : [Comedy, Family]
tvdb_id          : 281511
tvdb_language    : en
tvdb_network     : ABC (US)
tvdb_overview    : An upper-middle-class black man struggles to raise his children with a sense of cultural identity despite constant contradictions and obstacles coming from his liberal wife, old-school father and his assimilated,
color-blind kids.
tvdb_posters     :
tvdb_rating      : 8.1
tvdb_runtime     : 21
tvdb_season      : None
tvdb_series_name : black-ish
tvdb_status      : Continuing
tvdb_url         : http://thetvdb.com/index.php?tab=series&id=281511
zap2it_id        : EP01921845
```

**Comment by ktaragorn** [comment]
This is my full log with --dump.. if that helps..
```
$ flexget daemon reload && flexget series forget Blackish S09E02 &&  flexget execute --tasks test --disable-tracking --verbose --dump
There is a FlexGet process already running for this config, sending execution there.
2022-01-17 22:54:31 INFO     manager                       Reloading config from disk.
2022-01-17 22:54:32 INFO     manager                       Config successfully reloaded from disk.
There is a FlexGet process already running for this config, sending execution there.
Removed entities(s) matching `S09E02` from series `Blackish`.
There is a FlexGet process already running for this config, sending execution there.
2022-01-17 22:54:43 VERBOSE  details       test            Produced 1 entries.
2022-01-17 22:54:43 INFO     series.db     test            identified_by has locked in to type `ep` for Blackish
2022-01-17 22:54:43 VERBOSE  task          test            ACCEPTED: `Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON` by series plugin because choosing first acceptable match
2022-01-17 22:54:43 VERBOSE  details       test            Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2022-01-17 22:54:43 VERBOSE  exec          test            Executing: echo "found Black Space at mock://myurl"
2022-01-17 22:54:43 INFO     exec          test            Stdout: found Black Space at mock://myurl
-- Accepted: ---------------------------
title            : Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON
url              : mock://myurl
original_url     : mock://myurl
accepted_by      : series
imdb_id          : tt13660638
imdb_url         : http://www.imdb.com/title/tt13660638
media_id         : <LazyField - value will be determined when it is accessed>
original_title   : Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON
proper           : False
proper_count     : 0
quality          : hdtv h264
reason           : choosing first acceptable match
release_group    : None
season_pack      : None
series_episode   : 2
series_episodes  : 1
series_exact     : False
series_id        : S09E02
series_id_type   : ep
series_identified_by: auto
series_name      : Blackish
series_parser    : <SeriesParseResult(data=Blackish S09E02 sssssThats What Friends Are For HDTV x264
CRiMSON,name=Blackish,id=(9, 2),season=9,season_pack=None,episode=2,quality=hdtv h264,proper=0,special=False,status=OK)>series_releases  : [82]
series_season    : 9
task             : test
tvdb_absolute_number: <LazyField - value will be determined when it is accessed>
tvdb_actors      : <LazyField - value will be determined when it is accessed>
tvdb_air_time    : 9:30 PM
tvdb_airs_day_of_week: Sunday
tvdb_banner      : None
tvdb_content_rating: TV-14
tvdb_ep_air_date : <LazyField - value will be determined when it is accessed>
tvdb_ep_directors: <LazyField - value will be determined when it is accessed>
tvdb_ep_id       : <LazyField - value will be determined when it is accessed>
tvdb_ep_image    : <LazyField - value will be determined when it is accessed>
tvdb_ep_name     : <LazyField - value will be determined when it is accessed>
tvdb_ep_overview : <LazyField - value will be determined when it is accessed>
tvdb_ep_rating   : <LazyField - value will be determined when it is accessed>
tvdb_episode     : <LazyField - value will be determined when it is accessed>
tvdb_first_air_date: 2020-12-13 00:00:00
tvdb_genres      : [Crime, Drama]
tvdb_id          : 393293
tvdb_language    : en
tvdb_network     : Channel 13
tvdb_overview    : A rogue detective with unorthodox means leads an investigation into a massacre committed by unicorn
mask-wearing assassins at an Israeli high school.
tvdb_posters     : <LazyField - value will be determined when it is accessed>
tvdb_rating      : 0.0
tvdb_runtime     : 46
tvdb_season      : <LazyField - value will be determined when it is accessed>
tvdb_series_name : Black Space
tvdb_status      : Continuing
tvdb_url         : http://thetvdb.com/index.php?tab=series&id=393293
zap2it_id        :
```

**Comment by soloam** [comment]
Run the same but with "--dump eval" that will render lazy fields

**Comment by BrutuZ** [comment]
> Run the same but with "--dump eval" that will render lazy fields

Not really needed, both `tvdb_id` and `tvdb_series_name` are rendering and wrong.

Try a `flexget execute --tasks test --dump-config`, that will render the whole task's yaml after every plugin modifies it, including templates. Then check the series entry for inconsistencies

**Comment by ktaragorn** [comment]
`--dump-config` dumps
```
--- config from task: test
disable:
  - seen
exec: echo "found {{tvdb_series_name}} at {{url}}"
mock:
  - title: Blackish S09E02 sssssThats What Friends Are For HDTV x264 CRiMSON
    url: mock://myurl
seen: local
series:
  - Blackish:
      set:
        tvdb_id: 281511
thetvdb_lookup: true

---
```
