### ISSUE TITLE
[imdb_list]  Unknown IMDB type entry received: tvspecial. Skipping

### ISSUE THREAD

**Issue by girtsl** [Flexget/Flexget#3310]
### Expected behaviour:

All entries from `imdb_list` input are accepted. Particularly, entries with type `tvspecial` are treated as movies.

### Actual behaviour:

`imdb_list` does not accept entries with type `tvspecial` and outputs an appropriate log message.
This appears to be a recent change on IMDB side as I'm almost certain I didn't observe this behavior a few days ago.

https://github.com/Flexget/Flexget/blob/develop/flexget/components/managed_lists/lists/imdb_list.py#L32
https://github.com/Flexget/Flexget/blob/develop/flexget/components/managed_lists/lists/imdb_list.py#L347-L357

### Steps to reproduce:

Add a "TV special" to IMDB watchlist, have a task that uses said IMDB list as input. In my case it syncs IMDB entries to Trakt.
For example:
https://www.imdb.com/title/tt16301388/
https://trakt.tv/movies/death-to-2021-2021

#### Config:
```yaml
  sync-imdb-to-trakt:
    imdb_list:
      login: '{? imdb.login ?}'
      cookies: '{? imdb.cookie ?}'
      list: '{? imdb.list ?}'
    accept_all: yes
    list_add:
      - trakt_list:
          account: '{? trakt.account ?}'
          list: '{? trakt.movies_watchlist ?}'
          type: movies
    disable: seen
```
  
#### Log:
```
2022-01-11 09:26:01 VERBOSE  imdb_list     sync-imdb-to-trakt Unknown IMDB type entry received: tvspecial. Skipping
```

### Additional information:

- FlexGet version: 3.2.7
- Python version: 3.7
- Installation method: docker
- Using daemon (yes/no): yes
