### ISSUE TITLE
Template validation to strict

### ISSUE THREAD

**Issue by Toilal** [Flexget/Flexget#334]
This config should work, but it doesn't pass the validation, because the mandatory parameter 'url' from 'html' plugin is missing from template. Validation should be done on merged configuration ...

```
templates:
  login:
    html:
      username: xxx
      password: xxx

tasks:
  download_movies:
    html:
      url: "http://www.somesite.com/torrents"
      links_re:
        - "^http://www.somesite.com/torrents/[^/]+(?!/)[^/]+$"
    accept_all: yes
    download: ~
    template: login
```
