### ISSUE TITLE
Movie with apostrophe wont match

### ISSUE THREAD

**Issue by tyjtyj** [Flexget/Flexget#3356]
### Expected behaviour:
cant match tpb discover plugin for movie with apostrophe.
Other movie works flawlessly.

### Steps to reproduce:
- Step 1: ...
#### Config:

```
    discover:
      release_estimations:
        optimistic: 90 days
      what:
        - trakt_list:
            username: xxxxx
            account: xxxx
            list: Queue
      from:
        - piratebay:
            category: 207
            sort_by: leechers
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2022-02-11 11:36:00 VERBOSE  discover      movie_monitor_tpb Searching for `The King's Man (2021)` with plugin `piratebay` (1 of 2)
2022-02-11 11:36:00 VERBOSE  discover      movie_monitor_tpb No search results for `The King's Man (2021)`
```

</details>

### Additional information:

- FlexGet version: 3.2.18
- Python version: 
- Installation method: Docker
- Using daemon (yes/no): yes
- OS and version: Debian 11
- Link to crash log:
