### ISSUE TITLE
RSS Plugin Caches Entries when Reading Local Files

### ISSUE THREAD

**Issue by budgetfermium** [Flexget/Flexget#3372]
### Expected behavior:
 I expect FlexGet to immediately detect the new size (999) after I change the corresponding RSS feed entry.
More generally, I expect that when I use a file as an input, the rss plugin will never cache entries.

### Actual behaviour:
As you can see in my minimal working example, the rss plugin does not register the change in the RSS feed until I run FlexGet with the --no-cache argument.

### Steps to reproduce:
- Step 1: Start FlexGet with the YAML file I provided.
- Step 2: Download any RSS feed and remove all but one entry.
- Step 3: Run `flexget execute`.
- Step 4: Change the size of the entry in the RSS file.
- Step 5: Run `flexget execute`.
- Step 6: Run `flexget execute --no-cache`.

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  test:
    rss: 
      url: file:///file.xml
    exec:
      on_output:
        for_undecided:
          - echo "{{size}}"
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2022-02-25 21:47:05 INFO     scheduler                     Starting scheduler
2022-02-25 21:47:30 INFO     exec          test            Stdout: 111
2022-02-25 21:47:38 INFO     exec          test            Stdout: 111
2022-02-25 21:47:52 INFO     exec          test            Stdout: 999
```
</details>

### Additional information:

- FlexGet version: 3.3.1
- Python version: 3.9.5
- Installation method: Docker
- Using daemon (yes/no): Yes
- OS and version: Ubuntu 20.04 LTS
