### ISSUE TITLE
"now - transmission_date_done" doesn't work

### ISSUE THREAD

**Issue by ProteinPig** [Flexget/Flexget#3373]
### Expected behaviour:

"now - transmission_date_done" can filter entries from transmission.

### Actual behaviour:

"now - transmission_date_done" doesn't work

### Steps to reproduce:
- torrents in transmission 
- run cli flexget execute --tasks transmission_test, they are rejected. 

but, if run cli flexget --test execute --tasks transmission_test, it says they would be  accepted.

#### Config:
```yaml
  transmission_test:
    <<: *from_transmission
    accept_all: yes
    if:
      - now - transmission_date_done < timedelta(days=2): reject
    transmission:
      <<: *transmission_auth
      action: pause
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 3.3.1
- Python version:
- Installation method: docker/wiserain
- Using daemon (yes/no): yes
- OS and version:
- Link to crash log:

**Comment by ProteinPig** [comment]
OK, I run another test
```
  transmission_test:
    <<: *from_transmission
    set:
      time_now: '{{ now }}'
    accept_all: yes
    exec: echo '{{ time_now }}'
```
And I found every time every entry, time_now is 2022-02-27 04:07:00.955898
