### ISSUE TITLE
MoreThanTV Plugin - Site URL Needs Updating

### ISSUE THREAD

**Issue by spgomez** [Flexget/Flexget#3496]
### Discussed in https://github.com/Flexget/Flexget/discussions/3492

<div type='discussions-op-text'>

<sup>Originally posted by **spgomez** July  4, 2022</sup>
I'm getting the following error when trying to use the morethantv plugin (within the discover plugin):

> ERROR    discover      Series-Latest   Error searching with morethantv: MoreThanTV login failed: HTTPSConnectionPool(host='www.morethan.tv', port=443): Max retries exceeded with url: /login.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000000009E40EB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Here is my config file:

```
variables: variables.yml
schedules:
  - tasks: [Series-Latest]
    interval:
      minutes: 30
templates:
  client:
    transmission:
      host: localhost
      port: 9091
      add_paused: No
      ratio: -1
  tv:
    template: client
    series:
      - Dark Winds
      - The Old Man
      - Evil
      - What We Do in the Shadows
      - Y':' The Last Man
      - Doom Patrol
      - Fargo
    quality: 1080p
    set:
      path: D://My Downloads/tv shows/
  movies:
    quality: 1080p
    set:
      path: D://My Downloads/movies/
tasks:
  Sync-Series:
    manual: yes
    filesystem:
      regexp: .*(avi|mkv|mp4)$
      path: D://My Downloads/tv shows/
      recursive: yes
      retrieve: files
    disable: builtins
    all_series: yes
    exec: echo "Found {{title}}"
  Series-Latest:
    template: tv
    discover:
      what:
        - next_series_episodes: yes
      from:
        - morethantv:
            username: '{? mtv.username ?}'
            password: '{? mtv.password ?}'
            category: TV
            all_tags: yes
    notify:
      entries:
        title: >
          {%if task in ["Series-Latest"](/"Series-Latest")%} New Series Episode added to queue
          {%else%}Download Start from task {{Series-Latest}}
          {%endif%}
        message: >
          {%if series_name is defined%}{{series_name}} - {{series_id}} - {{quality|d('')}}
          {%else%}{{title}}
          {%endif%}}
        via:
          - pushsafer:
              private_key: '{? ps.key ?}'
              device: "55172"
              sound: 12
              icon: 28
              vibration: 1
              url: '{{trakt_series_trakt_url}}'
              url_title: Link
```

I believe the issue might stem from the fact the that plugin is using an outdated url. MoreThanTV is now hosted at https://www.morethantv.me/, as you can see from the error above, it's trying to connect to www.morethan.tv.</div>
