### ISSUE TITLE
[Feature request] Simplify bulk downloading torrents from the Internet Archive, such as great78

### ISSUE THREAD

**Issue by nemobis** [Flexget/Flexget#3505]
### Expected behaviour:

[Tens of millions items](https://archive.org/search.php?query=format%3A(BitTorrent)) at the Internet Archive are [available for download via BitTorrent](https://blog.archive.org/2012/08/07/over-1000000-torrents-of-downloadable-books-music-and-movies/). The Internet Archive servers provides webseeds and a torrent tracker.

Similar to several plugins to easily add torrents from various trackers, there should be a way for the user to add Internet Archive torrents from a selected collection (like [the Great 78](https://great78.archive.org/)). Because the Internet Archive offers many file formats in the same item, it should be possible to download the items partially.

### Actual behaviour:

It took me quite a bit of experimentation before I managed to find a working solution with flexget. I succeeded with the transmission backend, failed with deluge (partial downloads were messed up) and didn't try with rtorrent (which doesn't/didn't yet support webseeds).

I tried this last year, not sure if there we

### Additional information:

I'd like to know whether and where you'd like me to contribute a template and task, or what other format would be suitable for such a feature.

What I used is the following:

```yaml
templates:
  torrent:
    transmission:
      host: localhost
      port: <port>
      username: '<username>'
      password: '<password>'
  great78:
    template: torrent
    set:
      # Patterns are in fnmatch format, not regexes
      # https://docs.python.org/3/library/fnmatch.html
      skip_files:
        - '*.tif'
        - '*.afpk'
        # Original versions all have a prefix _78_.
        # Only the best one is copied into a different filename which
        # sorts alphabetically before.
        - '_78_*'
        # The match by prefix does not seem to work; use suffixes too.
        - '*EQ.flac'
        - '*EQ.mp3'
        - '*EQ.png'
        - '*EQ_spectrogram.png'
        - '*flat.flac'
        - '*flat.mp3'
        - '*flat.png'
        - '*flat_spectrogram.png'
        # Try to match padding files, whose name is only digits.
        - '*[0-9]'
      include_files:
        # Metadata is cheap (except for the padding files) and
        # can be useful to grep/parse locally to find things.
        - '*.xml'
        - '*.sqlite'
        - '*.jpg'
        - '*.json'
        # If there is a restored FLAC we definitely want it.
        - '*restored.flac'
tasks:
  # Only download interesting files from great78 Internet Archive torrents.
  # To be applied after having added the torrents to Transmission.
  filter_great78:
    from_transmission:
      host: localhost
      port: <port>
      username: '<username>'
      password: '<password>'
    disable:
      - seen
      - seen_info_hash
    regexp:
      accept:
        - '78_'
    content_filter:
      require: '*.flac'
    template: great78
  # Try to fetch new uploads in the great78 Internet Archive collection.
  add_great78:
    rss:
      # This gets only the latest 50, but the collection is updated
      # in big batches of several thousands.
      # TODO: continuation.
      url: 'https://archive.org/services/collection-rss.php?collection=georgeblood'
      link:
        - guid
    urlrewrite:
      # Fetch the IA identifier from RSS and build the torrent URL.
      internetarchive:
        regexp: 'https://archive.org/details/(?P<iaid>[-_.\w]+).*'
        format: 'https://archive.org/download/\g<iaid>/\g<iaid>_archive.torrent'
    regexp:
      accept:
        - '78_'
      from: guid
    template: great78
```
