### ISSUE TITLE
Adding labels to torrents in transmission

### ISSUE THREAD

**Issue by rsekman** [Flexget/Flexget#3520]
Since version 3.00 transmission now supports labels for torrents. They can be provided at add-time, see [Sec. 3.4 of the RPC spec](https://github.com/transmission/transmission/blob/main/docs/rpc-spec.md#32-torrent-mutator-torrent-set).

It would be neat if the transmission plugin accepted the `labels` keyword so Flexget could automatically label torrents., E.g. one could do
```yml
set:
    path: '/var/Downloads/{{series_name}}'
    label:
        - '{{series_name}}'
        - flexget
```
