### ISSUE TITLE
`configure_series_` field preventing merge of `configure_series`' settings

### ISSUE THREAD

**Issue by BrutuZ** [Flexget/Flexget#3549]
### Expected behaviour:
Series settings to be merged among all sources, `series`' individual and group settings, `configure_series`' general settings and individual entries' settings from `configure_series_` fields

### Actual behaviour:
`configure_series_` field prevents the inclusion of `configure_series`' general settings and is overridden by `series` settings instead of merging

### Steps to reproduce:
1. Configs below
2. `flexget execute --dump-config` 

### Examples:
<details>
 <summary>Test 1</summary>

#### Config 1:
```yaml
tasks:
  test:
    mock:
      - {'title': '[GroupA] Cool Show - 01'}
    configure_series:
      from:
        mock: [{'title': 'Cool Show'}, {'title': 'Nice Show'}]
      settings:
        from_group: ['GroupC']
    series:
      settings:
        shows:
          from_group:
            - GroupA
      shows:
        - Cool Show:
            from_group:
              - GroupB
```
#### Output 1:
```yaml
─── config from task: test ─────────
configure_series:                   
  from:                             
    mock:                           
      - title: Cool Show            
      - title: Nice Show            
  settings:                         
    from_group:                     
      - GroupC                      
mock:                               
  - title: '[GroupA] Cool Show - 01'
series:                             
  - Nice Show:                      
      from_group:                   
        - GroupC                    
  - Cool Show:                      
      from_group:                   
        - GroupB                    
        - GroupA                    
        - GroupC                    
────────────────────────────────────
```  
</details>
<details>
 <summary>Test 2</summary>

#### Config 2:
```yaml
tasks:
  test:
    mock:
      - {'title': '[GroupA] Cool Show - 01'}
    configure_series:
      from:
        mock: [{'title': 'Cool Show', 'configure_series_from_group': 'GroupD'}, {'title': 'Nice Show'}]
      settings:
        from_group: ['GroupC']
    series:
      settings:
        shows:
          from_group:
            - GroupA
      shows:
        - Cool Show:
            from_group:
              - GroupB
```
#### Output 2:
```yaml
─── config from task: test ────────────────
configure_series:                          
  from:                                    
    mock:                                  
      - configure_series_from_group: GroupD
        title: Cool Show                   
      - title: Nice Show                   
  settings:                                
    from_group:                            
      - GroupC                             
mock:                                      
  - title: '[GroupA] Cool Show - 01'       
series:                                    
  - Nice Show:                             
      from_group:                          
        - GroupC                           
  - Cool Show:                             
      from_group:                          
        - GroupB                           
        - GroupA                           
───────────────────────────────────────────
```
</details>
<details>
 <summary>Test 3</summary>

#### Config 3:
```yaml
tasks:
  test:
    mock:
      - {'title': '[GroupA] Cool Show - 01'}
    configure_series:
      from:
        mock: [{'title': 'Cool Show'}, {'title': 'Nice Show', 'configure_series_from_group': 'GroupD'}]
      settings:
        from_group: ['GroupC']
    series:
      settings:
        shows:
          from_group:
            - GroupA
      shows:
        - Cool Show:
            from_group:
              - GroupB
```
#### Output 3:
```yaml
─── config from task: test ────────────────
configure_series:                          
  from:                                    
    mock:                                  
      - title: Cool Show                   
      - configure_series_from_group: GroupD
        title: Nice Show                   
  settings:                                
    from_group:                            
      - GroupC                             
mock:                                      
  - title: '[GroupA] Cool Show - 01'       
series:                                    
  - Nice Show:                             
      from_group: GroupD                   
  - Cool Show:                             
      from_group:                          
        - GroupB                           
        - GroupA                           
        - GroupC                           
───────────────────────────────────────────
```
</details>

### Additional information:

- FlexGet version: 3.3.20
- Python version: 3.7
- Installation method: git
- Using daemon (yes/no): yes
- OS and version: W10

**Comment by BrutuZ** [comment]
Stale but still relevant

**Comment by BrutuZ** [comment]
Bump

**Comment by gazpachoking** [comment]
What's happening is that `'configure_series_from_group': 'GroupD'` has from_group as a string, rather than a list. If it were a list, it would combine with the other items in the list, but a string will just override. e.g.
```yaml
tasks:
  a_task:
    series:
      groupa:
        - show1:
            from_group:
              - series_show
      settings:
        groupa:
          from_group:
            - series_group
    configure_series:
      from:
        mock:
          - title: show1
            configure_series_from_group:
              - conf_show
      settings:
        from_group:
          - conf_group
```
output
```yaml
series:                                                                        
  - show1:                                                                     
      from_group:                                                              
        - series_show                                                          
        - series_group                                                         
        - conf_show                                                            
        - conf_group    
```

It's not clear to me that changing that behavior would be definitively better.
