### ISSUE TITLE
Web UI is missing in docker image

### ISSUE THREAD

**Issue by trim21** [Flexget/Flexget#3580]
### Expected behaviour:
web ui works fine

### Actual behaviour:

web ui is missing

### Steps to reproduce:
- Step 1: ...

run it with docker config like this:

```yaml
  flexget:
    image: ghcr.io/flexget/flexget:3.3.39
    command: [--loglevel, WARNING, daemon, start, --autoreload-config]
    ports:
      - "8998:8998"
```

#### Config:
```yaml
# loglevel: info
web_server: 8998
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```text
2022-10-23 19:26:19 CRITICAL webui                         Failed to start web ui, this can happen if you are running from GitHub version and forgot to run the web ui build, see https://flexget.com/Web-UI for instructions
```
</details>

### Additional information:

docker image `ghcr.io/flexget/flexget:3.3.39`

It works on 3.3.37 and broken in 3.3.38

https://github.com/Flexget/Flexget/compare/v3.3.37...v3.3.38
