### ISSUE TITLE
imdb failing on lookup - further issues

### ISSUE THREAD

**Issue by Larrikinau** [Flexget/Flexget#3586]
### Actual behaviour:

Movies are rejected.

### Steps to reproduce:
flexget --test --debug execute --task aoue --dump eval

#### Config:
```yaml
templates:
  movies-instant:
    imdb_lookup: yes
    metainfo_movie: yes
    require_field: imdb_id    
    imdb:
      min_score: 1.0
      min_votes: 1
      min_year: 1900
    proper_movies: yes
    seen_movies: loose
    set:
      content_filename: "{{ imdb_name }} ({{ imdb_year }}) - {{ quality|upper }}"  
  movies:
    imdb_lookup: yes
    metainfo_movie: yes
    imdb:
      min_score: 6.6
      min_votes: 5000
      min_year: 1990
      reject_genres:
        - horror
    require_field: imdb_id    
    proper_movies: yes
    quality:
      - 2160p
      - 1080p
      - webdl
    seen_movies: strict   
```
  
#### Log:
<details>

 <summary>(click to expand)</summary>

```
2022-10-28 13:25:00
VERBOSE
task
putio-movies
REJECTED: `Raymond.&.Ray.2022.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.HEVC-X.mkv` by require_field plugin because required field imdb_id is `None`
2022-10-28 13:25:00
VERBOSE
task
putio-movies
REJECTED: `Brightburn.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-X.mkv` by require_field plugin because required field imdb_id is `None`
2022-10-28 13:25:00
VERBOSE
task
movies
REJECTED: `Frozen.2013.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-X.mkv` by require_field plugin because required field imdb_id is `None`
2022-10-28 13:25:00
VERBOSE
task
movies
REJECTED: `Maleficent.2014.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-X.mkv` by require_field plugin because required field imdb_id is `None`
```
</details>

### Additional information:

- FlexGet version:3.4.2
- Python version: Python 3.6.9
- Using daemon (yes/no): yes
- OS and version: Ubuntu 22.04.1 LTS

**Comment by gazpachoking** [comment]
Your debug log looks a bit wrong.
Can you try again setting up a special test task like this, and running using the provided args and providing the output?
```yaml
tasks:
  test_task:
    mock:
      # Put the title of one of your failing lookups here instead of this
      - title: the.pink.panther.strikes.again.1976.1080p.bluray.x264.ac3-pxhd.mp4
    imdb_lookup: yes
    accept_all: yes
```
`flexget --test --debug execute --task test_task --dump eval`
