### ISSUE TITLE
Movie id's from movie lists are a string while some providers are integer

### ISSUE THREAD

**Issue by lostb1t** [Flexget/Flexget#3607]
The DB type for movie id's is varchar. This is to accommodate ids like imdb which include a string. (tt)
The problem is that some other providers like TMDB have integer id's. 

So when matching up an movie list against an provider where the id is an int the types do not match.

### Expected behaviour:

Using crossmatch on field tmdb_id should match correctly.

### Actual behaviour:

Using crossmatch on field tmdb_id will fail because the id from the movie list is a string and the id from the lookup an integer

### Steps to reproduce:
```

  from-transmission-lookup:
    metainfo_movie: yes
    tmdb_lookup: yes
    from_transmission:
      <<: *transmission_def
    accept_all: true
    manual: yes

  movies-queue:
    movie_list: watchlist
    accept_all: yes
    crossmatch:
      from:
        - from_task: from-transmission-lookup
      fields:
        - tmdb_id
      action: reject
      exact: yes
```
