### ISSUE TITLE
The timezone of tasks page on web UI is not the same with OS

### ISSUE THREAD

**Issue by StackStomp** [Flexget/Flexget#3609]
### Expected behaviour:

The timezone of tasks web page should has the same timezone with the OS on which flexget running. 

### Actual behaviour:

The tasks page timezone is UTC +0

### Steps to reproduce:
- Step 1:  start flexget
- Step 2: Log in to the web UI and open the task page

#### Config:
```yaml
templates:
  favorite:
    accept_all: yes
    download:
      path: /tmp/torrents/
      temp: /tmp/
    exec:
      on_output:
        for_accepted: python3 /det/deduplicate_existing_files.py -f '{{location}}' $(cat /flexget/det.cfg)

tasks:
  yyy1:
    rss: 'xxx'
    template: favorite
  yyy2:
    rss: 'xxx'
    template: favorite
  yyy3:
    rss: 'xxx'
    template: favorite
  yyy4:
    rss: 'xxx
    template: favorite

schedules:
  - tasks: '*'
    interval:
      minutes: 15

web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes
```
  
#### Log:

NA

### Additional information:

- FlexGet version: 3.5.5
- Python version: 3.9.2
- Installation method:pip from docker
- Using daemon (yes/no):yes
- OS and version: Ubuntu 22.04; docker: debian:bullseye-slim
- Link to crash log:NA
