### ISSUE TITLE
All tasks rejected

### ISSUE THREAD

**Issue by Rubiooo04** [Flexget/Flexget#3649]
### Steps to reproduce:
- Step 1: Execute 1 Tasks ( all good )
- Step 2: Add 2nd task
- Step 3: Execute 2 Tasks ( all rejected )

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  JHbendicion:
    rss: https://showrss.info/user/229110.rss?magnets=true&namespaces=true&name=null&quali
    series:
      - Criminal Minds
      - Rick and Morty
    transmission:
      host: transmission
      port: 9091
      username: admin
      password: "pedrobenito"
  sort_tv:
    priority: 2
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    thetvdb_lookup: yes
    require_field: series_name
    exec:
      auto_escape: yes
      on_output:
        for_entries: |
          if mediainfo "{{ location }}" | grep EAC3; then
            mkdir -p "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}" && ffmpeg -hwaccel auto -y -i "{{ location }}" -map 0 -c:s copy -c:v copy -c:a ac3 -b:a 640k "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}/{{ tvdb_series_name }} - {{ series_id }}{{ location | pathext }}"
          else
            mkdir -p "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}" && cp "{{ location }}" "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}/{{ tvdb_series_name }} - {{ series_id }}{{ location | pathext }}"
          fi
schedules: no
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
I dont get nothing in the log
```
</details>

#### Issue:
<details>
 <summary>(click to expand)</summary>

When I put only this configuration in the flexget configuration everything works fine but if I add one more task neither of the 2 tasks work (it tells me that it has rejected everything) and in the log there is no change

```
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  JHbendicion:
    rss: https://showrss.info/user/229110.rss?magnets=true&namespaces=true&name=null&quali
    series:
      - Criminal Minds
      - Rick and Morty
    transmission:
      host: transmission
      port: 9091
      username: admin
      password: "pedrobenito"
```

**Task  ↴ ↴**
![flexcget1](https://user-images.githubusercontent.com/77902247/210255183-1eff490e-b9b6-435b-a42c-cefe58308bf0.PNG)

**Log  ↴ ↴**
![flexcget2](https://user-images.githubusercontent.com/77902247/210255297-233dba5b-9d8b-4cc9-9919-85a1ebb6e9c5.PNG)

</details>

**Comment by BrutuZ** [comment]
I'm assuming they are being rejected by the [`seen` plugin](https://flexget.com/Plugins/seen)

**Comment by Rubiooo04** [comment]
I tried to disable the seen plugin, but it keeps rejecting my tasks
<details>
 <summary>(click to expand ^task image^)</summary>

![flexcget1](https://user-images.githubusercontent.com/77902247/210258067-5756356b-bfcf-4f77-acd0-03f423641783.PNG)

</details>

#### New Config:

<details>
 <summary>(click to expand)</summary>

```
tasks:
  JHbendicion:
    rss: https://showrss.info/user/229110.rss?magnets=true&namespaces=true&name=null&quali
    disable:
      - seen
      - seen_info_hash
    series:
      - Criminal Minds
      - Rick and Morty
    transmission:
      host: transmission
      port: 9091
      username: admin
      password: "Jpassword"
  sort_tv:
    priority: 2
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    disable:
      - seen
      - seen_info_hash
    thetvdb_lookup: yes
    require_field: series_name
    exec:
      auto_escape: yes
      on_output:
        for_entries: |
          if mediainfo "{{ location }}" | grep EAC3; then
            mkdir -p "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}" && ffmpeg -hwaccel auto -y -i "{{ location }}" -map 0 -c:s copy -c:v copy -c:a ac3 -b:a 640k "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}/{{ tvdb_series_name }} - {{ series_id }}{{ location | pathext }}"
          else
            mkdir -p "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}" && cp "{{ location }}" "/storage/series/{{ tvdb_series_name }}/Season {{ series_season }}/{{ tvdb_series_name }} - {{ series_id }}{{ location | pathext }}"
          fi
schedules: no

```
</details>

#### New log:
<details>
 <summary>(click to expand)</summary>


![flexcget2](https://user-images.githubusercontent.com/77902247/210257960-0e0a6ecd-7fdd-41f2-bff9-8cd03e7f8515.PNG)

</details>
