### ISSUE TITLE
[Feature request]new parameter for transmission plugin.

### ISSUE THREAD

**Issue by zero-custom** [Flexget/Flexget#3655]
Expected behaviour: flexget can notify the transmission daemon to start to download process through https.

https://github.com/Flexget/Flexget/blob/278ad19c3f4d59bcfa368907ee30c5b5e7c381a0/flexget/plugins/clients/transmission.py#L56
a new parameter to instruct flexget to use http or https to connect with transmission.

example:
```
transmission:
  transmission:
    host: https-server
    port: 443
    use_https: yes
```
