### ISSUE TITLE
Certifications missing

### ISSUE THREAD

**Issue by StefftheEmperor2** [Flexget/Flexget#3666]
### Expected behaviour:
Hi,
I'm trying to filter contents suitable for children from an input. Therefore I need those fields mapped in the imdb_lookup and tmdb_lookup. Could someone please add these fields?

### Actual behaviour:

certification fields are missing :-(

#### Config:
```yaml
tasks:
  move_downloads:
    filesystem:
        path:
          - "{? download_dir ?}"
        retrieve:
          - dirs
          - files
        recursive: 2
    set:
      relativePath: "{{ location[\"{? download_dir ?}\"|length+1:] }}"
    regexp:
      accept:
          - '^([a-zA-Z0-9\._\- ]*)\/([a-zA-Z0-9\._\- ]*)$'
      from: relativePath
    all_series:
      tracking: no
      parse_only: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    disable: seen
    seen_info_hash: no
    make_html:
      file: ~/output.html
      template: downloads.html.template
```
 
### Additional information:

- FlexGet version: c0bf79f47e7d61be48a3d47cc0ed0f3dd68efcdd
- Python version: 3.11
- Installation method: vanilla / git
- Using daemon (yes/no): no
- OS and version: Debian sid
