### ISSUE TITLE
docker container - add ability to pull more python modules from PIP_REQUIREMENTS_FILE environment variable

### ISSUE THREAD

**Issue by pleasantone** [Flexget/Flexget#3687]
### Expected behaviour:

The plex_watchlist plugin should work seamlessly as documented, as well as other plugins that have requirements
the developers have deliberately not chosen to include in the default requirements.txt.

### Actual behaviour:

```
2023-02-11 16:55:09 CRITICAL task          discover-plex-watchlist-movies plexapi package required
```

### Steps to reproduce:

- Step 1: Configure the plex watchlist feature in `config.yml`

```yaml
  discover-plex-watchlist-movies:
    priority: 49
    no_entries_ok: yes
    plex_watchlist:
      token: '{? plex.token ?}'
      type: movie
    accept_all: yes
    seen: local
    list_add:
      - movie_list: movies
```

- Step 2: execute the task

```
flexget execute --tasks discover-plex-watchlist-movies --now
```

#### Config:

You don't need my full config, it's irrelevant, the problem is that the plex_watchlist plugin requires the plexapi
python module and the developers deliberately chose to not include it in requirements.txt

```yaml
  discover-plex-watchlist-movies:
    priority: 49
    no_entries_ok: yes
    plex_watchlist:
      token: '{? plex.token ?}'
      type: movie
    accept_all: yes
    seen: local
    list_add:
      - movie_list: movies
```
  
#### Log:

<details>
 <summary>(click to expand)</summary>

```
2023-02-11 16:55:09 CRITICAL task          discover-plex-watchlist-movies plexapi package required
```
</details>

### Additional information:

- FlexGet version: 3.5.22
- Python version: 3.10.10
- Installation method: docker
- Using daemon (yes/no): yes (irrelevant)
- OS and version: docker current as of 2022-02-12

### Proposed fix:

Look at cpoppema/docker-flexget. He has some very cute [code](https://github.com/cpoppema/docker-flexget/blob/83ad55804c17d05aa5af209296665f7c58fdb24d/etc/cont-init.d/20-update-flexget) that looks at the environment variable `PIP_REQUIREMENTS_FILE` installs additional python modules.

This could go in etc/cont-init.d/ if we used s6 supervisor
```
if [ ! -z "$PIP_REQUIREMENTS_FILE" ]; then
    while IFS= read -r line; do
        if [ ! -z "$line" ] && [[ "$line" != \#* ]]; then
            pip install -U "$line"
        fi
    done < "$PIP_REQUIREMENTS_FILE"
fi
```

Another alternative, is look for the environment variable "FLEXGET_EXTRA_MODULES" which could be a comma-separated collection of modules, and install them that way. I suggest the former so it makes versioning and pinning cleaner, but don't really care strongly.

This is a pretty trivial and easy to fix problem, but I don't have a good build env to test it on.
