### ISSUE TITLE
Series `AEW Rampage` with identified_by value `date` are not supported

### ISSUE THREAD

**Issue by ddonindia** [Flexget/Flexget#3728]
I am getting with "identified_by value `date` are not supported" error while trying to DL AEW or WWE releases following is my config file

```
templates:
  dl:
    magnets: yes
    download: yes
    set:
      path: //tmp/

tasks:
  WrestlingTracker:
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    template:
      -  dl
    series:
      - AEW Rampage:
            identified_by: date
    discover:
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - piratebay:
            category: highres tv
            sort_by: seeds
            sort_reverse: false
        - piratebay:
            category: tv
            sort_by: seeds
            sort_reverse: false
        - search_rss:
            url: https://eztv.re/ezrss.xml
            all_entries: yes
            ascii: yes
            escape: yes
            link:
              - link
              - magneturi
        - limetorrents:
            category: tv
            order_by: seeds
```
[flexget.log](https://github.com/Flexget/Flexget/files/11077139/flexget.log) full trace log.

**Comment by BrutuZ** [comment]
Your `identified_by` has one indent too many.
Couldn't parse the log to confirm that's the issue, trace has TMI. Verbose is usually enough

**Comment by ddonindia** [comment]
Tried again by fixing indentation but still same result

```
2023-03-28 00:18:56 VERBOSE  next_series_episodes WrestlingTracker Series `AEW Rampage` with identified_by value `date` are not supported.
2023-03-28 00:18:56 WARNING  utils         WrestlingTracker Input next_series_episodes did not return anything
```
following are verbose logs:
```
[proxychains] config file found: /opt/tools/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.16-git-11-g66f99b1
2023-03-28 00:18:56 VERBOSE  task_queue                    There are 1 tasks to execute. Shutdown will commence when they have completed.
2023-03-28 00:18:56 VERBOSE  next_series_episodes WrestlingTracker Series `AEW Rampage` with identified_by value `date` are not supported.
2023-03-28 00:18:56 WARNING  utils         WrestlingTracker Input next_series_episodes did not return anything
2023-03-28 00:18:56 VERBOSE  discover      WrestlingTracker Discovering 0 titles ...
2023-03-28 00:18:56 INFO     discover      WrestlingTracker Ignoring interval because of --discover-now
2023-03-28 00:18:56 VERBOSE  details       WrestlingTracker Task didn't produce any entries.
2023-03-28 00:18:56 VERBOSE  details       WrestlingTracker Summary - Accepted: 0 (Rejected: 0 Undecided: 0 Failed: 0
```

**Comment by BrutuZ** [comment]
Ah I see, the "issue" is `discover` doesn't search for dates

**Comment by ddonindia** [comment]
Is it a bug or its designed that way only?

**Comment by BrutuZ** [comment]
Not a bug. I guess no one bothered to implement it probably because dates can be tricky due to having many different formats, maybe fear of server spam since they're often used for daily shows, and perhaps other reasons I can't think of right now.

Other than "not a bug" it's all speculation on my part though.

`next_series_episodes`, no, You can still have `discover` search for the bare show title using other inputs though. Even [`mock`](https://flexget.com/Plugins/mock) might work there

**Comment by ddonindia** [comment]
Thanks for reply. How do I use mock is there any tut? Is it possible to use dynamic date (today's date) in regx match?

**Comment by BrutuZ** [comment]
Mock is dead simple, no tutorial needed beyond the few lines in the wiki page linked. Just add it to your discover's `what:` field
```yaml
discover:
  what:
    - mock:
        - {title: 'AEW Rampage'}
  from:
    ...
```

You can't dynamically change the regexp, but maybe setting the `begin` in the `series` plugin will work?

**Comment by ddonindia** [comment]
@BrutuZ  Thanks with mock its working :).

here is full conf for future reference
```
templates:
  dl:
    magnets: yes
    download: yes
    convert_magnet: yes
    set:
      path: //tmp/

tasks:
  WrestlingTracker:
    thetvdb_lookup: yes
    tvmaze_lookup: yes
    template:
      -  dl
    series:
      - AEW Rampage:
          alternate_name:
            - All Elite Wrestling Rampage
          identified_by: date
          begin: "2023-03-21"
          quality: 1080p
      - AEW Dynamite:
          alternate_name:
            - All Elite Wrestling Dynamite
          identified_by: date
          begin: "2023-03-21"
          quality: 1080p
    discover:
      release_estimations: smart
      what:
        - mock:
           - {title: 'AEW Rampage'}
           - {title: 'AEW Dynamite'}
      from:
        - piratebay:
            category: highres tv
            sort_by: seeds
            sort_reverse: false
        - piratebay:
            category: tv
            sort_by: seeds
            sort_reverse: false
        - search_rss:
            url: https://eztv.re/ezrss.xml
            all_entries: yes
            ascii: yes
            escape: yes
            link:
              - link
              - magneturi
        - limetorrents:
            category: tv
            order_by: seeds
        - rarbg:
            category: x264 1080p
```
