### ISSUE TITLE
"transmission daemon require auth" when trying to connect to Docker container

### ISSUE THREAD

**Issue by steponmepls** [Flexget/Flexget#3729]
### Expected behaviour:

Send accepted entries to the transmission-daemon inside the docker container.

### Actual behaviour:
I deployed transmission-daemon using a [docker](https://hub.docker.com/r/linuxserver/transmission) container but I am unable to connect to it with Flexget. I used the very same credentials I use with transmission-daemon 3.00 but I am not being able to connect. I double checked the credentials are correct by logging-in in the web ui after launching the docker container. I also checked with other third party clients and I am able to connect as well. I also noticed that forcing the host from `localhost` to my network IP like `192.168.1.10` doesn't cause an auth error (probably meaning that I can actually connect to the daemon) but in the end a crash happens instead with error message `BUG: Unhandled error in plugin transmission: 'Torrent' object has no attribute 'totalSize'`. I believe that is a separate issue but I'll append the crash log at the bottom nonetheless.

### Steps to reproduce:
Use the Flexget's transmission plugin and use user, pass and port to connect to the docker container.

#### Config:
```yaml
variables: variables.yml

tasks:
  anime:
    template:
      - transmission
    inputs:
      - rss: https:/myfeeds.rss
    series:
      1080p:
        - My show
templates:
  transmission:
    transmission:
      username: '{? accounts.transmission.user ?}'
      password: '{? accounts.transmission.pass ?}'
      port: 9092
```
```yaml
accounts:
  transmission:
    user: user
    pass: mypassword
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
..
2023-03-27 14:00:15 VERBOSE  details       anime           Summary - Accepted: 1 (Rejected: 36 Undecided: 409 Failed: 0)
2023-03-27 14:00:15 CRITICAL plugin        anime           Error connecting to transmission: transmission daemon require auth
2023-03-27 14:00:15 WARNING  task          anime           Aborting task (plugin: transmission)
2023-03-27 14:00:15 CRITICAL plugin        cleaner         Error connecting to transmission: transmission daemon require auth
2023-03-27 14:00:15 WARNING  task          cleaner         Aborting task (plugin: from_transmission)
```
</details>
Zip containing debug logs and crash reports https://github.com/Flexget/Flexget/files/11078490/flexget.zip

### Additional information:

- FlexGet version: 3.5.34
- Python version: 3.11.2
- Transmission version: 4.0.2 
- transmission-rpc version: tried both 4.1.3 and 3.4.1
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Debian GNU/Linux bookworm/sid x86_64
