### ISSUE TITLE
variabes being changed from snake_case to camelCase

### ISSUE THREAD

**Issue by lenisko** [Flexget/Flexget#3754]
### Expected behaviour:

Pushover with variables should send message.

### Actual behaviour:

Pushover is not sending messages when variables are used. When variables are replaced by strings, it works.

### EDIT
https://github.com/Flexget/Flexget/issues/3754#issuecomment-1533333256 Found issue

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

variables: yes

schedules:
  - tasks: 'series-anime-automatic'
    interval:
      minutes: 30

tasks:
  series-anime-automatic:
    rss: "https://nyaa.si/?page=rss&u=subsplease"
    quality: 1080p
    template: anilist_series
    notify:
      entries:
        title: Anime(A) {{series_name}} - {{series_id}}
        via:
          - pushover:
              user_key: "{? pushover.userKey ?}"
              api_key: "{? pushover.apiKey ?}"
              priority: -1

templates:
  anilist_series:
    template: anime_series
    configure_series:
      settings:
        identified_by: sequence
      from:
        anilist:
          username: "{? anilist.username ?}"
          status: current
          release_status:
            - releasing
            - not_yet_released
          format:
            - tv
            - tv_short

  anime_series:
    transmission:
      host: "{? transmission.hostname ?}"
      port: 9091
      username: "{? transmission.username ?}"
      password: "{? transmission.password ?}"
      path: "/leech/anime/series/{{series_name|replace(':', '')}}"
      add_paused: no
```

#### Variables:
```yaml
anilist:
  username: xxx
pushover:
  apiKey: xxx
  userKey: xxx
transmission:
  hostname: xxx
  password: xxx
  username: xxx
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2023-04-28 00:44:36 WARNING notify series -anime Error while sending notification to `pushover`: application token is invalid
2023-04-28 00:44:31 WARNING notify series -anime Error while sending notification to `pushover`: application token is invalid
2023-04-28 00:44:26 WARNING notify series -anime Error while sending notification to `pushover`: application token is invalid
2023-04-28 00:44:21 WARNING notify series -anime Error while sending notification to `pushover`: application token is invalid
```
</details>

### Additional information:

- FlexGet version: `3.6.4`
- Python version: `3.9`
- Installation method: Docker `wiserain/flexget`
- Using daemon (yes/no): `yes`
- OS and version: `DSM 7.1.1-42962 Update 5`

**Comment by ksurl** [comment]
I'm on the latest and pushover works with variables. Can you try adding quotes in the variables file for pushover? Also try renaming the variable.

**Comment by gazpachoking** [comment]
You should be able to run `flexget --test execute --tasks series-anime-automatic --dump-config` to see what the config for the task ends up looking like after variable replacement. Maybe that helps debug.

**Comment by lenisko** [comment]
Thanks for hints. I'm using database storage.

Here's what I noticed: 

Variables in WebUI
```yml
anilist:
  username: xxx
pushover:
  apikey: xxx
  userkey: xxx
transmission:
  hostname: xxx
  password: xxx
  username: xxx
```
In database
```json
{"pushover": {"api_key": "xxx", "user_key": "xxx"}, "transmission": {"hostname": "xxx", "password": "xxx", "username": "xxx"}, "anilist": {"username": "xxx"}}
```

Looks like the keys are auto translated from `camelCase` to `snake_case`. Switched to `snake_case` in yml for now and I'll report later!
