### ISSUE TITLE
Error while sending notification to `telegram`: missing python-telegram-bot pkg

### ISSUE THREAD

**Issue by evilbulgarian** [Flexget/Flexget#3767]
### Expected behaviour:

Working telegram notifications from docker hub image. Please add python-telegram-bot to requirements.

### Actual behaviour:

Error while sending notification to `telegram`: missing python-telegram-bot pkg

### Steps to reproduce:

set up a telegram notification in config.yml

#### Config:
```yaml
        via:
          - telegram:
              bot_token: xxxxx
              parse_mode: markdown
              recipients:
                - group: xxxx

```
  
#### Log:
```
Error while sending notification to `telegram`: missing python-telegram-bot pkg
```
</details>

### Additional information:

- FlexGet version: 
- Python version: 3.11
- Installation method: dockerhub
- Using daemon (yes/no): yes
- OS and version: gentoo gnu/linux
- Link to crash log:
