### ISSUE TITLE
Can Flexget add or subtract a number from a series ID?

### ISSUE THREAD

**Issue by Aquaakuma** [Flexget/Flexget#3888]
I want to download TV series through RSS. The TV series titles provided by RSS are similar to ‘XXXX - 25’. I can use the manipulate plugin to format it as ‘XXXX S02E25’. However, 25 is actually the first episode of the second season. I hope to subtract 24 from 25. I have tried everything I can think of, but nothing works. It’s driving me crazy. If Flexget has this feature, please give me some hints.

**Comment by ksurl** [comment]
yes you can set a custom series id

in your series config, set a custom variable with the offset. then on the rename when moving, use the new id instead of the default accepted one if it exists.

```
series:
  - 'SERIES':
      alternate_name: SERIES_ALT
      set:
        custom_series_id: "{{(series_id)|int - 24)|string|pad(2)}}"
...
move:
  to: /blah/{{series_name}}/
  rename: "{{series_name}} {% if custom_series_id is defined %}S02E{{custom_series_id}}{% else %}{{series_id|pad(2)}}{% endif %}"
```
