### ISSUE TITLE
can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by jacaru** [Flexget/Flexget#3912]
After https://github.com/Flexget/Flexget/pull/3758, I am getting this error a lot:
```
can't compare offset-naive and offset-aware datetimes
```
What I am doing is comparing custom entry fields (set with the set plugin from the config template itself) containing string formatted naive dates coming from various sources, including `utcnow`, which was then changed to be offset aware. I use `parsedate` before comparing. Shouldn't `parsedate` be using pendulum as well in some way to generate dates that can be compared with naive dates?

**Comment by gazpachoking** [comment]
Good catch. `parsedate` indeed needs to be updated to use the compatibility class that allows comparing naive to offset aware datetimes. That being said, utcnow and now should already have that feature so I would expect your example  to work already. Are you on the latest version? (There were a couple other fixes after the initial merge.) If so, can you give some more details of you example so I can understand how both sides of the comparison somehow avoided getting our custom compatibility layer? Just want to make sure I'm fixing in all the places needed.

Here's the quick test I did which was already working. 
```yaml
tasks:
  a_task:
    mock:
      - title: someentry
    set:
      somedate: "2023-12-31"
      somecomparison: "{{somedate|parsedate < utcnow}}"
```

**Comment by gazpachoking** [comment]
Oh, were you comparing some parsed date to another? That indeed isn't working at the moment if only one specified a timezone.
```yaml
tasks:
  a_task:
    mock:
      - title: someentry
    set:
      somedate: "2023-12-31T00:00:00+03:00"
      otherdate: "2023-12-31"
      somecomparison: "{{somedate|parsedate < otherdate|parsedate}}"
```
