### ISSUE TITLE
unknown url type error should NOT be reported for magnet URIs

### ISSUE THREAD

**Issue by de666** [Flexget/Flexget#3944]
### Expected behaviour:

using plugins which handles magnet URIs correctly (eg. convert_magnet or rtorrent_magnet), no errors should be reported in logfile
since the URI is handled correctly, and correctly reported (as log INFO)

```
2024-02-29 11:45:15 INFO     rtorrent_magnet task_a          Writing rTorrent Magnet File: /data/meta-True Detective S04E04 Night Country Parte 4 ITA ENG 1080p AMZN WEB DL DD5 1 H 264 MeM GP mkv.torrent
```

### Actual behaviour:

error reported before INFO line
```
2024-02-29 11:45:15 ERROR    utils.requests task_a          Error getting magnet:?xt=urn:btih:BDB7F8CCD33D752343D19718D0C3AA1E2A98804E&dn=True+Detective+S04E04+Night+Country+Parte+4+ITA+ENG+1080p+AMZN+WEB-DL+DD5+1+H+264-MeM+GP+mkv&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fbt1.archive.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce: <urlopen error unknown url type: magnet>
```

### Steps to reproduce:
- configure rss plugin as input
- allow redirect (necessary otherwise no torrent file is downloaded)
- configure some plugins which handles magnet uri download (convert_magnet or rtorrent_magnet)
- run the task

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  task_a:
    redirect_url: yes
    no_entries_ok: yes
    rss:
        url: http://xxxx:9117/api/v2.0/indexers/limetorrents/results/torznab/api?apikey=xxxx&t=search&cat=5000&q=1080p
        all_entries: no
    rtorrent_magnet: /data/
    series:
      - True Detective

schedules:
  - tasks: [task_a]
    interval:
      minutes: 30

```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2024-02-29 11:45:15 ERROR    utils.requests task_a          Error getting magnet:?xt=urn:btih:BDB7F8CCD33D752343D19718D0C3AA1E2A98804E&dn=True+Detective+S04E04+Night+Country+Parte+4+ITA+ENG+1080p+AMZN+WEB-DL+DD5+1+H+264-MeM+GP+mkv&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fbt1.archive.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce: <urlopen error unknown url type: magnet>
2024-02-29 11:45:15 INFO     rtorrent_magnet task_a          Writing rTorrent Magnet File: /data/meta-True Detective S04E04 Night Country Parte 4 ITA ENG 1080p AMZN WEB DL DD5 1 H 264 MeM GP mkv.torrent
```
</details>

### Additional information:

- FlexGet version:  3.11.19
- Python version: 3.11.8
- Installation method: https://docs.linuxserver.io/images/docker-flexget/
- Using daemon (yes/no): yes
- OS and version: Alpine 3.19
- Link to crash log:

**Comment by de666** [comment]
any update on this?

**Comment by gazpachoking** [comment]
Hmm, I was not able to replicate this. Here's the config I tried:
```yaml
tasks:
  a_task:
    redirect_url: yes
    no_entries_ok: yes
    mock:
      - title: Test.S02E04.2160p.WEB-DL.DDP5.1.DoVi.H.265-xyz
        url: "magnet:?xt=urn:btih:BDB7F8CCD33D752343D19718D0C3AA1E2A98804EF"
    rtorrent_magnet: "~"
    accept_all: yes
```
