### ISSUE TITLE
[help] Plugins > Notifiers > email possible to send email with from name/header 

### ISSUE THREAD

**Issue by redcat42** [Flexget/Flexget#3958]
ive seen this 

https://flexget.com/Plugins/Notifiers/email

however, wanted to know if it is possible to send 'from' name not just email

for example

```
notify:
  task:
    via:
      - email:
          from: '"xxx" <xxx@xxx.com>'
          to: xxx@xxx.xxx
          smtp_host: smtp.host.com
          html: no
```

so when the receiver, 
receives a notification(on android for example), 
of the email it has a 
'from name'  instead of
just an email address
