### ISSUE TITLE
movie_list without CLI

### ISSUE THREAD

**Issue by alannssantos** [Flexget/Flexget#3966]
### has some way to add the movie in the config file instead of the CLI mode, using discover?

I'm using it that way, but I'd like to keep everything in the config file.
``` yml
tasks:
  Movies:
    discover:
      what:
        - movie_list: movies
      from:
        - yts: yes
      interval: 15 minutes
      release_estimations: ignore
    list_match:
      from:
        - movie_list: movies
    quality:
      - 1080p
      - bluray|webrip
    imdb_lookup: yes
    transmission: yes
```
