### ISSUE TITLE
Flexget Docker container stuck in "restarting (1) x# of seconds ago"

### ISSUE THREAD

**Issue by arcomador** [Flexget/Flexget#3984]
This has seemed to start since the latest build of Flexget was released. 

Any help would be greatly appreciated.

[Contents of my flexget.sh script]
```
docker run -d --name flexget --restart=always \
-v /opt/flexget/config:/config \
-v /lib/var/deluge/.config/deluge:/delugeconfig \
-p 5050:5050 ghcr.io/flexget/flexget:develop daemon start --autoreload-config


```
[config.yml]
```
web_server: yes
templates:
  delconf1:
    deluge:
      config_path: "/delugeconfig"
      host: 192.168.1.252
      path: "/datadriveroot/Torrents/incomplete/"
      username: "omitted"
      password: "omitted"
tasks:
  recent-shows:
    rss: "omitted"
    all_series: yes
    template: delconf1
    deluge:
      path: "/datadriveroot/Torrents/incomplete"
      move_completed_path: "/datadriveroot/VideoStorage/TV Shows/{{series_name}}/Season {{series_season}}"
      main_file_only: yes
      queue_to_top: yes
```
