### ISSUE TITLE
Trakt_lookup wrong movie

### ISSUE THREAD

**Issue by diogosena** [Flexget/Flexget#4009]
The trakt_lookup plugin is identifying the wrong movie

```
  test_trakt_lookup:
    manual: yes
    template:
      - disable-seen-retry
    mock:
      - title: "If.2024"
    trakt_lookup: yes
    accept_all: yes
    exec:
      - echo "{{ movie_name }}"
      - echo "{{ movie_year }}"
      - echo "{{ media_id }}"
      - echo "{{ trakt_movie_name }}"
```

the result is:
```

title             : If.2024
url               : mock://localhost/mock/-142416124
original_url      : mock://localhost/mock/-142416124
accepted_by       : accept_all
imdb_id           : tt27675815
media_id          : taxali gate 2024
movie_name        : Taxali Gate
movie_year        : 2024
original_title    : If.2024
quality           : <LazyField - value will be determined when it is accessed>
task              : test_trakt_lookup
tmdb_id           : 1232280
trakt_actors      : <LazyField - value will be determined when it is accessed>
trakt_genres      : ['crime', 'drama', 'thriller']
trakt_homepage    : None
trakt_language    : pa
trakt_languages   : ['en']
trakt_movie_id    : 996592
trakt_movie_name  : Taxali Gate
trakt_movie_slug  : taxali-gate-2024
trakt_movie_year  : 2024
trakt_overview    : In the red light district of Lahore, when the daughter of an underprivileged wedding dancer is raped by the powerful Choudhary's son, the neighbourhood pimp and the top prostitute help the pair seek justice.
trakt_rating      : 0
trakt_released    : 2024-02-16
trakt_runtime     : 95
trakt_tagline     : Nothing is sweeter than revenge
trakt_trailer     : https://youtube.com/watch?v=ZuGZDdfB7Rw
trakt_translations: <LazyField - value will be determined when it is accessed>
trakt_votes       : 0
```
