### ISSUE TITLE
Issue with multiple color range HDR and DV

### ISSUE THREAD

**Issue by ronerfbpr** [Flexget/Flexget#4074]
### Steps to reproduce:
- Step 1: Filter any series that the episode have both DV and HDR color range
- Step 2: The episode will be identified only as DV color range and not both.
- Example of rejected entry:
SeriesNameHere.S02E02.TitleHere.2160p.ATVP.WEB-DL.DDP5.1.Atmos.DV.HDR10+.H.265-Group
SeriesNameHere S02E02 TitleHere 2160p ATVP WEB-DL DDP5 1 DV HDR H 265-Group

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules:
  - tasks: [doit]
    interval:
      minutes: 15

templates:
  tv:
    series:
      settings:
        2160pHDR:
          quality: 2160p webrip+ hdr|hdrplus
          specials: no
      2160pHDR:
        - SeriesNameHere
    deluge:
      host: xxxxxxxxx
      username: xxxxxxxxx
      password: xxxxxxxxx
      path: /mnt/seriados/{{series_name}}/

tasks:
  doit:
    rss:
      url: xxxxxxxxx
      all_entries: no
    priority: 1
    template: tv
```
### Additional information:
- FlexGet version: 3.11.58
- Python version: 3.11.10
- Installation method: Docker (linuxserver/docker-flexget)
- Using daemon (yes/no): yes
- OS and version: Alpine 3.20
