### ISSUE TITLE
FlexGet is not compatible with python-telegram-bot versions above 12.8

### ISSUE THREAD

**Issue by vivodi** [Flexget/Flexget#4076]
### Summary
FlexGet is not compatible with python-telegram-bot versions above 12.8. 

This issue has been around for ages, can anyone make FlexGet compatible with the latest python-telegram-bot again?

### Expected behaviour:

FlexGet works with latest python-telegram-bot.

### Actual behaviour:
FlexGet is not compatible with python-telegram-bot versions above 12.8
### Steps to reproduce:
1. Install latest python-telegram-bot (v21.8) and latest FlexGet (v3.11.58)
2. Put [third-party plugins](https://github.com/madwind/flexget_qbittorrent_mod) under `plugins` folder.

#### Config:
I'm using a third-party plugin which is using the telegram module of FlexGet.
```yaml
tasks:
  sign_in:
    auto_sign_in:
      user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36'
      max_workers: 5
      get_messages: no
      get_details: no
      sites:
        milkie:
          login:
            username: *****
            password: *****
    accept_all: yes
    seen:
      fields:
        - title
    notify:
      task:
        always_send: true
        message: |+
          {%- if task.accepted -%}
          {%- for group in task.accepted|groupby('task') -%}
          FlexGet has just signed in {{ group.list|length }} sites for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- if task.failed %}
          {% for group in task.failed|groupby('task') %}
          The following sites have failed for task {{ group.grouper }}:
          {%- for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }} Reason: {{entry.reason|d('unknown')}}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- for group in task.entries|groupby('task') %}
          {% for entry in group.list %}
          {%- if entry.messages|d('') %}
          Messages:
          {{ entry.title }} {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
        via:
          - telegram_mod:
              bot_token: '*****'
              image: 'details_report.png'
              recipients:
                - username: '*****'
        

```
  
#### Log:
<details>
 <summary>(click to expand)</summary>
C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notifiers\telegram.py:262: RuntimeWarning: coroutine 'Bot.get_me' was never awaited
  self._bot.getMe()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2024-12-01 21:20:29 DEBUG    telegram      sign_in         loading cached chat ids
2024-12-01 21:20:29 DEBUG    telegram      sign_in         found 0 cached chat_ids: []
2024-12-01 21:20:29 DEBUG    telegram      sign_in         loading new chat ids
2024-12-01 21:20:29 ERROR    notify_entry  sign_in         'coroutine' object is not iterable
Traceback (most recent call last):

  File "C:\Users\vivodi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000022D776F7EC0>
    └ <Thread(task_queue, started daemon 27284)>
  File "C:\Users\vivodi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x0000022D776F7BA0>
    └ <Thread(task_queue, started daemon 27284)>
  File "C:\Users\vivodi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(task_queue, started daemon 27284)>
    │    │        │    └ ()
    │    │        └ <Thread(task_queue, started daemon 27284)>
    │    └ <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x0000022D1A074E00>>
    └ <Thread(task_queue, started daemon 27284)>

  File "C:\Users\vivodi\Projects\Flexget\flexget\task_queue.py", line 46, in run
    self.current_task.execute()
    │    │            └ <function Task.execute at 0x0000022D153D4E00>
    │    └ <flexget.task.Task object at 0x0000022D1A90C650>
    └ <flexget.task_queue.TaskQueue object at 0x0000022D1A074E00>

  File "C:\Users\vivodi\Projects\Flexget\flexget\task.py", line 88, in wrapper
    return func(self, *args, **kw)
           │    │      │       └ {}
           │    │      └ ()
           │    └ <flexget.task.Task object at 0x0000022D1A90C650>
           └ <function Task.execute at 0x0000022D153D4D60>

  File "C:\Users\vivodi\Projects\Flexget\flexget\task.py", line 717, in execute
    self._execute()
    │    └ <function Task._execute at 0x0000022D153D4CC0>
    └ <flexget.task.Task object at 0x0000022D1A90C650>

  File "C:\Users\vivodi\Projects\Flexget\flexget\task.py", line 686, in _execute
    self.__run_task_phase(phase)
    │                     └ 'output'
    └ <flexget.task.Task object at 0x0000022D1A90C650>

  File "C:\Users\vivodi\Projects\Flexget\flexget\task.py", line 515, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               │                 │       │      └ (<flexget.task.Task object at 0x0000022D1A90C650>, {'task': {'always_send': True, 'message': "{%- if task.accepted -%}\n{%- f...
               │                 │       └ 'output'
               │                 └ <PluginInfo(name=notify)>
               └ <flexget.task.Task object at 0x0000022D1A90C650>

  File "C:\Users\vivodi\Projects\Flexget\flexget\task.py", line 548, in __run_plugin
    result = method(*args, **kwargs)
             │       │       └ {}
             │       └ (<flexget.task.Task object at 0x0000022D1A90C650>, {'task': {'always_send': True, 'message': "{%- if task.accepted -%}\n{%- f...
             └ <Event(name=plugin.notify.output,func=on_task_output,priority=0)>

  File "C:\Users\vivodi\Projects\Flexget\flexget\event.py", line 21, in __call__
    return self.func(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ (<flexget.task.Task object at 0x0000022D1A90C650>, {'task': {'always_send': True, 'message': "{%- if task.accepted -%}\n{%- f...
           │    └ <bound method Notify.on_task_output of <flexget.components.notify.notify.Notify object at 0x0000022D1A769880>>
           └ <Event(name=plugin.notify.output,func=on_task_output,priority=0)>

  File "C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notify.py", line 152, in on_task_output
    self.send_notification(
    │    └ <function Notify.send_notification at 0x0000022D19D61DA0>
    └ <flexget.components.notify.notify.Notify object at 0x0000022D1A769880>

> File "C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notify.py", line 102, in send_notification
    send_notification(*args, **kwargs)
    │                  │       └ {'template_renderer': <bound method Task.render of <flexget.task.Task object at 0x0000022D1A90C650>>}
    │                  └ ('{% if not task.failed and not task.accepted %} Task {{task.name}} did not produce any entries.{% else %} [FlexGet] {{task.n...
    └ <bound method NotificationFramework.send_notification of <flexget.components.notify.notification_framework.NotificationFramew...

  File "C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notification_framework.py", line 121, in send_notification
    notifier_plugin.notify(
    │               └ <function TelegramNotifierMod.notify at 0x0000022D16793880>
    └ <flexget.plugins.telegram_mod.TelegramNotifierMod object at 0x0000022D153CA9C0>

  File "C:\Users\vivodi\Projects\Flexget\plugins\telegram_mod.py", line 44, in notify
    chat_ids = self._real_init(session, config)
               │    │          │        └ {'bot_token': '********************', 'image': 'details_report.png', 'recipients': [{'username': 'c...
               │    │          └ <sqlalchemy.orm.session.ContextSession object at 0x0000022D1A9C9FA0>
               │    └ <function TelegramNotifier._real_init at 0x0000022D167CDA80>
               └ <flexget.plugins.telegram_mod.TelegramNotifierMod object at 0x0000022D153CA9C0>

  File "C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notifiers\telegram.py", line 238, in _real_init
    chat_ids = self._get_chat_ids_n_update_db(session)
               │    │                         └ <sqlalchemy.orm.session.ContextSession object at 0x0000022D1A9C9FA0>
               │    └ <function TelegramNotifier._get_chat_ids_n_update_db at 0x0000022D167CDEE0>
               └ <flexget.plugins.telegram_mod.TelegramNotifierMod object at 0x0000022D153CA9C0>

  File "C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notifiers\telegram.py", line 333, in _get_chat_ids_n_update_db
    chat_ids, has_new_chat_ids = self._get_chat_ids(session, usernames, fullnames, groups)
                                 │    │             │        │          │          └ []
                                 │    │             │        │          └ []
                                 │    │             │        └ ['vivodi']
                                 │    │             └ <sqlalchemy.orm.session.ContextSession object at 0x0000022D1A9C9FA0>
                                 │    └ <function TelegramNotifier._get_chat_ids at 0x0000022D167CDF80>
                                 └ <flexget.plugins.telegram_mod.TelegramNotifierMod object at 0x0000022D153CA9C0>

  File "C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notifiers\telegram.py", line 375, in _get_chat_ids
    new_chat_ids = list(self._get_new_chat_ids(usernames, fullnames, groups))
                        │    │                 │          │          └ []
                        │    │                 │          └ []
                        │    │                 └ ['vivodi']
                        │    └ <function TelegramNotifier._get_new_chat_ids at 0x0000022D167CE0C0>
                        └ <flexget.plugins.telegram_mod.TelegramNotifierMod object at 0x0000022D153CA9C0>

  File "C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notifiers\telegram.py", line 439, in _get_new_chat_ids
    upd_usernames, upd_fullnames, upd_groups = self._get_bot_updates()
                                               │    └ <function TelegramNotifier._get_bot_updates at 0x0000022D167CE160>
                                               └ <flexget.plugins.telegram_mod.TelegramNotifierMod object at 0x0000022D153CA9C0>

  File "C:\Users\vivodi\Projects\Flexget\flexget\components\notify\notifiers\telegram.py", line 486, in _get_bot_updates
    updates.extend(ups)
    │       │      └ <coroutine object Bot.get_updates at 0x0000022D1A4B99C0>
    │       └ <method 'extend' of 'list' objects>
    └ []

TypeError: 'coroutine' object is not iterable
</details>

### Additional information:

- FlexGet version: v3.11.58
- Python version: 3.12
- Installation method: package
- Using daemon (yes/no): no
- OS and version: Windows 11 24H2
