### ISSUE TITLE
Input plugin plex_watchlist causing inputs task to abort due to missing plexapi python dependency

### ISSUE THREAD

**Issue by haydster7** [Flexget/Flexget#4091]
### Expected behaviour:
Watchlist `inputs` plugin that includes at least 1 `plex_watchlist` entry will successfully connect to plex and add the entries

### Actual behaviour:
Watchlist `inputs` plugin fails to run with error message `Plugin ``inputs`` cannot be used because dependency ``plexapi`` is missing.`

### Steps to reproduce:
- Step 1: Create task that includes the inputs plugin, and plex_watchlist child plugin e.g.
```
tasks:
  watchlist:
    inputs:
      - plex_watchlist:
          token: '#######'
          type: movie
    list_add:
      - movie_list: moviewatchlist
```
- Step 2: Run task "watchlist"

#### Config:
```yaml
accept_all: true                                                                                                                                   
inputs:                                                                                                                                            
  - trakt_list:                                                                                                                                    
      list: movie                                                                                                                                  
      strip_dates: false                                                                                                                           
      type: auto                                                                                                                                   
      username: ######                                                                                                                        
  - plex_watchlist:                                                                                                                                
      token: ###########                                                                                                               
      type: movie                                                                                                                                  
  - trakt_list:                                                                                                                                    
      list: watchlist                                                                                                                              
      strip_dates: false                                                                                                                           
      type: auto                                                                                                                                   
      username: #######                                                                                                                    
list_add:                                                                                                                                          
  - movie_list: moviewatchlist                                                                                                                     
priority: 1                                                                                                                                        
seen: local 
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2024-12-15 23:29:38 DEBUG    task          watchlist       executing watchlist
2024-12-15 23:29:38 DEBUG    input_cache   watchlist       cache name: trakt_list_8dfd2d74239822ab8240d28e877be201 (has: )
2024-12-15 23:29:38 VERBOSE  input_cache   watchlist       Restored 15 entries from db cache for trakt_list
2024-12-15 23:29:38 CRITICAL task          watchlist       plexapi package required
2024-12-15 23:29:38 WARNING  task          watchlist       Aborting task (plugin: inputs)
```
</details>

### Additional information:

I can see plexapi in `dev-requirements-extras.txt`, is it required in `requirements-docker.txt` as well?

- FlexGet version: 3.13.2
- Python version: 3.11.11
- Installation method: docker
- Using daemon (yes/no): yes
