### ISSUE TITLE
How do I set final quality 1080p h265/x265 while still allowing h264

### ISSUE THREAD

**Issue by 1337ingDisorder** [Flexget/Flexget#4197]
It looks like the original poster for this issue posted it as a Q&A, but it was never answered.

I have the same issue, and it looks like others have run up against this issue too, and no solution has ever been posted anywhere (at least nowhere that seems to be catalogued by google). 

I want to tell Flexget to PREFER files in x265, and to wait up to 48 hours for that preferred format, but then to ACCEPT an h264 version if it still can't find an x265 version.

Here's my relevant config:

```
  tv1080x5:
    series_premiere: yes
    series:
      settings:
        shows1080x5:
          quality: 720p-1080p
          target: 1080p h265
          timeframe: 48 hours
          tracking: no
          propers: yes
          upgrade: yes
      shows1080x5:
        - A Man on the Inside
        - A P Bio
        - Abbott Elementary
```

(...and so on, with shows to accept)

The problem is that Flexget seems to think I want h264 if it can find it, even if my stated preference is for h265.

What are us users all doing wrong?

Thanks in advance!

For context here's the Q&A inquiry a former user posted way back in 2021 that still hasn't been answered:

### Discussed in https://github.com/Flexget/Flexget/discussions/3044

<div type='discussions-op-text'>

<sup>Originally posted by **ghost** June 17, 2021</sup>
My goal is to download 1080p h265. Source is not a concern for me, how can i achieve this? Currently 1080p h264 webdl is higher priority than 1080p h265.

Current config:

```
templates:
  tv:
    series:
      settings:
        best:
          target: 1080p !10bit h265
          quality: 720p-1080p !10bit h265|h264
          timeframe: 4 hours
          upgrade: yes
          propers: 76 hours
```

What flexget sees:

`REJECTED: `Show S01E02 1080p HEVC x265 by series plugin because worse quality than already downloaded.`

```
┌Show────────┬───────────┬──────────────────────────────────────────────────────────────────────┬─────────────────────────────┬────────┐
│ Identifier │ Last seen │ Release titles                                                       │ Release Quality             │ Proper │
├────────────┼───────────┼──────────────────────────────────────────────────────────────────────┼─────────────────────────────┼────────┤
│ S01E01     │ 7d 1h     │ Show S01E01 HDR 2160p WEB h265                                       │ 2160p webdl h265 hdr        │        │
│            │           │ Show S01E01 720p HEVC x26*                                           │ 720p h265                   │        │
│            │           │ Show S01E01 1080p WEB h264                                           │ 1080p webdl h264            │        │
│            │           │ Show S01E01 720p WEB h264                                            │ 720p webdl h264             │        │
│            │           │ Show S01E01 1080p HEVC x265*                                         │ 1080p h265                  │        │
│ S01E02     │ 18h       │ Show S01E02             1080p DSNP WEB-DL Atmos H 264                │ 1080p webdl h264            │        │
│            │           │ Show S01E02             2160p DSNP WEB-DL DDP5 1 Atmos HDR HEVC      │ 2160p webdl h265 hdr dd+5.1 │        │
│            │           │ Show S01E02             1080p DSNP WEB-DL DDP5 1 Atmos H 264         │ 1080p webdl h264 dd+5.1     │        │
│            │           │ Show S01E02 MULTi 1080p WEB H264*                                    │ 1080p webdl h264            │        │
│            │           │ Show S01E02 720p HEVC x265                                           │ 720p h265                   │        │
│            │           │ Show S01E02 720p WEB h264                                            │ 720p webdl h264             │        │
│            │           │ Show S01E02 1080p WEB h264                                           │ 1080p webdl h264            │        │
│            │           │ Show S01E02 1080p HEVC x265                                          │ 1080p h265                  │        │
└────────────┴───────────┴──────────────────────────────────────────────────────────────────────┴─────────────────────────────┴────────┘
```</div>

**Comment by BrutuZ** [comment]
Try separating into two tasks (templates is your friend) each with its own quality and a 2 days [delay](https://flexget.com/Plugins/delay) on the h264 one

**Comment by 1337ingDisorder** [comment]
> Try separating into two tasks (templates is your friend) each with its own quality and a 2 days [delay](https://flexget.com/Plugins/delay) on the h264 one

Thanks for the suggestion!

This sounds like it would work, but then I'd have to maintain two identical lists of shows. Eg, if I wanted to add a show I'd have to add it to both lists, which could become problematic.

Is there a way to have two tasks use the same list of shows? If so, how would I alter the config I posted above in order to accomplish that?

**Comment by BrutuZ** [comment]
> I'd have to maintain two identical lists of shows

Hence templates, they're meant for that, reusing code in multiple tasks. Or include, that works too

**Comment by 1337ingDisorder** [comment]
> > I'd have to maintain two identical lists of shows
> 
> Hence templates, they're meant for that, reusing code in multiple tasks. Or include, that works too

Ok I'm taking a stab it this now, and I think I must be missing something.

I've separated it into two tasks, one with the quality set to h265 and one with the quality set to h264 to run 48 hours later.

But I'm still back to the same initial problem — the one with the quality set to h265 runs for 48 hours. If, during those 48 hours, it sees a version in h264 it downloads that one. Then if an h265 one comes out after (but still within the 48 hours) it SHOULD upgrade from the h264 to the target h265, but it doesn't. It just keeps the h264 version and calls it a day.

So we're back to the original issue.

How do I tell the h265 task to ONLY accept h265 and to skip h264 versions even if it sees them?

**Comment by BrutuZ** [comment]
Can't say, you forgot to show how the config looks like after the changes.
But the h264 task shouldn't output anything until the `delay` runs out.

I'm counting on the series plugin rejecting the h264 due to previously accepted HEVC, not positive it works though, unsure if it only delays the output or rechecks the filters too, I personaly only use it with a `list_remove` for shiws no longer airing

**Comment by gazpachoking** [comment]
When you use 'target' in series, it should not accept anything outside of that target until the 'timeframe' has passed. Is that not happening for you? What @BrutuZ is describing with two tasks will result in the same outcome as target/timeframe for the series plugin, but it's a bit more flexible because you can use any filter plugins instead of just using the quality target of the series plugin.

**Comment by 1337ingDisorder** [comment]
> When you use 'target' in series, it should not accept anything outside of that target until the 'timeframe' has passed. Is that not happening for you? 

Thanks, no it isn't. 

But that's exactly what I'm hoping to achieve.

Here's my full config (with series lists trimmed down and URLs snipped)

```
templates:

  lofi:
    series:
      settings:
        allshows:
          quality: 480p-1080p
          target: 480p
          timeframe: 1 hours
          tracking: no
      allshows:
        - Show 1
        - Show 2
        - etc
    download: /shared/torrents-unchecked/

  tv2160:
    series_premiere: yes
    series:
      settings:
        shows2160:
          quality: 1080p-2160p
          target: 2160p h265
          timeframe: 24 hours
          tracking: no
          propers: yes
          upgrade: yes
      shows2160:
        - Show 3
        - Show 4
        - etc
    download: /shared/torrents-unchecked/

  tv1080x4:
    series_premiere: yes
    series:
      settings:
        shows1080:
          quality: 720p-1080p
          target: 1080p h264
          timeframe: 24 hours
          tracking: no
          propers: yes
          upgrade: yes
      shows1080:
        - Show 5
        - Show 6
        - etc
    download: /shared/torrents-unchecked/

  tv1080x5:
    series_premiere: yes
    series:
      settings:
        shows1080x5:
          quality: 720p-1080p
          target: 1080p h265
          timeframe: 48 hours
          tracking: no
          propers: yes
          upgrade: yes
      shows1080x5:
        - Show 7
        - Show 8
        - etc
    download: /shared/torrents-unchecked/

tasks:
  PubTrak:
    rss: <RSS url snipped>
    template: 
      - lofi
      - tv2160
      - tv1080x4
      - tv1080x5
    download: /shared/torrents-unchecked/
  PrivTrak:
    rss: <RSS url snipped>
    template: 
      - tv1080x4
      - tv1080x5
  PrivTrakPaks:
    rss: <RSS url snipped>
    accept_all: yes
    download: /shared/torrents-unchecked/

```
