### ISSUE TITLE
Template waiting for better copy for apparently no reason?

### ISSUE THREAD

**Issue by 1337ingDisorder** [Flexget/Flexget#4201]
I have a template that seems to be behaving oddly.

Here's the template config:

```
  tv1080x4_5:
    series_premiere: yes
    series:
      settings:
        shows1080x4_5:
          quality: 1080p
          timeframe: 24 hours
          tracking: no
          propers: yes
      shows1080x4_5:
        - Show 1
        - Show 2
        - etc
    download: /shared/torrents-unchecked/
```

My understanding is this should accept the first 1080p copy it sees, whether it's h264 or h265 or any other codec/format etc. In theory any shows on my list that have a 1080p copy of any kind out, that copy should be accepted.

But that hasn't been the case.

Flexget log shows lines like this:

```
INFO     flexget.components.series.series PubTrak            `The Daily Show`: timeframe waiting for 17h:47min. Currently best is `The Daily Show 2025 01 29 Rachel Mason 1080p HEVC x265-MeGusta`.
INFO     flexget.components.series.series PubTrak            `Stephen Colbert`: timeframe waiting for 16h:57min. Currently best is `Stephen Colbert 2025 01 29 Will Ferrell 1080p HEVC x265-MeGusta`.
```

So it's seeing a 1080p copy out there, but for some reason it doesn't think those 1080p copies are good enough quality for the 1080p quality setting.

What am I missing here? I don't have any target codec that I want to specify, I just want to accept the first 1080p copy it sees.
