### ISSUE TITLE
configure_series next-episode.net Error during input plugin

### ISSUE THREAD

**Issue by paulpoco** [Flexget/Flexget#4207]
2025-02-01 15:05:45 WARNING  configure_series eztv            Error during input plugin text: RequestException: HTTPSConnectionPool(host='next-episode.net', port=443): Max retries exceeded with url: /PAGES/misc/export_calendar?z&u=paulpoco&k=df421b0def9e2fabc80f74147ca83f87.ics (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x14e644c70590>: Failed to establish a new connection: [Errno -3] Try again'))
2025-02-01 15:05:45 INFO     configure_series eztv            Did not get any series to generate series configuration

`    configure_series:
      from:
        text:
          url: "https://next-episode.net/PAGES/misc/export_calendar?z&u=some_user&k=some_secret.ics"
          entry:
            title: ^SUMMARY:([\w\s]*)-\s(s\d{2})(e\d{2})
            url: ^SUMMARY:([\w\s]*)-\s(s\d{2})(e\d{2})`

Latest version of Flexget 3.13.27 running from Docker

This is from deleting all flexget files except config.yml, somehow does get a series list from the exist tv folders

Or is there a better choice for adding shows, just used to next-episode.net.   Or just use the full series.yml?

I do not know if this is just one time or all the time.

**Comment by paulpoco** [comment]
Do I need to actually use this format instead?
https://flexget.com/en/Cookbook/Series/next-episode

I have been modifying my config.yml over the years to what I thing works but who knows.

Maybe my config.yml below is terrible.

web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes  

templates:
  global:
    # Make sure all filenames are Windows safe (for samba)
    pathscrub: windows
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"
    verify_ssl_certificates: no
    regexp:
      reject:
        - (s|d)ub(s|bed)?\b
        - \b(duo|tri|quadri|tetra|penta)logy\b
        - \b(s|d)ub(s|bed|lado|titulado)?\b
        - \bhc\b
        - \b3d\b
        - \btrailer\b
        - \bspanish\b
        - \bfre(nch)?\b
        - \bita(lian)?\b
        - \bspa(nish)?\b
        - \bger(man)?\b
        - \bcastellano\b
        - \brus(sian)?\b
        - \btamil\b
        - \bhindi\b
        - \bTemporada\b
        - \bEspanol\b
        - \bR5\b
        - \bWEBSCR\b
        - \bscreener\b
        - \bTS\b
        - \bCam\b
        - TrTd TeaM
        - \[TNTVillage\]
        - \[facepalm\]
        - \bASAP\b
    content_filter:
      reject:
        - 'password.txt'
        - '*.rar'
        - '*.wmv'
        - '*.avi'
        - '*.zip'
    domain_delay:
      bt-chat.com: 5 seconds
      torrentz.eu: 5 seconds
      thepiratebay.se: 10 seconds
      showrss.info: 10 seconds

  tv:
    tmdb_lookup: yes
    exists_series:
      path: /data/media/tv/
      allow_different_qualities: better
    configure_series:
      from:
        text:
          url: "https://next-episode.net/PAGES/misc/export_calendar?z&u=some_user&k=some_secret.ics"
          entry:
            title: ^SUMMARY:([\w\s]*)-\s(s\d{2})(e\d{2})
            url: ^SUMMARY:([\w\s]*)-\s(s\d{2})(e\d{2})
    series_premiere: no
    set:
      quality: 720p+
      upgrade: yes
      tracking: backfill
    deluge:
      username: admin
      password: deluge
      path: "/data/torrents/tv"
      content_filename: "{{series_name}} - {{series_id}} - {{quality}}"
      move_completed_path: "/data/media/tv/{{series_name}}/Season {{series_season}}/"
      magnetization_timeout: 30
      queue_to_top: no
      main_file_only: yes
      keep_subs: yes
    verify_ssl_certificates: no

  movies:
    inputs:
      - rss: https://www.limetorrents.lol/rss/16/
      - rss: https://www.torlock.com/movies/rss.xml
      - rss: https://www.torrentfunk.com/movies/rss.xml    
    imdb:
      min_score: 4.0
      min_votes: 300
      min_year: 1965
      reject_genres:
        - Horror
        - Musical
        - Music
      accept_languages:
        - english
      reject_mpaa_ratings:
        - X
    content_filter:
      reject:
        - '*.rar'
        - '*.wmv'
        - '*.avi'
        - '*.zip'
    quality: 1080p-2160p
    content_size:
      max: 60000
      min: 1800
    regexp:
      from: title
      reject:
        - ' ts '
        - hindi
        - german
        - s\d+e\d+
        - '\d{4}.\d{2}.\d{2}'
        - \d+x\d+
    imdb_lookup: yes
    require_field: imdb_url
    seen_movies: loose
    limit_new: 20
    exists_movie:
      path:
        - /data/media/movies
        - /data/torrents/movies
      lookup: imdb
      allow_different_qualities: no
    proper_movies: yes
    deluge:
      username: admin
      password: deluge
      magnetization_timeout: 50
      queue_to_top: no
    set:
      path: "/data/torrents/movies"
      move_completed_path: "/data/media/movies/{{ imdb_name|replace('/', '_')|replace(':', ' -') }} ({{ imdb_year }})"
      content_filename: |
        {{ imdb_name|replace('/', '_')|replace(':', ' -') }} ({{ imdb_year }}) - {{ quality }}
      label: movie
      addpaused: no
      ratio: 1

tasks:
  eztv:
    priority: 1
    template:
      - tv
    rss: https://eztv.ag/ezrss.xml

  karmorra:
    priority: 1
    template:
      - tv
    rss: "http://showrss.info/user/secret.rss?magnets=true&namespaces=true&name=null&quality=hd&re=yes"

  karmorra_all:
    priority: 1
    template:
      - tv
    rss: http://showrss.info/other/shows.rss?magnets=true

  torrentgalaxyH:
    priority: 1
    template:
      - tv
    rss: https://torrentgalaxy.to/rss.php?cat=41

  torrentgalaxyU:
    priority: 1
    template:
      - tv
    rss: https://torrentgalaxy.to/rss.php?cat=11
 
  pirateproxy:
    priority: 1
    template:
      - tv
    rss: https://pirateproxy.live/rss/new/208
 
  torlock_tv:
    priority: 1
    template: tv
    html:
      url: "https://www.torlock.com/television/rss.xml"

  limetorrent:
    priority: 1
    template: tv
    rss: "https://www.limetorrents.cc/rss/20/"

  queue_from_foobar:
    manual: yes
    template: movies
    
  seed_series_db:
    # The filesystem plugin will find all of your existing episodes
    filesystem:
      regexp: .*(avi|mkv|mp4)$
      path: /data/media/tv
      recursive: yes
      retrieve: files
    template: tv
    # We use the manual plugin so that this task only runs when explicitly called
    manual: yes

**Comment by paulpoco** [comment]
```
    import_series:
      settings:
        quality: webdl|hdtv <=720p
        target: 720p
        timeframe: 36 hours
        set:
          path: /home/public/TV/{{series_name}}/Season {{"%02d"|format(series_season)}}
      from:
        text:
          url: (url to ical)
          entry:
            title: ^SUMMARY:(.*) - [0-9](/0-9)+x[0-9](/0-9)+.*$
            url: ^SUMMARY:(.*) - [0-9](/0-9)+x[0-9](/0-9)+.*$
```

Above entry: vs mine,  especially the title and url lines

```
    configure_series:
      from:
        text:
          url: "https://next-episode.net/PAGES/misc/export_calendar?z&u=paulpoco&k=df421b0def9e2fabc80f74147ca83f87.ics"
          entry:
            title: ^SUMMARY:([\w\s]*)-\s(s\d{2})(e\d{2})
            url: ^SUMMARY:([\w\s]*)-\s(s\d{2})(e\d{2})
```
