### ISSUE TITLE
(question) jinja for loops in config.yml

### ISSUE THREAD

**Issue by mcrosson** [Flexget/Flexget#4215]
Is there a way to use jinja for loops within the `config.yml` to build a `sequence` or `anchor` that can be used with the `sequence` plugin? If not, is there a filter or form of jinja template that can be used in place of a for loop to achieve the same result?

I'm using the latest docker image of flexget (`ghcr.io/flexget/flexget`) and the below is a mock up of what I'm trying to accomplish. I'm currently getting yaml syntax errors and schema validation errors with every form of the below that I've tried.

``` yaml
variables:
  rss_feed_ids:
    - 1
    - 2
    - 3

templates:
  anchors:
    _rss_feeds: &rss_feeds
      {% for id in rss_feed_ids %}
      - rss : 'http://domain.tld/{{ id }}/api/[redacted url query]'
      {% endfor %}

tasks:
  test:
    sequence:
      *rss_feeds
```

**Comment by gazpachoking** [comment]
I don't think there is a good way. You can (ab)use the variables plugin to create lists or dicts, but the variables plugin doesn't expose a 'block' notation, only {??} for variables. Here's one terrible plan that would work, except for it seems our custom filters are not available in variables plugin templates. (I'll probably fix that shortly though.)
```yaml
variables:
  rss_feed_ids:
    - 1
    - 2
    - 3
tasks:
  test:
    sequence: |
      [{? rss_feed_ids|map('string')|map('re_replace', '(.)', '{"rss": "http://domain.tld/\\1/api/"}')|join(", ") ?}]
```
I think the real answer is that you should list out the full rss plugin configs. Are you using the rss_feed_ids variables in some other place that makes this more desirable?

**Comment by mcrosson** [comment]
> I think the real answer is that you should list out the full rss plugin configs. Are you using the rss_feed_ids variables in some other place that makes this more desirable?

It's more to do with I have 50 search terms to run across 5 trackers and managing 250 rss urls is a huge PITA to manage over time in YAML. (For me at least).

Thank you for the quick turn around on this.

**Comment by gazpachoking** [comment]
If you are running search terms through trackers perhaps the discover plug-in with search_rss is what you want?

**Comment by mcrosson** [comment]
discover with search_rss looks like it could be manageable but I can't tell how to define `what` so its a simple list of search terms. Is there a way to manually specify a list of search terms?

**Comment by gazpachoking** [comment]
Mock plugin is the best way to create entries from within the config:
```yaml
    discover:
      what:
        - mock:
            - this
            - that
            - theother
      from:
        - search_rss: http://somethingsomething{{search_term}}
        - search_rss: http://somethingelese{{search_term}}
```

**Comment by mcrosson** [comment]
`search_rss` seems to always return 0 results for me. When I view the rss feed in my browser, there is a lot of data present and I'm not sure why this isn't picking up any data.

CLI: `flexget execute --now --discover-now --tasks test-1`

config:

``` yaml
##########
# variables
##########
variables:
  rss_uri: http://domain.tld:port
  rss_api_key: long_alpha_numeric_string

##########
# config
##########
# enable web ui
web_server:
  web_ui: yes

#########
# tasks
tasks:
# test task
  test-1:
    discover:
      what:
        - mock:
          - term1
      from:
        - search_rss: 
            url: '{{rss_uri}}/1/api?apikey={{rss_api_key}}&t=search&cat=6000&q={{search_term}}'
            all_entries: yes
            other_fields:
              - guid
    accept_all: yes
    make_rss:
      days: -1
      items: 1000
      file: /data/test-1.rss
      title: '[{{ guid.split("/")[2] }}] {{ title }}'
```

**Comment by gazpachoking** [comment]
Variables from variables plugin have different jinja syntax as they are evaluated on config load.
`'{?rss_uri?}/1/api?apikey={?rss_api_key?}&t=search&q={{search_term}}'`

**Comment by mcrosson** [comment]
Both the `{? foo ?}` syntax and a hard coded `url` value don't seem to produce results.

However if I create a new test task with just `rss` and the url I get values returned.

config used for tests:

``` yaml
##########
# variables
##########
variables:
  rss_uri: http://domain.tld:port
  rss_api_key: long_alpha_numeric_string

##########
# config
##########
# enable web ui
web_server:
  web_ui: yes

#########
# tasks
tasks:
# test task
  test-1:
    rss: 
      url: '{? rss_uri ?}/1/api?apikey={? rss_api_key ?}&t=search&q=term1'
      all_entries: yes
      other_fields:
        - guid
    accept_all: yes
    make_rss:
      days: -1
      items: 1000
      file: /data/test-1.rss
      title: '[{{ guid.split("/")[2] }}] {{ title }}'
  test-2:
    discover:
      what:
        - mock:
          - term1
      from:
        - search_rss: 
            url: '{? rss_uri ?}/1/api?apikey={? rss_api_key ?}&t=search&q={{ search_term }}'
            all_entries: yes
            other_fields:
              - guid
    accept_all: yes
    make_rss:
      days: -1
      items: 1000
      file: /data/test-2.rss
      title: '[{{ guid.split("/")[2] }}] {{ title }}'
```

**Comment by gazpachoking** [comment]
Ahh, right, I had to run it and look at the log. discover is normally used for movies, so it tries to look up release dates to avoid searching for every movie every run. If you set 'release_estimations: ignore' your search should go through. Turn on debug logging and look for any hints if it still isn't working. There is also 'interval' option to discover, which is the minimum interval between searching for the same term again which you may want to set.

**Comment by mcrosson** [comment]
The `release_estimations` was definitely the 'missing piece' that got this setup fully working. Thank you again for all the help with this.

For anyone coming across this discussion, a complete example config:

``` yaml
##########
# variables
##########
variables:
  rss_uri: http://prowlarr.domain.tld:9696
  rss_api_key: [redacted]

##########
# config
##########
# enable web ui
web_server:
  web_ui: yes

##########
# schedule(s)
schedules:
  - tasks: test-1
    schedule:
      hour: 6,18
      minute: 21

#########
# tasks
tasks:
# test task
  test-1:
    discover:
      release_estimations: ignore
      what:
        - mock:
          - term1
          - term2
      from:
        - search_rss: 
            url: '{? rss_uri ?}/1/api?apikey={? rss_api_key ?}&t=search&q={{ search_term }}'
            all_entries: yes
            other_fields:
              - guid
        - search_rss: 
            url: '{? rss_uri ?}/2/api?apikey={? rss_api_key ?}&t=search&q={{ search_term }}'
            all_entries: yes
            other_fields:
              - guid
    accept_all: yes
    make_rss:
      days: -1
      items: 1000
      file: /data/test-1.rss
      title: '[{{ guid.split("/")[2] }}] {{ title }}'
```

**Comment by mcrosson** [comment]
And a more complex example using yaml anchors:

``` yaml
##########
# variables
##########
variables:
  rss_uri: http://prowlarr.domain.tld:9696
  rss_api_key: [redacted]

##########
# config
##########
# enable web ui
web_server:
  web_ui: yes

##########
# templates
##########
templates:
  anchors:
    _discovery_list_1: &discovery_list_1
      mock:
        - serch_term
        - multi+word+search+term
    _discover_from_list: &discover_from_list
      - search_rss: 
          url: '{? rss_uri ?}/1/api?apikey={? rss_api_key ?}&t=search&q={{ search_term }}'
          all_entries: no
          other_fields:
            - guid
      - search_rss: 
          url: '{? rss_uri ?}/2/api?apikey={? rss_api_key ?}&t=search&q={{ search_term }}'
          all_entries: no
          other_fields:
            - guid
    _template_make_rss: &template_make_rss
      days: -1
      items: 1000
      title: '[{{ guid.split("/")[2] }}] {{ title }}'

##########
# tasks
##########
tasks:
  test-discovery_list_1:
    discover:
      what:
        - <<: *lewd_performers_a_h
      from:
        - <<: *discover_from_list
      release_estimations: ignore
    accept_all: yes
    make_rss:
      file: /data/test-discovery_list_1.rss
      <<: *template_make_rss
```
