### ISSUE TITLE
ftp_list stating missing "ftputil" dependency even though it is installed

### ISSUE THREAD

**Issue by Stiefmeister** [Flexget/Flexget#4316]
### Expected behaviour:

ftp_list should work if ftputil is installed. 
"pip list" shows that ftputil 1.5.1 (latest version) is installed via entrypoint during docker startup.

### Actual behaviour:

flexget is aborting task due to missing plugin : 

WARNING Aborting task (plugin: ftp_list)
CRITICAL ftputil is required for this plugin

### Steps to reproduce:
- Start docker
- Run task with ftp_list entry

#### Config:
```
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules: no

tasks:
  radarr-movies:
    radarr_list:
      base_url: http://ip
      api_key: somekey
      port: 0101
      only_monitored: yes
      include_data: yes
      only_use_cutoff_quality: yes
    accept_all: yes
    proxy: socks5h://user:pass@proxy:port
    ftp_list:
      username: xxx
      password: xxx
      host: xxx
      port: 0123
      use_ssl: yes
      dirs:
        - /some/dir/
      retrieve:
        - dirs      
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
2025-03-21 16:21:07 WARNING task radarr -movies Aborting task (plugin: ftp_list)
2025-03-21 16:21:07 CRITICAL task radarr -movies ftputil is required for this plugin
2025-03-21 16:21:07 INFO manager Config successfully reloaded!
```
</details>

### Additional information:

- FlexGet version: 3.15.28
- Python version:
- Installation method: Docker (official image)
- Using daemon (yes/no):
- OS and version: Alpine/Docker
- Link to crash log:
