### ISSUE TITLE
Flexget not send message to matrix

### ISSUE THREAD

**Issue by Vctrsnts** [Flexget/Flexget#4317]
I have _Flexget version 3.15.26 in Docker_, and I also have a Matrix server (_Conduit_) along with the following clients:

- Element-Web
- FluffyChat
- Bash script

I have no problems sending messages from either client to the Matrix server (I can even send images without any problems).
I've also run tests from a bash script that sends messages to the Matrix server, and everything has worked correctly.
The problem arises when I try to send a message from Flexget to the Matrix server.
In the flexget file (`config.yml`) I have the following for notifications:
```
  notify-all:
    notify:
      entries:
        message: 'moveVideos'
        via:
          - matrix:
              server: 'URL_MATRIX'
              token: 'TOKEN'
              room_id: 'ROOM_ID'
```
I use the same _TOKEN_, _ROOM_ID_, and _URL_MATRIX_ configuration as the one I put in the BASH script, and what I see in the flexget log is the following:
`WARNING notify moveVideos Error while sending notification to `matrix`: 404 Client Error: Not Found for url: https://SERVER_MATRIX/_matrix/client/r0/rooms/ROOM_ID/send/m.room.message?access_token=ACCESS_TOKEN`
And in the matrix server log it is this:
`404 Client Error: Not Found for url: /_matrix/client/r0/rooms/ROOM_ID/send/m.room.message?access_token=ACCESS_TOKEN`

Does anyone know where the problem might be, because I don't know where to look anymore.
