### ISSUE TITLE
'ftp_list' decoding issue: 'utf-8' codec can't decode byte 0xdb in position 5: invalid continuation byte

### ISSUE THREAD

**Issue by Stiefmeister** [Flexget/Flexget#4325]
### Expected behaviour:
When running a task with ftp_list it should be able to list dirs / files.

### Actual behaviour:

When running task with ftp_list I am getting the following error: 
**'utf-8' codec can't decode byte 0xdb in position 5: invalid continuation byte**

Please note: 
- tested with several ftp servers
- tested with versions 3.12.* / 3.11.* as newer versions throw dependency error when using ftp_list - see bug report #4324 

### Steps to reproduce:
- Step 1: Install flexget incl. ftputil dependency
- Step 2: Run task with ftp_list 

#### Config:
```yaml
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules: no

tasks:
  ftp:
    ftp_list:
      username: xxx
      password: xxx
      host: xxx
      port: 0123
      ssl: yes
      dirs:
        - dir
      retrieve:
        - dirs     
```
  
#### Log:
<details>
 <summary>(click to expand)</summary>

```
'utf-8' codec can't decode byte 0xdb in position 5: invalid continuation byte
```
</details>

### Additional information:

- FlexGet version: 3.11.* / 3.12.*
- Python version:
- Installation method: Docker
- Using daemon (yes/no):
- OS and version:
- Link to crash log:

**Comment by vivodi** [comment]
I'm using [FileZilla Server 0.9.60.2](https://filezilla-server.en.uptodown.com/windows/download/2296543) and you have to uncheck this option:

![Image](https://github.com/user-attachments/assets/05552cba-cb98-4846-a40c-f00eef4cf45e)

The `ftp_list` plugin uses the `ftputil` dependency, which does not support TLS session resumption on the data connection, so this option must be disabled. Since disabling this option is insecure, the latest version of FileZilla does not provide this option.

If you don't mind the lack of security, you may consider using `plain unencrypted FTP` instead of `FTP over TLS`:
```
tasks:
  ftp:
    ftp_list:
      ...
      ssl: no
      ...
```
If you need encryption, you can use `SFTP` instead of `FTP over TLS`, specifically our `sftp_list` plugin: https://flexget.com/Plugins/sftp_list

**Comment by Stiefmeister** [comment]
Thanks a lot for checking. The ftp servers in question are not under my management and are mainly running on gLFTPD (with encryption enabled). So I assume this is the issue and I understand that there is currently not way to make this work!?

**Comment by Stiefmeister** [comment]
Seems like it is in general possible but would require some ftputil customization!?

![Image](https://github.com/user-attachments/assets/68f09479-58fe-49da-a24b-385d46dde2a3)

**Comment by vivodi** [comment]
Currently, the code for `ftp_list` supports `PROT P`, but it does **not** support `TLS session resumption on data connection when using PROT P`.  

However, your error message might not be related to this issue, but rather an encoding problem: Your FTP server is not using UTF-8 encoding, but another encoding instead.

Encoding option: https://docs.python.org/3.13/library/ftplib.html#ftplib.FTP

I’ve submitted a PR that adds an option for setting the encoding:
```yaml
tasks:
  ftp:
    ftp_list:
      ...
      encoding: utf-8
      ...
```
