### ISSUE TITLE
All Docker images built after switching to `uv` cannot install packages using `pip install` in the `entrypoint.sh`.

### ISSUE THREAD

**Issue by vivodi** [Flexget/Flexget#4372]
I should be able to resolve this issue at a _later_ time.

> I wanted to upgrade my docker based flexget installation from
> `image: flexget/flexget:3.12.1`
> to
> `image: flexget/flexget:3.15`
> 
> my custom `entrypoint.sh` contains: `pip install irc_bot` (like suggested in the [docs](https://flexget.com/InstallWizard/Docker#custom-entrypoint))
> 
> After changing the image tag like written above i'm getting this error
>  
> ERROR    irc                           ImportError: irc_bot module not found or version is too old. Shutting down daemon.
> 
> 
> [pyenv](https://github.com/pyenv/pyenv) and [pipx](https://github.com/pypa/pipx) is not avaliable in the image 😢  

 _Originally posted by @pred2k in [#3985](https://github.com/Flexget/Flexget/issues/3985#issuecomment-2660869109)_

**Comment by pred2k** [comment]
i forced myself to upgrade from an v3.12.1 image today.

i prefer docker deployments for a better isolation but was insprired by `uv tool install flexget[locked] --with irc-bot --python 3.11` from https://github.com/Flexget/Flexget/issues/3985#issuecomment-2622860015.

i made this `Dockerfile` which is kind of near to https://github.com/Flexget/Flexget/blob/develop/Dockerfile:
```Dockerfile
FROM docker.io/python:3.11-alpine

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN uv tool install flexget[locked,qbittorrent] --with irc-bot --python 3.11

ENV PATH="/root/.local/bin:$PATH"

ENTRYPOINT ["flexget"]
```

build it: `docker build . -t flexget-self-build`

and run with my `compose.yaml`:

```yaml
services:
  flexget:
    image: flexget-self-build:latest
    container_name: flexget
    command:
      - --loglevel
      - verbose
      - daemon
      - start
    #ports:
      #- 5050:5050                   # optional: for webui
    environment:
      - TZ=Europe/Berlin       # optional: defaults to UTC
    volumes:
      - ./config:/config        # required
```

and finally got v3.19.1 running with flexget connecting to my configured irc channel ❤️ 

i'm not very happy with building my own image because i dont get automated image update notification by [watchtower](https://github.com/nicholas-fedor/watchtower/) or [What's up Docker?](https://github.com/getwud/wud).

Maybe irc-bot could also be added to the standard flexget Image like the other mentioned in https://flexget.com/InstallWizard/Docker
or have an extra flexget:3.19.1-irc image? i don't know.

Maybe someone has another idea or solution...
