### ISSUE TITLE
import_series with 2 inputs

### ISSUE THREAD

**Issue by tknorris** [Flexget/Flexget#62]
This isn't an issue per se but I don't know where is a better place to get an answer. I've been using flexget for some time and am always amazed by it's flexibility. So, awesome job and thanks for your contribution!

My question concerns the best way to use import_series but with 2 different lists with different settings for each list. Basically, I want to have some series that default to dl'ing the SD version and fallback to the HD version, and for some series vice versa. I want to then control which series is which through the 2 different trakt lists. So far the only way I've found that works is as follows:

```
presets:
  hd-tv:
    import_series:
      settings:
        exact: yes
        propers: 3 days
        timeframe: 8 hours
        target: 720p
        set:
          movedone: ~/complete/video/TV Shows/{{series_name}}
          ratio: 1.0
          label: tv_shows

      from:
        trakt_list:
          username: <redacted>
          password: <redacted>
          api_key: <redacted>
          custom: hd-shows


  sd-tv:
    import_series:
      settings:
        exact: yes
        propers: 3 days
        timeframe: 8 hours
        target: <720p hdtv+
        set:
          movedone: ~/complete/video/TV Shows/{{series_name}}
          ratio: 1.0
          label: tv_shows

      from:
        trakt_list:
          username: <redacted>
          password: <redacted>
          api_key: <redacted>
          custom: sd-shows

tasks:
  <redacted>-hd-tv:
    priority: 30
    rss: <redacted>

    set:
      ratio: 4.0

    download: ~/test

    preset: [ hd-tv ]

  <redacted>-sd-tv:
    priority: 30
    rss: <redacted>

    set:
      ratio: 4.0

    download: ~/test

    preset: [ sd-tv ]
```

Is there a better (i.e. more efficient) way to implement this? The problem w/ this approach is it requires 2 tasks for each RSS task. I've tried various other combinations (including putting both pre-sets in the same task) and I can't get any other approach to work.
