### ISSUE TITLE
Transmission ignoring set params

### ISSUE THREAD

**Issue by elboletaire** [Flexget/Flexget#710]
This was previously notified in your old ticket system, here: http://flexget.com/ticket/2270

If I'm doing something wrong reopening it here I'm sorry, but I've not found anything about the old ticket system here on github, that's why I'm opening it again.

The original ticket complained about deluge but I can confirm this issue with transmission. 

You can check my entire flexget configuration files [on my dotfiles repo](https://github.com/elboletaire/dotfiles/tree/master/flexget), but the relevant parts are the transmission configuration and the usage of `set` on series.

I think that with a configuration file like this should fail too:

```yaml
secrets: secrets.yml
templates:
  global:
    transmission: 
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.usr }}'
      password: '{{ secrets.transmission.pwd }}'
    urlrewrite:
      divxtotal.com:
        regexp: 'https?:\/\/(?:www.)?divxtotal.com\/series\/torrent\/(?P<torrent>[0-9]+)\/.+'
        format: 'http://www.divxtotal.com/download.php?id=\g<torrent>'
  tv-es:
    thetvdb_lookup: yes
    inputs:
      - rss: http://www.divxtotal.com/rss.php
    series:
      settings:
        average:
          quality: hdtv+ <=720p !10bit
          target: <720p
          timeframe: 6 hours
          propers: 12 hours
          set:
            ratio: -1.0
            path: "/home/elboletaire/Vídeos/Series/{{ series_name }}/{{ series_season }}a Temporada/"
            # content_filename does not work with non-ascii chars on transmission
            # content_filename: "{{ tvdb_series_name }} - {{ series_id }} {{ tvdb_ep_name | default('Unknown ep. name') }}"
      average:
        - Gotham
# [...]
```

I'm currently using the latest available version from pip which is 1.2.407.

PD. The `content_filename` comment is another issue also reported [here](http://flexget.com/ticket/2824). If the current politics are to recreate all the issues, I could do it adding the corresponding configuration and log files.
