### ISSUE TITLE
Flexget and Trakt error to connect list

### ISSUE THREAD

**Issue by Magnus57** [Flexget/Flexget#742]
Hello, since the last update of Flexget I have no more access to my lists on Trakt.tv.

In the wiki it is necessary to put a PIN code, but I understand not:-(

Thanks for your help

**Comment by OmgOhnoes** [comment]
http://flexget.com/wiki/Plugins/trakt does a fairly comprehensive explanation.

In short:

1. Goto: ​http://trakt.tv/pin/346
2. In CLI enter: ```flexget trakt auth <account> <pin>```
   - Where ```<account>``` is a name of your choosing and ```<pin>``` is the pin you received from that webpage.
3. In your config.yml, under trakt_list add an option for account using the name you specified in ```<account>```.
  - ie:
```
sometask:
  trakt_list:
    username: yourusername
    account: someaccountname
    list: somelistname
```
