### ISSUE TITLE
Unhandled exception in movie_queue

### ISSUE THREAD

**Issue by tknorris** [Flexget/Flexget#75]
After upgrading from 1.1.74 to 1.1.104 I now get an error in the movie_queue plugin from a previously working task. The task is:

```
  get_movies:
      priority: 10
      rss: <redacted>
      content_size:
        max: 10000
      movie_queue: yes
      exists_movie: /content/video/Movies
      set:
        ratio: 6.0
        removeatratio: no
        movedone: /home/<redacted>/complete/staging/movies
        label: movies

      preset: [ send_email, use_seedbox_deluge ]
```

I'll add the log details as an attachment since it's a large stack trace.

Stack Trace: http://pastebin.com/TmxnWrCs
