### ISSUE TITLE
Connection from daemon was severed

### ISSUE THREAD

**Issue by AezDropZz** [Flexget/Flexget#788]
Hello,

I recently started using Flexget and was successful in a couple of tests yesterday, but today these ERROR's started showing up:

```
2016-01-12 16:06 ERROR    manager                       Connection from daemon was severed.
2016-01-12 16:42 ERROR    manager                       Connection from daemon was severed.
2016-01-12 17:08 ERROR    manager                       Connection from daemon was severed.
```

I have been looking into this online but most people had this issue while using transmission and flexget together. I simply use flexget to store the files from the RSS in a specific folder.

This is my config file:
```
tasks:
  Series:
    rss: https://rssurl.com
    series:
      - serie1:
          quality: hdtv <720p
      - serie2:
          quality: hdtv <720p
      - serie3:
          quality: hdtv <720p
      - serie4:
          quality: hdtv <720p
      - serie5:
          quality: hdtv <720p
      - serie6:
          quality: hdtv <720p
      - serie7:
          quality: hdtv <720p
    download: /path/to/folder
```

Another thing I might need to mention is that I use crontab to run flexget every hour with the following line:
```
* */1 * * * /usr/local/bin/flexget -c /path/to/config.yml --cron execute
```

Since the RSS did not produce any data that I needed today, I can't see if my configuration actually did what it was supposed to do (as I mentioned in the start, my tests yesterday worked fine). Could anyone help by telling if these error's are a problem or not and if they are, where they come from and how I get rid of them?

Thank you in andvance!
