### ISSUE TITLE
'ascii' codec can't decode byte 0xe2 in position 2132: ordinal not in range(128)

### ISSUE THREAD

**Issue by w4rn** [Flexget/Flexget#801]
Hello,

i keep having this message and i cant find a solution.
Recently i updated my showrrs link (new website, new link) and from that i have this issue.
```
tasks:
  series:
    rss: http://showrss.karmorra.info/rss.php?user_id=USERID&hd=2&proper=0
    all_series: yes
    pushbullet:
      apikey: *****************
      title: "[F] {{series_name}} {{series_id}}"
      body: "{{title}}\n\nSize: {{content_size}}MB"
    transmission:
      host: localhost
      port: 9091
      username: *********
      password: ********
      path: /media/Delta/Utorrent/Incoming
      addpaused: no
  # sorting task
  sort-files:
    filesystem:
     filesystem:
      # directory with the files to be sorted
      path: /media/Delta/Utorrent/Incoming/
      # fetch all avi, mkv and mp4 files, skips the .part files (unfinished tor$
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    seen: local
    # this is needed for the episode names
    thetvdb_lookup: yes
    all_series:
      # for some reason all_series rejects all episodes here, even with seen: l$
      parse_only: yes
    # TVDB doesn't recognise "Adventure Time with Finn and Jake" so you must ad$
    series:
      - Adventure Time
    move:
      # this is where the series will be put
      to: /media/Delta/{{ tvdb_series_name }}
      # save the file as "Series Name - SxxEyy - Episode Name.ext"
     to: /media/Delta/{{ tvdb_series_name }}
      # save the file as "Series Name - SxxEyy - Episode Name.ext"
      filename: '{{ tvdb_series_name }}.{{ series_id }}.{{ tvdb_ep_name }}{{ lo$
  subtitles:
    filesystem:
      path: /media/Delta/Utorrent/Incoming
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    subliminal:
      languages:
        - ita
      alternatives:
        - eng
      exact_match: yes
      providers: [addic7ed, opensubtitles]
      single: no
web_server:
  bind: 0.0.0.0
  port: 5050
api: yes
webui: yes

schedules:
 - tasks: series
   schedule:
    hour: 06-23
    minute: "*/15"
 - tasks: sort-files
   schedule:
    hour: 1-5/2
 - tasks: subtitles
   schedule:
    hour: 06-23
    minute: "*/45"
```

Any idea?

W4rn
