### ISSUE TITLE
exists_movie plugin has no effect

### ISSUE THREAD

**Issue by raysmalley** [Flexget/Flexget#838]
I recently built a new flexget database and now when I execute my config, it wants to download every movie on my trakt watchlist. I already have most of these movies. I tried to implement the exist_movies plugin, but it has no effect on the outcome.

Here is my config:

```
  secrets: secretfile.yml

  tasks:
    get_series:
      priority: 1
      transmission:
        username: '{{ secrets.trans.usr }}'
        password: '{{ secrets.trans.pwd }}'
        main_file_only: yes
        path: '/media/Media/Torrents/Downloads/Shows/{{ series_name }}'
      content_filter:
        reject: '*.rar'
      content_size:
        max: 800
      regexp:
        reject_excluding:
          - ettv|eztv|rartv|PublicHD
      exists_series: '/media/Media/Shows/'
      series:
         - The Walking Dead
         - Game of Thrones
         - Pretty Little Liars
         - Silicon Valley
         - Better Call Saul
         - Mr. Robot
         - Limitless
         - Fear the Walking Dead
         - Heroes Reborn
      discover:
        what:
          - emit_series: yes
        from:
          - search_rss: http://extratorrent.com/rss.xml?cid=8
          - kat:
              category: tv
              verified: yes
          - piratebay:
              category: 208
              sort_by: seeds
          - torrentz: verified
      email:
        from: '{{ secrets.email.usr }}'
        to: '{{ secrets.email.to }}'
        subject: 'Flexget Series'
        smtp_host: smtp.gmail.com
        smtp_port: 587
        smtp_username: '{{ secrets.email.usr }}'
        smtp_password: '{{ secrets.email.pwd }}'
        smtp_tls: yes

    fill_movie_queue:
      priority: 2
      trakt_list:
        username: '{{ secrets.trakt.usr }}'
        account: '{{ secrets.trakt.usr }}'
        list: watchlist
        type: movies
        strip_dates: yes
      exists_movie:
        path: /media/Media/Movies
        type: files
      accept_all: yes
      movie_queue: add
 
    get_movies:
      priority: 3
      transmission:
        username: '{{ secrets.trans.usr }}'
        password: '{{ secrets.trans.pwd }}'
        main_file_only: yes
        path: /media/Media/Torrents/Downloads/Movies
      torrent_alive: yes
      content_size:
        max: 3000
      quality: 1080p
      discover:
        what:
          - emit_movie_queue: yes
        from:
          - search_rss: http://extratorrent.com/rss.xml?cid=4
          - kat:
              category: movies
              verified: yes
          - piratebay:
              category: 207
              sort_by: seeds
          - torrentz: verified
      movie_queue: accept
      email:
        from: '{{ secrets.email.usr }}'
        to: '{{ secrets.email.to }}'
        subject: 'Flexget Movies'
        smtp_host: smtp.gmail.com
        smtp_port: 587
        smtp_username: '{{ secrets.email.usr }}'
        smtp_password: '{{ secrets.email.pwd }}'
        smtp_tls: yes

    clean:
      priority: 4
      clean_transmission:
        username: '{{ secrets.trans.usr }}'
        password: '{{ secrets.trans.pwd }}'
        finished_for: 7 days
```
