### ISSUE TITLE
Series not deleted in DB after removal from trakt list

### ISSUE THREAD

**Issue by wtluke** [Flexget/Flexget#862]
Hi,

I removed a series ("Last Week Tonight with John Oliver") from my trakt watchlist last week, but it's still mentioned in the database (running `flexget series list`). Additionally, Flex isn't searching for the show (it doesn't appear in any logs).

- Adding new shows to Trakt updates Flex's DB fine.
- Re-adding the show doesn't cause it to be searched.
- I've tried removing it using `flexget series forget "Last Week Tonight with John Oliver (2013)"` which works fine for other shows, but not this.
- I've used --no-cache too.

Is there another command to remove it manually from the DB, or do I have to dig inside with a shovel? It's a weird bug; never come across it before.

Will

```
configure_series:
      from:
        trakt_list:
          username: a
          list: watchlist
          type: shows
      settings:
        timeframe: 2 hours
        target: 720p
        identified_by: ep
```
