### ISSUE TITLE
Render error in make_rss

### ISSUE THREAD

**Issue by TangoAlpha** [Flexget/Flexget#876]
Version:

```
# flexget --version
1.2.459.dev
```

Problem:
make_rss tags an RSS entry title with " - (Render Error)" for downloads that use TheTVDB as a lookup.
Entries that use IMDB lookup seem fine.
Expecting a full RSS entry built up from the appropriate TheTVDB entry.

Config:

```
templates:
  rss_feed:
    make_rss:
      file: '<redacted>/feed.xml'
      days: -1
      items: 10
      link:
        - imdb_url

  eztv-rss:
    template:
...
      - rss_feed
    rss:
      url: 'https://eztv.ag/ezrss.xml'
    configure_series:
...
    thetvdb_lookup: yes
```

Log:

```
Error while rendering entry <Entry(title=<redacted tv episode>,state=accepted)>, falling back to plain title: (TypeError) 'NoneType' object is not iterable
```
